### ISSUE TITLE
pg数据源创建工单审核时出错

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1002]
**SQLe Version**
UI Version: main 9ad6f1b
Server Version: main-ee e4e5da233a

1.新增白名单sql指纹匹配
![image](https://user-images.githubusercontent.com/63177450/199927377-dd005c72-d9e6-4f1f-adb3-1ba819abd71d.png)
2.添加一个pg数据源
3.使用该数据源创建工单，输入审核sql语句，然后点击审核，出现请求错误提示
![img_v2_8c4252b4-a742-4a3f-9030-47c6a046c35g](https://user-images.githubusercontent.com/54339501/197988313-76041254-f895-4931-b79a-481fe9170964.jpg)
![7ea9f741-eeec-4cc2-b0d9-05ffd4e98c3b](https://user-images.githubusercontent.com/54339501/197988376-f520ba2c-e740-4743-a8dd-b1a26538bce3.jpeg)
暂时绕过手段：
删除sql指纹匹配，便可以重新对pg数据源审核的sql进行正常的审核
![image](https://user-images.githubusercontent.com/63177450/199927445-c2753077-6ed7-4566-ae3c-3a91cd368c78.png)

**Comment by taolx0** [comment]
### 为什么 pg数据源创建工单审核时出错 ？
因为这里的解析白名单sql报错
https://github.com/actiontech/sqle/blob/e853534cf4f9738bb941ea12500015b72b7960d2/sqle/server/audit.go#L125

**Comment by Marcus9530** [comment]
验证版本
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba

验证步骤；
添加一条白名单sql语句，然后在创建工单内点击审核，当前并无报错

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/54339501/205011652-fd588e94-9b52-4d79-ae93-df598c1231df.png">

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/54339501/205011626-3e06e870-2e6d-4881-95f9-26943352d752.png">
