### ISSUE TITLE
VARCHAR 定义长度过长 此规则只能在建表时被检测出来，增加、修改表字段不能被检查出来

### ISSUE THREAD

**Issue by bdper0** [actiontech/sqle#1023]
VARCHAR 定义长度过长 此规则只能在建表时被检测出来，增加、修改表字段不能被检查出来
![image](https://user-images.githubusercontent.com/18696217/199168445-310b778b-4aa1-4ebe-8b6c-657237de374f.png)
![image](https://user-images.githubusercontent.com/18696217/199168488-ef1baade-1c96-48f3-b761-23681c837925.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba
验证步骤：
1.开启该规则
2.然后创建的时候设置一个字段为varchar且长度超过默认限制值。点击审核之后出现审核提示
3.然后对该表进行增加一个字段为varchar且长度超过默认限制值。点击审核之后出现审核提示
4.然后对该表进行修改一个字段为varchar且长度超过默认限制值。点击审核之后出现审核提示


<img width="1705" alt="image" src="https://user-images.githubusercontent.com/54339501/204992110-2896bb7c-441b-49ad-b8b0-127b581e77f4.png">
创建表
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/54339501/204992761-ae41658b-847a-4cb4-8033-2c82c822fa85.png">

增加表字段
<img width="1812" alt="image" src="https://user-images.githubusercontent.com/54339501/204992135-59d78dc8-4f4f-4976-9874-fa0567d19856.png">
修改表字段
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/54339501/204992636-03d1d7aa-2b11-4de5-9d88-d091a762de6c.png">
