### ISSUE TITLE
新增MySQL规则"数据库对象名英文字母不推荐混用大小写"

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1025]
**Database Type**

MySQL

**Rule Description**

数据库对象名英文字母不推荐混用大小写

**Why**

数据库对象命名规范，不推荐采用大小写混用的形式建议词语之间使用下划线连接，提高代码可读性

**Comment by sjjian** [comment]
## Note:
该规则也是 OceanBase for MySQL 的特有规则。在MySQL侧添加后，在OceanBase 插件移除。

**Comment by taolx0** [comment]
### 自测
![image](https://user-images.githubusercontent.com/63177450/200217520-f8333298-f306-44cf-b758-a5359753dfdc.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤：
创建一个数据库然后使用大小写当库名字，点击审核，触发审核提示

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/54339501/205015980-276ff1ab-7810-4e1a-83e5-c5d8d6fc8e2d.png">
