### ISSUE TITLE
check instance connectable behavior different when driver is build by pkg/driver package

### ISSUE THREAD

**Issue by drivebyer** [actiontech/sqle#103]
**SQLe Version**
main a87c83d1574eee90a08dc0e1719a2ce6a0557f8c

**Describe the bug**
check instance connectable behavior different between pg plugin and oracle plugin

**To Reproduce**
1. use oracle plugin
2. fill the instance info with wrong password
3. check connectable
4. See: a. HTTP code 500 with Internal Server Error; b. connect success on UI

**Expected behavior**
a. HTTP code 200 with custom API result
b. connect failed on UI

**Suggestion**
nil

**Comment by Marcus9530** [comment]
"release-1.2111.x 3d69edc91e634ae9d93f1a0ff2301016f2ea4249"
验证通过
验证步骤：
1.数据源管理添加oracle数据库
2.添加数据源的时候输入错误的端口然后点击保存
3.返回无法连接，然后为正确的端口，密码修改为错误的再次连接依旧是无法连接
4.密码修改为正确的，然后点击连接，连接成功
![image](https://user-images.githubusercontent.com/54339501/143391138-f3dd2807-2dd2-40a8-a7c7-7817573ee60e.png)
![image](https://user-images.githubusercontent.com/54339501/143391180-020aa261-3659-4733-b54e-a3cd6012610d.png)
![image](https://user-images.githubusercontent.com/54339501/143391252-8c1e61a0-6834-4ece-b896-43c61a2776df.png)
