### ISSUE TITLE
字段属性为not null时必须带default 默认值

### ISSUE THREAD

**Issue by bdper0** [actiontech/sqle#1031]
**Database Type**
 MySQL 

**Rule Description**
 字段属性为not null时必须带default 默认值 

**Why**
not null 没带默认值会导致 insert 不带该字段时报错

**Comment by taolx0** [comment]
###
此规则会忽略 主键自增 的列，因为主键自增的列不需要设置默认值

### 自测
![image](https://user-images.githubusercontent.com/63177450/200469594-b6d1a201-73ce-49bc-9de5-f434f649d94e.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63

验证步骤
创建一个多数据源的工单
然后点击s2
前端自动跳转到s2数据源审核的sql语句

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/54339501/205016795-a3d94762-0a1d-410a-8ea4-82a43eea4c49.png">
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/54339501/205016819-cd85896d-26f8-4203-bfb5-2d6b6933eeed.png">

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ce3927e
Server Version: main-ee e4e5da233a
验证步骤：
使用下述sql语句进行审核，可以看到test2跟test3字段给予相关提示
`create table not_exist ( 
    id int auto_increment not null, 
    test1 varchar(255) not null default "unit test",
    test2 varchar(255) not null,
    test3 varchar(255) not null,
    primary key (id)
);`

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/54339501/205018163-2e360520-91c9-4b89-87d1-453ba4bddf51.png">
