### ISSUE TITLE
社区版本创建工单时审核报错

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1037]
**SQLe Version**
1.2210.0

**Describe the bug**
社区版本创建工单时审核报错，点击审核时无响应。前端报错信息如下：
![10bb04fe-b39a-44a7-8de5-2d57302e2254](https://user-images.githubusercontent.com/18008452/199690643-f85f91e4-3340-4f0a-b799-ac5051c7e0d8.jpeg)

**Comment by Marcus9530** [comment]
复现版本
UI Version: release-1.2210.x dedd463
Server Version: release-1.2210.x 877ddd71f7

复现步骤；
创建一个工单，然后输入审核语句，点击审核，无任何反应。控制台报错

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/54339501/205220979-88d7d435-c786-4ea4-bc75-2c8eb4923a67.png">

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main 0099984568
验证步骤
创建一个工单，然后输入审核语句，点击审核，可以正常审核，控制台无报错


<img width="1357" alt="image" src="https://user-images.githubusercontent.com/54339501/205221631-712eda50-5479-4c57-b437-c5029211df74.png">
