### ISSUE TITLE
创建数据源时必须添加规则模版

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1043]
**Describe**
创建数据源时，如果不指定规则模版，sqle默认该数据源没有任何规则模版

**Suggestion**
添加数据源时，增加检测是否绑定规则模版的逻辑

**Why**
不绑定规则模版，会导致数据源没有任何审核规则

**Comment by taolx0** [comment]
1. 包含规则模版名，创建实例成功
![image](https://user-images.githubusercontent.com/63177450/210476086-2e33a07c-3501-43ec-ba21-50ee1f59910f.png)
2. 不包含规则模版名，报错
![image](https://user-images.githubusercontent.com/63177450/210476146-df4a9b1d-f7a2-4e55-b02c-5b6f88135b3c.png)

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证通过
验证步骤：

在界面上添加数据源的时候，不选择审核规则模版，前端给到提示
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/54339501/220869121-db1a7d78-b8da-4ade-9747-efc89b125f6a.png">
在界面上添加数据源的时候，选择审核规则模版，直接添加成功
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/54339501/220869161-3145ce69-72e1-401b-9ee7-81583b52a21f.png">
在swagger界面调添加数据源的接口，不传入审核规则模版，发请求，可以看到返回结果提示审核规则模版名必填
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/54339501/220870439-091c5f13-1727-48e7-9061-5438961c5f0e.png">
在swagger界面调添加数据源的接口，传审核规则模版，发请求，可以看到正常添加数据源成功
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/54339501/220870774-f17e78e1-666d-47b2-9c17-b25f3f369f0a.png">
