### ISSUE TITLE
scannerd 增加超时参数

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1055]
**Describe**
scannerd 请求 sqle 增加超时命令行参数

**Why**
满足用户想自定义超时参数的需求

**Comment by taolx0** [comment]
###  描述
<img src="https://user-images.githubusercontent.com/63177450/200767365-e7aec54b-78dc-4be8-a266-f9e4dd6472c2.png" height = "50%" width="50%">

### 自测
1. 触发审核任务接口增加 sleep 5s 逻辑
![image](https://user-images.githubusercontent.com/63177450/200768818-858c2cb9-5443-4536-bf10-4ab8e147b681.png)
2. 超时的情况
![image](https://user-images.githubusercontent.com/63177450/200768996-61458ae6-dd0f-496a-8898-23cc4cab0845.png)
3. 未超时的情况
![image](https://user-images.githubusercontent.com/63177450/200769273-d62cb653-d82c-4713-b23a-f5e44642ed40.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
1.设置超时时间限制为3秒，然后对sqle的表进行锁表用来模拟网络延迟，锁表5秒，可以看到超出限制时间后直接退出
2.重新设置时间限制为20秒，锁表5秒，可以看到解除锁表状态之后，scannerd立马就扫描审核成功了


![image](https://user-images.githubusercontent.com/54339501/205262375-e8ea1c97-b38d-4c29-95a3-4508099a88b5.png)
![image](https://user-images.githubusercontent.com/54339501/205262649-100dcbf4-5c37-43aa-ab16-dc56c4dc7a0e.png)
