### ISSUE TITLE
一批SQL上线时，其中某条SQL执行失败未终止上线

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1089]
**SQLe Version**
sqle main
**Describe the bug**

一批SQL上线时，其中某条SQL执行失败未终止上线。应该从失败SQL开始终止流程，减少影响面。

![image](https://user-images.githubusercontent.com/18008452/201896070-2fd88059-3a69-4fe9-ba90-bde9f82ff693.png)

**To Reproduce**
1. 提交几条能通过审核的SQL
2. 创建工单后，自行操作数据库，让其中某条SQL实际无法执行
3. 上线工单

**Expected behavior**

SQL执行失败后，终止工单内后续SQL的执行

**Comment by sjjian** [comment]
## 原因
SQLE在进行一批SQL的上线时未正确处理每次执行的返回错误，导致实际执行错误时未终止流程

**Comment by Marcus9530** [comment]
复现版本
UI Version: main ce3927e
Server Version: main-ee e4e5da233a
复现步骤
执行一批sql语句，第二条sql语句会失败，后续sql可以正常执行，然后对工单进行上线，可以看到工单在第二条失败之后，继续执行了后续的sql


<img width="1375" alt="image" src="https://user-images.githubusercontent.com/54339501/204997545-fc158313-fef4-4d31-90c4-b8c9ff86cc24.png">

**Comment by Marcus9530** [comment]
验证版本
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba
验证步骤
执行一批sql语句，第二条sql语句会失败，后续sql可以正常执行，然后对工单进行上线，可以看到工单在第二条失败之后，不再继续执行了后续的sql


<img width="1795" alt="image" src="https://user-images.githubusercontent.com/54339501/204997779-8ea05095-1b5a-47b8-b4c7-1f13a0b0a9b3.png">
