### ISSUE TITLE
display SQLE version on UI

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#110]
## 需求
可以通过页面看到SQLE 前后端的版本信息

**Comment by HuangWeiCen** [comment]
数据: 后端提供/v1/basic_info 接口返回后端版本信息, 前端版本信息由前端自行处理
样式: 建议参考开源项目DTLE的版本信息
![image](https://user-images.githubusercontent.com/37464327/148873932-1548a15e-f88d-447a-836e-ead042ca2770.png)
![image](https://user-images.githubusercontent.com/37464327/148873956-6a416097-7935-4332-90ac-6060d5eac6d9.png)
界面中包含前后端的版本号(版本号整齐一些), 下方为产品简介(前端写死即可), 产品简介内容详见sqle官方文档
