### ISSUE TITLE
新增审核规则背景解释

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1124]
## 需求
1. 新增规则背景解释，并在SQLE的规则，配置规则的界面展示；

在全局规则页面和规则模板编辑页面用灰色的文字添加一行规则背景，展示一定数量的字符，多的用省略号，当鼠标悬停在灰色字符上时，浮窗展示全部的内容
![image](https://user-images.githubusercontent.com/36940986/202997627-d4331531-0267-4e46-bca8-ee8cd658a871.png)

编辑规则时展示完整的背景内容
![image](https://user-images.githubusercontent.com/36940986/202997551-0b451b26-64cb-48d7-921a-801364961dff.png)

## 要求
1. 需要考虑审核插件的支持

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main 0099984568
验证步骤
查看mysql类型的审核规则，当前已实现的审核规则都已经新增了规则背景说明

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/54339501/205222069-6519ce26-9e43-40cb-905e-2dfd21891b63.png">
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/54339501/205222090-c3767f10-be7d-4bd6-91cd-f1880a6454f6.png">
