### ISSUE TITLE
【项目管理】增加项目概览页面

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1127]
增加项目统计页面作为进入项目的首页
- dashboard点击项目名称时跳转到项目概览页面
- 社区版点击项目跳转到项目概览页面
- 企业版点击项目列表条目进入项目概览页面

![image](https://user-images.githubusercontent.com/36940986/203453321-6150f72a-0164-4749-ba12-d74eb209200d.png)

**Comment by HuangWeiCen** [comment]
## 接口自测流程

### 1. 创建两个工单, 一个扫描任务, 两个实例, 一个包含一个用户的用户组, 一个没用户的用户组, 三个用户, 一个规则模板, 两个白名单
![image](https://user-images.githubusercontent.com/37464327/203684431-0930fe7d-32cc-42fc-bc77-12e5bf4b3958.png)
![image](https://user-images.githubusercontent.com/37464327/203684452-365f5fc2-6630-4611-aa1e-91f24b001b08.png)
![image](https://user-images.githubusercontent.com/37464327/203684485-3878b877-e427-41ff-bd20-485740430cdb.png)
![image](https://user-images.githubusercontent.com/37464327/203684386-929736dd-be5b-4851-8f3a-582cb84a271c.png)
![image](https://user-images.githubusercontent.com/37464327/203684367-830b9c5b-1f91-4291-8ca1-48c8e512d80f.png)
![image](https://user-images.githubusercontent.com/37464327/203684508-ab9641d2-7a82-401b-9062-de7b83ac82d6.png)
![image](https://user-images.githubusercontent.com/37464327/203684526-3237c19a-75b5-4cb1-a400-66c0bf46d10f.png)

### 2. 调用此接口
![image](https://user-images.githubusercontent.com/37464327/203684317-0150655b-bf32-4cc8-ab50-09d97352e075.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 2529990
Server Version: main-ee fdad3476ba
验证步骤：
创建12个工单，4个数据源，1个审核规则模版，2个扫描任务，1个白名单，3个项目成员。项目橄榄正常展示数据统计


![image](https://user-images.githubusercontent.com/54339501/205223707-85f79f08-a358-4074-a690-17fab359f5d6.png)
