### ISSUE TITLE
【项目管理】全局规则页面，筛选条件把数据源改为规则模板

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1130]
- 如果项目筛选框没有选择项目，则规则模板筛选框可选全局规则模板
- 如果项目筛选框选择了项目，则规则筛模板选框可选对应项目的规则模板
- 规则模板下拉列表标注是“全局规则模板”还是“项目规则模板”，类似数据源下拉框的数据库类型
![image](https://user-images.githubusercontent.com/36940986/203017424-9d047298-b9eb-41e5-b2f5-ce7cf53405ec.png)

**Comment by HuangWeiCen** [comment]
# 后端方案
原
/v1/projects/{project_name}/instances/{instance_name}/rules
可以用
/v1/projects/{project_name}/rule_templates/{rule_template_name}/
替代

/v1/rules 新增入参 filter_global_rule_template_name , 用于筛选全局规则模板

**Comment by HuangWeiCen** [comment]
## /v1/rules 自测流程

### 1. 将 default_MySQL模板中的内容改为只有一条规则
![image](https://user-images.githubusercontent.com/37464327/203509867-e4e3333e-7a27-4335-918f-58037b64b261.png)

### 2. 使用swagger进行查询, 过滤器正常生效
![image](https://user-images.githubusercontent.com/37464327/203509941-6dc7e1bd-4c38-4c64-b86d-13172883cf9f.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
1.default项目内创建一个规则模版 dtest
2.aaa项目创建一个规则模版test
3.在全局规则界面，点击default可以看到dtest规则模版
4.然后选择aaa项目，可以看到之一test规则模版
5.不选择任何项目，可以看到dtest和test规则模版
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/54339501/205223340-76a64abc-dc80-4385-8a89-2702e8349bc5.png">


<img width="1477" alt="image" src="https://user-images.githubusercontent.com/54339501/205223325-561a9ced-9a35-4bf9-9f59-0aa6d8dcab2e.png">
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/54339501/205223356-6e08f1f1-77e6-4b5f-b373-7ac7b16969e0.png">
