### ISSUE TITLE
建议优化项目成员角色字段的展示

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1136]
当设置了项目成员跟成员组添加了对应的角色跟数据的之后，那么该用户或者用户组在角色字段的时候就会带有数据源：角色名的展示方式，感觉怪怪的，其实数据源跟角色分开展示

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/54339501/203242475-a70b698e-2ebc-46aa-bdc4-65347509e4b5.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/54339501/203242589-628b7d70-0c1b-42f2-8dd7-ed6adabf4195.png">

**Comment by ColdWaterLW** [comment]
## 优化方案
![image](https://user-images.githubusercontent.com/36940986/203245077-0a3e69c2-824e-4b36-a1c4-9de337bb3f1f.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
当前已经对文案进行调整
<img width="1887" alt="image" src="https://user-images.githubusercontent.com/54339501/205018584-8ad8722e-c75d-4cee-a0a6-f5d45e714725.png">
