### ISSUE TITLE
【项目管理】前端bug处理以及接口调整

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1138]
1. 白名单界面只有 admin 用户或者项目管理员才拥有增、删、改功能

![img_v2_a6c0761e-e373-4870-8e15-63e81c80d1ag](https://user-images.githubusercontent.com/42765421/203458009-dcc53fe0-5eaa-47e1-a8f5-bf19d60b1e63.jpg)

2. 分析功能界面跳转出现错误
![img_v2_af4bd67d-6449-4878-bb7e-ac013ed0a22g](https://user-images.githubusercontent.com/42765421/203458074-7ec5974a-1fdd-4924-af92-84fe7030dc42.jpg)

3. SQL 分析界面接口升级
/v1/projects/{project_name}/audit_plans/reports/{audit_plan_report_id}/sqls/{number}/analysis [get]
=>
/v1/projects/{project_name}/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls/{number}/analysis [get]

4. 项目成员界面表格列: “项目拥有者” => “项目管理员”

**Comment by ColdWaterLW** [comment]
关联issue： #960

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 2529990
Server Version: main-ee fdad3476ba
验证步骤：
创建12个工单，4个数据源，1个审核规则模版，2个扫描任务，1个白名单，3个项目成员。项目橄榄正常展示数据统计


![image](https://user-images.githubusercontent.com/54339501/205223707-85f79f08-a358-4074-a690-17fab359f5d6.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
1.使用admin用户跟项目管理员用户a1查看白名单界面，可以对其操作，使用一个 普通用户t1查看白名单界面，发现没有可用的按钮

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/54339501/205223986-16103cca-25e2-4599-930c-cbe249a5bc1d.png">
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/54339501/205224022-f5ca310a-f2d4-4c97-b621-6e0d31579f3a.png">
<img width="1804" alt="image" src="https://user-images.githubusercontent.com/54339501/205224141-b0202019-e758-4c63-aa0c-4eed51ffdc8d.png">

2.然后创建一个工单，点击审核sql的分析功能，并没有跳转到dashboard
<img width="1824" alt="image" src="https://user-images.githubusercontent.com/54339501/205224448-cbb5e249-7b92-4057-9cbc-47d81d8e1d3a.png">
3.下发一个查询语句，然后点击分析，界面正常展示信息
<img width="1684" alt="image" src="https://user-images.githubusercontent.com/54339501/205224697-14668c60-736b-4fa4-8482-b9b695c1b5d7.png">
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/54339501/205224737-b9016612-bd8b-47fe-96b2-ba2fe4c7b55d.png">

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/54339501/205224711-2cc8ad47-f59e-4351-b298-2d2a5379e141.png">
4.项目成员管理界面，文案信息已更为项目管理员
<img width="1807" alt="image" src="https://user-images.githubusercontent.com/54339501/205224848-c7f1bf22-ed01-4e7f-a984-5f7365a91a1a.png">
