### ISSUE TITLE
审核计划的token如果跟jenkins上配置的不一致，实际上还会继续给推送收集的sql语句

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#114]
**SQLe Version**
  "release-1.2111.x 5d24144eb56b6202d030ac935897053b793f1a23"

**To Reproduce**
1.创建审核计划配置jenkins 触发gitlab sqle可以看到审核计划的语句
2.把审核计划给删除，然后重新创建一个新的审核计划，名字保持跟删除的保持一致
3.gitlab触发变更，然后jenkins进行构建，然后成功了
![image](https://user-images.githubusercontent.com/54339501/143534439-f8854a1d-4dc5-4820-9496-625f9278caab.png)
![image](https://user-images.githubusercontent.com/54339501/143534458-99a83a2d-b5a5-4f4d-aaf2-9c2a44b361fe.png)
两边的token明显不一致，但是还可以继续推送收集的sql信息
**Expected behavior**
期望是审核计划删除之后，对应的token会失效，应该使用最新的token来进行推送

**Comment by drivebyer** [comment]
缺陷原因：
SQLE 接受 scanner 上传 SQL 时，未对上传的 Token 和审核计划名做一致性校验。

修复方案：
在 `ScannerVerifier` 拦截器中增加校验，校验请求的 审核计划的 token 是否和数据库中未删除的审核计划的 token 一致。

**Comment by HuangWeiCen** [comment]
发现一个延申问题, 审核计划删掉再重新创建一个同名计划后, 审核执行时的任务报告ID(audit_plan_report_id)不会清零,而是从之前的那个审核计划的最后一个报告ID继续往下计数

**Comment by Marcus9530** [comment]
验证版本
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 892ff4c7c3
验证步骤：
1.新建一个审核任务，然后在gitlab上进行变更，触发jenkins的编译
2.在sqle上删除这个审核任务，然后新建一个审核任务，此时jenkins的token和新审核任务的不一致，不应该会继续推送sql语句信息
3.观测jenkins的编译，控制台输出信息提示token检查不一致，sqle上新建审核任务也没有收到新的sql语句信息

![image](https://user-images.githubusercontent.com/54339501/151110441-4a628888-2abc-4899-b7e5-6d2203cb990d.png)
![image](https://user-images.githubusercontent.com/54339501/151110464-ad7d7968-a69f-4714-b0e1-e4605bb52f71.png)
![image](https://user-images.githubusercontent.com/54339501/151110491-c8e0652b-0ba0-43b4-b632-464d8e6f4baa.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 892ff4c7c3
验证步骤：
1.新建一个审核任务，然后在gitlab上进行变更，触发jenkins的编译
2.在sqle上删除这个审核任务，然后新建一个审核任务，此时jenkins的token和新审核任务的不一致，不应该会继续推送sql语句信息
3.观测jenkins的编译，控制台输出信息提示token检查不一致，sqle上新建审核任务也没有收到新的sql语句信息

![image](https://user-images.githubusercontent.com/54339501/151110441-4a628888-2abc-4899-b7e5-6d2203cb990d.png)
![image](https://user-images.githubusercontent.com/54339501/151110464-ad7d7968-a69f-4714-b0e1-e4605bb52f71.png)
![image](https://user-images.githubusercontent.com/54339501/151110491-c8e0652b-0ba0-43b4-b632-464d8e6f4baa.png)
