### ISSUE TITLE
创建工单-sql语句的输入框大小被固定

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1147]
问题：创建工单页面中，sql语句的输入框大小恒定，无法适应窗口大小
预期：sql语句的输入框大小适应窗口大小
【初始状态】
![image](https://user-images.githubusercontent.com/113898890/203720918-6de48ba3-9d8c-41da-901f-372dc8d56898.png)
【扩大浏览器大小后】
![image](https://user-images.githubusercontent.com/113898890/203721057-88a9e6be-1eb1-49e0-8291-12e71e18a925.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.在小窗口模式下，sql语句的输入框大小
2.然后切换到大窗口模式下，sql语句的输入框大小随着变大，效果很明显。

<img width="881" alt="image" src="https://user-images.githubusercontent.com/54339501/209630292-273460d8-fe31-418d-9e10-9c23bca61b6d.png">
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/54339501/209630310-6d4262d6-34fe-4cd9-bb01-8432ad12e17b.png">
