### ISSUE TITLE
项目流程模板界面更新模板表单以及详情页应该删除 “审批流程模板名称”、“审批流程模板描述”、“应用的数据源”

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1155]
![image](https://user-images.githubusercontent.com/42765421/204429498-a9abcbef-cd26-484e-b7b7-68c9ba16cd37.png)
模板详情部分应该隐藏, 同时调整编辑按钮的位置至右上角

![image](https://user-images.githubusercontent.com/42765421/204429619-13c10996-d670-4fb7-8e97-0f3a0f2cd163.png)
编辑表单目前只是禁用掉了, 应该直接隐藏

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
进入项目内查看审批流程模版，当前已去除 “审批流程模板名称”、“审批流程模板描述”、“应用的数据源”，然后点击编辑，在基本信息也只有创建工单的最高审核提示信息
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/54339501/205222384-37e58593-22f8-4ddb-9cf8-1da837945f78.png">
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/54339501/205222416-0abd6b8f-5788-4608-8623-e5c557d54e0b.png">
