### ISSUE TITLE
工单概览增加点击快速跳转工单详细的功能

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1156]
**Describe**

工单概览增加点击快速跳转工单详细的功能。多数据源提交工单时概览内会有多行，点击对应的行时会跳转到对应的tab页
![img_v2_f37ae7cc-9b41-4751-999a-b4f83fc3790g](https://user-images.githubusercontent.com/18008452/204449029-1d5de512-8fb2-454a-a001-6add5271c3cf.jpg)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63

验证步骤
创建一个多数据源的工单
然后点击s1
前端自动跳转到s1数据源审核的sql语句

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/54339501/205016795-a3d94762-0a1d-410a-8ea4-82a43eea4c49.png">
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/54339501/205016819-cd85896d-26f8-4203-bfb5-2d6b6933eeed.png">
