### ISSUE TITLE
创建工单时选择第一项数据源, 若想选择其他类型的数据源, 只能通过刷新浏览器或者重置表单才能实现

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1157]
![1eb12f95-5350-4b52-9c60-766de90ef719](https://user-images.githubusercontent.com/42765421/204476192-90f482e6-901c-4722-a790-cdf100695ba9.jpeg)

现状: 在相同sql模式下选择第一个数据源后会根据其类型和流程模板做一个过滤, 并且数据源的下拉框没有清除功能, 这样导致的问题就是选择了一个数据源后导致其他类型的数据源不可见, 只能通过重置表单或者刷新网页.

原因:  因为在添加项目管理需求之前, 所有数据源必须使用同一流程模板, 所以在选择第一项数据源后会进行一次过滤, 同时会根据 sql 模式是否为相同进行对数据源类型的筛选.

解决方式:  取消在选择数据源后对数据源的过滤.  因为在添加项目管理后, 创建工单的数据源皆为同一项目下的数据, 无需考虑所选数据源是否为同一流程模板, 并且现在存在一个功能点: 是当选择不同数据源类型后, sql 模式会自动切换成不同, 并且禁用掉这个开关, 只有当数据源选择相同后才能重新切回相同.

**Comment by Marcus9530** [comment]
复现版本
UI Version: main ce3927e
Server Version: main-ee e4e5da233a
复现步骤
创建工单，选择不同sql时，第一个选择myql，然后第二个数据源只能选择mysql类型

<img width="952" alt="image" src="https://user-images.githubusercontent.com/54339501/205226248-ce0ed300-a279-4341-b1d0-7d5cbf170245.png">

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤：
创建工单，然后第一个数据源选择mysql类型，第二个数据源可以看到pg类型的，点击选择pg数据源，然后自动切换为不同sql模式

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/54339501/205228301-3ab41560-2dc8-48a4-8564-72f2b5cc8a9c.png">
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/54339501/205228315-13285fae-f396-4b50-909b-8952a56c8f3a.png">
