### ISSUE TITLE
更新数据源时无法取消绑定审核规则模版

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1158]
**SQLe Version**
sqle main

**Describe the bug**

更新数据源时无法取消绑定审核规则模版
**To Reproduce**

修改某个已绑定规则模版的数据源，将规则模版删除后保存，再次打开还是绑定状态

![img_v2_3a9549be-eab6-432d-86bb-ed449cad2f5g](https://user-images.githubusercontent.com/18008452/204493160-28fa14d5-acfe-4a72-b35f-0194bcc4c70c.jpg)
![img_v2_9f984b50-918d-4e92-8a73-ab1e487c76dg](https://user-images.githubusercontent.com/18008452/204493177-6b9b6f8f-73a7-4ddb-9ec4-7a100f70b344.jpg)
![img_v2_ab3d688e-5e8d-417c-9ba2-847ee89b80fg](https://user-images.githubusercontent.com/18008452/204493201-f1101a3c-3497-4c59-8728-644d4f54c51d.jpg)

**Comment by ColdWaterLW** [comment]
当去掉模板名后，前端需要把rule_template_name传回空字符串。如果不传这个字段则后端不会对这个字段作变更

**Comment by Marcus9530** [comment]
复现版本
UI Version: release-2.2211.x ff420bf
Server Version: release-2.2211.x 0099984568
复现步骤：
1.添加一个数据源然后绑定一个审核规则模版
2.然后保存之后，重新编辑，点击去除审核规则模版
3.然后点击保存，但是界面上依旧显示有审核规则模版
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/54339501/209773565-6cd85705-6af1-4592-8def-5566ec2d12b7.png">
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/54339501/209773589-f0c7ae2a-2b0f-49fd-8381-4f10b4d824d5.png">

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.添加一个数据源然后绑定一个审核规则模版
2.然后保存之后，重新编辑，点击去除审核规则模版
3.然后点击保存，更新成功，界面上不在展示审核规则模版


<img width="1231" alt="image" src="https://user-images.githubusercontent.com/54339501/209773921-04a6a4bc-7c5c-4744-919c-969f45e867ed.png">
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/54339501/209773938-6cd65aae-925f-4b60-a26b-97c99c1a84b1.png">
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/54339501/209773961-63b32652-6720-4259-9f24-a186a8b09445.png">
