### ISSUE TITLE
当一个全局用户设置为项目管理员之后，该用户无法被删除

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1161]
**SQLe Version**
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba

1.在用户管理那里创建一个用户test
2.然后在项目里面设置test用户为项目管理员
3.回到用户管理里面删除test用户，删除失败，提示了该用户绑定了工作模版
4.查看了审批模版并没有绑定该用户
![ceb03fd6-7d6f-44ef-9b1e-9f494b37b91b](https://user-images.githubusercontent.com/54339501/204724508-f97d3ab7-d417-4023-8825-ed8bd01dde37.jpeg)
![5480eea2-4cd2-4986-84d5-a9fd1fbc3413](https://user-images.githubusercontent.com/54339501/204724522-26353001-76f8-4467-ba23-33ed3eb887c6.jpeg)

**Comment by HuangWeiCen** [comment]
# 问题修复
## 1. 修复用户没绑定审核模板却被当作绑定的问题

## 2. 修复用户被当作项目最后一个管理员, 但实际不是的问题(处理问题1时发现的, 一起修了)


# 自测流程
1. 创建一个新用户
![image](https://user-images.githubusercontent.com/37464327/204973225-e4bd3152-4b06-4f0f-98aa-f0f4c02b11c9.png)
2. 将此用户绑定到一个项目中, 并将其设为管理员(不要是最后一个管理员), 同时绑定工单审核权限
![image](https://user-images.githubusercontent.com/37464327/204973544-299e1ed0-8e45-4782-9432-b97ed6cc2a69.png)
3. 检查流程模板, 确认创建工单时可以匹配到这个用户
![image](https://user-images.githubusercontent.com/37464327/204973705-5f77fadf-0b9e-42bf-8cda-f1d160bef553.png)
4. 创建一个会匹配到此用户审核的工单
![image](https://user-images.githubusercontent.com/37464327/204974459-18ab61e6-5de6-4d07-a583-b7dcdf2ae9c9.png)
![image](https://user-images.githubusercontent.com/37464327/204974543-e65c6ca4-52b9-4631-95c5-258ae3e3f431.png)
5. 结束工单并修改流程模板
![image](https://user-images.githubusercontent.com/37464327/204974604-df9baab3-209e-4f9d-b076-1370e3744231.png)
![image](https://user-images.githubusercontent.com/37464327/204974824-67d04b03-f357-478f-a05e-9c9ced8ae6e7.png)
6. 删掉此用户, 删除成功
![image](https://user-images.githubusercontent.com/37464327/204974857-f5f7a75d-cf90-48fb-8d72-4e0000dd7100.png)
7. 再创建一个用户绑定到此项目中, 将其设为唯一的管理员
![image](https://user-images.githubusercontent.com/37464327/204975017-b1311212-6ad5-44ae-b47e-8ad882832b9c.png)
8. 删除此用户, 删除失败
![image](https://user-images.githubusercontent.com/37464327/204975087-6af5a180-2cd0-417b-bca7-14270968e766.png)
9. 将此用户设为流程模板审核人
![image](https://user-images.githubusercontent.com/37464327/204975154-4b646bc3-2997-4cbe-99ed-d08e745af04b.png)
10. 删除此用户, 删除失败
![image](https://user-images.githubusercontent.com/37464327/204975221-e657328c-a36c-466a-a553-5124d019d61a.png)
11. 给此用户审核工单的权限, 并使其不是最后一个管理员
![image](https://user-images.githubusercontent.com/37464327/204976068-2f59adbc-d9c2-41b4-9392-4ec0968c8928.png)
12. 流程模板改回有权限的人可以审核
![image](https://user-images.githubusercontent.com/37464327/204976152-6714d036-9ac9-45f2-a578-4e9510066c9d.png)
13. 删除此用户, 删除成功
![image](https://user-images.githubusercontent.com/37464327/204976193-298b15ee-017a-4ab5-8704-9adc3ac06b1e.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
1.创建一个用户设置为项目管理员，然后在全局用户管理对其进行删除，可以正常删除成功

<img width="1854" alt="image" src="https://user-images.githubusercontent.com/54339501/205229503-db68afca-706d-4aa0-8750-f70722299d34.png">
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/54339501/205229619-020ac87d-fc1e-46e1-9edc-10345d885c8c.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/54339501/205229635-71da8128-fc9a-4369-a1f3-f16098fceb7c.png">
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/54339501/205229649-2172f182-518f-440b-b61a-456e83b4c467.png">
2.项目下设置2个用户为管理员，然后在全局用户进行删除，删除第一个的时候没有提示为最后一个管理员可以正常删除，删除第二个的时候正常提示为最后一个管理员
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/54339501/205231005-d9cdb9ff-8c34-46b1-aa06-ded23d0e6eaa.png">
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/54339501/205231146-4f787e2c-237a-457c-b708-84cd48bf3ecc.png">
<img width="1899" alt="image" src="https://user-images.githubusercontent.com/54339501/205231177-65e00970-708a-45c1-8234-26c501ab5ea9.png">
3.重新创建刚刚删除的用户t1，然后在项目内重新设置为管理员，可以正常设置成功
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/54339501/205231250-9b78348d-dd9b-4698-bbd5-fcad635049b6.png">
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/54339501/205231393-bb1bed09-63d8-4ce6-b077-280b5ee4872f.png">
<img width="1703" alt="image" src="https://user-images.githubusercontent.com/54339501/205231405-98d97faa-6b64-44d3-8f0d-c192843fb07f.png">
