### ISSUE TITLE
当项目里设置用户组之后，项目成员列表进行筛选的时候会展示绑定的用户组下的用户

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1162]
**SQLe Version**
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba

1.创建用户组test
2.创建t1,t2,t3用户，然后绑定到用户组test
3.项目里面项目成员组列表绑定用户组test
4.然后在项目成员列表点击筛选，可以看到test组下的用户
![c9b85fde-ba40-4468-987c-e8d8f5e82800](https://user-images.githubusercontent.com/54339501/204734071-2f98fb12-9154-4953-9f43-872aa4159e53.jpeg)
这里筛选建议是只展示了绑定好的用户，而不是用户组下面的用户，否则会引起疑问让人不解，并没有设置这几个用户到项目成员里面，从哪里来的用户数据

**Comment by HuangWeiCen** [comment]
# 修复内容
增加成员提示接口 /v1/projects/{project_name}/member_tips
此接口仅展示直接绑定的成员, 不展示成员组中的成员

# 自测流程

1. 创建一堆用户
![image](https://user-images.githubusercontent.com/37464327/206073809-e2cc8fa5-38ab-4a0d-918a-4ea9e637e32b.png)

2. 将部分用户加入项目
![image](https://user-images.githubusercontent.com/37464327/206073860-3e019964-9377-4a45-81d7-7934d9dc8a46.png)

3. 调用接口, 发现查询结果和界面展示结果一致
![image](https://user-images.githubusercontent.com/37464327/206073900-16ec250a-ec9a-4143-b877-6474a10e8575.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.创建用户组aaa
2.创建a1,a2,a3用户，然后绑定到用户组aaa
3.项目里面项目成员组列表绑定用户组aaa
4.然后在项目成员列表点击筛选，此时不在展示aaa组下的用户

<img width="1902" alt="image" src="https://user-images.githubusercontent.com/54339501/209618011-554cbbe9-761b-4303-a44b-9e5190857cff.png">
