### ISSUE TITLE
管理项目权限的账户审核页面的关闭工单无法使用点击报“you are not allow to operate the workflow”

### ISSUE THREAD

**Issue by yunxixi** [actiontech/sqle#1164]
**SQLe Version**

Version:
  "main-ee fdad3476ba7078dd0901057b8276be8fd6d8b9bb"

**Describe the bug**
管理项目权限的账户审核页面的关闭工单无法使用点击报“you are not allow to operate the workflow”

**To Reproduce**

1.创建一个工单；
2.创建一个用户赋予管理项目权限的；
3.登录账户审核工单；
I点击审核工单之后，驳回工单：点击关闭工单提示“you are not allow to operate the workflow”
II点击审核工单，不做任何操作点击关闭工单提示“you are not allow to operate the workflow”
![image](https://user-images.githubusercontent.com/16645348/204973910-2f52ae7b-461d-4271-867e-5d7aa4976c17.png)
![image](https://user-images.githubusercontent.com/16645348/204974369-cadd9789-89b3-4507-b7a8-e800c70c829a.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/16645348/204974495-8b40f432-c240-4b9b-bba8-4c4735354674.png)
![image](https://user-images.githubusercontent.com/16645348/204974544-bb63af1b-d684-4081-a795-25fb7458a375.png)

**Suggestion**

**Comment by HuangWeiCen** [comment]
# 修复内容
修复关闭工单时项目管理员提示没有权限的问题


# 自测流程
1. 使用管理员登录sqle
![image](https://user-images.githubusercontent.com/37464327/204978090-1f96cfa1-83a7-43cf-850f-47bf3c2c22d4.png)
2. 关闭工单, 关闭成功
![image](https://user-images.githubusercontent.com/37464327/204978263-6d54f5e8-30d6-4382-915d-1c3f05d75795.png)

**Comment by Marcus9530** [comment]
帮@yunxixi上传验证结果
验证版本
Server Version: main-ee 0b72a93f63
验证步骤
如上进行操作，点击操作之后给予相关提示 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/54339501/205263219-ad74a061-a6dc-459e-b46b-6627bb99b3f0.png">
