### ISSUE TITLE
没有sql查询权限的用户依旧是可以看到在cloudbeaver界面看到

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1165]
**SQLe Version**
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba

1.创建两个项目test1、test2
2.然后创建一个用户组test，组内有t1,t2,t3用户
3.然后在test1项目组下添加一个数据源mysql1
4.然后在test1项目组下设置项目成员用户组，设置test1组跟数据源mysql1，并且角色选择dba
5.切换到test2项目下添加一个数据源select
6.然后在test2项目中添加一个角色只有查看他人创建的工单权限
7.然后在test2项目中设置项目成员用户组，设置test1组跟数据源select，并且角色选择上一步创建的
8.使用t2用户进行登录，可以在cloudbeaver界面select数据源，并且可以对此进行操作。
<img width="786" alt="image" src="https://user-images.githubusercontent.com/54339501/204975243-5e26f697-c560-4029-9584-f6bc854ddcc3.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/54339501/204975172-9cff8f17-b3dc-4707-8171-e7fec6caa171.png">
疑问：在test2项目组内使用了test用户组，但是所赋予的权限并没有给sql查询操作的权限，但是依旧在cloudbeaver界面可以对test2项目中添加的数据源进行操作，是否不太合理？建议进行修复

**Comment by HuangWeiCen** [comment]
问题已无法复现, 猜测是修其他bug时这个问题也被一起解决了
