### ISSUE TITLE
项目列表页面权限控制和文本内容修改

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1167]
1. 只有项目管理员或者 admin 才能操作
![img_v2_c94c5ee4-c015-4bd1-b482-a9665cb0189g](https://user-images.githubusercontent.com/36940986/204977373-a810c5aa-bae5-47ef-8b32-b3e3014e2d09.jpg)

2. 文本内容错误
![img_v2_c96618ab-5490-44d4-a078-e061c83bb26g](https://user-images.githubusercontent.com/36940986/204977464-2917c346-547d-4e76-9875-ca4c83cf9ce6.jpg)

**Comment by Marcus9530** [comment]
复现版本
UI Version: main e6c1ebf
Server Version: main-ee fdad3476ba
复现版本
使用admin用户删除一个项目的时候，提示确认要删除规则模版"test"么?

<img width="1858" alt="image" src="https://user-images.githubusercontent.com/54339501/205002480-37294e73-435e-4552-9430-c6e435ba5ac8.png">

**Comment by Marcus9530** [comment]
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤：
1.使用admin删除项目的时候文案并没有提示删除规则
2.只用admin用户才可以点击删除项目的按钮，其他用户都不可以


<img width="1891" alt="image" src="https://user-images.githubusercontent.com/54339501/205003751-5035db94-5d2f-45c8-9538-804bb4305dce.png">
<img width="1910" alt="image" src="https://user-images.githubusercontent.com/54339501/205003821-228e3f4f-9b14-4b7a-a3e3-6e4efd7a1655.png">
