### ISSUE TITLE
support multi-params configuration of rule

### ISSUE THREAD

**Issue by drivebyer** [actiontech/sqle#117]
### 背景
1. #55 中需要新增 3 个配置，层级不同，无法通过 3 条规则友好的表示
2. 当前规则只支持配置 1 个规则值，无法支持复杂规则的自定义
3. 当前规则值以字符串的形式展示，用户在修改规则值时，缺少类型限制（用户可能在规则值中填写任何值）

**Comment by drivebyer** [comment]
### step 1:
new struct in driver package:
```go
type RuleParam struct {
	Name string
	Desc string
	Type RuleParamType

	Value interface{}
}

type RuleParamType int

const (
	RuleParamTypeString RuleParamType = iota
	RuleParamTypeInt
	RuleParamTypeBool
)
```

### step 2:
`Rule` change to:
```go
type Rule struct {
	Name string
	Desc string
	Category string
	Level  RuleLevel
        // 变更处
	Params []*RuleParam
}
```

### step 3:
upgrade API

**Comment by sjjian** [comment]
##  接口变更
### 涉及的查询接口
1. [get]/v1/rules 规则列表接口
2. [get]/v1/rule_templates/{rule_template_name}/ 审核模板详情
### 查询接口变更
`RuleReqV1` 结构的 `value` 字段弃用，改为 `params` 字段，对应的是结构`RuleParamResV1` 列表，对应下面字段：
1. `key` ：该配置项的主键
2. `value`：该配置项的值
3. `desc`：该配置项的描述，对应页面的展示
4. `type`：value对应的值类型，在页面进行验证，bool，int，string

### 涉及的修改接口
1. [post]/v1/rule_templates 添加规则模板
2. [patch]/v1/rule_templates/{rule_template_name}/ 修改规则模板

### 修改接口的变更
`RuleReqV1`结构体的`value` 字段弃用，改为`params` 字段，对应的是结构`RuleParamResV1`列表，对应下面字段：
1. `key` ：该配置项的主键
2. `value`：该配置项的值
