### ISSUE TITLE
sqle-ui 前端代码编译报错，/src/App.tsx

### ISSUE THREAD

**Issue by theseusyang1** [actiontech/sqle#1171]
TypeScript error in /Users/theseusyang/代码/sqle-dev/sqle-ui/src/App.tsx(113,22):
This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided.  TS2746

    111 |                 <Suspense fallback={<HeaderProgress />}>
    112 |                   <EmptyBox if={!loading}>
  > 113 |                     <Switch>
        |                      ^
    114 |                       {registerRouter(globalRouterConfig)}
    115 |                       <Redirect to="/" />

**Comment by theseusyang1** [comment]
<img width="735" alt="4ec8f393d5f90e7c47c378249e87b24e" src="https://user-images.githubusercontent.com/113496312/205029028-eb4995ae-43cf-45d4-8262-24d02bc64058.png">

**Comment by sjjian** [comment]
问题社区群反馈，有专人支持
