### ISSUE TITLE
项目不存在时报错信息优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1174]
![img_v2_912d8a51-8586-49b7-9616-0f20ea9aacfg](https://user-images.githubusercontent.com/36940986/205541033-ff18bc0e-ba97-40f6-8001-688dd05de8b2.jpg)

报错信息改得自然一点

**Comment by ColdWaterLW** [comment]
改为“project [projec name] is not exist”

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.创建项目test1
2.进入到项目test1，然后创建工单但不提交
3.新开一个标签页，然后在项目管理界面删除项目test1
4.回到步骤2中的标签页，进行提交，提示test1项目不存在


<img width="1590" alt="image" src="https://user-images.githubusercontent.com/54339501/209620824-7716453a-d1b2-48f3-a395-8845b985a0b8.png">
