### ISSUE TITLE
错别字修正

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1175]
是连接用户，不是链接用户
![image](https://user-images.githubusercontent.com/36940986/205542585-06ae4a56-9cc8-4050-98d7-11339cfe6e8a.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3


已更正为连接用户
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/54339501/209746471-ea41e8c5-aae3-4b3e-a2f8-66672213d96a.png">
