### ISSUE TITLE
对pg进行上线特定的语句如"create index ..."会执行失败

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1180]
**SQLe Version**
sqle main

**Describe the bug**
对pg进行上线特定的语句如"create index ..."会执行失败。报错信息如下：
```bash
time="2022-12-07T11:19:28+08:00" level=info msg="start execution..." task_id=8 thread_id=A97
time="2022-12-07T11:19:28+08:00" level=info msg="execution is completed, err:unknown SQL type " task_id=8 task_status=exec_failed thread_id=A97
```

**To Reproduce**
1. 搭建带pg审核插件的SQLE平台，并配置好数据源等环境
2. 提前创建表 `CREATE TABLE t1(id int);`
3. 提交工单，SQL为`CREATE INDEX "index_id" ON "t1" USING btree ("id");`
4. 工单上线，结果为执行失败

**Comment by sjjian** [comment]
## 原因
SQLE 进行上线时会判断对DDL和DML采用不同的上线模式，DML会使用事务上线，对于非DDL和DML类的语句直接报错不执行。那么存在两个问题：
1. SQL的类型由审核插件判定，插件是否能完全处理所有类型
2. SQLE 是否不上线非DDL和DML的SQL语句不合理

本次 issue 是由于pg插件未处理所有SQL类型，将“create inde” 定义为其他类型导致SQLE上线报错。

## 建议
1. SQLE侧完善上线流程
2. pg插件判定SQLE类型优化，至少对常用的SQL类型定义在详细处理

**Comment by HuangWeiCen** [comment]
# 修复说明

## 插件修复说明
经复现, 企业版PG插件未发现此问题, 社区版PG插件复现成功, 仅需修复社区版插件即可

### 企业版复现结果
![image](https://user-images.githubusercontent.com/37464327/206364617-ff23c1df-a71e-4505-9ed6-9253c3388dfa.png)
![image](https://user-images.githubusercontent.com/37464327/206364627-b08429ba-681f-417a-820d-97d4bce18202.png)

### 社区版复现结果
![image](https://user-images.githubusercontent.com/37464327/206364647-c94b8638-7624-4ab5-b302-55bd60133239.png)
![image](https://user-images.githubusercontent.com/37464327/206364674-c3b6fdbc-81a1-494c-88a8-7915450e5060.png)

## SQLE 修复说明
经查看代码, SQLE 在发现SQL既不是DML也不是DDL时会拒绝上线并报错, 现放开此限制

# 修复方式

## 插件修复方式
使用企业版的sql类型判断函数替换社区版的sql类型判断函数

## SQLE修复方式
在发现 SQL 类型无法识别时依然执行此SQL, 但增加日志和SQL执行结果告知用户这条SQL类型无法识别
![image](https://user-images.githubusercontent.com/37464327/206365233-b40d6ff9-ec4a-47d0-8391-626ec28e5c53.png)

**Comment by HuangWeiCen** [comment]
# 排查结论
目前插件中被当作DML的语句都支持以事务的方式执行
![image](https://user-images.githubusercontent.com/37464327/206387066-87147e6f-c718-4d14-810f-3988706c29ce.png)


# 自测流程

1. 执行alter table, 执行成功
![image](https://user-images.githubusercontent.com/37464327/206387150-6bf08d7f-78b8-47d5-8de3-63d82bee3228.png)

2. 执行create index, 执行成功
![image](https://user-images.githubusercontent.com/37464327/206387542-0360aaf4-96b5-4f1e-95da-a11d1d2ff82e.png)

3. 执行 create user, 执行成功
![image](https://user-images.githubusercontent.com/37464327/206387582-12b5d1ef-bcfe-40e7-8fb4-51b934518750.png)

**Comment by Marcus9530** [comment]
因pg插件已经修复，无法使用之前审核插件进行复现，故直接验证，不再复现。

**Comment by Marcus9530** [comment]
验证版本
UI Version: main d121bfc
Server Version: main 74ce317940
验证步骤：
1.添加一个pg数据源
2.然后创建工单，创建对表创建index，可以正常上线
3.继续创建工单，对表进行alter table，也可以正常上线

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/54339501/209909445-fb81f2b8-1f05-49a4-af22-75da5b801795.png">

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/54339501/209909376-26923492-f2b5-4690-bd95-35b130a0560a.png">
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/54339501/209910169-ec17cc42-4ffb-4c74-b829-29e0f5ea58dd.png">
