### ISSUE TITLE
项目成员功能优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1182]
## 1. 添加项目成员时，建议增加检索功能
**现状**：关联用户时，当前通过下拉列表选择
**问题**：若平台用户有50个，需要列表一条条拉过来寻找，效率较低无法快速找到对应成员
**预期**：关联用户时，筛选框也提供检索功能，方便项目管理员在添加成员时快速定位
**原型**
检索前
![image](https://user-images.githubusercontent.com/36940986/206114805-bfa42282-2373-4d74-9e12-2c140d5eaeac.png)

检索后
![image](https://user-images.githubusercontent.com/36940986/206114819-0bc3e195-8837-494a-bfdc-9e47c70e015b.png)

## 2. 赋权时，数据源与角色选框位置对调
**现状**：关联用户时，先选角色后选数据源
**问题**：平台当前逻辑为：针对具体数据源，给对应用户/用户组赋予角色权限，当前排布无法体现这一点
**预期**：赋权时，优先选数据源，在数据源基础上选角色操作权限
**原型**
![image](https://user-images.githubusercontent.com/36940986/206115003-4103abdb-0608-4e01-97f0-b578c7875bc3.png)

## 3. 添加项目用户组时，显示组内成员
**现状**：当前关联用户组时，无从知晓组内成员有哪些，添加成功后，也无法知晓组内成员
**预期**：预期需要在选择用户组时，显示组内成员名称；添加成功后，在用户组列表页也能查看组员名称
**效益**：增加用户组组员信息，方便项目管理员选取对应成员组

**原型**
点击关联用户组，显示可用用户组，鼠标移入，显示组内成员
![image](https://user-images.githubusercontent.com/36940986/206115517-b282a634-4f32-404a-aaec-9c8ff027858d.png)

用户组添加完成后，显示组名及组员信息，用户组成员过多的话用省略号收起来，鼠标悬停展示全部成员
![image](https://user-images.githubusercontent.com/36940986/206115564-6fcf1375-185c-4b25-87db-01d19f0f318b.png)

## 4. 为项目成员、成员组添加角色时，显示角色权限
**现状**：当前编辑成员、成员组角色时，无从知晓所选角色有哪些权限
**预期**：在选择角色时，显示组角色权限
**效益**：增加角色权限信息，方便项目管理员选取对应角色
原型参考第3点，用户组组内成员显示方式

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3

优化场景1:
当前项目成员可以进行检索，并展示对应的信息
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/54339501/209746951-ff6f8910-8f07-44b4-9bb5-db9371112391.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/54339501/209746961-f7e25680-398d-4649-9ce2-785db368bd6a.png">
优化场景2:
添加项目成员的时候，数据源位置靠前，成员组也是如此
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/54339501/209747118-ab90851c-cc56-478b-9333-5e2069f9dfb1.png">
<img width="1722" alt="image" src="https://user-images.githubusercontent.com/54339501/209747165-1f9ea546-355c-479c-a8d6-dd556f918e92.png">
优化场景3:
在项目内添加的成员用户组，可以展示对应的用户组内的用户信息
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/54339501/209749903-fb04e510-6613-4ab5-a9b9-28ede4296315.png">

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/54339501/209749873-9ec1a033-10f0-4edd-b453-3225c371344c.png">
优化场景4:
无论是成员还是成员组在添加权限的时候都可以展示出角色对应的权限信息
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/54339501/209750020-960f51ef-0460-4957-81a9-5b6946837886.png">
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/54339501/209750050-f17c41dc-2abe-4903-834f-8347bf5f65e8.png">
