### ISSUE TITLE
关闭工单后，数据源下可操作按钮立即变灰

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1183]
现状：关闭工单后，工单下数据源不可再操作
问题：工单下数据源“立即上线/定时上线”按钮仍为可点击的状态，需刷新后才变灰
![image](https://user-images.githubusercontent.com/113898890/206130965-7abd1883-c16b-4015-8dd6-65745a0291b8.png)
需求：关闭工单后，工单下数据源“立即上线/定时上线”按钮立即变灰，表示不可再操作

**Comment by Marcus9530** [comment]
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/54339501/220832204-2f6dad71-0620-4235-8a54-e673f0f944c8.png">
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/54339501/220832264-23d11ea1-f0c1-4a36-84c1-ae24dbde304e.png">
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/54339501/220832448-69209158-ae8b-479f-924f-6837c8785b9c.png">
