### ISSUE TITLE
界面优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1192]
## 1. 更改流程模板中权限选项的说明
**现状**：
审核/上线步骤中，匹配用户匹配的实际是对具体数据源有审核/上线权限的用户，而非项目内拥有审核/上线权限的所有用户

**预期**：
“匹配所有拥有审核权限的用户”修改为“匹配拥有数据源审核权限的成员”
“匹配所有拥有上线权限的用户”修改为“匹配拥有数据源上线权限的成员”

**效益**：
减少理解歧义

**影响范围**：
修改模板流程页
流程模板页

## 2. 流程模板展示匹配权限用户的提示
**现状**：
流程模板中添加一层审核环节，匹配具有审核权限的用户
![image](https://user-images.githubusercontent.com/36940986/206970626-cb96dbb5-a018-45e6-8051-84dc144326ea.png)
保存后，该步骤下审核人信息缺失
![image](https://user-images.githubusercontent.com/36940986/206970653-40740e4f-64a3-49a4-95d1-ef359547066f.png)

**预期**：
显示该步骤下对应审核人提示“匹配拥有数据源审核权限的成员”
![image](https://user-images.githubusercontent.com/36940986/207215744-6190d6b6-0daa-445d-ab8e-404e8f4b70cc.png)

**效益**：
避免该流程模板内容空缺导致的疑惑

**影响范围**：
流程模板页面

**原型**：

## 3. 流程模板单个步骤内各要素保持等距，增加步骤间间距
**现状**：
当前流程模板的单一步骤内各要素间距不一致
![image](https://user-images.githubusercontent.com/36940986/206970884-66728b6a-17f3-459e-b0db-0dfdc82150a1.png)

**预期**：
单个步骤内各要素保持等距，不同步骤间增加距离

**效益**：
提高页面易读性、段落感

**影响范围**：
流程模板页面

**参考原型**：
![image](https://user-images.githubusercontent.com/36940986/206970976-e85b4fb3-6c48-4c00-b160-d84035e31257.png)

## 4. 流程模板各步骤说明隐藏，鼠标移入后显示
**现状**：
当前审核流程各步骤说明跟随在步骤节点后，页面相对不整洁
![image](https://user-images.githubusercontent.com/36940986/207216006-3ede53db-4a25-47c6-9dfd-1457e2c78dbd.png)

**预期**：
流程模板各步骤说明隐藏，移入后显示
![image](https://user-images.githubusercontent.com/36940986/207216061-5ff77abe-4d46-4d05-91cf-3885478f3bf9.png)

**效益**：
提高页面整洁程度

**影响范围**：
- 流程模板页面
- 编辑流程模板页面

## 5. 创建工单时，页头提示文字内容重复
**现状**：
创建工单时，页头提示文字为“工单基本信息”，与页面中的“工单基本信息”模块重复，建议修改页头文字
![image](https://user-images.githubusercontent.com/36940986/206976453-ee98b6c9-23ec-4493-97db-4f0d95aa3a7b.png)

**预期**：
修改页头文字为：创建工单

**影响范围**：
创建工单页

原型：
![image](https://user-images.githubusercontent.com/36940986/206976525-9fba0aa4-2155-4102-a8d9-9c33ed633b31.png)

## 6. 数据源列表筛选项去掉“连接用户”
连接用户作用是连入数据源，不作为区分数据源的有效标志，建议去除该筛选项
![image](https://user-images.githubusercontent.com/36940986/206976719-a20e0e07-db46-4011-97c2-f24269e81c40.png)

## 7. 点击规则模板名称，跳转规则详情页面
**现状**
当前查看规则模板中应用的规则，需要点击顶部标签栏“规则”标签，筛选项目、模板后，查看该模板下应用的规则
无法直接查看查看当前项目下某个规则模板应用的规则
![image](https://user-images.githubusercontent.com/36940986/206978538-90c3c6e8-6f2e-4787-a3b6-ce322a1d6129.png)

**需求预期**
在规则模板列表、数据源列表、智能扫描列表中，点击规则名称，跳转规则页面，查看该规则模板应用的规则

**效益**
当成员在项目中，需要查看规则列表中某个规则模板应用的规则时，点击规则名称即可跳转，无需切换页面再做筛选，减少查看成本

**影响范围**
- 全局/项目规则模板列表
- 规则页面
- 数据源列表
- 智能扫描列表

**原型**
![image](https://user-images.githubusercontent.com/36940986/206978826-a757463e-9f16-4523-bf83-bb9e6c384f6d.png)

## 8. 项目中显示公共模板及项目模板
**现状**
规则模板区分全局模板及项目内部模板
当前项目内规则模板列表仅显示项目内创建的模板，不显示全局模板
全局模板仅在数据源关联模板的时候，通过下拉选项了解

**需求预期**
项目内
- 规则模板列表中增加一个字段【属性】，区分公共模板及项目模板
- 只有admin可以编辑公共模板
- 列表外增加筛选项，筛选公共模板、项目模板

**效益**
能查看到项目中可用的全部规则模板并筛选

**影响范围**
项目规则模板页

**原型**
![image](https://user-images.githubusercontent.com/36940986/207801782-4d40458f-f281-40ae-b1ad-0ae2d1705e93.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3

优化场景1:
文案已做变更
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/54339501/209639450-6aacce71-ae56-4754-9794-6cffa9fd9444.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/54339501/209639479-17c3a18b-6f08-410d-b97b-fe24ca445359.png">
优化场景2:
添加一层审核步骤，选择匹配具有审核权限的用户，保存之后依旧显示匹配拥有数据源审核权限的成员
<img width="606" alt="image" src="https://user-images.githubusercontent.com/54339501/209640225-632b3f0f-07b5-4b24-94a5-87899381802f.png">
优化场景3:流程模板单个步骤内各要素保持等距，增加步骤间间距
<img width="602" alt="image" src="https://user-images.githubusercontent.com/54339501/209640676-5731b554-c05a-46df-af52-444c4ad6e1cd.png">
优化场景4:步骤说明已移入tips提示里面
<img width="699" alt="image" src="https://user-images.githubusercontent.com/54339501/209640818-ba9fed66-8914-4e67-8270-319e9098c966.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/54339501/209640841-86dec820-512f-4993-8ecc-a0c3db45b81c.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/54339501/209640856-4fa38852-47e0-4a7e-b1fe-1b26e3b3d8b1.png">
优化场景5:
创建工单界面，文字已不在重复
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/54339501/209641042-81cd64eb-36c7-4cc1-9d6b-d654f2b49d9b.png">
优化场景6:
s数据源界面搜索添加已无连接用户
<img width="1895" alt="image" src="https://user-images.githubusercontent.com/54339501/209641181-d517afff-fa46-469e-8585-c991d4663b44.png">
优化场景7:
数据源界面跳转
<img width="1804" alt="image" src="https://user-images.githubusercontent.com/54339501/209641870-e8651103-889b-4bea-9a99-76acb4321405.png">
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/54339501/209641891-dc1130fa-1298-4c20-863c-df2a4ee126a3.png">
智能扫描任务界面跳转
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/54339501/209641987-d3810a96-c294-4ae4-b9b6-5a72cd68315f.png">
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/54339501/209642012-f4e90799-6b63-48d1-83b9-f5d8101da563.png">
规则列表界面跳转
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/54339501/209642044-f5daa6d3-7da8-4dde-9e2d-67f7f04b4e4c.png">
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/54339501/209642071-acbbc6f0-d25c-4948-9ae8-977e0c03fbe2.png">
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/54339501/209642149-6aecbd67-3cc4-4c3e-ac60-0e11d53a5749.png">
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/54339501/209642194-bc115a21-792a-4b1a-9406-1aac46b4c657.png">
优化场景8:项目中显示公共模板及项目模板
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/54339501/209642690-71264419-e5ec-4dcb-9862-bdeaa4acc972.png">
