### ISSUE TITLE
解析MyBatis XML文件报错 <otherwise> data is invalid

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1193]
**SQLe Version**

sqle main

**Describe the bug**

解析MyBatis XML文件报错 <ohterwise> data is invalid，当otherwise标签内有<if>等其他嵌套标签时。测试用例：
```xml
<mapper namespace="Test">
    <select id="testChoose">
        SELECT
        *
        FROM
        fruits
        <where>
            <choose>
                <when test="name != null">
                    AND name = #{name}
                </when>
                <otherwise>
                    <if test="price != null and price !=''">
                        AND price = ${price}
                    </if>
                </otherwise>
            </choose>
        </where>
    </select>
</mapper>
```
**Expected behavior**

期望正常解析

**Comment by sjjian** [comment]
## 原因
当前的的mybatis xml 解析器只支持解析 otherwise 标签内写纯文本的SQL判断。当otherwise标签内带if标签时会报解析出错

**Comment by sjjian** [comment]
## 复现
![image](https://user-images.githubusercontent.com/18008452/207239364-111142ff-9899-4723-854c-0392bad16485.png)
## 验证
![image](https://user-images.githubusercontent.com/18008452/207240697-abc053be-66eb-4ec3-b116-4b66931c585e.png)

**Comment by Marcus9530** [comment]
UI Version: main 8925aed
Server Version: main-ee 0b72a93f63
复现步骤：
1.使用上述的xml文件创建工单时，选择上传mybatis文件，然后出现报错信息

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/54339501/209635363-cb2c2e25-98e7-43b6-84cc-a51c011ace39.png">

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.使用上述的xml文件创建工单时，选择上传mybatis文件，可以正常审核，没有出现报错信息



<img width="1729" alt="image" src="https://user-images.githubusercontent.com/54339501/209635610-b6881291-a9fc-4fd3-8acf-f3a563fd179e.png">
