### ISSUE TITLE
定时上线的工单仍可以通过调接口驳回

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1196]
现状：处于定时上线状态的工单在界面上是不能被驳回的，但是调用工单驳回接口还是可以驳回。
期望：前后端逻辑统一，处于定时上线状态的工单不能被驳回

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-2.2211.x ff420bf
Server Version: release-2.2211.x 0099984568
复现步骤：
1.创建一个工单，然后设置定时上线
2.然后在swagger界面调用驳回工单接口对其进行驳回
3.驳回成功，回到界面上查看，该工单确实驳回成功

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/54339501/209774957-cfa99f91-1054-4630-a26c-70328e1d5376.png">
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/54339501/209774997-d7c0f1c2-c299-49db-9878-a0d6b7af7c5c.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/54339501/209775022-c779e531-6113-48da-9424-ce7aae1c5800.png">

**Comment by Marcus9530** [comment]
验证版本
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：

1.创建一个工单，然后设置定时上线
2.然后在swagger界面调用驳回工单接口对其进行驳回
3.驳会失败，回到界面上查看，依旧为定时上线状态


<img width="1827" alt="image" src="https://user-images.githubusercontent.com/54339501/209775575-58e05df8-223e-461b-a8b6-6450eef756a8.png">
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/54339501/209775677-e2bc1460-6bdd-42b8-9644-9657a31647c3.png">
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/54339501/209775708-b606649e-56e9-4943-bf36-24f4367f38c9.png">
