### ISSUE TITLE
创建的项目设置好项目成员之后，如果把该项目直接删除，重新创建一摸一样的项目名字，成员依旧存在。

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1204]
**SQLe Version**
Server Version: main-ee 00e48a44a8

1.创建一个项目test1
2.在项目test1下添加一个项目成员user1
3.使用admin用户删除test1项目
4.创建新的项目，名字依旧为test1
5.然后进入到test1项目里面，可以看到已经有一个成员use1
理论上删除重新创建的项目，依旧为默认初始化的项目，不应该保留上一个项目的信息。

**Comment by HuangWeiCen** [comment]
# 修复内容
1. 修复成员列表接口存在已删除项目中的成员
2. 修复成员tips接口存在已删除项目中的成员
3. 修复成员组列表接口存在已删除项目中的成员组
4. 修复成员组tips接口存在已删除项目中的成员组
5. 修复用户tips接口启用项目过滤器时存在已删除项目中的成员

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.创建一个项目test1
2.在项目test1下添加一个项目成员user1
3.使用admin用户删除test1项目
4.创建新的项目，名字依旧为test1
5.然后进入到test1项目里面，当前已经看不到任何成员
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/54339501/209619363-c530bd51-0a10-49af-b78f-3f83b371c05e.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/54339501/209619381-00cd36b2-5597-478d-b218-b28756965f54.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/54339501/209619385-cb7f7c9d-cc65-4de0-b553-2e0665b45908.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/54339501/209619400-c0dc4b25-be1e-4d0c-a0bd-0ba007b437e0.png">
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/54339501/209619451-17242ba4-c64a-43a0-84db-5d6bc79c4b1e.png">
