### ISSUE TITLE
数据源的下拉tips显示ip、port

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1211]
创建工单时辨认数据源非常不便利，特别是从dmp同步过来的数据源，下拉展示的是dmp的实例组ID，有些是随机生成的，没有规则性

**Comment by HuangWeiCen** [comment]
# 调整方式
API增加 ip , port 两个参数, 前端可使用这两个参数拼出对应提示信息
![image](https://user-images.githubusercontent.com/37464327/208624455-4a1021de-7849-49b2-b3cb-dfee91c541c6.png)

**Comment by HuangWeiCen** [comment]
# 自测流程
1. 使用admin登录, 调用此接口, 返回数据正常
![image](https://user-images.githubusercontent.com/37464327/208629290-f8c60ff6-f617-4548-8510-4b2b5c856834.png)
2. 使用一个普通用户登录(非管理员非admin), 调用此接口, functional_module选一项, 返回数据正常
![image](https://user-images.githubusercontent.com/37464327/208629339-90b4616d-b8bf-4979-b998-27fd8ab1eb59.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.创建多个数据源
2.使用admin登录，然后创建工单，查看数据源，发现可以看到ip+端口
3.切换到普通用户，然后创建工单，查看数据源，也可以看到ip+端口


<img width="1353" alt="image" src="https://user-images.githubusercontent.com/54339501/209765626-11c932dd-fd8a-49cb-8b6a-de7b5a4852de.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/54339501/209766270-bd6ce6f6-25f9-495f-9c1e-13063423026a.png">
