### ISSUE TITLE
顶部项目管理标签支持直接切换项目

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1212]
**现状**
企业版，用户进入/切换项目时需要的动作：点击顶部标签“项目”，跳转到项目列表页，选中列表中的项目，跳转项目详情页，需要操作的步骤较多

**期望**
点击“项目”标签，显示下拉菜单，包含三个要素

【全部项目】点击跳转所有项目页
【搜索框】点击检索关键词，根据关键词匹配项目名称，模糊检索
【最近打开的项目】根据时间倒序排序，展示最近进入过项目详情页的项目，三个；若为首次登录，则最近打开项目保持为空

**原型参考**
![img_v2_223658fb-ae1f-4110-9754-cf75801d374g](https://user-images.githubusercontent.com/36940986/208568368-3aaf531e-c3a9-4d7a-b694-86980bcbc1db.jpg)

检索时，输入关键词显示项目名称，检索结果最多同时显示三条，更多检索结果通过右侧滚动条实现
![img_v2_ba2279e6-e6e2-4ffa-9bbe-9de8da23b22g](https://user-images.githubusercontent.com/36940986/208570296-fddb6d5a-4620-455d-8a3d-809ca873abc8.jpg)

若首次登录，没有最近打开的项目，则在“最近打开项目”下显示“暂无最近打开的项目”字样
![img_v2_2c9ade96-f8b8-4b4e-9e20-9fe9506ec84g](https://user-images.githubusercontent.com/36940986/208571998-0c90b782-b421-43e5-9da1-b3a739151acc.jpg)

**优化原因**
- 减少用户进入步骤
- 方便用户获得最近查看的项目信息

**Comment by Gygkimo95** [comment]
点击“项目”标签，显示下拉菜单，包含三个要素
- 【所有项目】，点击跳转所有项目页
- 【搜索框】，点击检索关键词，根据关键词匹配项目名称，模糊检索
- 【最近打开的项目】，根据时间倒序排序，展示最近进入过项目详情页的项目，三个

![image](https://user-images.githubusercontent.com/113898890/208406637-cf2bdfe7-248b-4c2e-ad3f-ecd5449dd0a3.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.不创建任何项目，然后点击顶部导航栏，可以看到提示暂无最近打开的项目
2.场景几个项目，然后分别进去到项目里面，点击顶部导航栏，可以看到最近打开的3个项目
3.点击顶部导航栏项目，进行搜索还可以展示对应的符合条件的项目名

<img width="536" alt="image" src="https://user-images.githubusercontent.com/54339501/209764249-ca02b423-4e8f-4aa0-b42a-2af0481f863b.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/54339501/209764435-b7ea89b9-24a4-4354-bde7-f416be5d5724.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/54339501/209764659-53fca73e-81df-4b49-9f0c-765db77e0470.png">
