### ISSUE TITLE
去掉从规则模板侧绑定数据源的功能

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1213]
仅支持在数据源管理页面，绑定数据源使用的规则模板

1. 需要隐藏相关规则模板页面中的"应用的数据源"要素
影响范围：
- 创建规则模板
- 编辑规则模板
- 导入规则模板
- 克隆规则模板

2. 去掉规则模板列表的“绑定的数据源”列
影响范围：
- 项目下的两个规则模板列表
- admin管理的全局规则模板列表

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
当前创建规则模板、编辑规则模版、导入规则模版、克隆规则模版都没有绑定数据源功能，并且无论是项目的规则模版列表还是全局规则模版列表都没有数据源列

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/54339501/209763856-bcbb01b6-e85f-44ef-b142-ede8051dfe6a.png">
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/54339501/209763882-5b579843-ea4e-434b-81d3-d9525e57011e.png">
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/54339501/209763904-ee78d616-9c03-47df-b35a-a7072cd68886.png">
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/54339501/209763924-ce55fe91-3c75-4cbd-b0ca-8f123eb5897a.png">
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/54339501/209763942-b2a6d9ff-ac7c-48b9-a598-4e28e1199569.png">
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/54339501/209763950-e1d1f8e5-bfd6-4aa0-8e10-7a7176ad007f.png">
