### ISSUE TITLE
审核插件中，xml文件的审核结果有误

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1218]
**SQLe Version**
  main 30405cbe30

**Describe the bug**
使用插件审核xml文件，出现错误

- sql分句不正确
- 由于分句不正确，导致审核结果只有“语法错误或解析器不支持，请人工确认SQL正确性”，审核结果无法给出具体的修改意见

**To Reproduce**
针对同一文件，
下图为平台审核结果
![image](https://user-images.githubusercontent.com/113898890/208808359-390c90aa-4c91-41d2-aea0-80327c83a9e4.png)
下图为审核插件返回的审核结果
![image](https://user-images.githubusercontent.com/113898890/208808422-8a90aef7-dcd7-478d-b661-813134df8e4e.png)

**Expected behavior**

- 审核插件需要正确划分sql语句
- 需要针对具体sql返回具体的审核结果

xml文件内容
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.mapperxml.select.SelectMapper">
    <!-- 启用全局二级缓存
         文件中所有 select 结果将会缓存
         文件中 insert, update, delete 将会刷新缓存
         使用 LRU 算法清楚缓存
     -->
    <cache/>
    <!-- 接收一个 int 返回 hashmap (列名作为键, 列值作为值) -->
    <select id="selectPerson" parameterType="int" resultType="hashmap">
        SELECT * FROM users
    </select>

    <!-- $符号只进行字符串替换 -->
    <sql id="idAndName">
        ${alias}.id, ${alias}.name as ${alias}_name
    </sql>

    <select id="selectPersonProp" resultType="map">
        select
        <include refid="idAndName"><property name="alias" value="t1"/></include>,
        <include refid="idAndName"><property name="alias" value="t2"/></include>
        from person as t1, author as t2
        where t1.id = t2.id
    </select>

    <!-- 下划线自动转驼峰需要在 mybatis-config.xml 中有额外的配置 -->
    <select id="selectPersonObj" resultType="com.example.mapperxml.bean.Person">
        SELECT * FROM person WHERE id = #{id}
    </select>
    <select>
        select * from mysql.user;
    </select>
</mapper>
```

**Comment by HuangWeiCen** [comment]
## 问题结论
正常操作的情况下未发现此问题, xml文件审核结果与预期一致
![image](https://user-images.githubusercontent.com/37464327/208860908-0246f5be-6606-4230-b910-801147d3f102.png)

## 审核结果异常原因猜测

### 1. 使用v0.1.0版本的插件进行审核的
v0.1.0版本的插件不支持mybatis文件审核, 建议升级插件, 升级方式: 卸载旧插件, 安装新插件

### 2. 使用v0.2.0版本的插件但xml文件的后缀名是 .sql
将文件后缀名改为 .xml 并使用 Mybatis Audit 选项进行文件审核
![image](https://user-images.githubusercontent.com/37464327/208861561-d534f547-5f6d-4fb9-9566-ed1a76232f8c.png)

@Gygkimo95 请检查一下是否为上述两个错误操作之一
