### ISSUE TITLE
增加访问sqle的url地址前缀

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1224]
关联issue #1177 

**Describe**
钉钉端审批增加工单链接地址

**Suggestion**
系统配置->全局配置增加url地址前缀配置，类似 http://x.x.x.x:10000 这种形式，期望检测下 ip ，端口的格式
![54dd948d-f3f1-458c-9e76-520bba666c29](https://user-images.githubusercontent.com/63177450/209768452-7300d20d-eade-4e3e-89d9-a6c84f17fdc3.jpeg)

前端感叹号提示信息：配置能访问sqle的url地址信息，用于IM审批通知

**Why**
用户可能配置各种代理，端口映射。sqle无法获取能访问sqle的url地址，需要用户自己配置。

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 4842afb
Server Version: main-ee 17dd4ca441
验证步骤：
1.在系统设置中设置url地址前缀
2.然后触发钉钉审核提示信息，可以看到工单链接中的地址就是设置的url地址

<img width="439" alt="image" src="https://user-images.githubusercontent.com/54339501/210052642-9904fc75-ba13-4130-978b-0980e421543f.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/54339501/210052671-91b9582d-18b9-4445-948a-a4fa095444f2.png">
