### ISSUE TITLE
测试钉钉AppKey和AppSecret是否正确

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1227]
关联issue #1177 

**Describe**
有测试按钮可以验证钉钉AppKey和AppSecret填写是否正确

**Suggestion**
类似 SMTP ，在钉钉配置左边增加 测试 按钮
![image](https://user-images.githubusercontent.com/63177450/209771998-2c7b1a2f-7417-4463-b343-ce0543d3f8e5.png)

**Why**
用来验证钉钉AppKey和AppSecret填写是否正确

**Comment by taolx0** [comment]
自测
1. appkey ，appsecret 正确的情况
![image](https://user-images.githubusercontent.com/63177450/210318321-52014b44-5c39-4c1a-a6b3-62cd713dad0d.png)

2. appkey,appsecret 未配置
![image](https://user-images.githubusercontent.com/63177450/210318566-3972dad3-16a0-499c-a571-8c0b21385ffc.png)

4. appkey,appsecret 错误
![image](https://user-images.githubusercontent.com/63177450/210318510-44ebc806-13f3-4f7a-8fbf-2536000fa616.png)

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证通过
验证步骤：
1.appkey ，appsecret 填写正确，然后点击测试
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/54339501/220827484-2e4e886b-ed32-4053-b809-00affd974c41.png">
2.appkey ，appsecret 填写错误，然后点击测试
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/54339501/220827855-2f324bc2-7e4d-400c-abbe-ed59e9363dd6.png">
3.appkey ，appsecret 不配置的情况下，点击测试
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/54339501/220827914-83645783-b9f9-463c-9670-e6a39412b6c3.png">
