### ISSUE TITLE
支持集成 cloudbeaver 最新版本

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1237]
目前只支持22.2.0版本，期望支持最新版，兼容22.2.0

**Comment by HuangWeiCen** [comment]
# 新增兼容版本
22.3.1 版本

# 自测流程
1. 使用SQLE集成 22.3.1版本的Cloudbeaver
![image](https://user-images.githubusercontent.com/37464327/210942170-c80e9879-cc5c-440e-af12-47ca67a892dd.png)
2. 进入SQL工作台, 并使用admin登录
![image](https://user-images.githubusercontent.com/37464327/210942260-ce0dd99b-830a-4ca6-babb-1c5e2d9070c8.png)
3. 登陆成功, 检查数据源展示正常
![image](https://user-images.githubusercontent.com/37464327/210942361-ee2b0683-20e9-404a-ae6d-ac3e34b589b7.png)
4. 连接一个数据源, 连接正常
![image](https://user-images.githubusercontent.com/37464327/210942423-05c2f8f8-1091-4ff8-8e36-f8a1c3ddcee1.png)
5. 执行一条审核失败的SQL, 正常报错, 报错内容正确
![image](https://user-images.githubusercontent.com/37464327/210942487-df6d0b1f-5b68-46d7-9654-25814d27c8d5.png)
![image](https://user-images.githubusercontent.com/37464327/210942507-60636513-b67c-4ff5-a723-534ebd85b79a.png)
6. 执行一条审核通过的SQL, 执行正常
![image](https://user-images.githubusercontent.com/37464327/210942563-9403938a-5367-4d7a-ae8a-a6181647088d.png)
7. 修改一个数据源的信息
![image](https://user-images.githubusercontent.com/37464327/210942701-b24403cb-c978-4a20-9a3c-31d44bfa1350.png)
8. 重新登录CloudBeaver, 发现数据源信息修改成功
![image](https://user-images.githubusercontent.com/37464327/210942801-708b38a5-237e-45cf-a24b-b7fee2e19255.png)
9. 使用普通用户登录Cloudbeaver
![image](https://user-images.githubusercontent.com/37464327/210942876-0a59d866-8da2-42c1-912a-085102a856c1.png)
10. 从SQLE修改用户密码
![image](https://user-images.githubusercontent.com/37464327/210942932-7b3bd742-985a-4fc8-9916-0a5943ceff78.png)
11. 用新密码登录Cloudbeaver, 登陆成功
![image](https://user-images.githubusercontent.com/37464327/210943004-897959d4-365a-4684-bc5a-07f0d7f6b234.png)
12. 检查日志没有异常情况
![image](https://user-images.githubusercontent.com/37464327/210943031-c1ee4dda-d987-4209-8858-3651ff315017.png)

**Comment by HuangWeiCen** [comment]
# 自测流程
1. 使用SQLE集成 22.3.1版本的Cloudbeaver
![image](https://user-images.githubusercontent.com/37464327/210942170-c80e9879-cc5c-440e-af12-47ca67a892dd.png)
2. 进入SQL工作台, 并使用admin登录
![image](https://user-images.githubusercontent.com/37464327/210942260-ce0dd99b-830a-4ca6-babb-1c5e2d9070c8.png)
3. 登陆成功, 检查数据源展示正常
![image](https://user-images.githubusercontent.com/37464327/210942361-ee2b0683-20e9-404a-ae6d-ac3e34b589b7.png)
4. 连接一个数据源, 连接正常
![image](https://user-images.githubusercontent.com/37464327/210942423-05c2f8f8-1091-4ff8-8e36-f8a1c3ddcee1.png)
5. 执行一条审核失败的SQL, 正常报错, 报错内容正确
![image](https://user-images.githubusercontent.com/37464327/210942487-df6d0b1f-5b68-46d7-9654-25814d27c8d5.png)
![image](https://user-images.githubusercontent.com/37464327/210942507-60636513-b67c-4ff5-a723-534ebd85b79a.png)
6. 执行一条审核通过的SQL, 执行正常
![image](https://user-images.githubusercontent.com/37464327/210942563-9403938a-5367-4d7a-ae8a-a6181647088d.png)
7. 修改一个数据源的信息
![image](https://user-images.githubusercontent.com/37464327/210942701-b24403cb-c978-4a20-9a3c-31d44bfa1350.png)
8. 重新登录CloudBeaver, 发现数据源信息修改成功
![image](https://user-images.githubusercontent.com/37464327/210942801-708b38a5-237e-45cf-a24b-b7fee2e19255.png)
9. 使用普通用户登录Cloudbeaver
![image](https://user-images.githubusercontent.com/37464327/210942876-0a59d866-8da2-42c1-912a-085102a856c1.png)
10. 从SQLE修改用户密码
![image](https://user-images.githubusercontent.com/37464327/210942932-7b3bd742-985a-4fc8-9916-0a5943ceff78.png)
11. 用新密码登录Cloudbeaver, 登陆成功
![image](https://user-images.githubusercontent.com/37464327/210943004-897959d4-365a-4684-bc5a-07f0d7f6b234.png)
12. 检查日志没有异常情况
![image](https://user-images.githubusercontent.com/37464327/210943031-c1ee4dda-d987-4209-8858-3651ff315017.png)

**Comment by Marcus9530** [comment]
因受到https://github.com/actiontech/sqle/issues/1310该任务影响，无法再通过cloudbeaver界面进行登录，所以只测试sqle本身对cloudbeaver的兼容以及功能的正常使用,
22.2.0回归测试已经验证过，故不在重复验证
验证步骤
1.添加 22.3.1/22.2.3/22.2.1版本的Cloudbeaver
2.然后在sqle进行配置
3.打开工作台
4.数据源没有开启运行前审核的时候，输入一条sql语句正常执行
5.开启运行前审核的时候，输入一条sql语句出现审核提示
**cloudbeaver:22.2.3**
<img width="1831" alt="image" src="https://user-images.githubusercontent.com/54339501/221119523-80ad732e-3d33-4563-9df0-6137b4f1854b.png">
<img width="928" alt="image" src="https://user-images.githubusercontent.com/54339501/221121741-0d21ceb3-de6d-4772-aaf6-df439d101322.png">

**cloudbeaver:22.3.1**
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/54339501/221121587-f5d7fc51-9d17-4d42-9755-2b1d266a7a49.png">

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/54339501/221121656-7b458b49-4fe4-41b7-99b9-6979eeda3e2a.png">
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/54339501/221121714-f6199a96-dfd9-4c74-a6c6-15f1235c86e2.png">
**cloudbeaver:22.2.1**
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/54339501/221132814-f079866c-4bde-42d1-b129-86575faa290d.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/54339501/221132878-5dca4b46-660d-488c-b01f-ad13bf3c7146.png">
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/54339501/221132968-919dea10-2ff1-4bc5-883d-0908ae022a5b.png">
