### ISSUE TITLE
关闭工单时页面报错

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1241]
sqle版本：
<img width="426" alt="image" src="https://user-images.githubusercontent.com/36940986/210499983-8207e8c8-a29f-4197-bf87-63002e9f26ce.png">

复现步骤：
1. 创建工单
2. 在审核步骤驳回工单
3. 关闭工单

页面报错：
![image](https://user-images.githubusercontent.com/36940986/210498172-f01db7f3-d888-48d7-bca9-cc1558e13835.png)
![image](https://user-images.githubusercontent.com/36940986/210498219-85f99bf5-60ce-48bd-be9d-1f197d1cfd79.png)

日志发现panic信息：
```
echo: http: panic serving 192.168.21.249:53626: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x1e1d920, 0x3e75af0})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/actiontech/sqle/sqle/api/controller/v1.CancelWorkflow({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/sqle/api/controller/v1/workflow.go:572 +0x8ac
github.com/actiontech/sqle/sqle/api/middleware.licenseAdapter.func1.1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/sqle/api/middleware/license_qa.go:13 +0x42
github.com/actiontech/sqle/sqle/api/middleware.VerifyUserIsDisabled.func1.1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/sqle/api/middleware/verify_user.go:25 +0x1f0
github.com/labstack/echo/v4/middleware.JWTWithConfig.func1.1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/vendor/github.com/labstack/echo/v4/middleware/jwt.go:238 +0x603
github.com/actiontech/sqle/sqle/api/middleware.JWTTokenAdapter.func1.1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/sqle/api/middleware/jwt.go:26 +0x25c
github.com/labstack/echo/v4.(*Echo).add.func1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/vendor/github.com/labstack/echo/v4/echo.go:552 +0x88
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x2295d60, 0xc0016697c0})
	/usr/local/src/sqle/vendor/github.com/labstack/echo/v4/middleware/logger.go:117 +0x168
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000994240, {0x22586a8, 0xc001985880}, 0xc0015e2e00)
	/usr/local/src/sqle/vendor/github.com/labstack/echo/v4/echo.go:662 +0x2a2
net/http.serverHandler.ServeHTTP({0xc0001ce000}, {0x22586a8, 0xc001985880}, 0xc0015e2e00)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc00021aaa0, {0x226af78, 0xc00011cb80})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
```

**Comment by taolx0** [comment]
1. 驳回工单
![image](https://user-images.githubusercontent.com/63177450/210723720-c0450ef9-ff76-4897-b4e2-aa33cd56ace2.png)
2. 正常关闭工单

**Comment by taolx0** [comment]
https://github.com/actiontech/sqle/issues/1245#issue-1520291706

**Comment by Marcus9530** [comment]
UI Version: release-2.2212.x 4842afb
Server Version: release-2.2212.x-ee 17dd4ca441
复现步骤：

1. 创建一个工单
2. 然后在审核步骤驳回其工单
3. 关闭工单，出现报错信息，且后台出现panic信息

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/54339501/220837624-9eafdb39-3432-4f8a-b5ba-67653dfaaed0.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/54339501/220837646-57463e61-d729-4261-9f9d-a3c08564a97d.png">
![image](https://user-images.githubusercontent.com/54339501/220837817-b79c31bf-a2b3-4f95-85a1-d98ccf55b21f.png)

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证通过
验证步骤：

1. 创建一个工单
2. 然后在审核步骤驳回其工单
3. 点击关闭工单，没有出现任何报错，并且工单状态为关闭

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/54339501/220860818-2f9bfc69-7300-479d-b6b5-618de0adfc14.png">
<img width="1852" alt="image" src="https://user-images.githubusercontent.com/54339501/220860868-eb6e0bb5-2874-451f-b7e9-442b7571e470.png">
