### ISSUE TITLE
告警的信息内带上工单链接

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1248]
向用户发出的邮件、微信等通知内容中加上工单的链接

**Comment by HuangWeiCen** [comment]
## 修改内容
只增加了工单的地址, 扫描任务暂时没有加

### 没加原因

## 自测流程
1. 配置好SMTP, 企业微信, SQLE url
![image](https://user-images.githubusercontent.com/37464327/211965593-77a4a64e-af12-461f-9008-4f7fe0be660e.png)
2. 配置好用户的邮箱和微信ID
略
3. 创建一个工单
![image](https://user-images.githubusercontent.com/37464327/211965731-be0c56d7-d493-4651-af18-46a0ab17f6f0.png)
4. 确认微信收到消息
![img_v2_b68498ae-47c9-4ec5-bf07-01e72dacd98g](https://user-images.githubusercontent.com/37464327/211965835-a8d1f7a1-2880-44cf-bc5c-972391a2ab23.jpg)
5. 确认邮箱收到消息
![image](https://user-images.githubusercontent.com/37464327/211965874-faf2244b-2b0c-4cfe-8160-7c25af41b67b.png)
6. 确认链接内容正常
![image](https://user-images.githubusercontent.com/37464327/211965939-d899b917-3202-4989-bbbd-2eb18d542f4a.png)
7. 去掉全局配置中的sqle url
略
8. 再创建工单就没有相关信息了
![img_v2_f5dfa450-0ff6-4824-b784-6336c43735dg](https://user-images.githubusercontent.com/37464327/211966149-6b5440bc-833a-43a1-93a9-0865e664cfca.jpg)
![image](https://user-images.githubusercontent.com/37464327/211966184-446627ed-e40a-434e-994a-7ac825b8095c.png)

**Comment by Marcus9530** [comment]
UI Version: main 1d23c35
Server Version: main-ee a5dc40605f
验证通过
验证步骤
创建工单后，可以看到邮件，钉钉，企业微信收到的消息通知里面都带有工单链接


邮件
<img width="541" alt="image" src="https://user-images.githubusercontent.com/54339501/221109958-4633fcb7-5a51-460c-a104-88957d3679aa.png">
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/54339501/221110096-a8e5dbb8-08c6-49c8-b712-2014e727e557.png">
企业微信
![image](https://user-images.githubusercontent.com/54339501/221109875-5bd117ff-b95f-4389-9961-b573521464b5.png)
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/54339501/221110144-e567a887-0ae9-4895-98b1-4c8ca435a892.png">
钉钉
<img width="431" alt="image" src="https://user-images.githubusercontent.com/54339501/221109798-bfc27671-4547-42ea-ae96-d1964535e968.png">
钉钉工单链接打开错误的在这个任务修复：https://github.com/actiontech/sqle/issues/1332#issuecomment-1441431220

然后去掉url地址
<img width="331" alt="image" src="https://user-images.githubusercontent.com/54339501/221110414-c6654a8f-28e2-4317-95c2-6f08261b56af.png">
邮件
<img width="448" alt="image" src="https://user-images.githubusercontent.com/54339501/221110512-217ab19d-b899-4b02-b6d6-4f43a85c6f8f.png">
企业微信
![image](https://user-images.githubusercontent.com/54339501/221110560-af04bb74-541c-46f1-a574-71d3a3397193.png)
<img width="466" alt="image" src="https://user-images.githubusercontent.com/54339501/221110626-755eb531-2776-4c57-b9b7-29334feda819.png">
