### ISSUE TITLE
界面去掉废弃的参数

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1259]
这两个参数现在没有用到了，可以去掉
![img_v2_173c5cb5-7c9d-43f6-9193-74929ff608bg](https://user-images.githubusercontent.com/36940986/211702873-c2563f62-26ee-4bdd-ae4a-ce64dc275758.jpg)

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证步骤
当前添加数据源的时候，界面上已经移除了对应的两个废弃参数。
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/54339501/220858805-59e3b2b0-2861-41b3-ace0-5e0c62882f71.png">

但是需要考虑的是后端是否也要移除的对应的参数信息？
