### ISSUE TITLE
编辑数据源，若不需要审核SQL查询，则不显示审核等级筛选框

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1274]
**Describe**
编辑数据源信息页面，设置“SQL查询是否需要审核”：无论是否需要审核，设置审核等级的筛选框都存在，会误导用户。实际只有需要审核的情况，才需要设置等级。
![image](https://user-images.githubusercontent.com/113898890/212657136-32d346a2-435d-41ea-aff5-2ea6ed6cbb56.png)

**Suggestion**

* 若开启审核，显示并设置“运行查询的最高审核等级”筛选框
 ![image](https://user-images.githubusercontent.com/113898890/212656052-f5dfe7f6-66e3-4b3f-a158-e82b636d396a.png)
* 若不开启审核，不显示“运行查询的最高审核等级”筛选框
 ![image](https://user-images.githubusercontent.com/113898890/212656359-12a7c28e-437d-40f5-8d58-79771c7e6da7.png)

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证通过
添加数据源的时候，不选择开启审核，则不会出现审核等级筛选框，选择开启审核之后则出现


<img width="1353" alt="image" src="https://user-images.githubusercontent.com/54339501/221076683-ce6402c0-c4b3-4ea7-8dda-0d2f8e8113ce.png">
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/54339501/221076701-04c4db39-3727-41b2-9d14-4ff60782a285.png">

**Comment by Marcus9530** [comment]
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证通过
添加数据源的时候，不选择开启审核，则不会出现审核等级筛选框，选择开启审核之后则出现


<img width="1353" alt="image" src="https://user-images.githubusercontent.com/54339501/221076683-ce6402c0-c4b3-4ea7-8dda-0d2f8e8113ce.png">
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/54339501/221076701-04c4db39-3727-41b2-9d14-4ff60782a285.png">
