### ISSUE TITLE
pg执行SQL时找不到表

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1277]

**Comment by taolx0** [comment]
### 背景
sqle 会在用户级别下，上线sql。创建工单时，如果选择了其他数据库会导致找不到表的情况。

### 复现
1. 创建数据源，连接用户选择 root
![87BF4BD378958A0D648BBB6B4B960C42](https://user-images.githubusercontent.com/63177450/215376412-560e03da-1d50-4034-8a94-3ce941e4d928.jpg)

2. 创建工单时，选择 test_other_user 
![image](https://user-images.githubusercontent.com/63177450/215376568-9def5de2-d0c9-4dac-a51e-e887edcb0f12.png)

3.  上线 sql 选择 root 用户下的表
会报表不存在的错误

**Comment by ColdWaterLW** [comment]
无法复现
