### ISSUE TITLE
支持查看平台操作记录【企业版】

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1281]
### 查看平台操作记录
**功能入口**
点击顶部菜单栏日志icon，跳转操作记录页

![image](https://user-images.githubusercontent.com/36940986/215436563-7bd0048b-6fbf-43db-8468-1e0230402c2c.png)

**权限**
admin可查看操作记录

**查看操作记录**
- 支持筛选
   - 时间范围
   - 项目
   - 操作人
   - 操作对象
- 支持分页
- 按时间倒序排序

![image](https://user-images.githubusercontent.com/63177450/217201154-4a276852-f093-49c3-b599-041e18a49e87.png)

**Comment by taolx0** [comment]
### 新增接口
1. /v1/operation_records/operation_type_names [get]
2. /v1/operation_records/operation_contents [get]
3. /v1/operation_records [get]

### 变更接口
1. /v1/project_tips [get] 增加 functional_module 查询参数

**Comment by Marcus9530** [comment]
UI Version: main 1d23c35
Server Version: main-ee a5dc40605f
新增优化场景：
当选择操作类型时，只会展示对应的操作内容，当操作类型不做任何选择时，会展示所有的操作内容
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/54339501/221080652-c19cb93b-c2d9-4671-b3c4-f1437e73b93c.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/54339501/221080669-5d0125a7-8f12-4c8f-91c3-8b3f6d921f8b.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/54339501/221080686-61e9774d-699d-4d33-89be-047bd500ee18.png">
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/54339501/221080742-a2f2fffb-981e-44c8-93f4-1ecf7dcc5045.png">

**Comment by Marcus9530** [comment]
UI Version: main 1d23c35
Server Version: main-ee a5dc40605f
新增优化场景：
当选择操作类型时，只会展示对应的操作内容，当操作类型不做任何选择时，会展示所有的操作内容
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/54339501/221080652-c19cb93b-c2d9-4671-b3c4-f1437e73b93c.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/54339501/221080669-5d0125a7-8f12-4c8f-91c3-8b3f6d921f8b.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/54339501/221080686-61e9774d-699d-4d33-89be-047bd500ee18.png">
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/54339501/221080742-a2f2fffb-981e-44c8-93f4-1ecf7dcc5045.png">
