### ISSUE TITLE
在SQL上线过程中执行涉及同一插件的操作会打断上线流程

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#1282]
# Bug描述

如题所示, 扫描任务审核, 其他工单审核SQL, 上线SQL, 测试数据库连通性等操作都会打断

# 复现方式

1. 上线一条长耗时SQL
![image](https://user-images.githubusercontent.com/37464327/215423549-0974b180-9e53-4176-8cf2-be071f24ae32.png)
2. SQL执行过程中对同一数据源执行sql审核, 此时应当会报错
![image](https://user-images.githubusercontent.com/37464327/215423807-e4a34e5f-c51b-47e3-b606-1497a1d57323.png)
3. 再次查看执行中的SQL, 发现执行失败
![image](https://user-images.githubusercontent.com/37464327/215423899-f0804ab9-a243-44f2-8fd8-23a684fd2216.png)

**Comment by ColdWaterLW** [comment]
只验证了pg插件有这个问题，需要确认其它插件及MySQL是否也有这个问题

**Comment by HuangWeiCen** [comment]
# 参考方案

## 问题原因

1. 目前SQLE中每个数据库类型的插件都只有一个全局唯一的对象
2. 这个插件对象内部包含了一个连接对象, 用于连接插件
3. 这个连接对象只能被开启一次, 当连接被关闭后无法再打开, 只能再创建一个新的连接对象然后打开
4. 为了防止插件对象中的连接对象被重置后旧的连接对象没有被关闭, 每次重置连接对象时都会关闭一下旧的连接
5. 不关闭连接直接抛弃连接对象是不可行的, SQLE的插件没有自动退出机制, 不关闭连接会导致SQLE的连接越来越多

## 参考解决方案

将插件对象由原来的全局唯一改为每次使用插件时都创建一个全局插件对象的副本, 并在使用结束后由调用方自行关闭连接

**Comment by Marcus9530** [comment]
UI Version: release-2.2212.x 4842afb
Server Version: release-2.2212.x-ee 17dd4ca441
复现步骤：
1.添加一个pg数据源
2.然后使用pg数据源创建一个工单，sql执行时间过长，然后执行上线，可以看到上线中
3.在使用pg数据源创建一个新工单，点击审核，报错
4.返回工单列表，查看第二步中的工单可以看到已经上线失败

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/54339501/220836504-99644ef8-30a6-4651-95bc-05d3a67f22d9.png">
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/54339501/220836548-94720789-20f1-4480-8340-79369f4630a4.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/54339501/220836573-1db1c318-a76b-41d9-8f06-1d17aa61a34d.png">

**Comment by Marcus9530** [comment]
UI Version: main 1d23c35
Server Version: main-ee a5dc40605f
验证通过
验证步骤：
1.添加一个pg数据源
2.然后使用pg数据源创建一个工单，sql执行时间过长，然后执行上线，可以看到上线中
3.在使用pg数据源创建一个新工单，点击审核，审核通过后点击上线，可以看到上线成功
4.返回工单列表，查看第二步中的工单依旧是正在上线，没有上线失败
<img width="1835" alt="image" src="https://user-images.githubusercontent.com/54339501/221104200-2ce19104-7b28-4a9c-9d73-ec7fcd0f159e.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/54339501/221104280-0a173926-8545-458d-af20-a9a86f7ca093.png">
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/54339501/221104313-43b841d6-b854-4aa9-8846-11ded06fc923.png">
1.添加一个oracle数据源
2.然后使用oracle数据源创建一个工单，sql执行时间过长，然后执行上线，可以看到上线中
3.在使用oracle数据源创建一个新工单，点击审核，审核通过后点击上线，可以看到上线成功
4.返回工单列表，查看第二步中的工单依旧是正在上线，没有上线失败
