### ISSUE TITLE
[feature request]: show suggest of SQL keywords when user input SQL

### ISSUE THREAD

**Issue by Rain-1214** [actiontech/sqle#129]
**Describe**
user can't reseive any suggest when user input SQL at create order or update SQL of order or create whitelist for SQL.

**Suggestion**
at least we can prompt SQL keywords

**Why**
for  user experience

**Comment by Marcus9530** [comment]
Version:
  "release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
验证通过
验证步骤：
在创建工单的时候可以查看会出现一些关键字联想
![image](https://user-images.githubusercontent.com/54339501/147809335-685e9995-876a-4d61-8d60-19552c9b5fb8.png)
![image](https://user-images.githubusercontent.com/54339501/147809341-12b92008-5b89-430c-a5b0-b242c7107670.png)
