### ISSUE TITLE
ui界面优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1294]
## 1 导入规则模板文件时，增加文字告知用户只支持json格式的文件
![image](https://user-images.githubusercontent.com/36940986/216893927-654e3b33-425a-47df-9e30-5f71da9f6260.png)

## 2 审核流程模板页面，展示“允许创建工单的最高审核等级”
![image](https://user-images.githubusercontent.com/36940986/216894006-9050a58f-6e45-40d9-91ef-fc7dfca138db.png)

## 3 全局配置修改表述文字
![image](https://user-images.githubusercontent.com/36940986/216894133-13be9c11-8de1-4197-82bb-f06c4c28340f.png)
背景
针对已完成的工单，一旦存储时间>设置的时间（如12312小时），则系统自动删除该工单

现状
当前表述内涵：以12312小时为一个周期，周期性地自动检查并清理表中的过期数据

与预期想要传递的内涵不一致

建议修改内容
“已完成的工单回收周期”变更为“已完成的工单自动过期时间”

## 4 工单详情页，已有工单名称，工单基本信息栏的仍重复一遍工单名称，考虑删除工单基本信息栏的工单名称
![image](https://user-images.githubusercontent.com/36940986/216894346-dfc51e0c-81ca-4177-875e-64b60c06fe98.png)

**Comment by LZS911** [comment]
对第一项优化的修复方式修改为: 取消增加文字提示, 改为限制用户只允许选择后续为 json 的文件来进行上传.
