### ISSUE TITLE
SQLE panic when trigger pt-osc suggestion

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#130]
**SQLe Version**
main 201d68a30a9a5281ab31587a563e8a07999a51e2

**Describe the bug**
SQLE panic when trigger pt-osc suggestion

**To Reproduce**
1. 创建测试库表
```sql
CREATE DATABASE `t1`;
CREATE TABLE `t1`.`fruits` (
  `id` bigint(11) NOT NULL,
  `uid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) 
```
1. enable rule "改表时，表空间超过指定大小(MB)审核时输出osc改写建议"， 可以将配置最大表空间调小，例如：“0"，降低触发条件
2. 提交审核工单，SQL语句:
```sql
alter table fruits add column create_date TIMESTAMP default current_timestamp
```
3. 点击审核，SQLE 崩溃
![image](https://user-images.githubusercontent.com/18008452/145188303-df5fe58c-c236-4aae-bcda-94acc8410e62.png)

**Expected behavior**
正常提示 pt-osc 建议

**Comment by sjjian** [comment]
目测是 `Inspect`.`inst`对象在重构过程中丢失了赋值

**Comment by Marcus9530** [comment]
Version:
  "main 4e6cf6f59d0f23ff1dcdb5185cdbf8a3ecffa478"
复现成功
1.创建测试库表
CREATE DATABASE `t1`;
CREATE TABLE `t1`.`fruits` (
  `id` bigint(11) NOT NULL,
  `uid` int(11) NOT NULL DEFAULT '0',
  `name` varchar(100) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) 
2.enable rule "改表时，表空间超过指定大小(MB)审核时输出osc改写建议"， 可以将配置最大表空间调小，例如：“0"，降低触发条件
3.提交审核工单，SQL语句:
alter table fruits add column create_date TIMESTAMP default current_timestamp
4.查看sqle的pid文件发现进程已经发生了变化
![image](https://user-images.githubusercontent.com/54339501/147813427-41eb3c6c-18ac-4aef-8161-7a615c95c231.png)

![image](https://user-images.githubusercontent.com/54339501/147813348-150e2bf6-7298-4eed-8a94-50f4d97aa746.png)

**Comment by Marcus9530** [comment]
Version:
  "release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
验证通过
验证步骤

1.创建测试库表
CREATE DATABASE t1;
CREATE TABLE t1.fruits (
id bigint(11) NOT NULL,
uid int(11) NOT NULL DEFAULT '0',
name varchar(100) NOT NULL DEFAULT '0',
PRIMARY KEY (id)
)
2.enable rule "改表时，表空间超过指定大小(MB)审核时输出osc改写建议"， 可以将配置最大表空间调小，例如：“0"，降低触发条件
3.提交审核工单，SQL语句:
alter table fruits add column create_date TIMESTAMP default current_timestamp
4.查看sqle的pid文件没有发生任何变化
![image](https://user-images.githubusercontent.com/54339501/147813630-9b5b4eff-0f7e-45ff-bca1-e7bd43a9c390.png)
![image](https://user-images.githubusercontent.com/54339501/147813661-1a756cbc-d9eb-4025-8d8a-a22473b24518.png)
