### ISSUE TITLE
界面优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1311]
## 智能扫描访问凭证说明
**背景**
MyBatis Scanner 通过指定代码目录，扫描并解析目录中的 MyBatis XML 文件得到 SQL 语句。
MyBatis Scanner 将解析出的 SQL 上传至 SQLE Server 后，触发审核并得到审核结果。
访问凭证作用：审核任务上传凭证
参考用户手册：https://actiontech.github.io/sqle-docs-cn/3.modules/3.6_auditplan/scanner_management.html

**现状**
初次使用的用户并不知道访问凭证的作用，需要查看用户手册了解，不直观

**预期**
访问凭证字段增加感叹号tips，说明这个字段的使用场景
提示文字：用于审核任务上传凭证

## 项目概览页面交互
**预期**
鼠标在框内点击后，跳转到对应的页面
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/36940986/218361906-ddd80a7f-e81a-446e-82a6-17292680d4e5.png">

**Comment by Marcus9530** [comment]
验证通过
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证步骤

智能扫描界面，访问凭证已加上tips提示
<br class="Apple-interchange-newline">
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/54339501/220872117-7404a32a-225e-4072-adba-910ecaf3ad9c.png">
项目概览界面
点击不同的项目信息，可以跳转到对应的界面进行查看
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/54339501/220872969-9b63d3bc-8a57-43a8-8636-29a6983357b6.png">
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/54339501/220873010-ab562baf-ca14-43de-9330-72a0fd2b76cc.png">
<img width="1873" alt="image" src="https://user-images.githubusercontent.com/54339501/220873065-1efdbd96-379d-4c63-9d13-f67c69c57473.png">
<img width="1911" alt="image" src="https://user-images.githubusercontent.com/54339501/220873102-fa41c5b3-8d96-4448-b8d3-5eabf40b92b0.png">
<img width="1839" alt="image" src="https://user-images.githubusercontent.com/54339501/220873149-19e3ddc4-88af-4194-8326-61108bf98a29.png">
<img width="1837" alt="image" src="https://user-images.githubusercontent.com/54339501/220873178-2cc3be72-c3e9-4499-8bbe-f0e7817d1074.png">
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/54339501/220873260-88683ca2-97ea-4cd1-bb8b-8badfbcdfa4b.png">
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/54339501/220873338-9fd1ce6a-9fdd-4794-a68d-b2c6d8d4aaad.png">
<img width="1816" alt="image" src="https://user-images.githubusercontent.com/54339501/220873436-09c8400b-d37d-478d-8a04-9321d52773e7.png">
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/54339501/220873471-414e0ff3-e841-4719-a048-84039da71095.png">
