### ISSUE TITLE
界面优化【2.2303.0 版本长期任务】

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1328]
- [x] 1.【后端】当有个工单所使用的数据源还没有走完审核流程的时候，对数据源进行删除，文案需要优化
        之前的文案：local can't be deleted,cause wait_for_audit or wait_for_execution workflow exist
![image](https://user-images.githubusercontent.com/36940986/220016621-5b25646f-7ad0-43ff-b4e0-ba1d8f334f7a.png)

- [x] 2. 平台切换英文功能不完整，暂时隐藏
- [x] 3. SQL分析页面，当屏占比>100%时，内容显示不完全，需要做自适应
**现状**
![image](https://user-images.githubusercontent.com/36940986/220018043-c852c420-0b49-4819-a1c8-e40ae109ffe6.png)
**预期**
SQL分析页面需要做自适应，当放大的时候，页面容不下列表的所有字段，表格底部加个滚动条

- [x] 4. SQL分析列表，复制图标删除
![image](https://user-images.githubusercontent.com/36940986/220018190-d2455640-ce08-4675-a11e-1724aa0e4a97.png)

- [x] 5. 将时间展示格式统一为 YYYY-MM-DD HH:mm:ss
部分展示格式不统一，如下
![img_v2_81554bb2-b83a-4443-90c1-9d35a416273g](https://user-images.githubusercontent.com/36940986/220508053-5950bdd5-f87a-4515-ad4b-c1c5e691f785.jpg)

- [x] 6. 关闭工单后期望给个关闭成功的提示 #1337 
- [x] 7. 添加/编辑数据源，运维时间需做说明提示
说明文字：设置运维时间后，仅能在此运维时间段内上线工单
![image](https://user-images.githubusercontent.com/36940986/221745182-c3ec7ede-96fd-4e77-8289-1b40270f3120.png)
- [x] 8. 新建/编辑智能扫描任务页面，规则模板提示文字变更
新建/编辑智能扫描任务页面，对于审核规则模板的提示，与现状不符。因为添加数据源时，审核规则模板字段是必填的
建议删除提示文字后半部分，改为：“如果未指定此项会优先使用数据源绑定的模板”
- [x] 9. 用户中心支持修改手机号
**现状**
用户接入飞书，需要配置手机号，目前仅admin能配置用户手机号
**预期**
用户可在用户中心配置自己的手机号
![image](https://user-images.githubusercontent.com/36940986/224595419-40f6caf8-06e8-4c9f-be13-9b75a46008f8.png)
- [x] 10. 
**问题**
企业微信推送的账号实际为企业微信内部userID，与微信ID内涵不一致，现有命名方式容易造成误解，建议修改

**预期**
将【微信ID】修改为【企业微信UserID】
![image](https://user-images.githubusercontent.com/36940986/224598817-7a96b823-5ebc-4026-a86d-6ddc04a30726.png)
<img width="859" alt="image" src="https://user-images.githubusercontent.com/36940986/224657077-b69e9a21-614e-4ca3-88dc-1b27d99deff3.png">

- [x] 11. 用户中心，禁用用户/用户组字段，需要增加效果说明提示

**预期**
禁用字段前新增提示icon，用户鼠标移入时可了解开启禁用时实现的效果

**禁用用户**
提示文字：当用户被禁用，该用户将无法登录

**禁用用户组**
提示文字：当用户组被禁用，组内用户不会被禁用，但会失去该用户组所关联的数据源及对应角色权限
![image](https://user-images.githubusercontent.com/36940986/227829319-adad3971-e2f7-4b81-bad3-aba8d4a39631.png)

- [x] 12. 删除用户后，用户组列表绑定用户没有及时刷新，需要手动刷新才展示正常
创建用户组，里面包含用户u3，在用户中心删除用户3，切换tab查看用户组，用户u3还在组里。需要刷新页面才会消失
**预期**
删除组内用户后，用户组的绑定用户，需要及时刷新

- [x] 13. 项目内左侧功能菜单栏，扫描任务名称展示不全
![image](https://user-images.githubusercontent.com/36940986/227829737-56f0edfa-0d22-41d4-9bd2-c918abff56d1.png)
**预期**
鼠标移入后显示完整名称

- [x] 14. 项目规则模板页面，公共模板列表和项目模板列表调换位置

**Comment by Marcus9530** [comment]
UI Version: main 0e45cf6
Server Version: main-ee afd9f5e894

场景1:删除一个还没有走完工单流程的数据源的提示文案已优化
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/54339501/229035218-973257eb-25f4-4b6b-add2-76bdc8ca85e9.png">
场景2:中英文切换功能已隐藏
<img width="317" alt="image" src="https://user-images.githubusercontent.com/54339501/229035316-b18af23d-b60a-4e75-9a6f-f32cb8ec590d.png">
场景3:SQL分析页面，当屏占比>100%时，内容显示不完全，需要做自适应
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/54339501/229035424-0426e57c-aeff-4984-854e-64b4b7b5a135.png">
缩放太大时，界面下面出现左右滚动条
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/54339501/229035530-e697d30c-6983-4219-89ee-15f0673e2c62.png">
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/54339501/229035589-3d949e0d-d8ce-4779-8e30-a5207002356d.png">
场景4: SQL分析列表，复制图标删除
<img width="1885" alt="image" src="https://user-images.githubusercontent.com/54339501/229037432-63357581-7730-476e-8a6a-0686643ae41e.png">
场景 5. 将时间展示格式统一为 YYYY-MM-DD HH:mm:ss
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/54339501/229037534-cb904ef0-2312-4666-a251-a933f426938d.png">
场景6：点击工单关闭给到了相关提示
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/54339501/229037628-fd2b7d13-1583-4f75-bbb2-48ecabd543a7.png">
场景7： 添加/编辑数据源，运维时间添加tips文案说明
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/54339501/229037794-dc3a9580-30be-419f-af3b-fb3bc4f6ef6f.png">

场景8:新建/编辑智能扫描任务页面，规则模板提示文字变更
新建/编辑智能扫描任务页面，对于审核规则模板的提示，与现状不符。因为添加数据源时，审核规则模板字段是必填的
建议删除提示文字后半部分，改为：“如果未指定此项会优先使用数据源绑定的模板”
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/54339501/229037917-f9e25191-a66e-492f-9ce5-2e774bf8431d.png">
场景9：个人中心可以修改手机号
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/54339501/229038028-def3934e-6dbf-4889-b98c-76514409b25e.png">
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/54339501/229038070-2f599c5c-a24b-42ac-98f6-6b988c94f27a.png">
场景10:微信id改成qi企业微信userid
<img width="458" alt="image" src="https://user-images.githubusercontent.com/54339501/229038157-576af5e0-c7cd-46bb-8c41-c111d0d8e526.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/54339501/229038290-35aa9ba3-a092-4096-9151-1f2c21994b63.png">

场景 11.：用户中心，禁用用户/用户组字段，需要增加效果说明提示
<img width="927" alt="image" src="https://user-images.githubusercontent.com/54339501/229038425-681083b3-3f44-418a-b0df-f76cbc857f61.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/54339501/229038454-2a063675-b6a5-4535-a7d4-38d9ded14679.png">

场景12:删除用户后，用户组列表绑定用户立即刷新
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/54339501/229038563-eaac980f-a9df-44ec-a67c-733e461f2192.png">
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/54339501/229038584-ffd1b211-8fae-4c9d-be04-1ce00abf8081.png">
场景13: 项目内左侧功能菜单栏，鼠标dian点击扫描任务类型，名称展示完全
<img width="788" alt="image" src="https://user-images.githubusercontent.com/54339501/229038900-3a7957c8-bafb-49af-8b8d-5eccc3f8b0e4.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/54339501/229038922-f8546ffc-7c03-4865-9cc2-9f7df5ca3bcc.png">
场景14: 项目规则模板页面，公共模板列表和项目模板列表调换位置
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/54339501/229039042-b7641bfe-7c4f-400e-9771-dd6cd5c74e02.png">
