### ISSUE TITLE
当工单驳回之后，创建工单的用户收到邮件之后点击工单链接提示工单不存在

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1332]
复现步骤：
1.创建test用户，然后绑定一个邮箱
2.开全局设置中的smtp功能
3.然后使用test用户随便创建一个工单，提交审核
4.切换到admin用户，把这个工单给驳回
5.等待test用户绑定的邮箱收到邮件
6.在审核驳回的提示邮件点击工单链接，提示工单不存在
<img width="623" alt="image" src="https://user-images.githubusercontent.com/54339501/220829674-cc27d017-138b-4ec8-ac72-67e55f93798d.png">
<img width="1896" alt="image" src="https://user-images.githubusercontent.com/54339501/220829759-c9b9b1c1-930f-418f-9692-a84cb47b0385.png">

原因是想看工单详情的话，请求地址最后一个是$workflow_id，而不是filter_subject参数
<img width="1735" alt="image" src="https://user-images.githubusercontent.com/54339501/220829877-902be715-4bbb-4a34-a954-36bced5e461b.png">

期望：邮件里面的工单链接直接返回工单详情的请求地址。这样用户点击之后可以直接看到工单详情

**Comment by ColdWaterLW** [comment]
关联工单：#1280

**Comment by taolx0** [comment]
### 钉钉审批通知的工单链接也有这个问题 https://github.com/actiontech/sqle/issues/1177

![image](https://user-images.githubusercontent.com/63177450/220866329-664bd321-f78c-4d97-a68d-4c0d1c3057ad.png)

**Comment by Marcus9530** [comment]
UI Version: main 1d23c35
Server Version: main-ee 54cabfa628
验证通过
验证步骤：
1.开启smtp、微信、钉钉通知
2.创建一个工单
3.可以看到三个通知方式，目前的工单链接都可以正常打开查看工单详情

钉钉
<img width="416" alt="image" src="https://user-images.githubusercontent.com/54339501/221136847-f7f1310f-a068-492d-95e5-85f5b9570b5a.png">
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/54339501/221136888-c9e00e3d-bf19-4ced-a3a4-9c8c7a699ef2.png">
企业微信
![image](https://user-images.githubusercontent.com/54339501/221137146-acc06d9f-57c5-4938-adeb-55ddbf95fcf3.png)
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/54339501/221137195-c88c22b2-5b25-4c77-b693-ba3525d94f36.png">
邮件
<img width="784" alt="image" src="https://user-images.githubusercontent.com/54339501/221137714-75c30d64-33b6-4ce3-b6bf-fcefbda01ccb.png">
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/54339501/221137751-321f6475-e290-4cd1-924e-d30711a26beb.png">
