### ISSUE TITLE
系统设置页面布局优化

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1342]
**Describe**
通过标签聚类的方式，对系统设置中的功能实现分类
用户可通过标签了解该页面中各要素实现的功能，快速定位

**Why**
当前系统设置页面功能已较多，产生了如下问题
- 没有排序顺序，功能查找不便
- 用户仅能通过功能名称猜测具体实现功能

**Suggestion**
- 入口
管理员账号下， 点击更多，点击系统设置，进入系统设置页面

- 需求概要
在系统设置页面新增四个标签选项，用户点击某一标签，查看该标签对应的系统设置功能

- 详细设计
当前共设置五个标签页，分别为【消息推送】、【流程对接】、【登录对接】、【全局配置】、【许可证】，各标签下对应的功能要素如下
  - 用户点击【消息推送】，可查看的功能要素包括
    - SMTP邮箱推送
    - 企业微信
    - 飞书
  - 用户点击【流程对接】，可查看的功能要素包括
    - 钉钉审批
  - 用户点击【登录对接】，可查看的功能要素包括
    - LDAP
    - OAuth2
  - 用户点击【其他配置】，可查看的功能要素包括
    - 工单回收时间
    - url地址前缀
  - 用户点击【许可证】，可查看的功能要素包括
    - license

- 需求原型
![image](https://user-images.githubusercontent.com/113898890/221459981-02ab7384-2ca3-4f0e-b65c-d65410d674ab.png)

**Comment by zhouzhilu9** [comment]
UI Version: main e7369d7
Server Version: main-ee ee91bb3a68

验证通过
系统设置中共 5个标签页
![image](https://user-images.githubusercontent.com/99949903/228713900-6631f994-56cc-4c07-939a-6513b57402af.png)
消息通知：
![image](https://user-images.githubusercontent.com/99949903/228713971-3f218ca8-0d59-42ac-9f36-5d039c01fb0b.png)
流程对接：
![image](https://user-images.githubusercontent.com/99949903/228714012-a968d566-4a50-4725-8db6-45b7e1a1275d.png)
登录对接：
![image](https://user-images.githubusercontent.com/99949903/228714151-17295064-6dd7-4df8-b469-46309c21dbb7.png)
全局配置：
![image](https://user-images.githubusercontent.com/99949903/228714201-0a9c042f-a191-4a05-9028-43cb6ba790a9.png)
许可证：
![image](https://user-images.githubusercontent.com/99949903/228714293-680bb187-6c3a-4953-8486-8903cf1be1f5.png)
