### ISSUE TITLE
SQLE 配置 sqle_config.secret_key 参数失效，配置后SQLE进程夯

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1343]
**SQLe Version**
main

**Describe the bug**
SQLE 配置 sqle_config.secret_key 参数失效，配置后SQLE进程夯。目测SetAesSecretKey函数内部死锁。

**To Reproduce**
1. 在SQLE 配置文件内显式的配置该参数即可复现，配置文件文档参考：https://actiontech.github.io/sqle-docs-cn/2.deploy/2.4_after_deploy.html 。

**Expected behavior**

**Suggestion**

**Comment by zhouzhilu9** [comment]
UI Version: main e7369d7
Server Version: main-ee 2619c7411a

启动sqle之前配置随机32字符
![image](https://user-images.githubusercontent.com/99949903/228799862-fffda5e8-dd98-47ae-ada2-34bb8d0570d5.png)
启动sqled服务可以正常启动
![image](https://user-images.githubusercontent.com/99949903/228800041-03ae8626-5229-4a7c-99fa-776a7747520c.png)
