### ISSUE TITLE
数据库审核插件系统优化

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1347]
# 目前存在的问题
1. SQLE每次调用插件系统都会启动一个新的进程，导致资源占用高。
2. SQL审核接口目前每次只能审核一条SQL，导致部分场景下的规范无法实现，例如：审核建表语句是否添加注释时无法实现，在PG等数据库上，添加注释并非是将注释写在create table 语句内，而是独立的语句。导致对单条语句审核时无法得知后续是否有加注释

# 方案
1. 升级插件接口，并保持旧接口兼容；
2. 将插件进程设计为常驻进程；
3. SQL审核接口支持批量审核。

**Comment by Marcus9530** [comment]
保证原有功能正常使用即可
