### ISSUE TITLE
添加项目登录后快速重定向至指定页面的功能

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1350]
**Suggestion**
1. 当用户在未登录的情况下在浏览器地址栏输入项目内某个页面的 URI 时,目前会重定向至 login 页面,且登录后会进入项目的首页, 希望在用户登录后能够直接导航至之前在浏览器地址栏输入的页面.
2. 用户在打开多个 sqle 页面的情况下, 退出其中某一个页面时, 希望在其他的页面刷新或者调用接口后能够自动返回到登录页面, 且登录后能够直接跳转至之前打开的页面
3. 当前获取用户数据时接口出现错误时会自动登出到 login 页面, 并且只会在该接口请求状态码为 401 的时候会在下次登录时自动重定向至登出前的页面. 希望在该接口出现任何错误的情况下都能够在下次登录后自动重定向至登出前的页面.

**Why**
提高用户体验

**Comment by zhouzhilu9** [comment]
首次登录，会直接跳到登录界面
![image](https://user-images.githubusercontent.com/99949903/228716960-7f5ec25b-9961-43d3-bc0f-4e98840b4403.png)
登录后，再次浏览器中重新进入项目地址会跳转为自动登录
![image](https://user-images.githubusercontent.com/99949903/228717176-cc750af9-7d59-45f8-bf47-f2beb55b368a.png)
退出当前页面登录后，刷新浏览器中其他已登录的页面会自动跳转到登录界面
![image](https://user-images.githubusercontent.com/99949903/228717404-1737c405-d4d8-4167-9081-2f01f30ae3ee.png)
登录成功后会直接跳转到之前的页面而不是首页
![image](https://user-images.githubusercontent.com/99949903/228717587-3194acdc-e902-423a-8298-4a6166b28a97.png)
