### ISSUE TITLE
社区版支持推送工单信息到企业微信的功能

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1352]
通过企业微信推送工单信息的功能开源到社区版

**Comment by zhouzhilu9** [comment]
UI Version: main e7369d7
Server Version: main-ee 2619c7411a
验证通过
![image](https://user-images.githubusercontent.com/99949903/228734975-a7086d2b-2874-4ab2-8e6b-431c45d11c77.png)
