### ISSUE TITLE
编辑用户功能异常

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1356]
**Describe**
admin登录，进入用户中心，用户xiaoming是已禁用状态
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/36940986/223610655-34301ee4-1e09-4223-aef4-ed07d76b9006.png">
点击编辑xiaoming用户
显示为未禁用
<img width="517" alt="image" src="https://user-images.githubusercontent.com/36940986/223610839-17f6e744-5805-4595-81f9-04eccfa53af0.png">

**Comment by zhouzhilu9** [comment]
UI Version: main e7369d7
Server Version: main-ee 2619c7411a

1，编辑用户为禁用用户
![image](https://user-images.githubusercontent.com/99949903/228721143-80c65735-0dc1-4812-a086-5e01f66507eb.png)
2，查看用户列表中状态为禁用
![image](https://user-images.githubusercontent.com/99949903/228721248-5a4c98ba-4703-4bbd-92a8-ad0c1d52f840.png)
3，再次点击用户编辑
![image](https://user-images.githubusercontent.com/99949903/228721297-e3e742ba-29b1-40e7-af55-edbca08e8010.png)
