### ISSUE TITLE
修改流程模板后，工单进度显示异常

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1360]
**复现步骤：**
1. 查看流程模板，有一个审核步骤
<img width="685" alt="image" src="https://user-images.githubusercontent.com/36940986/224283231-ee0a384b-0dc1-4c94-9eb2-d6d9180f299f.png">
2. 创建工单
<img width="599" alt="image" src="https://user-images.githubusercontent.com/36940986/224284483-a9fa318a-4482-4cfc-b4d2-6ec2a18e4532.png">
3. 驳回工单
<img width="797" alt="image" src="https://user-images.githubusercontent.com/36940986/224285149-35be45ab-44d5-446c-95c3-6bbd97d6521e.png">
4. 修改流程模板，把审核步骤去掉
<img width="880" alt="image" src="https://user-images.githubusercontent.com/36940986/224285471-9997c402-4d2e-42bb-aeb4-0a1d1995f304.png">
5. 回到之前的工单，修改SQL语句后提交工单更新。工单状态变成“待上线”，但进度显示“等待上一步执行”，实际无法再对工单操作

**预期**：修改流程模板不应该影响已创建的工单，修改工单后应该还是处于驳回前的状态
<img width="856" alt="image" src="https://user-images.githubusercontent.com/36940986/224285719-0193dc81-944e-4747-9598-63183af5dfcc.png">

**Comment by jessun** [comment]
#### 修复方案
在一个工单开始处理后，如果变更了工单流程模板，那么在继续更新这个工单时，工单流程会按照变更后的工单流程进行，就会导致该问题。所以在一个工单在开始新增后，该工单的处理流程步骤必须按照创建时的工单流程模板进行。这就要求：
- 每个工单都和一个具体的工单流程模板有关联；
- 如果已经按照工单流程模板创建了工单，那么该工单流程模板不可被修改、删除；
- 一个项目 project 可以关联一个工单流程模板。project 在更新工单流程模板时：
    - 如果该工单流程模板没有任何工单，那么直接更新该工单流程模板；
    - 如果该工单流程模板已经有任何工单关联，那么直接建立一个全新的工单流程模板，将该项目 project 与之关联。

#### 变更内容
- 工单流程模板的绑定关系变更。model.Instance 移除 WorkflowTemplateId，model.Workflow 新增 WorkflowTemplateId 做绑定。所有的关联查询需要做变更；
- 页面【流程模板】-【修改当前审批流程模板】后端逻辑调整。如果当前审批流程模板已经有关联的工单时，那么后端是新增工单流程。如果没有工单关联，则修改该工单模板流程。  

#### 变更的影响场景
- 工单的流转
- 项目的审核流程模板的修改

#### 升级变更
- 表 sqle.instances 需要删除列 workflow_template_id；
- 表 sqle.workflows 需要新增列 workflow_template_id，需要填充数据，使用工单关联的 instance 的 workflow_template_id 填入。

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

1，创建工单
2，对工单进行驳回
![image](https://github.com/actiontech/sqle/assets/99949903/5edbe0d2-ea70-4743-b5b0-e9d6d815de43)
3，修改审核流程，移除审核步骤
![image](https://github.com/actiontech/sqle/assets/99949903/dab435c8-5253-4bed-ba59-a491cd7a5707)
4，修改被驳回的工单
5，返回点击工单，查看工单状态和概览中状态都为待审核
![image](https://github.com/actiontech/sqle/assets/99949903/005e1cc4-685c-4fd7-977b-4a4d7431d835)
