### ISSUE TITLE
配置可关闭SSL安全认证

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1365]
### 来源
社区群

### 现象
无法正常发送邮件，报以下错误
![image](https://user-images.githubusercontent.com/63177450/225191995-b0c43129-1c6e-4456-80c6-682bfd9c404d.png)

### 原因
因为邮箱客户端会默认验证邮箱服务器凭证，凭证验证错误导致了这个报错。

### 预期
预期可以自定义是否验证凭证。

**Comment by taolx0** [comment]
### 添加了下图所示的配置，配置 tls InsecureSkipVerify 参数，这个参数的作用是验证邮箱服务器的凭证和主机名是否在邮箱客户端凭证中。如果设置为 true ，邮箱客户端会忽略检测凭证（任意证书和主机名都可以通过验证），因此邮箱客户端可以向不能通过验证的邮箱服务器发送邮件。

https://github.com/actiontech/sqle/blob/38f730753228656cae7635f815f08b98c980f966/sqle/notification/email.go#L58
![image](https://github.com/actiontech/sqle/assets/63177450/fa2c7353-af7e-4680-ad2f-ee7709309c92)
![image](https://github.com/actiontech/sqle/assets/63177450/ac7d4a14-85db-4249-ad7d-fcebbf464990)

**Comment by hasa1K** [comment]
#### 复现步骤
1. 在系统设置页面中配置SMTP服务时将SMTP地址填为IP地址而不是域名
![image](https://github.com/actiontech/sqle/assets/53266479/9da9925f-d987-4c84-8592-8a636fc17164)

2. 点击测试就能复现上述的错误
![image](https://github.com/actiontech/sqle/assets/53266479/fdf75b0d-38a1-4248-afeb-393a33aab13a)

#### 问题原因
在使用gomail发送邮件时，它会尝试验证收件服务器的证书。当证书中不包含IP SANs时，验证过程会失败并出现这个错误。

#### 解决方案
1. SMTP地址使用域名代替IP地址
2. 使用上述的临时解决方案，跳过认证（存在安全问题，不建议在生产环境中使用）
3. 如果是自建邮件服务，需要在邮件服务器更新证书以包含IP SANs

**Comment by hasa1K** [comment]
#### 升级方案
在SMTP配置页面增加一个按钮，让用户选择是否跳过认证。并提示用户如果跳过认证会有什么影响。默认不跳过认证
![image](https://github.com/actiontech/sqle/assets/53266479/852f9137-a24c-4dac-b9d1-d4f30fe3c141)

**Comment by Marcus9530** [comment]
复现版本：Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
1.在系统设置界面，消息推送选择smtp
2.填入上述的ip地址，输入邮箱
3.点保存之后，点击测试，出现上述报错
![image](https://github.com/actiontech/sqle/assets/54339501/d272cef5-55eb-4657-a19f-1363a8ef4fbb)

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee 35e1c6cd86
验证步骤：
1.在系统设置界面，消息推送选择smtp
2.填入上述的ip地址，输入邮箱
3.点保存之后，点击测试，成功发出测试邮件
![image](https://github.com/actiontech/sqle/assets/54339501/67274f88-c628-40b8-9b57-70f19ca1f1f5)
![image](https://github.com/actiontech/sqle/assets/54339501/f03bd360-3283-49ca-92e7-d143f9c45fe0)

**Comment by Marcus9530** [comment]
当前在dms中碰到个现象就是不开启跳过ssl的话，使用测试邮箱就会失败
![image](https://github.com/actiontech/sqle/assets/54339501/25a515c8-30ee-46f5-b416-6cbf5a27d4cb)
![image](https://github.com/actiontech/sqle/assets/54339501/f2c9a703-b21d-47e0-8c88-ec423794c733)
