### ISSUE TITLE
支持自定义数据库审核插件的启动命令

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1373]
## 背景
目前SQLE启动审核插件默认使用无参数的执行插件二进制文件。对于jar包则无法支持
## 方案
使用sqle.yml 配置插件的启动命令，默认情况保持原有逻辑。

**Comment by taolx0** [comment]
### 使用说明
1. 插件放入 plugins 目录下（https://actiontech.github.io/sqle-docs-cn/3.modules/3.7_auditplugin/auditplugin_management.html）
![image](https://user-images.githubusercontent.com/63177450/228117256-919910bb-d1b6-4fbc-b410-8a0620bc6d4e.png)

2. 配置启动命令，在 /etc/sqled.yml 下增加plugin_config配置，plugin_name 是指插件的文件名，cmd 是指启动该插件的命令（启动命令填写绝对路径）
![image](https://user-images.githubusercontent.com/63177450/228117612-2fbbbf71-a3a5-4ffe-ad1d-2917863bfced.png)

![image](https://user-images.githubusercontent.com/63177450/228117499-ba3cdd5f-29b9-43c5-894c-87315964d5b7.png)

3. 重启sqle

**Comment by zhouzhilu9** [comment]
UI Version: main e7369d7
Server Version: main-ee 2619c7411a

验证通过
新增插件，并重启容器
![image](https://user-images.githubusercontent.com/99949903/228799062-775329b6-1a03-49ce-9988-9df64313faaf.png)

数据源中新增插件类型
![image](https://user-images.githubusercontent.com/99949903/228799359-c6de55eb-7274-4844-9410-ba1a8b558dcc.png)
规则模板中新增插件模板
![image](https://user-images.githubusercontent.com/99949903/228799455-17708653-1bf8-449f-907f-f5dc8db9b52b.png)
