### ISSUE TITLE
自定义平台logo和标题【企业版】

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1374]
## 需求
支持对平台的界面相关logo、标题等信息的个性化配置；

### 需求概要
系统设置-个性化设置中，新增外观个性化内容编辑入口，支持用户自定义
- 个性化logo
- 个性化标题
 ### 详细设计
- 默认显示：显示平台初始化时的logo及标签页面名称（Action SQLE）
- 操作场景：用户需要自定义平台名称及logo
- 操作行为：点击修改/上传并更新icon，编辑平台标题/上传logo
- 操作限制：
  - 图片大小/格式：建议尺寸为 58 × 48 的png图片
  - 标题长度：暂不限制
- 操作效果：修改后即时生效
- 操作权限：平台管理员
- 影响范围：
  - 登录页：网页标签名称及登录提示
  - 平台详情页：网页标签名称及导航栏提示

### 原型概览
修改入口
![image](https://user-images.githubusercontent.com/36940986/226565468-2b729c8b-f374-44be-ad82-09a7e147a7a6.png)

修改标题及logo，保存配置后效果
![image](https://user-images.githubusercontent.com/36940986/226255103-aadf4511-55de-4441-823b-11f1412f40be.png)

详情页
![image](https://user-images.githubusercontent.com/36940986/226255139-c53c0515-2d16-41ad-ba11-479fe941bc06.png)

**Comment by taolx0** [comment]
# 上传头像，并实时更新  
  
## 1. 上传图片接口  
  
每次用户上传新的头像，使用时间戳作为文件名，保存在服务器上，将图片地址返回至前端，避免浏览器读取缓存的旧头像。  
  
标题按照正常逻辑返回即可。  
  
### 1.1 注意点  
  
1. 压缩图片存储  
2. 限制图片大小  
3. 使用 multipart/form-data 传输头像  
4. 如果用户没有上传头像，使用默认头像
