### ISSUE TITLE
即时通讯工具的配置需要加密保存

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1396]
现支持的钉钉、飞书配置都是明文保存在sqle数据库里，app secret字段属于密钥，应该加密保存

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee 35e1c6cd86

验证步骤：
1.添加飞书跟钉钉配置到sqle
2.查看sqle的global_configuration_im表
3.发现app secret字段现在是加密保存
![image](https://github.com/actiontech/sqle/assets/54339501/481ed5ce-7497-4751-8f4d-10d1689e740b)
