### ISSUE TITLE
后端开放工单描述长度限制

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1397]
后端开放工单描述长度限制，长度限制设定为3000个字符。前端暂不做调整

## 升级方案
执行sql
```
ALTER TABLE workflows MODIFY `desc` varchar(3000);
```

**Comment by zhouzhilu9** [comment]
UI Version: main 7c9f5e9
Server Version: main-ee b40610209f
验证通过
查看后端表结构限制：
![image](https://user-images.githubusercontent.com/99949903/228753061-ab617a40-b5fa-4d58-8a68-e9c42541da10.png)

![image](https://user-images.githubusercontent.com/99949903/228753990-7ca803b2-9692-4d5f-b112-ed21bcecbc12.png)
