### ISSUE TITLE
索引有大写字母，创建工单时审核报错

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1399]
## SQLe Version
main-49a0dad

## Describe the bug
1. 创建表
```
 CREATE TABLE `tb1` (
  `a` int(11) DEFAULT NULL,
)
```
2. 添加名字包含大写字母的index
```
alter table tb1 add index inE (`a`);
```
3. 创建工单，删除索引
![image](https://user-images.githubusercontent.com/36940986/227914653-f730ea46-e7ac-45a1-a36f-1b441ce64da4.png)
 4. 审核报错
![image](https://user-images.githubusercontent.com/36940986/227915158-0ec08ffb-6e83-4317-b60a-2fc549a8a2e3.png)

## Expected behavior 
索引存在，不应该报索引不存在的错误

**Comment by jessun** [comment]
## 问题原因

根据官方文档，MySQL 的索引不区分大小写，https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html。
因此在审核 Alter Table 语句时，非匿名索引都应该被转为小写后进行比较。

## 验证点
除了上述验证外，还有一点变更：审核结果描述中的索引不再会被错误地转为小写。

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

1,创建表信息
![image](https://github.com/actiontech/sqle/assets/99949903/751a4876-994b-482f-a2d3-adaf93a5994e)
2，创建工单删除索引，审核通过
![image](https://github.com/actiontech/sqle/assets/99949903/f5ace316-f337-4381-9b35-5214795a3a1a)
