### ISSUE TITLE
飞书推送消息建议新增工单链接，不然需要到sqle平台找到对应的工单

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1402]
如图所示，当前飞书推送的消息中没有带工单链接，无法快速准确的找到的对应的工单，需要到sqle平台找才可以，比较不方便，建议新增个工单链接，快速点击一下进入到sqle的对应工单详情链接里面
<img width="723" alt="image" src="https://user-images.githubusercontent.com/54339501/228144058-0deaafc5-b0ea-470b-85b3-1259e9c974c0.png">
可参考过往issue：https://github.com/actiontech/sqle/issues/1248

**Comment by jessun** [comment]
经确认已支持。

**Comment by Marcus9530** [comment]
<img width="804" alt="image" src="https://github.com/actiontech/sqle/assets/54339501/20926017-a300-4e6c-af9b-d1caa1ca9045">
