### ISSUE TITLE
Dashboard页面项目待办工单数量统计有误

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1403]
**SQLe Version**
UI Version: main 1ce7b6c
Server Version: main-ee ee91bb3a68
当前项目内实际工单数量跟Dashboard页面项目工单数量显示不一致，猜测后端统计工单数量有误

<img width="776" alt="image" src="https://user-images.githubusercontent.com/54339501/228161588-1a271478-2ffd-4e7f-a219-75b8bae70afa.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/54339501/228161926-89268d8e-15b6-4f2a-a53d-7685643c1724.png">
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/54339501/228161964-4eedf77c-b1f7-4530-9eb5-8d10385cf33e.png">
![image](https://user-images.githubusercontent.com/54339501/228162979-6580c3df-a019-4be8-9b75-09813a54cb72.png)

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/228163041-c91aa21a-f344-42ef-80a1-8c7fa0c10efd.png)

**Comment by ColdWaterLW** [comment]
和产品同步后确认符合预期
自己下发的工单、自己审核，相对情况 就比较少。。这类统计出现冗余，也是可以的。。
- 常规场景：A创建工单，B审核；
  - A登录后，项目统计的工单数 就只有我的工单情况；
  - B登录后，项目统计的工单数 就只有待处理工单情况；
- 特殊场景：A创建工单，A又是审核
  - 项目统计的工单数 就重复统计，但是对数字是正确的。
