### ISSUE TITLE
在sql工作台上打开oracle数据源失败

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1407]
**SQLe Version**
UI Version: main e7369d7
Server Version: main-ee 2619c7411a
复现步骤：
1.搭建一个oracle容器并启动
2.sqle上添加oracle数据源
3.然后在sql工作台上打开oracle失败
![64ca79c3-68a0-4225-a45b-a863d509bcad](https://user-images.githubusercontent.com/54339501/228759354-70136cc4-bd4d-46e3-a9dd-3e57415e5aed.jpeg)

**Comment by ColdWaterLW** [comment]
**原因**
初步推断是cloudbeaver使用的oracle驱动配置问题

**临时解决方案**
使用cloudbeaver管理员登录，去修改oracle驱动配置
![image](https://github.com/actiontech/sqle/assets/36940986/81025263-4ce1-43ff-9278-653b482e05a3)
![image](https://github.com/actiontech/sqle/assets/36940986/7acc06d3-d628-46ae-a8ea-e15d7c80d030)
修改后点击保存

**Comment by iwanghc** [comment]
### **问题原因：**
oracle.jdbc.timezoneAsRegion属性是在Oracle JDBC驱动程序的较新版本中引入的，主要用于处理日期和时间时区信息。
此问题在Oracle11g中复现，Oracle12c中并未出现，
所以Oracle JDBC驱动程序的早期版本（如Oracle 11g中使用的版本）可能不支持此属性
### **可行解决方案：**
**方案一**、dms中添加cloudbeaver map类型配置【properties】，并设置属性"oracle.jdbc.timezoneAsRegion": false，将新建数据源timezone region默认关闭
**方案二**、在cloudbeaver中启动脚本中（cloudbeaver容器/opt/cloudbeaver/run-server.sh）设置jvm参数，
指定时区：
export JAVA_OPTS="-Duser.timezone=GMT+08" 
或者将其设置为false：（不建议）
export JAVA_OPTS="-Doracle.jdbc.timezoneAsRegion=false"
### **最终方案：**
方案一
原因：timezoneAsRegion设置为true时会将数据库中日期时间转为本地时区，对于sqle来说几乎不会使用， 且oracle11g中并无此属性，所以可以默认设置为关闭，若oracle12c有需要使用，在cloudbeaver驱动属性中打开即可。
