### ISSUE TITLE
每条审核结果对应的审核建议细化，可查看对应建议的说明

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1411]
**Describe**
目前审核结果只展示触发的审核规则，没有详细建议
![image](https://user-images.githubusercontent.com/36940986/229419557-540feecf-3f9e-46f3-bdfd-44b74b111093.png)
影响的页面：
1. 工单详情
![image](https://user-images.githubusercontent.com/36940986/229419891-7c9c30cb-9399-4cf6-a095-a3137055c482.png)
 
2. 创建工单的审核结果
![image](https://user-images.githubusercontent.com/36940986/229420109-52f86cdb-81fb-4156-8fa9-3f7c67dcecd6.png)

**Suggestion**
建议将鼠标移动到审核结果内容上时，展示详细的审核规则建议，类似审核规则页面
![image](https://user-images.githubusercontent.com/36940986/229419702-43932a46-cea8-4b33-b8e5-41230af11490.png)

**Why**
方便用户根据审核建议优化sql

**Comment by jessun** [comment]
1. 变更方案
对于【审核结果】而言，变更前包含的信息为：
- audit_level：审核等级；
- audit_result: 审核结果，可能包含多个 error 级别的结果，使用换行符"\n"来区别处理；
- audit_status: 审核状态。
其中 audit_result 字段由字符串调整为 audit_results 数组，包含的 item 为：
```
[
    {"level": "error", "message": "schema 不存在", "rule_name": "xxxxxx"},
    {"level": "error", "message": "禁止使用没有where条件的sql语句或者使用where 1=1等变相没有条件的sql", "rule_name": "xxxxx"},
]
```

2. 变更内容
- sqle 模型变更
    - 表 execute_sql_detail(对应Model ExecuteSQL) 新增 audit_results 字段，格式为MySQL JSON 格式。原字段 audit_result 废弃，计划使用额外的升级工具来处理。
    - 表 audit_plan_report_sqls_v2（对应Model AuditPlanReportSQLV2）新增 audit_results 字段，格式为MySQL JSON 格式。原字段 audit_result 废弃，计划使用额外的升级工具来处理。

- sqle 后端 API 变更
    - 新增 GET: /v2/tasks/audits/{task_id}/sqls 接口返回值 audit_result 由字符串调整为 json object 数组
    - 新增 POST: /v2/sql_audit  同上
    - 新增 GET: /v1/projects/{project_name}/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls 同上
    - 升级 /v1/rules，新增 filter_rule_names 请求参数

- sqle 后端其他变更
    - 插件的 v2 grpc 接口 Audit() 返回值新增字段以支持 rule_name 字段的返回

3. 剩余任务
    - 升级工具支持表字段升级变更
    - 其他审核插件的 grpc 方法 Audit() 返回值变更

**Comment by Marcus9530** [comment]
UI Version: release-2.2304.x 3e01d1b
Server Version: release-2.2304.x-ee 6e284f0e41
验证步骤
1.创建工单，然后输入一条sql语句
2.点击审核之后，可以看到审核提示
3.点击审核提示可以看到对应的审核建议信息


<img width="1278" alt="image" src="https://user-images.githubusercontent.com/54339501/235070626-2a164353-0045-4a32-b614-4ece8e47f8eb.png">
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/54339501/235070648-e208707f-5a3a-4d96-a2d3-68caddc00246.png">
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/54339501/235070668-b7929dad-42bd-410e-82e3-2f6ca0adab23.png">
