### ISSUE TITLE
界面优化【2.2304.0 版本长期任务】

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1412]
- [x] 1. 页面展示的文字重叠
 **现状**
用笔记本电脑打开浏览器，缩放为100%的情况下，创建项目规则，可以看到审核规则注释信息会跟一些自定义的阈值重叠
 
![image](https://user-images.githubusercontent.com/36940986/229427756-cbf2230b-f0ad-40a2-a6d8-6dcca2a7653d.png)

预期
不应该会重叠展示，需要做到自适应。

- [x] 2. 创建扫描任务时，选择一个数据源后，数据库类型被限定，之后修改数据源，只能在限定数据库类型中选数据源
**现状**
扫描任务创建页，选择数据源名称后，数据库类型被固定，如下图为mysql
![image](https://user-images.githubusercontent.com/36940986/230816739-a967625b-f3d7-4b7a-b921-677f3c3efb11.png)

此时需要切换数据源，只能在mysql数据库类型下选择
![image](https://user-images.githubusercontent.com/36940986/230816771-62672244-d300-45ae-a4d7-82afbf97ca15.png)

如需选择其他数据库类型的数据源，则需要刷新该页面
![image](https://user-images.githubusercontent.com/36940986/230816796-dd0b602b-4da7-4206-894d-a0c6192577fc.png)

**预期**
选择数据源后，数据库类型依然可选；如果改变数据库类型，则已选的数据源置空，需要重新选择

- [x] 3. 编辑审核规则模板完成后，应提示模板名称
在完成提示中新增规则模板名称
![image](https://user-images.githubusercontent.com/36940986/230831536-9df2ee94-71b4-4ce1-ae66-ce6d9ef31f8d.png)

**Comment by Marcus9530** [comment]
复现成功
复现版本：
UI Version: release-2.2303.x 0e45cf6
Server Version: release-2.2303.x-ee afd9f5e894
场景1：在浏览器创建进行缩放150%的时候可以看到审核规则注释信息会跟一些自定义的阈值重叠
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/54339501/235041565-3fc62797-61f8-49b3-9213-462c327422b5.png">
场景2:创建扫描任务的时候,选择好数据源之后，想修改成其他类型的数据源无法选择，需刷新整个页面才可以
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/54339501/235042123-55340f7f-ad27-42ef-9fb1-b241533bccc8.png">
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/54339501/235043381-dd75ede6-2f50-4f00-91cc-d853c5423215.png">
