### ISSUE TITLE
跳转sql工作台，显示可用的数据源与实际数据源列表中有出入

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1417]
**SQLe Version**
main-ee afd9f5e894

**Describe the bug**
数据源列表添加oracle数据源后，点击sql工作台，预期对oracle数据源操作，实际找不到oracle数据源

**To Reproduce**

1. 添加数据源
![image](https://user-images.githubusercontent.com/113898890/229683076-ccfd7337-ef88-4e8e-977f-7521d75e43fb.png)
2. 跳转sql工作台，没有可用的oracle数据源
![d8bff36b-26d0-4659-92b6-b7b54413a502](https://user-images.githubusercontent.com/113898890/229690106-a606f76d-8340-4d80-b911-932ed479f998.jpeg)
3. sqle平台登出，进入sqle数据库，删除cb两张缓存表
![image](https://user-images.githubusercontent.com/113898890/229690303-e372ca79-a657-42b7-870a-52a69d06d37a.png)
4. 重启sqled，重新登录平台，跳转sql工作台，仍无对应oracle数据源

**Expected behavior**

sql工作台应显示数据源列表中添加的数据源

**Comment by ColdWaterLW** [comment]
无法复现
