### ISSUE TITLE
调整工单描述的长度限制

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1451]
相关issue ：https://github.com/actiontech/sqle/issues/1397

后端支持的工单描述长度为3000，前端目前是限制在50个字符，需要调整到3000。支持使用垂直滚动条展示过长的内容

**Comment by Marcus9530** [comment]
UI Version: release-2.2304.x 3e01d1b
Server Version: release-2.2304.x-ee 6e284f0e41
验证通过步骤：
创建工单，在工单描述文字框，输入3000文字，然后超过限制数量之后的文字前端不会保存，点击创建工单，查看工单描述，可以看到工单描述中的文字内容，并且是垂直滚动条进行滑动
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/54339501/235045629-b2e5651c-2822-46f9-a600-8487c01041db.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/54339501/235045691-6f311b9d-31cb-42f5-834a-d825ac96d56e.png">

但是建议工单描述展示框给一个固定的范围，然后在上下滑动查看，可能展示效果会更好一点
