### ISSUE TITLE
使用pg数据源，在审核语句的时候带上库名，会导致sql分析界面查询的时候不存在

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1467]
**SQLe Version**
UI Version: release-2.2304.x 3e01d1b
Server Version: release-2.2304.x-ee 6e284f0e41

1.使用以下sql准备数据
`create table Teacher(TId varchar(10),Tname varchar(10));
insert into Teacher values('01' , '张三');
insert into Teacher values('02' , '李四');
insert into Teacher values('03' , '王五');`
2.创建工单，然后审核语句为
`SELECT * FROM test.Teacher`
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/54339501/234216828-c6f583a9-48b5-4e3b-ac86-0b0b1dcbaa52.png">

3.点击sql分析，可以看到报错提示"test.teacher" does not exist
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/54339501/234216740-e41649cd-a507-49cc-84ec-5597f753ca24.png">

4.不带库名的时候
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/54339501/234219254-40f0f994-5bfb-43bd-876b-0d50e0e53b47.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/54339501/234219310-8d82b95f-ba50-408c-82fd-802f57c267f4.png">

**Comment by ColdWaterLW** [comment]
不是缺陷
