### ISSUE TITLE
添加数据源时根据数据源类型自动切换默认端口

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1473]
目前添加数据源页面的端口号默认都是3306
![image](https://user-images.githubusercontent.com/36940986/234482034-f12c48ae-8a7e-41fe-bec7-2d3b04921701.png)

预期：用户切换数据源类型时，根据选择的数据源类型切换默认端口

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main 9ea89a6
Server Version: main-ee 4fa2562356

1,数据库类型切换为SQLserver
![image](https://github.com/actiontech/sqle/assets/99949903/0b4e2976-025b-4ad1-9f95-0f6181569b58)
2，切换为mysql
![image](https://github.com/actiontech/sqle/assets/99949903/a0348e0b-f2f7-41db-b683-d060e6ea1701)
3，切换为DB2
![image](https://github.com/actiontech/sqle/assets/99949903/82e5a309-9658-4f0d-bc5f-74f4fa0429f1)
4，切换为oracle
![image](https://github.com/actiontech/sqle/assets/99949903/a55c3ca8-9094-4325-978d-5bd446a34af0)
5，切换为Postgresql
![image](https://github.com/actiontech/sqle/assets/99949903/a996c908-7750-4fad-a9c6-6744fc9ea072)
**目前ob和tidb数据库无法自动切换默认端口，默认为0**
![image](https://github.com/actiontech/sqle/assets/99949903/ca11e825-9a92-4cec-b75d-7135887f574f)
![image](https://github.com/actiontech/sqle/assets/99949903/e06a6c5c-3826-422e-9bef-9cd5a4c205eb)
