### ISSUE TITLE
被驳回的工单，操作按钮置灰，但实际还可点击

### ISSUE THREAD

**Issue by LLLKLQLJ** [actiontech/sqle#1480]
**SQLe Version**
UI Version: release-2.2304.x 3e01d1b
Server Version: release-2.2304.x-ee 6e284f0e41

**Describe the bug**

工单被驳回，概览中操作都置灰
![image](https://user-images.githubusercontent.com/30652272/234744411-8e4e76d0-f5a1-4c2c-b76b-b24c222d5946.png)

实际点击操作中的按钮跳转到另一个tab中，容易造成困惑
![image](https://user-images.githubusercontent.com/30652272/234744494-f638a3cf-f063-4f86-9fca-618feb823b98.png)

期望：按钮置灰就不可点击

**Comment by ColdWaterLW** [comment]
**方案**
鼠标放在灰色的按钮上时光标变为禁用图标，并且点击不作任何响应

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

1,创建一个工单并驳回
![image](https://github.com/actiontech/sqle/assets/99949903/59598161-6dff-4288-8361-a4cac90877ba)
2，点击操作中的“立即上线”和“定时上线”无反应
