### ISSUE TITLE
慢日志扫描任务SQL详情出现空白SQL，阻碍扫描任务执行

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1482]
**SQLe Version**
ee-2.2303 rel

**Describe the bug**
mysql慢日志扫描任务审核，提示the node is empty after parse.the sql is:
查看扫描任务详情中的SQL统计信息，存在一条空白的SQL记录
![image](https://user-images.githubusercontent.com/113898890/234776222-d86730a7-0a93-4197-8b45-fb1656c5a287.png)

**Expected behavior**
慢日志扫描任务中不应出现空白SQL，阻碍扫描

**Comment by Gygkimo95** [comment]
* 情况如下：
  * 为了尽快出测试结果，所以把慢查时间设为了0，导致所有的SQL都进入了慢查日志（包括";"，但其实这句是空的SQL）
  * sqle去扫描慢查日志，把这句";"也扫描进去了，但其实这句SQL本体就是空白的，所以页面显示为空白，提示然后出现报错 the node is empty after parse.the sql is: ，阻碍了扫描任务 
  * 之后修改慢日志文件，将";"部分删除，再次执行扫描任务，可以正常执行

* 结论：慢查文件中的空语句阻塞了扫描任务
鉴于目前这种场景出现的概率不高，优化收益不高，产品侧目前暂不优化

**Comment by taolx0** [comment]
### 自测
![image](https://github.com/actiontech/sqle/assets/63177450/585b6089-005a-44bc-b0f4-3410a8a547a6)

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
1.往慢日志写入一个空白的
2.等待扫描任务进行采集
3.点击审核，可以看到审核报错
![image](https://github.com/actiontech/sqle/assets/54339501/2757ec29-9956-437e-b5d0-9b6e015c39f3)
![image](https://github.com/actiontech/sqle/assets/54339501/8d17577c-98cd-44c4-a30f-c15f557f5108)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee 35e1c6cd86
验证步骤：
1.往慢日志写入一个空白的
2.等待扫描任务进行采集
3.点击审核，可以正常审核

![image](https://github.com/actiontech/sqle/assets/54339501/e06bbac6-a0a1-4606-b571-e9015151ff4b)
![image](https://github.com/actiontech/sqle/assets/54339501/3b70e611-6f71-4448-a524-1694f5fc3eae)
