### ISSUE TITLE
重复安装sqle，钉钉无法收到审批

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1487]
### 复现
1. 安装sqle，配置钉钉，点击提交按钮，创建工单，钉钉端成功收到审批
![image](https://user-images.githubusercontent.com/63177450/235122018-58e7301c-5b74-44c9-b1b0-162eb4320902.png)

2. 移除sqle环境，再次安装sqle，配置钉钉，点击提交按钮，此时钉钉端无法收到审批

### 原因
钉钉审批模版名不能相同，第二次配置钉钉的审批名字和第一次相同，导致创建创建审批模版失败，无法获取审批模版的process_code，导致参数错误，向钉钉端发送审批请求失败。

**Comment by hasa1K** [comment]
#### 解决方法
发送`FormCreateWithOptions` 请求失败后，判断错误码是不是`formName.error`，如果是`formName.error`说明审批模板已经创建过了，发送`GetProcessCodeByNameWithOptions`请求，通过审批表单名获取到process code并更新到数据库中

**Comment by hasa1K** [comment]
#### 补充
需要开启钉钉应用开发的权限管理中的OA审批的工作流模板读权限

**Comment by Marcus9530** [comment]
验证通过
验证步骤：
1.第一次配置钉钉，然后创建好工单可以看到钉钉上受到审核提示
2.然后清理sqle环境
3.重新搭建sqle环境
4.再一次配置钉钉
5.创建工单，然后回到钉钉可以看到收到审批提示
![image](https://github.com/actiontech/sqle/assets/54339501/448df5fb-d8a5-40f3-b82a-5bc2459669c5)
![image](https://github.com/actiontech/sqle/assets/54339501/173a79ce-b46a-4ea9-b08f-9bdc78c06ccf)
![image](https://github.com/actiontech/sqle/assets/54339501/21da5716-9425-4a9b-855c-1b5a17ff3183)
![image](https://github.com/actiontech/sqle/assets/54339501/ed2ac009-7ad9-48a0-96be-951945e8bc8e)
![image](https://github.com/actiontech/sqle/assets/54339501/482e60fa-7bcf-4c3f-a134-a1eab317341a)
