### ISSUE TITLE
mysql规则触发有误：“避免使用IN (NULL)/NOT IN (NULL) ，该用法永远非真将导致条件失效”

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1495]
**SQLe Version**
main-ee 50c38d935c

**Describe the bug**
平台创建工单填入SQL：update  audit_plans set name=103167,token=10015771 where id in (3283,13434);
审核结果提示：
![image](https://user-images.githubusercontent.com/113898890/237007056-f08c649d-a5e0-4e6c-b2f5-bc9808e17f23.png)

**Expected behavior**
（）非null值，不应触发“避免使用IN (NULL)/NOT IN (NULL) ，该用法永远非真将导致条件失效”的规则

**Comment by ColdWaterLW** [comment]
**问题原因**
在判断IN和NOT IN中的值时，当值为空字符串时认为是NULL，这样只有值为字符串类型能判断正确，值为其他类型时就会出现错误

**解决方案**
判断IN和NOT IN中的值时不做值对比，而是判断值的类型是否为NULL

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

创建工单,进行审核，审核通过
![image](https://github.com/actiontech/sqle/assets/99949903/39f58c7c-a539-40eb-b199-ef3e7a9ed2fb)
