### ISSUE TITLE
工单审核结果需要显示SQL语法高亮

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1499]
**SQLe Version**
UI Version: main 45a292b
Server Version: main-ee 50c38d935c

**Describe the bug**
参考之前的文档，审核结果SQL这里是有语法高亮的
![262fe87e-7b3b-4bf9-a6ea-46ecac83d827](https://github.com/actiontech/sqle/assets/113898890/9b024941-2d89-44d0-8fc8-32368cc86042)
上个月调整过审核结果这边的显示之后，高亮消失
![dd8dbc70-c3bb-48a9-8403-a34a254821ed](https://github.com/actiontech/sqle/assets/113898890/ad2b5a78-fdd2-4c77-b222-140676da12d8)

**Expected behavior**
审核结果SQL显示高亮

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

创建工单，进行审核，查看审核结果中的sql语句有语法高亮提示
![image](https://github.com/actiontech/sqle/assets/99949903/f74eec7f-4fbe-4e02-8aa1-edfa02e06f91)
点击工单，查看工单中的执行语句，仍有高亮提示
![image](https://github.com/actiontech/sqle/assets/99949903/e895689a-b816-4b4b-b28a-67a88e008110)
