### ISSUE TITLE
智能扫描任务中，修复【SQL分析】操作返回的 "database not selected" 错误。

### ISSUE THREAD

**Issue by jessun** [actiontech/sqle#1518]
**Describe**
在新建的智能扫描任务中，用户可以不选择数据库（schema），对于扫描的任务而言没有影响。
但是在用户使用【SQL分析】功能时，可能会返回「database not selected」错误。

**Why**
在进行【SQL分析】时，sqle 调用 MySQL 的部分接口没有传入正确的 Schema 参数。

**Suggestion**
- 调整部分扫描任务，使得 sqle 在进行SQL分析时，能够正确传入参数；
- 调整 SQL 分析功能实现（TODO）

需要确保的场景有：

- [ ] MySQL 慢日志采集；
- [ ] MySQL processlist 采集；

**Comment by jessun** [comment]
## 变更原因

在 processlist 等扫描任务的采集中，虽然记录了sql 关联的schema，但是该字段信息没有记录在【审核报告】的sql表"audit_plan_report_sqls_v2"中。
进而导致【SQL分析】在调用MySQL插件接口，接口返回 "Error 1046: No database selected"。

![image](https://github.com/actiontech/sqle/assets/13587641/6a991070-eaa4-4242-9ca2-7981650c80ec)


## 变更方案

在扫描任务采集时，将采集中产生的 schema 字段连同 sql 一同存储。在审核时，再将 sql 和 schema 一同发给审核插件进行审核。

涉及的扫描任务：processlist/slow_log/mybatis。

## 变更内容
1. 表"audit_plan_sqls_v2"和"audit_plan_report_sqls_v2"新增字段"schema"，表明该行记录的 sql 所关联的 schema。
2. SQL 分析 API 在实现上要调整为：在原有的参数基础上增加一个参数 "schema"

**Comment by hasa1K** [comment]
#### 慢日志变更方案
扫描任务采集慢日志有两种方式
1. 通过scanner采取慢日志文件中的sql信息
2. 通过查询mysql.slow_log采集慢日志文件中的sql信息
慢日志文件中不记录sql对应的Schema，第一种方式没有办法修改
第二种方式，在获取慢日志信息时会获取到Schema的信息，并且记录在AuditPlanSQLV2表中的Info字段中。但是在sql分析传参时使用的是AuditPlan中的InstanceDatabase

针对第二种方式的修改:
model层
AuditPlanSQLV2和AuditPlanReportSQLV2新增数据库字段Schema


server层
获取mysql.slow_log并将慢sql写入数据库时，添加Schema字段，标明慢sql是哪个数据库
触发SQL自动审核时，生成AuditPlanReportSQLsV2时，从AuditPlanSQLV2获取单条sql对应的数据库

API层
对应接口内部传参时使用AuditPlanReportSQLV2的Schema代替AuditPlan的InstanceDatabase

**Comment by hasa1K** [comment]
#### processlist变更方案
server层
获取正在执行的sql并写入AuditPlanSQLsV2表时，添加Schema字段
触发SQL自动审核时，生成AuditPlanReportSQLsV2时，从AuditPlanSQLV2获取单条sql对应的数据库

API层
对应接口内部传参时使用AuditPlanReportSQLV2的Schema代替AuditPlan的InstanceDatabase

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee 35e1c6cd86
验证步骤：


慢日志表扫描任务

![image](https://github.com/actiontech/sqle/assets/54339501/9d726e9a-55ff-4efe-8e4b-a9ced51e9dab)
![image](https://github.com/actiontech/sqle/assets/54339501/85ae55f5-2455-43c6-be73-71ecfc3cb446)
![image](https://github.com/actiontech/sqle/assets/54339501/bd54937e-4fad-4849-aae3-7e6900990a63)
processlist扫描任务

![image](https://github.com/actiontech/sqle/assets/54339501/b5747c26-c2c9-44b1-a333-a5745a4d867d)
![image](https://github.com/actiontech/sqle/assets/54339501/4471f6c7-30d6-4eb7-9b21-02a3a3a4115f)
![image](https://github.com/actiontech/sqle/assets/54339501/752b4427-ac88-4bca-8b4f-5fc158d58504)
