### ISSUE TITLE
支持中止SQL上线操作

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1519]
SQLe 新增功能，能够支持 SQLe 能够对正在上线中 SQL 执行 Kill query 操作。

**Comment by jessun** [comment]
## 变更方案

- 新增 SQL API 实现，后端可以对进行中的上线中的 SQL 进行 Kill。
该接口为异步接口，用户需要自行刷新页面确认Kill是否成功。

- 新增审核插件接口 KillQuery()，支持对执行的SQL进行 Kill Query 操作。
MySQL 审核插件实现参考： https://github.com/rocketlaunchr/mysql-go

## 变更内容
1. 后端新增 POST API，支持前端能够对一个或者多个上线任务进行 Kill 
/v2/projects/default/workflows/:workflow_id/tasks/kill
/v2/projects/default/workflows/:workflow_id/tasks/:task_id/kill

2. 插件新增 Kill() 接口，并且完成 MySQL 的 Kill() 接口的功能实现。在 MySQL 执行上线时，记录当前的 connection_id。在收到Kill()调用后，MySQL 插件新建连接来 kill 正在执行中的query。
参考实现：https://github.com/rocketlaunchr/mysql-go/blob/b20aedd5edd83063b1ccd09cbe43440b8b3119c5/helpers.go#L13

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/1539
