### ISSUE TITLE
将成员设为项目管理员后，无需设置数据源及操作权限

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1536]
## 背景
将成员设为项目管理员后，该成员自动拥有该项目中所有数据源的所有操作权限，无需额外设置数据源及权限

### 将成员设为项目管理员后，无需设置数据源及操作权限
**说明**
将成员设为项目管理员后，该成员自动拥有该项目中所有数据源的所有操作权限，无需额外设置数据源及权限

**需求概要**
项目管理员添加成员时，若不设为项目管理员，则可以为成员配置可用的数据源及角色权限
项目管理员添加成员时，若将成员设置为项目管理员，则不需要为成员配置可用的数据源及角色权限

**原型设计**
不设为项目管理员的情况，保持现状不变
![image](https://github.com/actiontech/sqle/assets/36940986/8266cede-8dc5-4030-9575-eb6fb229aead)
设为项目管理员的情况，隐藏【添加角色与数据源的绑定】按钮
![image](https://github.com/actiontech/sqle/assets/36940986/86b27e4e-7fdc-435a-bd23-acf0d610543d)

**影响范围**
【添加成员、编辑成员】弹窗

### 成员列表权限列，项目管理员显示【All】
**说明**
项目管理员拥有该项目中所有数据源的所有操作权限，但在成员列表中权限列显示为空，无法直观获得该信息，需要增加说明

**需求概要**
在项目管理员的权限列上标识【All】，说明是对所有数据源有所有操作权限，区别那些因没有设置数据源、权限而权限列显示为空的普通成员

**原型设计**
![image](https://github.com/actiontech/sqle/assets/36940986/3eda0390-fd54-4a85-9b34-734771ee3193)

**影响范围**
成员列表页

**Comment by Marcus9530** [comment]
需求测试中已验证
