### ISSUE TITLE
mysql审核sql：update t_admin_user set mobile = '123213123' where mobile = '13466667777';，报 convert OB MySQL create table sql failed 错误

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1537]
**SQLe Version**
main c06efc94583b0aa7bdd9e235d6c093040f88f78d

**To Reproduce**
1. 禁用下图规则
![image](https://github.com/actiontech/sqle/assets/63177450/8db3e472-a39b-456f-b4ff-2c1423fd5a93)
2. 创建选择下图版本数据源（MySQL 8.0.28之后的版本）
![image](https://github.com/actiontech/sqle/assets/63177450/6c1c9116-d9f3-4cac-a6ea-ce39d277c2b0)
3. 创建以下的表
```
CREATE TABLE `t_admin_user`
(
    `user_id`          bigint NOT NULL COMMENT '主键',
    `username`         varchar(100)    DEFAULT NULL COMMENT '用户名',
    `password`         varchar(64)     DEFAULT NULL COMMENT '密码',
    `salt`             varchar(32)     DEFAULT NULL COMMENT '安全符',
    `img`              varchar(200)    DEFAULT NULL COMMENT '头像',
    `realname`         varchar(100)    DEFAULT NULL COMMENT '真实姓名',
    `num`              varchar(100)    DEFAULT NULL COMMENT '员工编号',
    `mobile`           varchar(20)     DEFAULT NULL COMMENT '手机号',
    `email`            varchar(50)     DEFAULT NULL COMMENT '邮箱',
    `sex`              int             DEFAULT NULL COMMENT '0 未选择 1 男 2 女 ',
    `dept_id`          bigint          DEFAULT NULL COMMENT '部门',
    `post`             varchar(50)     DEFAULT NULL COMMENT '岗位',
    `status`           int    NOT NULL DEFAULT '2' COMMENT '状态,0禁用,1正常,2未激活',
    `parent_id`        bigint          DEFAULT '0' COMMENT '直属上级ID',
    `last_login_time`  datetime        DEFAULT NULL COMMENT '最后登录时间',
    `last_login_ip`    varchar(30)     DEFAULT NULL COMMENT '最后登录IP 注意兼容IPV6',
    `create_time`      datetime        DEFAULT NULL COMMENT '创建时间',
    `create_user_id`   bigint NOT NULL COMMENT '创建人ID',
    `update_time`      datetime        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_user_id`   bigint          DEFAULT NULL COMMENT '修改人ID',
    `is_binding_work`  int             DEFAULT '0' COMMENT '是否绑定企业微信',
    `wx_mobile`        varchar(255)    DEFAULT NULL COMMENT '企业微信手机号',
    `wx_user_id`       varchar(255)    DEFAULT NULL COMMENT '企业微信userid',
    `dingtalk_user_id` varchar(255)    DEFAULT NULL COMMENT '钉钉用户id',
    PRIMARY KEY (`user_id`) USING BTREE,
    KEY `parent_id` (`parent_id`) USING BTREE,
    KEY `dept_id` (`dept_id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb3
  COLLATE = utf8mb3_bin
  ROW_FORMAT = DYNAMIC COMMENT ='用户表';
```
4. 审核sql：update t_admin_user set mobile = '123213123' where mobile = '13466667777'; 
![image](https://github.com/actiontech/sqle/assets/63177450/3c13cfe1-3e88-4c89-930a-d86195e385c7)

**Expected behavior**
能正常执行流程

**Comment by taolx0** [comment]
## why？
mysql 解析器不支持 utf8mb3 字符集表的解析
![image](https://github.com/actiontech/sqle/assets/63177450/a7fa732c-f604-4f20-9912-746853d826f8)

**Comment by jessun** [comment]
related issue #488

**Comment by sjjian** [comment]
## 临时方案：
启动规则 ”停用上线审核模式“ 可绕过

**Comment by Marcus9530** [comment]
复现版本 ：
Server Version: main-ee 35e1c6cd86
复现步骤：
1.搭建一个mysql8.0.31版本的容器
2.在sqle平台添加8.0.31版本的mysql到数据源
3.在mysql8.0.31上创建表t_admin_user
4.然后回到sqle上创建工单
5.使用上述sql进行审核，可以看到报错

![image](https://github.com/actiontech/sqle/assets/54339501/67251d61-e272-42d4-8601-fb7e387702bf)

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee ac054975fa

验证步骤：
1.搭建一个mysql8.0.31版本的容器
2.在sqle平台添加8.0.31版本的mysql到数据源
3.在mysql8.0.31上创建表t_admin_user
4.然后回到sqle，开启所有的mysql审核规则
5.使用上述sql进行审核，当前可以正常审核触发相关审核提示
![image](https://github.com/actiontech/sqle/assets/54339501/01619fa0-27da-42b4-a86b-6eb85f162e54)
