### ISSUE TITLE
工单详情内对正在执行的sql点击中止上线之后，sqle直接panic

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1539]
UI Version: main 9ea89a6
Server Version: main-ee 4fa2562356

复现步骤：
1.创建一个工单，里面输入一些批量sql进行审核
2.然后执行上线
3.在正在执行状态中，点击中止上线，出现panice
![46b06c9d-fc9f-42ab-b8ab-2fd64d1885fa](https://github.com/actiontech/sqle/assets/54339501/2b284ff0-3be6-48ab-814e-cf93be1d468c)

**Comment by ColdWaterLW** [comment]
**原因**
遍历事务返回的结果时逻辑错误，导致数组越界
