### ISSUE TITLE
AuditPlanSQLV2 model 的GetFingerprintMD5() 方法存在 bug

### ISSUE THREAD

**Issue by jessun** [actiontech/sqle#1545]
**SQLe Version**
0d19e77

**Describe the bug**
![image](https://github.com/actiontech/sqle/assets/13587641/05222207-bbf7-4b27-ac1e-50bdf1fdcd85)
当a.FingerprintMD5不为空时，该函数会陷入死循环。截至目前，该问题暂未导致产品问题。

**验证建议**
由于该段问题代码无法被触发。建议验证以下任一场景，确保这些扫描任务中「SQL统计信息」中抓取的SQL符合预期即可：
- 扫描任务，MySQL 慢日志（mysql.slow_log 表）
- 扫描任务，MySQL 库表元数据
- 扫描任务，阿里云RDS MySQL 慢日志
- 扫描任务，阿里云RDS MySQL 审计日志

**Comment by Marcus9530** [comment]
该场景特殊无法复现，故直接验证。

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main bc602fc
Server Version: main-ee b4dc252855
验证步骤：
1.添加一个慢日志表采集的扫描任务
2.等待采集慢sql，发现可以正常到慢日志表中的sql语句
<img width="1135" alt="image" src="https://github.com/actiontech/sqle/assets/54339501/12b8b2ba-72c3-4aac-8aff-67096e6059d2">
<img width="1066" alt="image" src="https://github.com/actiontech/sqle/assets/54339501/b58bc965-f8f3-4c39-b445-207d40086d5c">
