### ISSUE TITLE
添加白名单时在弹窗中无法输入 SQL 语句

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1546]
**SQLe Version**
UI Version: release-2.2304.x 767f7f4

**Describe the bug**
![image](https://github.com/actiontech/sqle/assets/42765421/92a3c3e0-7bd4-4c32-b271-3ffcd631bf32)

**To Reproduce**
1. 使用 admin 账号登录 sqle 企业版
2. 点击项目菜单, 查看所有项目, 然后进入 default 项目
3. 点击左侧菜单, 进入白名单页面, 点击添加白名单

**Expected behavior**
希望在添加白名单时能够正常输入 SQL 语句

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
添加白名单的时候，点击sql语句准备输入，但是无法输入任何sql
<img width="1609" alt="image" src="https://github.com/actiontech/sqle/assets/54339501/1cdda49f-8459-4133-ab51-b6f7873cff43">

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main bc602fc
Server Version: main-ee b4dc252855
验证步骤：
当前进入到白名单界面可以正常输入sql语句
<img width="1455" alt="image" src="https://github.com/actiontech/sqle/assets/54339501/45547d66-01be-43f6-be32-0ceb9edf4c31">
