### ISSUE TITLE
升级方案

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1550]
由于新版本有破坏性变更，不能直接兼容旧版本的数据，所以需要向社区用户提供从2.2305.0版本升级到2.2306.0版本的方法

**需要做升级方案的issue**
- [x] https://github.com/actiontech/sqle/issues/1396 
- [x] https://github.com/actiontech/sqle/issues/1588

**Comment by taolx0** [comment]
### 智能扫描任务点击审核报错升级方案
`ALTER TABLE audit_plan_report_sqls_v2_test
    CHANGE COLUMN `sql` `sql` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL;`

**Comment by hasa1K** [comment]
#### 即时通讯工具的配置升级方案
在系统设置中重新配置下有关消息推送和流程对接中的密码和密钥
