### ISSUE TITLE
规则“复合索引的列数量不建议超过阈值” 触发存在不成功的情况

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1554]
**SQLe Version**
release-2.2305.x-ee 8abf46130b

**Describe the bug**
* 前置：设置阈值为3
* 执行SQL1：alter table table_test add index index_test1 (a,b,c,d,e,f);
* 审核结果未成功触发
* 执行SQL2：CREATE TABLE t1(id int PRIMARY KEY,name varchar(10),age int,dd int,ee int,gg int,kk int,index(name,age,dd,gg));
* 审核结果成功触发

**To Reproduce**
* 阈值设为3
![image](https://github.com/actiontech/sqle/assets/113898890/4043d38a-878c-426e-a7ca-fc60e1de9f0f)
* SQL1审核结果
![image](https://github.com/actiontech/sqle/assets/113898890/4458fc43-27e5-4c1d-9106-1801acc7a5dd)
* SQL2审核结果
![image](https://github.com/actiontech/sqle/assets/113898890/33d8bb5d-890d-4369-8044-e42abaeb7811)

**Comment by jessun** [comment]
## 问题原因
<img width="927" alt="image" src="https://github.com/actiontech/sqle/assets/13587641/ceb9074b-eda8-461c-b4bc-4c045b58c9a6">

目前在该审核规则上，如果启用了「停用上线审核模式」规则，会跳过 AlterTable 检查。受该规则影响的规则如下：

检查DDL创建的新索引对应字段是否已存在过多索引，AlterTable 和 CreateIndex 语句不再检查。
使用explain加强预检查能力，AlterTable 和 CreateIndex 语句不再检查。
表必须有主键，AlterTable 不再检查。
主键建议使用自增，AlterTable 不再检查。
主键建议使用 bigint 无符号类型，即 bigint unsigned，AlterTable 不再检查。
索引个数建议不超过阈值，AlterTable 和 CreateIndex 语句不再检查。
复合索引的列数量不建议超过阈值，AlterTable 和 CreateIndex 语句不再检查。
禁止将blob类型的列加入索引，AlterTable 和 CreateIndex 语句不再检查。
主键禁止使用自增，AlterTable 不再检查。

## 解决方法
禁用「停用上线审核模式」规则

**Comment by Gygkimo95** [comment]
前置
![image](https://github.com/actiontech/sqle/assets/113898890/ac5cd7aa-fd93-45fa-babf-b57fe33f7852)
SQL1审核结果
![image](https://github.com/actiontech/sqle/assets/113898890/9517e57a-e34f-4499-a650-22927a238394)

结论：禁用「停用上线审核模式」规则后，规则“复合索引的列数量不建议超过3个”触发成功
