### ISSUE TITLE
cloudbeaver session id过期后，没有更新

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1579]
**SQLe Version**

**Describe the bug**
cb的session id过期后，sqle没有重新获取新的session_id，导致连接不上cb

![image](https://github.com/actiontech/sqle/assets/53266479/0fbbc2a2-62c2-4968-9058-22805719dcc5)
![image](https://github.com/actiontech/sqle/assets/53266479/f301c342-c0d4-43a3-8641-296b4727a8f4)

**Comment by hasa1K** [comment]
#### 解决方案
由于cloudbeaver没有刷新token得机制，只能重新登录。可以在echo添加一个新的中间件，识别cloudbeaver返回的结果是否带有error字段，并且错误信息是session id过期。识别到session id过期后，重新发送登录请求获取到新的session id，再将之前的请求重新发送一次。

**Comment by Marcus9530** [comment]
复现版本：
UI Version: main 111f6455
Server Version: main-ee 35e1c6cd86
复现步骤：
1.搭建cb跟sqle
2.然后配置好sqle跟cb信息
3.在sqle点击sql工作台跳转到cb界面
4.然后等待几分钟，登陆cb服务器，修改系统时间为当前时间的往后20天
5.等待两分钟，当前cb页面提示session过期，点击数据源提示sessionerror
![image](https://github.com/actiontech/sqle/assets/54339501/5cc7f80c-d71a-41bb-8153-17fc1987ab20)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d8eab78
Server Version: main-ee 9702d3761f

验证步骤：
**场景一：**

1.搭建cb跟sqle
2.然后配置好sqle跟cb信息
3.在sqle点击sql工作台跳转到cb界面
4.然后等待几分钟，登陆cb服务器，修改系统时间为当前时间的往后20天
5.等待两分钟，在当前cb页面进行操作，没有之前的报错提示，可以正常进行


![image](https://github.com/actiontech/sqle/assets/54339501/2b530a2d-d423-4fc7-be86-9816c0d847ee)
![image](https://github.com/actiontech/sqle/assets/54339501/3426b5d3-dc3b-4948-bcf5-ce13f7ec251d)
![image](https://github.com/actiontech/sqle/assets/54339501/18eed231-eb32-4651-ae58-54a019f42e93)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 86710b0
Server Version: main-ee d6ade44ccf

验证步骤：
1.sqle部署好cb
2.调整cb服务器为6天后的时间
3.然后在cb界面上执行sql语句，刷新之类的操作也没有出现报错提示。
![img_v2_a4f64608-a6a4-464c-8134-ca94b3f5833g](https://github.com/actiontech/sqle/assets/54339501/f73ad250-3508-43f5-9f45-993e134caa6a)
![image](https://github.com/actiontech/sqle/assets/54339501/0e97b8c7-2c42-482c-9646-395716d56d3b)
![image](https://github.com/actiontech/sqle/assets/54339501/6f7da97d-ea53-40bd-8b3d-d1c7bd20f450)
