### ISSUE TITLE
同一个项目里可以创建同名工单

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1582]
预期：同一个项目里不能有同名工单

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
在一个项目内创建两个名字一样的工单，可以成功创建
![image](https://github.com/actiontech/sqle/assets/54339501/b39f4af9-1ee5-4245-b6b8-c93e39d52a53)

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee 35e1c6cd86

验证步骤：
当前在一个项目内，无法创建两个名字一摸一样的工单

![image](https://github.com/actiontech/sqle/assets/54339501/7f1504d0-4ffc-4e6a-a10d-4bdc9705f782)
