### ISSUE TITLE
智能扫描任务点击审核报错 "Error 1046: Data too long"

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1588]
**SQLe Version**

**Describe the bug**

![img_v2_e7343f09-7b79-42cd-9d5f-339e6f981eag](https://github.com/actiontech/sqle/assets/18008452/cf73cadc-99d2-433c-8738-2384e6c01e12)
原因：
智能扫描任务的 audit_plan_sqls_v2 （SQL统计） 里SQL可存储长度为mediumtext ；生成审核报告时 audit_plan_report_sqls_v2 (审核报告) SQL字段长度为 text。因此当SQL采集到太长的 SQL 超过 text 长度导致生成审核报告时报错。

audit_plan_sqls_v2 表
```sql
CREATE TABLE `audit_plan_sqls_v2` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `audit_plan_id` int(10) unsigned NOT NULL,
  `fingerprint` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `fingerprint_md5` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sql_content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `info` json DEFAULT NULL,
  `schema` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint_md5` (`audit_plan_id`,`fingerprint_md5`),
  KEY `idx_audit_plan_sqls_v2_deleted_at` (`deleted_at`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
audit_plan_report_sqls_v2 表
```sql
CREATE TABLE `audit_plan_report_sqls_v2` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `audit_plan_report_id` int(10) unsigned DEFAULT NULL,
  `sql` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `number` int(10) unsigned DEFAULT NULL,
  `audit_results` json DEFAULT NULL,
  `schema` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_plan_report_sqls_v2_deleted_at` (`deleted_at`),
  KEY `idx_audit_plan_report_sqls_v2_audit_plan_report_id` (`audit_plan_report_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
**To Reproduce**

采集到的SQL超过text长度即可复现

**Expected behavior**

**Suggestion**

建议保持 audit_plan_sqls_v2 表和 audit_plan_report_sqls_v2表SQL字段长度一致

**Comment by Marcus9530** [comment]
复现版本：Server Version: release-2.2305.x-ee 8abf46130b

复现步骤：
1.往慢日志写入一个很长的sql语句，该语句大于65535
2.然后添加一个慢日志扫描任务
3.等待采集到sql，点击审核，提示报错

![image](https://github.com/actiontech/sqle/assets/54339501/d3caf487-172d-4a95-813d-f3738d9bb556)

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee 35e1c6cd86
验证步骤：
1.往慢日志写入一个很长的sql语句，该语句大于65535
2.然后添加一个慢日志扫描任务
3.等待采集到sql，点击审核，可以正常审核

![image](https://github.com/actiontech/sqle/assets/54339501/f840b5a0-9c59-481c-a9d9-b5c118b96971)
![image](https://github.com/actiontech/sqle/assets/54339501/568efda1-16d5-4f09-8770-2ba6f2929283)
