### ISSUE TITLE
优化社区版与企业版之前功能的对比

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1592]
**Describe**
希望能够更加具体地展示企业版中独有的功能特点。

**Suggestion**
 例如社区版的报表统计仅提供了商业链接，无法展示该页面的具体功能效果。建议添加企业版的报表统计功能展示，以便用户更清晰地了解该功能的具体效果。这样可以更好地评估企业版相对于社区版的优势和差异。
![image](https://github.com/actiontech/sqle/assets/42765421/6cad94d7-dfce-49b4-8e0e-f2aa2ab59c53)

调整建议: 
![image](https://github.com/actiontech/sqle/assets/42765421/e0e540dc-1afc-4c2e-a518-19f6094cc59d)

预期的影响范围:
1. 报表统计
2. 外部数据源同步
3. 系统设置-oauth2.0配置
4. 白名单

**Comment by Marcus9530** [comment]
验证版本
社区版本：UI Version: main 7c2f8c4
Server Version: main 42364c019f
验证步骤：
如图所致，当前社区版本的这几个页面都给出了相关功能提示

1. 报表统计
2. 外部数据源同步
3. 系统设置-oauth2.0配置
4. 白名单

![image](https://github.com/actiontech/sqle/assets/54339501/27a17538-3836-4df7-9321-151e2af0231f)
![image](https://github.com/actiontech/sqle/assets/54339501/d95a6193-31af-4b1f-9b35-8eb46acc29fb)
![image](https://github.com/actiontech/sqle/assets/54339501/cf8257d3-214c-482c-91ca-352c1969518c)
![image](https://github.com/actiontech/sqle/assets/54339501/4ea202f9-238b-4037-a5a5-b96a31d8ad3a)
