### ISSUE TITLE
优化scannerd采集慢日志文件后SQL上传流程

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1597]
## 问题现象
scannerd抓取慢日志文件SQL后，会把所有原始SQL推送给sql，没有进行聚合。导致sqle在将这批sql insert到元数据表时可能会出现很长的一条sql，不合理

## 复现
1. 创建一个慢日志扫描任务
2. 启动scannerd扫描一个很大的慢日志文件(其中有一些重复的或者类似的SQL)
3. 查看sqle插入慢日志的sql

## 解决方案
慢日志扫描时，scannerd在把sql上传之前先对sql进行指纹聚合

关联issue：#1588

**Comment by ColdWaterLW** [comment]
#1588

**Comment by taolx0** [comment]
### 自测
![image](https://github.com/actiontech/sqle/assets/63177450/4feabebc-c69c-43a5-b9ef-9043fd123b97)

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
1.添加一个慢日志扫描任务
2.开启mysql的慢日志功能
3.然后等待采集慢sql
4.查看sqle的日志，发现有条sql统计为1，即把所有的sql未聚合
![image](https://github.com/actiontech/sqle/assets/54339501/a27531e0-7ce3-4550-932f-1c4c6676c7ad)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee 35e1c6cd86
验证步骤：
1.添加一个慢日志扫描任务
2.开启mysql的慢日志功能
3.然后等待采集慢sql
4.查看sqle的日志，当前统计不是在1，复合预期。
![image](https://github.com/actiontech/sqle/assets/54339501/8715a0db-f36f-4df8-9465-9f126645f85f)
