### ISSUE TITLE
MySQL update生成回滚语句有误

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1599]
## 复现步骤
1. 启用MySQL规则“在 DML 语句中预计影响行数超过指定值则不回滚”
2. 在MySQL数据源创建表 ```create table tb7(id int,type int,appId varchar(30),is_white boolean,primary key (id));```并写入如下数据
![image](https://github.com/actiontech/sqle/assets/36940986/7c45dd2b-3e05-4132-9e66-efbf9cc56266)
4. 创建工单，输入update语句（update语句需要有实际命中的行，否则不会生成回滚语句）
```UPDATE tb7 set appId='app123456745746574', is_white=1 WHERE id=455 AND type=233;```
6. 点击审核
![image](https://github.com/actiontech/sqle/assets/36940986/cad89742-10af-4fcb-8759-9ed590366fdb)

**Comment by hasa1K** [comment]
#### 问题原因
update对象的原数据以键值对的形式获取(key为列名，value为值)
回滚语句在获取原数据内容时，使用`col.Name.String()`获取到小写的列名去键值对中获取值，这样的形式无法兼容到大写列名。

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
1.给mysql创建表并且打入数据
```
create table tb7(id int,type int,appId varchar(30),is_white boolean,primary key (id));
INSERT INTO tb7 (id, type, appId, is_white) VALUES (1, 2, 'app123', true);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (2, 1, 'app456', false);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (3, 2, 'app789', false);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (4, 1, 'app321', true);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (5, 2, 'app654', true);
```
2.然后使用上述updata语句进行审核
3.查看回滚语句可以看到返回appid=null
![image](https://github.com/actiontech/sqle/assets/54339501/ea0d2c9d-8eb2-41ae-afec-ef3b0c0b09d4)

**Comment by Marcus9530** [comment]
验证版本
Server Version: main-ee b4dc252855
验证步骤：
1.给mysql创建表并且打入数据

```
create table tb7(id int,type int,appId varchar(30),is_white boolean,primary key (id));
INSERT INTO tb7 (id, type, appId, is_white) VALUES (1, 2, 'app123', true);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (2, 1, 'app456', false);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (3, 2, 'app789', false);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (4, 1, 'app321', true);
INSERT INTO tb7 (id, type, appId, is_white) VALUES (5, 2, 'app654', true);
```
![d90415b2-1881-44c6-a3ec-c2af6a62d85d](https://github.com/actiontech/sqle/assets/54339501/e060f516-789c-4b06-83f0-3de9a74b4dfb)
2.然后使用上述updata语句进行审核
3.查看回滚语句可以看到返回appid=app321 复合预期。
