### ISSUE TITLE
百度云rds实例的慢日志扫描任务没有完全拉取慢sql的统计数量

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1609]
**SQLe Version**
UI Version: main d441e71
Server Version: main-ee 30bf302510

复现步骤：
1.添加一个百度云rds实例数据源
2.添加一个百度云rds实例慢日志扫描任务
3.对百度云rds实例进行压测
4.查看百度云界面rds实例慢日志
![image](https://github.com/actiontech/sqle/assets/54339501/2f4720c0-5c7d-4e79-a18b-a0bada05ade6)
5.然后在查看sqle的扫描任务中的sql信息统计
![image](https://github.com/actiontech/sqle/assets/54339501/24489ffd-f34c-431b-8e32-4b372112a0b6)

6.明显有很大差异

**Comment by taolx0** [comment]
### 自测
![Uploading image.png…]()

**Comment by Marcus9530** [comment]
验证版本
UI Version: main bc602fc
Server Version: main-ee b4dc252855
验证步骤：
1.添加一个百度云rds实例数据源
2.添加一个百度云rds实例慢日志扫描任务
3.对百度云rds实例进行压测
4.查看扫描任务的慢sql信息统计，当前为一致


![93740837-9b3f-490f-b744-8aa4b9db5e23](https://github.com/actiontech/sqle/assets/54339501/0adc8346-fa52-46bb-b4ff-83318d366d9c)
