### ISSUE TITLE
审核规则【复合索引不建议超过阈值】在所有审核规则开启下无法触发

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1616]
**SQLe Version**
UI Version: main bc602fc
Server Version: main-ee b4dc252855

复现步骤：
1.开启所有的审核规则
2.对一张表添加多个复合索引，并且超过阈值

![77d6025a-8678-40fb-a07d-efd7a0bb357b](https://github.com/actiontech/sqle/assets/54339501/11830d18-135b-4575-a4b9-c689ff4674f1)
![c97886ff-c263-4f4d-8c0c-602037a2be44](https://github.com/actiontech/sqle/assets/54339501/13be4b26-e872-4166-b4e7-d03351bf539d)
![5c48d35e-7676-4db8-b435-dd6ce1287a45](https://github.com/actiontech/sqle/assets/54339501/649b829c-8792-42c9-99db-deece61a9ee9)
![0bcbf3c7-909d-401d-ae1d-6e1055ec9c22](https://github.com/actiontech/sqle/assets/54339501/510b27f5-a5aa-495b-a85e-e2dbb5c3ccd3)

3.可以看到审核结果中没有出现对应的审核提示
影响范围：mysql、mycat

**Comment by winfredLIN** [comment]
您好，关于《issue1616：审核规则【复合索引不建议超过阈值】在所有审核规则开启下无法触发》

该问题的原因是：
在开启所有的审核规则的情况下，同时开启了审核规则【停用上线审核模式】。在Server Version: main-ee b4dc252855的版本中，停用上线审核模式，即离线审核模式下，对创建索引的审核，系统只判断创建的索引是否存在重复项，不对【复合索引不建议超过阈值】的审核规则进行判断。

解决方案是：
编辑数据源对应的规则模板，禁用【停用上线审核模式】这一规则即可解决问题。
