### ISSUE TITLE
格式化 SQL 语句后审核时解析出错

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1617]
未格式化时审核 SQL 语句

![img_v2_d97844e5-316e-41d8-abeb-ccc31ad38e6g](https://github.com/actiontech/sqle/assets/42765421/39faa2ea-4788-4553-aab9-66d47c92fe67)

格式化后审核 SQL 语句
![img_v2_6b3a339d-dff4-43a4-9aab-79498e76c90g](https://github.com/actiontech/sqle/assets/42765421/9cb6a0b4-af95-48d2-8630-89f5ae734a0f)

原因: 
格式化时未指定数据库类型导致 GROUP_CONCAT(a)  变成了 GROUP_CONCAT  (a)

预期:
希望 格式化前后得到的 SQL 审核结果一致.

**Comment by Marcus9530** [comment]
复现成功：
输入sql点击优化之后，审核解析失败

`SELECT GROUP_CONCAT(a) FROM t;`
 

<br class="Apple-interchange-newline">

![17a928e1-9eea-476a-a3ae-c3598a97b7d7](https://github.com/actiontech/sqle/assets/54339501/25b2525a-641b-432f-a143-150ca14ad712)
![e20dd736-e3cc-4293-b380-deaba1c4c2bf](https://github.com/actiontech/sqle/assets/54339501/f39610cb-10d1-41a8-95f9-f39f59fc5b4f)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 7c2f8c4
Server Version: main-ee 35e1c6cd86
验证步骤：

输入sql点击优化之后，正常审核成功

`SELECT GROUP_CONCAT(a) FROM t;`
![image](https://github.com/actiontech/sqle/assets/54339501/4f0b5200-12e9-4818-abdf-03f98b2b9822)
