### ISSUE TITLE
当工单状态为待上线时,无法终止上线

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1618]
**SQLe Version**
sqle ce main

**Describe the bug**
当工单状态为待上线时,点击终止上线,报错
![6dd0c47c-b2de-46fb-8e89-c222112d806b](https://github.com/actiontech/sqle/assets/63177450/75882a30-1c2c-4eb1-b95b-2dac413f31a1)

**To Reproduce**
1. 创建一个包含两个task的新工单
2. 点击立即上线
3. 点击终止上线

**Expected behavior**
能正常终止上线

**Suggestion**
检测是否能终止上线的逻辑,应该结合工单状态和task状态判断

**Comment by Marcus9530** [comment]
复现版本：Server Version: release-2.2305.x-ee 8abf46130b

复现步骤：
1.创建工单，使用两个不同数据源
2.输入两个sql进行审核，然后创建工单并审核通过
3.点击第一个数据源的sql 立即上线，然后立马点击中止上线
4.提示无法终止上线

![image](https://github.com/actiontech/sqle/assets/54339501/3e30bfca-857a-4210-8f30-e9a53c1949c6)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee 35e1c6cd86

验证步骤：
1.创建工单，使用两个不同数据源
2.输入两个sql进行审核，然后创建工单并审核通过
3.点击第一个数据源的sql 立即上线，然后立马点击中止上线
4.可以成功取消上线
![image](https://github.com/actiontech/sqle/assets/54339501/8cc6ebd7-7d4f-48cb-883e-6a8197406d72)
![image](https://github.com/actiontech/sqle/assets/54339501/42835a8c-a6f3-4b73-99fa-d9cecf555af2)
