### ISSUE TITLE
Dashboard 列表以及 Header 的菜单顺序调整

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1625]
1. Dashboard 列表调整
   现状如下:

     <img width="1336" alt="image" src="https://github.com/actiontech/sqle/assets/42765421/69f539de-be7f-40c1-9c01-68401d73209c">

   建议取消工单描述列的固定宽度. 现状导致表格信息展示不完全

2. Header 的菜单顺序调整
    现状如下:

     <img width="644" alt="image" src="https://github.com/actiontech/sqle/assets/42765421/61a4f663-58f6-46f1-a5ee-ad6bf1af078c">
  
   建议调整 “项目” 与 “规则” 的顺序

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d8eab78
Server Version: main-ee 9702d3761f

当前Dashboard的近 24h 这个, 当描述为空的状态下可以看到表格最后一列，不需要滚动条
![image](https://github.com/actiontech/sqle/assets/54339501/b9f4a132-40cf-44ce-8ea4-af89e2361a50)
当前已经调整 “项目” 与 “规则” 的顺序
![image](https://github.com/actiontech/sqle/assets/54339501/29eeede6-1818-4372-b4a9-e81796ae7ca1)
