### ISSUE TITLE
慢日志表扫描任务中解析的show create table语句，点击sql分析报错

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1626]
**SQLe Version**
UI Version: main 7c2f8c4
Server Version: main-ee 35e1c6cd86

复现步骤：
1.添加一个慢日志表扫描任务
2.设置慢日志阈值为0
3.执行show create table 语句 
4.等待采集sql，点击sql分析报错
![cbQlKssDyV](https://github.com/actiontech/sqle/assets/54339501/8d8b9c5a-5cef-4baf-8293-134c5273e284)

**Comment by hasa1K** [comment]
问题原因：
后端使用MySQL中的EXPLAIN进行分析sql，但是`show create`语句不支持EXPLAIN进行分析
