### ISSUE TITLE
慢日志表类型扫描任务等待一会之后，点击进去查看详情报错

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1627]
**SQLe Version**
Server Version: main-ee 35e1c6cd86

1.添加一个慢日志表类型的扫描任务
2.等待几分钟进去查看sql信息正常
3.过了十分钟进去查看提示报错
![img_v2_08156105-314f-4f04-b982-f35fa3d2922g](https://github.com/actiontech/sqle/assets/54339501/d5c0672c-9650-4de6-b2e3-500043bfcd46)

**Comment by ColdWaterLW** [comment]
复现方式：
1. 创建慢日志表扫描任务
2. 制造一条慢sql，确保没有和这条慢sql指纹相同的其他慢sql，此时显示正常
3. 再执行一遍上一条慢sql，此时报页面错 

从sqle.audit_plan_sqls_v2表里可以看到info.average_query_time这个字段会出现字符类型和数值类型的值
![image](https://github.com/actiontech/sqle/assets/36940986/a0f6fcfc-b12a-40da-b23a-56ea2518deae)

**Comment by ColdWaterLW** [comment]
## 升级方案
需要把sqle库中已有的average_query_time字段统一为数值类型

**Comment by ColdWaterLW** [comment]
在企业版修复

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee ac054975fa

验证步骤：

1.创建慢日志表扫描任务
2.制造一条慢sql，确保没有和这条慢sql指纹相同的其他慢sql，此时显示正常
3.多次执行一遍上一条慢sql，查看扫描任务界面sql池，没有报错
4.然后查看sqle.audit_plan_sqls_v2表里可以看到info.average_query_time这个字段可以看到当前为数值类型的值
![image](https://github.com/actiontech/sqle/assets/54339501/bb3f8b16-7cb8-46e4-94c8-603a96b99e50)
![image](https://github.com/actiontech/sqle/assets/54339501/d2eaa087-821b-4c7b-a9fa-e1da4ec5a6ca)
