### ISSUE TITLE
jetbrains插件审核增加SQL分析结果展示【企业版】

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1628]
## 现状
展示的审核结果信息太少，不便于分析优化
![image](https://github.com/actiontech/sqle/assets/36940986/9468c975-77ba-4d96-a487-457de61d2237)

## 期望
- [x] 支持在线审核SQL
- [x] 展示更详细的信息，增加SQL分析结果

**Comment by taolx0** [comment]
### 查看日志文档
![3550b844-08ea-4ab3-92d7-6de992b68044](https://github.com/actiontech/sqle/assets/63177450/9324db0f-4e04-401d-878f-95bea9d5a74d)
