### ISSUE TITLE
在线获取的建表语句中存在geometry类字段时，解析失败，阻塞流程

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1630]
### 复现：
1. 使用SQLE平台之外的方式（因为SQLE平台现在对于geometry不能解析）创建一个表tb1，包含geometry类型的字段
```
CREATE TABLE `tb1` (
  `a` geometry DEFAULT NULL,
  `b` int(11) DEFAULT NULL
)
```
2. 审核SQL
```
ALTER TABLE tb1 ADD c int
```
报错如下，审核流程终止
![image](https://github.com/actiontech/sqle/assets/36940986/2c5f30da-ce67-487e-93aa-65b4e145b3a7)

### 原因：
**预检测**过程中会在线获取show create table，把建表ddl转成语法树,create table中有geometry类型的字段,现有的代码不支持 geometry 数据类型,导致了报错

### 预期
提示解析错误，但不中止审核流程

**Comment by taolx0** [comment]
### utf8mb3无法解析方案
1. 升级解析器,测试下来,最新的tidb解析器不存在这个问题.(sqle的解析器已经改写过,需要改写代码)

### 不支持 geometry 类型的方案 (tidb 不支持 geometry 数据类型)
1. 修改解析器,支持 geometry 数据类型

**Comment by ColdWaterLW** [comment]
# 实际采取的解决方案及影响面
## 预检查
即检查SQL上线是否存在失败的可能性

**现状**
解析建表语句失败，页面弹错，审核中止

**修改后**
解析建表语句失败，以审核结果的形式提示用户，继续其他规则的审核
![image](https://github.com/actiontech/sqle/assets/36940986/6268701f-86d0-4643-8b6d-40b74457f051)

**影响面**
* alter table
* create index
* delete 
* drop index
* insert
* update

## 规则
**现状**
解析建表语句失败，页面弹错，审核中止

**修改后**
解析建表语句失败，不影响其他规则的审核，继续其他规则的审核

**影响面**
⚠️ 建表语句解析失败时，部分规则不考虑数据源的表的实际状态，但SQL上下文审核仍然有效
* 检查DDL创建的新索引对应字段是否已存在过多索引 / 检查DDL是否创建冗余的索引 / 索引个数建议不超过阈值
    * 建表语句解析失败，认为表上没有已经存在的索引
* 复合索引的列数量不建议超过阈值
    * 建表语句解析失败，正常触发
* 建议创建约束前,先行创建索引 / 禁止对长字段排序
    * 建表语句解析失败，跳过规则
* 禁止将blob类型的列加入索引
    * 建表语句解析失败，跳过规则。相关语法： alter table add constraint；create index 
* 索引字段需要有非空约束 / 为至少一个索引添加非空约束
    * 建表语句解析失败，认为表上没有已经存在的列，相关语法如下：
       * alter table add column；alter table add constraint; alter table modify column
       * create index

**Comment by Marcus9530** [comment]
复现版本：Server Version: main-ee 94a205c3d9
复现步骤；
1.登陆mysql直接建表
`CREATE TABLE `tb1` (
  `a` geometry DEFAULT NULL,
  `b` int(11) DEFAULT NULL
)`
2.然后在sqle上对该mysql创建工单进行审核
`ALTER TABLE tb1 ADD c int
`
3.点击审核报错，提示以下错误
![image](https://github.com/actiontech/sqle/assets/54339501/d69ae587-8ef7-45c4-8318-1d75c6a074c5)

**Comment by Marcus9530** [comment]
```
#创建表
CREATE TABLE mytable (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    location GEOMETRY
);
#创建存储过程
DELIMITER //
CREATE PROCEDURE insert_data()
BEGIN
    DECLARE i INT DEFAULT 1;
    WHILE i <= 100000 DO
        SET @name = CONCAT('name', i);
        SET @x = RAND() * 10;
        SET @y = RAND() * 10;
        SET @point = CONCAT('POINT(', @x, ' ', @y, ')');
        INSERT INTO mytable (name, location) VALUES (@name, ST_GeomFromText(@point));
        SET i = i + 1;
    END WHILE;
END //
DELIMITER ;
#开始插入数据
CALL insert_data();
```

**Comment by Marcus9530** [comment]
验证版本：sqle-f5dc735c3edd0ccb88185216754b
Server Version: release-2.2305.x-ee f5dc735c3e
验证步骤：
### 创建工单进行审核
![image](https://github.com/actiontech/sqle/assets/54339501/21d64e6d-26be-477f-a657-ccc01864409b)
![image](https://github.com/actiontech/sqle/assets/54339501/cd9e925f-7903-4660-b3e8-ad43720a4f54)
![image](https://github.com/actiontech/sqle/assets/54339501/1d5300c3-4617-423c-936b-156f762a85b3)
![image](https://github.com/actiontech/sqle/assets/54339501/964a4668-c22e-4920-b6fc-1c1055d70cb8)
![image](https://github.com/actiontech/sqle/assets/54339501/8dc7dd2c-7ff1-4f7b-b653-0addd05de102)
![image](https://github.com/actiontech/sqle/assets/54339501/d6c94879-b6d6-4988-92d7-0964c6870ac5)

**Comment by Marcus9530** [comment]
main版本验证：
Server Version: main-ee aee242bad3

**创建工单进行审核**
![image](https://github.com/actiontech/sqle/assets/54339501/56967d4d-ba30-4ad6-b316-a1818825db7a)
![image](https://github.com/actiontech/sqle/assets/54339501/4bfffe50-6e83-4c6e-9434-c14edf8a60cd)
![image](https://github.com/actiontech/sqle/assets/54339501/5c5625a2-0047-4403-a1d6-74a1a6b47f74)
![image](https://github.com/actiontech/sqle/assets/54339501/5ce5257e-49a0-40f3-ae16-675b9331ae91)
![image](https://github.com/actiontech/sqle/assets/54339501/11c9e8fa-bc5d-4f5e-a8d5-b69f27503d56)
![image](https://github.com/actiontech/sqle/assets/54339501/6af93f26-bfc0-479d-81cb-3cad542c0320)
**审核规则**
当前带有geometry类型的字段建表语句跟之前一样不支持解析，所以无法触发相关审核提示【检查DDL创建的新索引对应字段是否已存在过多索引】、【检查DDL是否创建冗余的索引】、【索引个数建议不超过阈值】
当不带有geometry类型的字段建表语句进行审核时，可以正常触发这三个审核规则

![image](https://github.com/actiontech/sqle/assets/54339501/e86f82d2-2eda-4754-8354-b4e79d86e5b9)
![image](https://github.com/actiontech/sqle/assets/54339501/f8c66b7d-176f-4299-9cc3-680812867f72)
![image](https://github.com/actiontech/sqle/assets/54339501/c1177b8c-36dc-47ac-addb-41ffe41cfa49)
【复合索引的列数量不建议超过阈值】已在日志中跳过，可继续进行后续审核
![image](https://github.com/actiontech/sqle/assets/54339501/9a799b4b-cd10-4dff-be26-08c114b10930)
![image](https://github.com/actiontech/sqle/assets/54339501/dd669e94-dfb6-4503-b4dc-2a02f047e1f9)
【建议创建约束前,先行创建索引 / 禁止对长字段排序】
![image](https://github.com/actiontech/sqle/assets/54339501/41b1a811-3b08-4065-ac52-b4b90def2eb0)
![image](https://github.com/actiontech/sqle/assets/54339501/810772e3-e081-4059-aa0e-1d498e01993e)
![image](https://github.com/actiontech/sqle/assets/54339501/f5566f92-2666-4b9a-8d16-850cdf0b03ab)
![image](https://github.com/actiontech/sqle/assets/54339501/dd70e509-8318-42ab-8096-fbb5f7555814)
【禁止将blob类型的列加入索引】
![image](https://github.com/actiontech/sqle/assets/54339501/b5674264-9aa8-4bb1-a13e-5bf4bfd6efe4)
![image](https://github.com/actiontech/sqle/assets/54339501/3fee1d53-540d-437d-80d0-0e510a621416)

![image](https://github.com/actiontech/sqle/assets/54339501/0b0d3ebc-3c54-4241-a8c7-58bb7727c2af)
![image](https://github.com/actiontech/sqle/assets/54339501/6197d811-1be5-40ee-b2f4-e8e2219c2d6c)
【索引字段需要有非空约束 / 为至少一个索引添加非空约束】

![image](https://github.com/actiontech/sqle/assets/54339501/af87b6f7-b1ad-4eed-9911-0c087b16abc9)
![image](https://github.com/actiontech/sqle/assets/54339501/2792b94c-139d-4c77-8c28-f99aa6f80aa9)
![image](https://github.com/actiontech/sqle/assets/54339501/61d2f4a7-df4b-453b-bc69-ca5f82a233bd)

![image](https://github.com/actiontech/sqle/assets/54339501/348f49a0-fefe-4dc0-9ee0-af76b08b5085)
**回滚语句**
![image](https://github.com/actiontech/sqle/assets/54339501/06277bfd-40ef-4090-b2a6-19a141539a37)
![image](https://github.com/actiontech/sqle/assets/54339501/9e61fd12-2f8e-47fc-b2ba-6377ead5a132)
![image](https://github.com/actiontech/sqle/assets/54339501/00b6f651-b113-468d-bb27-8da9cf7af605)
![image](https://github.com/actiontech/sqle/assets/54339501/68707602-0913-46f4-80da-56910eb45820)
![image](https://github.com/actiontech/sqle/assets/54339501/a6a46b18-3484-4cf1-85b5-f1a6d6d350b8)
![image](https://github.com/actiontech/sqle/assets/54339501/04b58470-5337-419b-8659-9626a78d86d9)
![image](https://github.com/actiontech/sqle/assets/54339501/d19dde78-b23d-4c63-b2f1-07eea8e54e87)
![image](https://github.com/actiontech/sqle/assets/54339501/a6d1527c-c851-4cb9-9132-1608d7631efb)
![image](https://github.com/actiontech/sqle/assets/54339501/49376d3d-9fd0-4795-85a8-6768b2c90213)
![image](https://github.com/actiontech/sqle/assets/54339501/6086b8bc-adec-4e4a-a95a-0bb36ddffd04)
![image](https://github.com/actiontech/sqle/assets/54339501/759baf16-3559-44f3-92a9-4d3d5899b92f)

**osc建议**
![image](https://github.com/actiontech/sqle/assets/54339501/aaa5dcde-43bc-4ce6-90fb-e25f152bf1f2)
![image](https://github.com/actiontech/sqle/assets/54339501/888b1c5d-256c-4300-8441-84eb4e02ec8b)
