### ISSUE TITLE
sql去重只有第一个语句才有回滚语句，另外去重之后保留了两个sql语句不太合理

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1633]
**SQLe Version**
Server Version: main-ee 35e1c6cd86

复现步骤：
1.使用一条sql在创建工单的时候，多次重复输入，然后点击审核
2.只有第一个出现回滚语句，后面的重复sql没有出现回滚语句
3.点击去重之后，只保留有回滚语句的跟没有回滚语句的两个sql，个人理解应该只保留一个sql展示
![f2b2cd65-1a90-4c55-97cd-7b5371f70aac](https://github.com/actiontech/sqle/assets/54339501/5b113c06-77f5-4014-adc4-4c10a2eb7aaf)
![5edd826a-53a8-4c7a-bf8a-3d3284877672](https://github.com/actiontech/sqle/assets/54339501/12f3eedc-34eb-4d0b-ac90-ab8351f3fe0d)
期望：
1.所有sql都有回滚语句
2.只保留一个sql

**Comment by ColdWaterLW** [comment]
判断重复的依据是sql指纹和审核结果一致
审核结果不一样，所以不算重复
