### ISSUE TITLE
操作记录界面进行多重筛选，发现筛选结果不符合预期

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1636]
Server Version: main-ee 35e1c6cd86
复现步骤：
在操作记录界面进行多重筛选，主要是选择操作时间，可以看到结果不符合预期
![371b919a-99b1-46ee-9dbf-b805ebbb5d1b](https://github.com/actiontech/sqle/assets/54339501/4b89340f-093e-4322-9491-2d5d459e3b26)
![39da9c2f-8bf3-4f59-b447-1a4b3a4fcae2](https://github.com/actiontech/sqle/assets/54339501/39728a7a-6703-4e54-b7a0-94adff03e2a2)

**Comment by ColdWaterLW** [comment]
没有复现
