### ISSUE TITLE
修复当task处于正在上线中时,工单概览待操作人为当前登陆用户的问题

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1640]
**SQLe Version**
main

**Describe the bug**
当task处于正在上线中时,工单概览带操作人总是为当前登陆用户

**To Reproduce**
1. 创建工单
2. 添加用户t2和t3
![image](https://github.com/actiontech/sqle/assets/63177450/a25f6711-6370-4306-99c6-617d546f1842)
3. 确认流程模版
![image](https://github.com/actiontech/sqle/assets/63177450/11726378-fd65-4a81-a317-2c7801c6f0e9)
4. 点击立即上线(上线sql为select sleep(60)),分别用t2,t3登陆sqle
5. 工单待操作人为sqle的当前登陆用户,而不是实际的流程模版分配用户

**Expected behavior**
待操作人是 t2.t3,而不是当前登录用户
![image](https://github.com/actiontech/sqle/assets/63177450/5c6b7f7b-b110-4d79-8498-edfbd76c6957)

**Comment by Marcus9530** [comment]
复现版本：
Server Version: main-ee 35e1c6cd86
复现步骤：
1.添加3个用户，t1、t2、t3
2.给默认的dba角色增加一个上线权限
3.给t1、t2在项目内设置dba权限
4.给t3设置dev权限
5.然后登陆t3用户创建工单，select sleep（160）
6.然后切换到t1用户进行审批通过，在上线
7.切换到t2用户，可以看到带操作用户为当前t2用户

![image](https://github.com/actiontech/sqle/assets/54339501/21643693-e3d6-4b47-b89d-944b503ac760)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee ac054975fa

验证步骤：
1.添加3个用户，t1、t2、t3
2.给默认的dba角色增加一个上线权限
3.给t1、t2在项目内设置dba权限
4.给t3设置dev权限
5.然后登陆t3用户创建工单，select sleep（160）
6.然后切换到t1用户进行审批通过，在上线
7.分别切换到t1、t2用户，可以看到带操作用户为t1、t2
![image](https://github.com/actiontech/sqle/assets/54339501/c40b6d52-2891-44a4-b4b7-6487b11399db)
![image](https://github.com/actiontech/sqle/assets/54339501/ee46d4cc-d910-46a1-8292-2d899f2b8e38)
