### ISSUE TITLE
系统设置中 Webhook 配置文案错误 以及 测试微信推送永远显示成功

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1642]
1. 系统设置中 Webhook 配置文案错误

![img_v2_810ff5c1-fbc9-437f-8aac-6aeff833348g](https://github.com/actiontech/sqle/assets/42765421/d54023f6-0376-42ce-a3d4-275645e28c7a)

2. 测试微信推送永远显示成功
![img_v2_8824c454-098a-4f2e-90e8-d9cc318dde3g](https://github.com/actiontech/sqle/assets/42765421/f20af065-ceba-4423-963d-eb03ce48fc01)

3. 创建工单时选择数据源, 此时会展示该数据源对应的规则模板, 但是当点击重置所有内容后, 规则模板仍然在界面上
![image](https://github.com/actiontech/sqle/assets/42765421/7a0ad4fa-5c27-4ddc-be39-fd12a4ba4612)

预期:
1.  Webhook 配置文案调整为: 是否开启Webhook通知
2. 当测试微信推送 的 is_wechat_send_normal 返回为 false 时, 希望能展示返回的错误信息, 而不是 测试成功.
3. 当点击重置所有内容后, 界面上全部恢复为初始状态

**Comment by Marcus9530** [comment]
场景一：
Webhook 配置文案已经调整为: 是否开启Webhook通知
![image](https://github.com/actiontech/sqle/assets/54339501/2e2745e1-f457-44dc-9539-2510d383672d)
![image](https://github.com/actiontech/sqle/assets/54339501/bc6af4e1-2ebe-48f8-ae37-6bdb7ce325e3)
场景二：
微信测试推送当填写参数有错误的时候，返回报错信息
![image](https://github.com/actiontech/sqle/assets/54339501/86af810d-d0ef-4f7f-b41c-6d73155b36be)
![image](https://github.com/actiontech/sqle/assets/54339501/34b77f43-458f-44fd-9e56-48227d2a395d)
当所有的参数都正确时，测试推送成功
![image](https://github.com/actiontech/sqle/assets/54339501/3539def9-0f87-400d-b4ca-dd1e0f276f43)
场景三：
当前点击重置所有内容之后，审核规则模版也一起被重置为默认
![image](https://github.com/actiontech/sqle/assets/54339501/5430c3a1-feb2-48d9-a9c0-5d03da2844df)
![image](https://github.com/actiontech/sqle/assets/54339501/0cd1c572-e906-4ca8-a90b-c1189b53a620)
