### ISSUE TITLE
智能扫描支持扫描SQL文件

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1690]
- [x] scannerd支持扫描SQL文件
- [x] SQLE页面支持添加SQL文件扫描任务（所有数据源类型）

**Comment by hasa1K** [comment]
sql文件扫描任务添加在所有数据库类型的扫描任务中
![image](https://github.com/actiontech/sqle/assets/53266479/bc5fff8d-d528-4c9c-9ad9-df071d9c5de7)

**Comment by hasa1K** [comment]
执行scanner
命令如下：
./scannerd sqlfile -H127.0.0.1 -N"test0724" -P"10001" -J"default" -D/root/sqle/sqle/cmd/scannerd/scanners/mybatis/testdata/ -A"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcG4iOiJ0ZXN0MDcyNCIsImV4cCI6MTcyMTcyODU0NywibmFtZSI6ImFkbWluIn0.CojdTvBkr-iN_26tWI-Kr6mMnJt1NIDr-Y3v7m9ySuM"


-J, --project：说明扫描任务所在项目，例如“default”；
-H, --host string：指定SQLE主机所在地址；
-P, --port string：指定SQLE所在端口；
-N, --name string：指定扫描任务名称，scannerd会将获得的SQL传至指定的任务池中审核；
-D, --dir string：指定要扫描的XML文件路径
-A, --token string：输入扫描任务凭证token；

**Comment by Marcus9530** [comment]
测试点：
1.scanner正常启动sqlFile类型可以推送到扫描任务中
2.scanner正常启动sqlFile类型但是指定文件不是sql类型文件，无法采集sql语句
3.sqlFile类型文件持续新增sql语句，启动的scanner会一直采集sql语句推到sqle上
4.正常添加一个SQL文件扫描任务
5.修改一个SQL文件扫描任务
6.删除一个SQL文件扫描任务
