### ISSUE TITLE
规则列表分类进行排序, 优化编辑规则模板时的规则列表样式

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1701]
1.  优化编辑规则模板时的规则列表样式
  现状:
  ![img_v2_d9443671-2f81-4c11-bc43-5b01695094cg](https://github.com/actiontech/sqle/assets/42765421/a03d307d-2ae9-4123-99c8-e5796ba9a738)

  希望当规则分类过多时, 能隐藏部分规则分类, 类似

  ![img_v2_423e2647-7598-43a4-b27b-a28946e6550g](https://github.com/actiontech/sqle/assets/42765421/833c1453-8493-4bce-b62e-01c1a1e72f96)

   影响范围: 
      - 编辑全局规则模板
      - 编辑项目内规则模板

2. 规则列表分类进行排序
  现状
  ![img_v2_423e2647-7598-43a4-b27b-a28946e6550g](https://github.com/actiontech/sqle/assets/42765421/c13823e8-05f7-4b3b-a7e5-c85ddf7aeb4b)

  希望能够将 sqle 提供的规则分类排在前面

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 2191921
Server Version: main-ee a8cc6af2e0
验证步骤：
1.添加很多个不同规则分类名
2.添加/编辑审核规则模版的时候查看规则分类，目前多余的分类已经隐藏

![image](https://github.com/actiontech/sqle/assets/54339501/2aecb4c3-c252-49b8-9dbe-037180cc2aa7)
![image](https://github.com/actiontech/sqle/assets/54339501/062ca731-d480-4a9e-96da-58c41694e2a3)
![image](https://github.com/actiontech/sqle/assets/54339501/ce410a00-aa48-4fb2-a68d-c520aa233bb6)
![image](https://github.com/actiontech/sqle/assets/54339501/30137bf6-3fe8-4f7e-9d5a-0f263dacf13b)
