### ISSUE TITLE
项目概览的工单状态报表添加 正在上线 状态

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1712]
现状
![image](https://github.com/actiontech/sqle/assets/42765421/94c63666-fbd3-4d71-90b4-9a1f7e918b8b)
目前该饼图展示了工单的 6 个状态, 但是并没有展示正在上线的工单, 希望能够加上

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 39bbc2a
Server Version: main-ee d6ade44ccf
验证步骤：
1.创建不同状态的工单，包括正在上线的工单
2.查看项目统计
3.出现正在上线工单的状态


![image](https://github.com/actiontech/sqle/assets/54339501/54de3947-200e-41ac-ae4c-f8634d99eceb)
![image](https://github.com/actiontech/sqle/assets/54339501/9be0aac2-bf29-4dfb-a527-fdab6392b671)
