### ISSUE TITLE
插件中止上线功能

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1718]
## pre1
- [x] ob for mysql
- [x] tdsql

## pre2
- [x] tidb

## pre3
- [ ] mycat （不支持）
- [x] oracle
- [ ] db2（延期）
- [ ] sql server（延期）

## 验证关注点
dml是按事务执行的，需要验证kill掉之后事务是否正常回滚了

**Comment by hasa1K** [comment]
tidb插件使用中止上线功能需要开启enable-global-kill配置

**Comment by Marcus9530** [comment]
### tidb

**Comment by Marcus9530** [comment]
### tdsql

准备tdsql数据库
![image](https://github.com/actiontech/sqle/assets/54339501/49b503ab-ee72-4d88-a6a0-943b49f5a0fa)
![image](https://github.com/actiontech/sqle/assets/54339501/f311337d-b1eb-4bf2-b187-3e84550b1c16)
sqle添加tdsql数据源
![image](https://github.com/actiontech/sqle/assets/54339501/ab696874-1a7f-471f-a3f8-ab25e70d87b9)

事务1:
![image](https://github.com/actiontech/sqle/assets/54339501/ea1ddbbc-94ec-4427-b770-bc3dc079211c)
![image](https://github.com/actiontech/sqle/assets/54339501/7a84a617-c9d0-43b4-9ee8-593bd5ebbfdf)
![image](https://github.com/actiontech/sqle/assets/54339501/fa692d70-f10b-4375-b359-f5ead2debed4)
![image](https://github.com/actiontech/sqle/assets/54339501/6de7ba32-cf93-4a45-9473-dc472dd76e71)
表中数据还在，说明事务回滚
![image](https://github.com/actiontech/sqle/assets/54339501/8193e680-3e8c-4981-9bf5-4b187e5af8ec)

事务2:
![image](https://github.com/actiontech/sqle/assets/54339501/ed4c3c05-522c-48c4-b45f-c747db19490f)
![image](https://github.com/actiontech/sqle/assets/54339501/4ca6d9d2-5d5d-4972-8fb8-3a36fce81c77)
![image](https://github.com/actiontech/sqle/assets/54339501/650e792c-5d8f-4e34-9c2e-54e84acfa8cf)
![image](https://github.com/actiontech/sqle/assets/54339501/1f41c962-ebad-45ca-8cef-8c24bbf787d1)
表中数据还在，说明事务回滚

![image](https://github.com/actiontech/sqle/assets/54339501/988d788a-2dd1-414c-8a30-ab0abbe69b54)

事务3:
![image](https://github.com/actiontech/sqle/assets/54339501/86f47e83-a18f-4871-aee6-8014004f16b8)
![image](https://github.com/actiontech/sqle/assets/54339501/bc1a7dd8-4fc7-413a-bea3-dc321b4edc24)
![image](https://github.com/actiontech/sqle/assets/54339501/62ef5fc7-0c3b-4486-8d7c-9b3f5a462010)
![image](https://github.com/actiontech/sqle/assets/54339501/18d776d9-e071-49e7-aed6-f876a38ad6b6)
![image](https://github.com/actiontech/sqle/assets/54339501/8905604d-5a75-4d88-b242-05f86a7f6b19)
![image](https://github.com/actiontech/sqle/assets/54339501/69ece993-0489-4c2b-b0cb-da7e4903f3a4)

**Comment by Marcus9530** [comment]
### ob for mysql
添加数据源
![image](https://github.com/actiontech/sqle/assets/54339501/f8a3cd26-c489-4b10-8eb8-a6b22f480a5e)
![image](https://github.com/actiontech/sqle/assets/54339501/82e5bf8f-fdf6-4860-8bf3-802af7f66c1d)

事务1:
![image](https://github.com/actiontech/sqle/assets/54339501/24ff3ad4-7210-4038-a30a-84c0af32038b)
![image](https://github.com/actiontech/sqle/assets/54339501/1c3fa785-1ce6-4c64-a3bc-0dc791f35263)
![image](https://github.com/actiontech/sqle/assets/54339501/c09fcf8f-a711-4c9d-92aa-392fca87d611)
表中数据还存在
![image](https://github.com/actiontech/sqle/assets/54339501/b846bd9f-5a53-4784-b604-69ccda5d28bc)

事务2:
![image](https://github.com/actiontech/sqle/assets/54339501/7a72a5fe-0f99-408e-9af1-98c4a7c8b943)
![image](https://github.com/actiontech/sqle/assets/54339501/e2bccb11-6fff-4252-a4fa-447770cd7180)
![image](https://github.com/actiontech/sqle/assets/54339501/7ab0acb0-c31d-4c75-bb52-ad6a1b9d7c2a)
![image](https://github.com/actiontech/sqle/assets/54339501/7641af89-aba2-4ca4-9958-435519dd14d5)
![image](https://github.com/actiontech/sqle/assets/54339501/34f169f0-d9f9-449d-928f-3425e71c50d5)

**Comment by Marcus9530** [comment]
### oracle
准备表
`-- 创建customers表
CREATE TABLE customers (
    customer_id NUMBER,
    customer_name VARCHAR2(100),
    email VARCHAR2(100),
    address VARCHAR2(100)
);

-- 创建products表
CREATE TABLE products (
    product_id NUMBER,
    product_name VARCHAR2(100),
    price NUMBER(10, 2),
    stock NUMBER
);

-- 创建orders表
CREATE TABLE orders (
    order_id NUMBER,
    customer_id NUMBER,
    order_date DATE,
    total_amount NUMBER(10, 2),
    status VARCHAR2(20)
);

-- 创建order_items表
CREATE TABLE order_items (
    order_item_id NUMBER,
    order_id NUMBER,
    product_id NUMBER,
    quantity NUMBER,
    unit_price NUMBER(10, 2)
);`
使用存储过程造数据
![image](https://github.com/actiontech/sqle/assets/54339501/54ef3897-1bc4-4c98-899f-98c11170d20e)
 事务1:
![image](https://github.com/actiontech/sqle/assets/54339501/dbba05f6-0eb7-41a4-a615-4f9115a256a3)
![image](https://github.com/actiontech/sqle/assets/54339501/61bb2da8-2599-4006-85cf-8cdbdc45af6d)
![image](https://github.com/actiontech/sqle/assets/54339501/2fb7f042-e64e-46b0-b17a-d11df9af0ab5)
![image](https://github.com/actiontech/sqle/assets/54339501/6069e5bb-1e85-4fb8-86ec-f1059a893aea)
