### ISSUE TITLE
如果删除工单内的数据源,点击导出工单,程序panic

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1725]
**SQLe Version**
main-ee

**To Reproduce**
1. 创建数据源 t1
2. 创建工单,选择数据源 t1 完成上线流程
3. 删除数据源 t1
4. 点击 导出工单按钮,程序panic

**Expected behavior**
数据源被删除的情况下,能正常导出工单

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-2.2307.x 39bbc2a
Server Version: release-2.2307.x-ee d6ade44ccf
复现步骤：

1. 创建数据源 t1
2. 创建工单,选择数据源 t1 完成上线流程
3. 删除数据源 t1
4. 点击 导出工单按钮,程序panic

![image](https://github.com/actiontech/sqle/assets/54339501/2ce4b7f3-33df-4bb1-a9d3-15d5c55beb66)
![image](https://github.com/actiontech/sqle/assets/54339501/65641bf0-6342-48e8-94b7-c98656bf9793)
![image](https://github.com/actiontech/sqle/assets/54339501/0fee86cf-b8da-4885-abd8-e88662134c6d)
![image](https://github.com/actiontech/sqle/assets/54339501/59d9e15b-436b-4c22-83df-1fbe370366dc)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 39bbc2a
Server Version: main-ee f28d346ae0
验证步骤：

1. 创建数据源 t1
2. 创建工单,选择数据源 t1 完成上线流程
3. 删除数据源 t1
4. 点击 导出工单按钮,可以正常到处工单，不会panic

![image](https://github.com/actiontech/sqle/assets/54339501/1f80d3cd-c2db-4a4f-b00a-af4d8334441f)
![image](https://github.com/actiontech/sqle/assets/54339501/979cea7b-a3ea-4791-8fa4-56b246e18ccc)
![image](https://github.com/actiontech/sqle/assets/54339501/7c3fd57e-4639-4e77-8e8f-9c373c9ec2ad)

**Comment by taolx0** [comment]
### why
实例被删除,导出工单接口的select查询无法根据外键查询到已经被删除的实例记录,对结构体内的实例字段的引用引发了空指针错误

### 修复
导出工单接口可以查询到已经被删除的记录
