### ISSUE TITLE
scannerd扫描mybatis、sql文件时，建议输出所有审核结果

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1729]
**现状**
scannerd扫描mybatis、sql文件，输出审核结果时，遇到error等级的审核结果就结束输出了，只能到sqle页面上才能看到所有sql的审核结果。这样不方便使用者直接通过命令行或者ci控制台观察审核结果

**预期**
输出全量的审核结果

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 39bbc2a
Server Version: main-ee f28d346ae0
验证步骤：
无论是mybatis还是sql文件，当scanner碰到error级别的审核提示之后还会继续往后审核，输出了所有sql的审核提示

### scannerd扫描mybatis
![image](https://github.com/actiontech/sqle/assets/54339501/567334ec-a3bc-449c-9865-f581d697798e)
### scannerd扫描sql文件
![image](https://github.com/actiontech/sqle/assets/54339501/5306a421-49d1-42b1-9cc9-a9b40e3f0d51)
