### ISSUE TITLE
统一UI的资源名称限制

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1733]
后端已对名称长度限制做了修改，ui也需要统一修改
#1731

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 948cc8d
Server Version: main-ee a492a485a9
验证步骤：
当前所支持的的创建任务类型前端最大支持119个字符，超过后给予提示无法创建，不超过可以正常创建

扫描任务
![image](https://github.com/actiontech/sqle/assets/54339501/3917f12e-db9f-4d7b-9b78-51ee41fb2208)
![image](https://github.com/actiontech/sqle/assets/54339501/8505acfa-820a-4993-96e5-c156cddb65dd)
![image](https://github.com/actiontech/sqle/assets/54339501/0c02b5e1-651f-4d46-a9b1-ec2f2eb59cde)
数据源
![image](https://github.com/actiontech/sqle/assets/54339501/16a2818f-9658-4a5e-9fef-e06c3dbfbab6)
![image](https://github.com/actiontech/sqle/assets/54339501/766755db-7c60-40d8-bc25-4901a1f76d58)
![image](https://github.com/actiontech/sqle/assets/54339501/78fab722-701e-4949-b4dc-38fb5a3d39dc)
用户角色
![image](https://github.com/actiontech/sqle/assets/54339501/1714ee91-c6f7-4ac5-ac8c-ff1c2c0226b5)
![image](https://github.com/actiontech/sqle/assets/54339501/9dc5286f-8cf9-4610-92a9-736eeb606b57)
![image](https://github.com/actiontech/sqle/assets/54339501/a205c7e0-84f2-4e6f-ab59-cc52cbe21a48)
用户名
![image](https://github.com/actiontech/sqle/assets/54339501/f72a1882-eea2-4168-8b66-9dca42f937e1)
![image](https://github.com/actiontech/sqle/assets/54339501/7ebc51f4-ab25-4d54-bf6e-2da8cc806915)
![image](https://github.com/actiontech/sqle/assets/54339501/7120263a-8aef-4519-8a3e-35796130f520)
用户组
![image](https://github.com/actiontech/sqle/assets/54339501/037100e1-efb0-4b2d-93bb-d80ef1e73d87)
![image](https://github.com/actiontech/sqle/assets/54339501/1f274f85-d411-4df8-882b-e0fb4337a4a4)
![image](https://github.com/actiontech/sqle/assets/54339501/178610d1-21dc-4538-913d-0fbfae4e4f72)
规则模版
![image](https://github.com/actiontech/sqle/assets/54339501/e2b0786a-f720-4eb9-8878-26757c1c8501)
![image](https://github.com/actiontech/sqle/assets/54339501/4cc57858-8e14-46e0-8d9d-adb2e38943a1)
![image](https://github.com/actiontech/sqle/assets/54339501/cee07d8e-82f8-43d8-8770-3cb2bf081e55)
