### ISSUE TITLE
IntelliJ IDEA插件支持含有跨文件定义的MyBatis文件扫描

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1746]
## 场景
当MyBatis跨namespace引用的SQL时，对引用的xml文件进行审核，会报id不存在的错误：如下
要审核的xml文件中引用了namespace为“com.ctg.hro.dao.common.CommonDao”的prefix变量，这个prefix是在namespace为“com.ctg.hro.dao.common.CommonDao”的另一个文件中定义的
![image](https://github.com/actiontech/sqle/assets/36940986/680a24a7-e0f0-43df-8066-daf8f78c2722)

审核报错
![image](https://github.com/actiontech/sqle/assets/36940986/b184d88c-712a-47c2-9187-05df5fa6426d)

## 期望
可以审核跨namespace引用的mybatis文件

## 修复方案
1. 优化MyBatis解析库，支持跨namespace的变量解析
2. IntelliJ IDEA插件支持一次性审核文件夹下的所有xml文件，只要变量的定义和引用都在文件夹下，就能解析成功

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 39bbc2a
Server Version: main-ee f28d346ae0
验证步骤：
1.在一个文件夹下创建多个xml文件
2.其中有2个跨namespace引用的mybatis文件
3.对文件夹进行sqle审核
4.可以看到idea下出现审核提示，并且把文件夹下所有xml文件中的sql给进行了审核
![image](https://github.com/actiontech/sqle/assets/54339501/8c9e38ab-5756-46d3-84fc-4e1cbfaf5acf)
![image](https://github.com/actiontech/sqle/assets/54339501/472271b3-6c11-4c11-8618-6fb51d13ce5b)
![image](https://github.com/actiontech/sqle/assets/54339501/68f815ff-4878-4cc6-ac50-0660af30b7db)
