### ISSUE TITLE
配置钉钉之后，关闭工单会导致钉钉轮询发送panic

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1756]
# 问题描述
流程对接中配置钉钉并开启
![image](https://github.com/actiontech/sqle/assets/53266479/74bb9733-be35-42c0-9c04-d3b8a54f52d0)

然后创建工单，并将工单关闭
![image](https://github.com/actiontech/sqle/assets/53266479/c0036c75-7af9-4100-80b1-8ad39d23a7ef)

在等待一段时间后，后端会发生panic
![image](https://github.com/actiontech/sqle/assets/53266479/712aa94d-3de9-48ae-8717-11405efe19a8)

**Comment by hasa1K** [comment]
问题原因：
在钉钉轮询功能中，需要获取当前工单步骤下的用户信息。
但是当工单关闭后，工单当前步骤id被设为0，导致从数据库中查出的workflow.Record.CurrentStep为nil，引发了panic

**Comment by winfredLIN** [comment]
问题的根源是：
在关闭工单的接口中，只修改了工单的状态，没有修改钉钉工单（dingtalk_instance）的状态（status）。
这导致钉钉工单的状态仍为initialized，进而导致如果一个工单关闭，但在钉钉上被同意/拒绝，则在钉钉轮询功能中，程序会获取到已关闭的工单并试图访问其中nil的变量，最终导致panic。（不应修改已关闭的工单）

钉钉轮询的功能的目的是：
轮询钉钉工单的审批状态，如果状态为同意/拒绝，再去获取与更新工单的状态。

解决的方案是：
在关闭工单和批量关闭工单的接口中增加修改钉钉工单状态为canceled的逻辑

**Comment by Marcus9530** [comment]
sqle-4876ec13454a18ae37f6e396511

复现步骤：
1.配置钉钉
2.创建工单
3.在钉钉上进行审核
4.然后在sqle上关闭工单
5.查看std日志可以看到panic信息
![image](https://github.com/actiontech/sqle/assets/54339501/80b6a5d4-c875-4cae-a304-5f5412a483e5)

**Comment by Marcus9530** [comment]
验证版本：UI Version: main 948cc8d
Server Version: main-ee a492a485a9

验证步骤：
1.配置钉钉
2.创建工单
3.在钉钉上进行审核
4.然后在sqle上关闭工单
5.查看std日志发现没panic信息


![image](https://github.com/actiontech/sqle/assets/54339501/3f9940ae-5cba-4e29-a7c4-709fd13d1b41)

![image](https://github.com/actiontech/sqle/assets/54339501/aaf185a1-6516-4e56-9a1d-cac123b5cfa2)

![image](https://github.com/actiontech/sqle/assets/54339501/bbee33e0-76d0-4be0-afba-6c5221e9874e)
