### ISSUE TITLE
创建扫描任务的时候调用接口名字过长导致创建失败

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1758]
原始需求：
https://github.com/actiontech/sqle/issues/1731

复现步骤：
1.打开swagger页面
2.找到创建扫描任务的接口
3.请求参数中设置名字过长
4.查看请求结果
![image](https://github.com/actiontech/sqle/assets/54339501/de57f1c2-67e4-4c54-8e6f-4f9f88a1a945)

**Comment by ColdWaterLW** [comment]
**原因**
扫描任务名称长度限制开放到120个字符后，导致生成的token内容过程
相关issue #1731

**Comment by winfredLIN** [comment]
您好，关于《Issue1758：创建扫描任务的时候调用接口名字过长导致创建失败》

该问题的原因是：
由于扫描任务的名称过长，导致基于该名称生成的Token过长，长度超过了数据表中定义的长度上限，进而导致INSERT失败

当前解决方案：
当前版本，为了能够正常创建扫描任务，请不要设置过长的扫描任务名称

我们也会尽快修复该bug~谢谢

**Comment by winfredLIN** [comment]
关于《Issue1758：创建扫描任务的时候调用接口名字过长导致创建失败》
上一次修改的解决方案是：对创建扫描任务创建JWT Token传入的用户名称（currentUserName）和扫描任务名称（req.Name）使用MD5转换到固定长度的字符串，并且在检查扫描任务的JWT Token的sqleMiddleware.ScannerVerifier()中，使用apnInToken != utils.Md5(apnInParam)判断检查新的JWT Token 并且保留对老的JWT Token的判断检查

但上一次的修改存在的问题是，没有考虑到JWT Token中的用户名称在全局中间件中会校验用户的合法性，通过JWT Token解析出用户名称，从而验证用户的合法性，这里如果使用MD5会导致无法获取到真是的用户名。

因此在这一次的修改中，取消了使用MD5对用户名转换长度
