### ISSUE TITLE
当一个上线失败的工单，点击关闭工单失败

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#176]
**SQLe Version**
SQLe Version:
 "release-1.2112.x-ee ec268e80e8ac897c20551f487b59b19200ff0011"

**To Reproduce**
1.创建一个工单，审核语句为select * from mysql.test
2.点击审核，然后执行立即上线
3.查看工单状态，显示上线失败，然后进入到该工单内，点击关闭工单，无法关闭
![image](https://user-images.githubusercontent.com/54339501/147633111-3177e10a-1dc9-4148-a6b7-46d63140f157.png)

**Expected behavior**
是否考虑对于上线失败的工单可以不提供关闭工单的按钮展示，或者对于上线失败的工单可以使用关闭工单功能是其强制关闭

**Comment by sjjian** [comment]
工单详情页面上线失败的工单需要隐藏关闭工单按钮

**Comment by Marcus9530** [comment]
Version:
  "release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
验证通过
验证步骤：
1.创建一个上线失败的工单
2.进入到该工单内，已经去除了关闭工单功能按钮

![image](https://user-images.githubusercontent.com/54339501/147809101-c69b2776-040e-4c68-bb68-1b42af5ef29d.png)
