### ISSUE TITLE
建议优化一下定时上线任务选择时间的交互方式

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#177]
**Describe**
Version:
  "release-1.2112.x-ee ec268e80e8ac897c20551f487b59b19200ff0011"
1.创建一个工单，然后选择定时上线任务，点击选择时间
![image](https://user-images.githubusercontent.com/54339501/147634036-b6b829d5-87ae-474c-9e1e-43382bcf0686.png)
2.然后点击此刻，直接回到了定时任务时间确认框
![image](https://user-images.githubusercontent.com/54339501/147634066-2fe85b00-fbaa-4e86-9079-c9bd9fefa09f.png)
3.如果此时点击定时上线，那么尤其选择时间是精确到秒，所以导致定时上线不成功
![image](https://user-images.githubusercontent.com/54339501/147634205-880ef7c8-1034-4d5e-b516-cdb170ff2696.png)

**Suggestion**
所以期望的是点击此刻之后，应该还在选择时间，此刻功能个人理解是快速帮你定位当前时间，所以点击此刻之后可以根据自己工作量安排来设置当前时间之后的几分钟或者几小时之类的，而不是点击此刻之后就立即退出选择时间框
![image](https://user-images.githubusercontent.com/54339501/147633972-15316ac1-0351-4577-b251-c123cd1f12de.png)

**Why**
容易误导用户点击此刻之后可以直接使用定时上线功能

**Comment by sjjian** [comment]
建议点击此刻后时间选择框不退出，仍能自由调整时间

**Comment by caichuanwang** [comment]
处理意见：取消此刻按钮

**Comment by Marcus9530** [comment]
Version:
  "release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
验证通过
验证步骤：
1.创建一个审核工单，然后设置定时上线
2.在选择定时上线时间点的时候已经去除了此刻功能，且选中时间之后不会立即退出


![image](https://user-images.githubusercontent.com/54339501/147808805-bbbac46f-190e-4ea0-98e2-effb5b7bc4d4.png)
