### ISSUE TITLE
创建工单成功后,数据源待操作人用户密码被更新

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1775]
**SQLe Version**
main-ee 2.2308.0

**Describe the bug**
创建工单成功后,工单内task的待上线人用户密码会被更新(仅当流程模版执行上线是根据权限匹配上线人时触发)

**To Reproduce**
1. 创建密码为1的用户t1,增加dba角色上线工单权限,赋予dba权限给用户t1
![te](https://github.com/actiontech/sqle/assets/63177450/c723c07e-3f2a-48de-991c-18e28ec0efce)

2. 选择数据源mysql,创建工单

3. 创建工单成功后,使用t1用户登录sqle,报密码错误提示
![image](https://github.com/actiontech/sqle/assets/63177450/edd7a898-3027-48c2-acef-d366ba95aa45)

**Expected behavior**

**Suggestion**

**Comment by taolx0** [comment]
#原因
gorm踩坑

**Comment by Marcus9530** [comment]
UI Version: main 39bbc2a2
Server Version: main-ee c00d528276
自动化环境对应的场景中，所用的用户密码已无法正常登陆
![image](https://github.com/actiontech/sqle/assets/54339501/b46afb6b-05cd-4824-89ac-38f47ade2bf7)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main da7bffd
Server Version: main-ee efeff4310f
验证步骤：

- 创建密码为1的用户t1,增加dba角色上线工单权限,赋予dba权限给用户t1
- 选择数据源mysql,创建工单审核工单
- 创建工单成功后,使用t1用户登录sqle,可以正常登陆

![image](https://github.com/actiontech/sqle/assets/54339501/d8a0271c-9b88-4d15-b20d-4810073de49d)
![image](https://github.com/actiontech/sqle/assets/54339501/bc5aaccf-5c68-458b-b0d6-fa71d8c90520)
![image](https://github.com/actiontech/sqle/assets/54339501/fa753c08-4e1c-4b30-9a78-7b6b9ed754eb)
