### ISSUE TITLE
MySQL审核规则新增和调整

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1783]
## 新增规则
|规则名|分类|风险等级|默认阈值|备注|进度|
|----|-----|---|------|-------|-------|
|使用TEXT 类型的字段建议和原表进行分拆，与原表主键单独组成另外一个表进行存放||notice|||:white_check_mark:|
|建议在组合索引中将区分度高的字段靠前放||notice|||:white_check_mark:|
|JOIN字段必须包含索引||error|||:white_check_mark:|
|扫描行数超过阈值，筛选条件必须带上主键或者索引||error|10万||:white_check_mark:|
|查询数据量超过阈值，筛选条件必须带上主键或者索引||error|10万||:white_check_mark:|
|表行数超过阈值，建议对表进行拆分||warn|1000万|只在库表元数据扫描时检查create table语句|:white_check_mark:|     
|禁止对索引列进行数学运算和使用函数|索引失效|error|||:white_check_mark:|
|连接表字段的字符集和排序规则必须一致|索引失效|error|||:white_check_mark:|
|使用联合索引时，必须使用联合索引的首字段|error||||:white_check_mark:
|禁止对联合索引左侧字段进行IN 、OR操作|error||||:white_check_mark:

## 需要调整规则名的规则
- [x] 表字段必须有NOT NULL约束 -> 表字段建议有NOT NULL约束

## 需要调整风险等级的规则
禁止使用聚合函数 -> warn
表字段建议有NOT NULL约束 -> notice
建议连库查询时，确保SQL执行计划中使用的索引区分度大于阈值 -> error

**Comment by hasa1K** [comment]
表行数超过阈值，建议对表进行拆分
该规则只适用于库表元数据扫描并且需要与停用上线审核模式规则一起使用
