### ISSUE TITLE
当开启索引优化规则时，jenkins脚本运行失败

### ISSUE THREAD

**Issue by chenjiayuan123** [actiontech/sqle#180]
SQLe Version
"release-1.2111.x 5d24144"

To Reproduce
1.创建审核计划配置jenkins 触发gitlab sqle可以看到审核计划的语句
2.开启索引优化规则，查看运行脚本结果
![image](https://user-images.githubusercontent.com/54424145/147746507-ed88161c-a2bc-4197-adcd-97facd03c682.png)
该缺陷稳定复现

**Comment by sjjian** [comment]
## 原因：
在对Mybatis 收集的SQL进行索引优化时执行explain失败，因为该SQL不是完整的SQL，是SQL指纹，无法执行explain，导致审核失败报错

## 修复：
当执行explain失败时，仅不进行索引优化，允许其他审核正常执行

**Comment by sjjian** [comment]
## 测试影响
影响索引优化相关功能

**Comment by chenjiayuan123** [comment]
Version:
"release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
验证通过
验证步骤：
1.创建审核计划配置jenkins 触发gitlab sqle可以看到审核计划的语句
2.开启索引优化规则，查看运行脚本结果
脚本运行正常，sqle触发审核
![image](https://user-images.githubusercontent.com/54424145/147809227-a866a4a8-0da6-4dca-a4d4-633f91dc8928.png)
