### ISSUE TITLE
MySQL审核时如果SQL内切换过schema, 则会导致审核接口报错预检查失败

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1830]
**SQLe Version**

**Describe the bug**
MySQL审核时如果SQL内切换过schema, 则会导致审核接口报错
![image](https://github.com/actiontech/sqle/assets/18008452/f6b6dd5a-ce46-4145-941a-4b07782a04e2)

**To Reproduce**

1. 在数据源下创建两个数据库db1, db2，db1 存在表t1
2. 审核时指定数据库为db2
3. 审核语句`use db1; insert into t1 (id) values (1)`
4. 接口审核失败，如上面描述中截图

**Expected behavior**

**Suggestion**

**Comment by sjjian** [comment]
问题来自：https://github.com/actiontech/sqle/pull/604/files

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-2.2308.x 39bbc2a
Server Version: release-2.2308.x-ee 4876ec1345
复现步骤：

在数据源下创建两个数据库mysql，test。mysql 存在表t1
审核时指定数据库为test
审核语句use mysql;
INSERT INTO user (Host, User, Password) VALUES ('localhost', 'myusername', PASSWORD('mypassword'));
接口审核失败，如上面描述中截图
![image](https://github.com/actiontech/sqle/assets/54339501/fd0b8bca-abda-4fd2-83fe-36817d6b81fe)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 948cc8d
Server Version: main-ee a492a485a9

验证步骤：

1. 在数据源下创建两个数据库mysql，test。mysql 存在表t1
2. 审核时指定数据库为test
3. 审核语句use mysql;INSERT INTO user (Host, User, Password) VALUES ('localhost', 'myusername', PASSWORD('mypassword'));
4. 目前可以正常审核，接口没报错

![image](https://github.com/actiontech/sqle/assets/54339501/76769dd6-c51c-4f0b-a89c-e5eca473bf92)
