### ISSUE TITLE
工单被驳回后,上线工单步骤待操作人丢失

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#1838]
**SQLe Version**
2.2308.x

**Describe the bug**
创建新的工单,点击驳回按钮,驳回更新后的工单上线工单步骤的待操作人丢失,导致不能工单无法上线

**To Reproduce**
1. 创建一个工单
3. 执行驳回工单操作
4. 执行修改审核语句，并更新当前工单
5. 审核通过后,上线工单步骤待操作人为空
![image](https://github.com/actiontech/sqle/assets/63177450/fcfcf882-14c8-45e7-aa13-a175898a5276)

**Expected behavior**
即使工单被驳回后,工单待操作人依然存在

**Suggestion**
工单被驳回后,在更新工单接口内存储实例对应的待操作人
![image](https://github.com/actiontech/sqle/assets/63177450/490ec423-ca09-4789-aea1-5b204a54354d)

**Comment by taolx0** [comment]
UI: main aeee2f9d
DMS: main-ee 19ee2c1ea2
SQLE: main-ee 342c635080
![20240130172755-convert](https://github.com/actiontech/sqle/assets/63177450/90b5b440-d82b-4194-9e35-05030c9b5cc6)
