### ISSUE TITLE
创建一个工单使用查询语句期望能够触发索引审核提示，但是未能触发

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#184]
**SQLe Version**
Version:
  "release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"

**To Reproduce**
1.创建一个工单，然后审核sql语句如下，可以正常触发其他审核提示，但是没有能够触发索引优化提示
SELECT SId from SC where score = ‘90’
![image](https://user-images.githubusercontent.com/54339501/147808926-dedf1e59-e38b-41bf-b0a8-77bead2db29d.png)
查看explain执行语句，显示type为all
![image](https://user-images.githubusercontent.com/54339501/147808965-43f9ee34-3e2b-4378-b079-3a10ef68f738.png)
根据sqle对索引优化建议的逻辑判断应该是符合条件的，所以是期望进行审核提示
原因分析：
time=“2021-12-31T14:09:37+08:00” level=error msg=“get execution plan failed, sqle: select sid from sc where score = ‘90’;, error: Error 1146: Table ‘test.sc’ doesn’t exist”
sqle日志中输出一条表未找到的信息，但是在界面输入的是SC，sqle实际去查找的是sc

**Comment by drivebyer** [comment]
表明使用小写不会出现上述现象。

缺陷原因：
后端对表名一律使用小写处理。

**Comment by Marcus9530** [comment]
验证通过
验证版本
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee b9c5c53f80
使用一个表名带有大写字母的进行查询，触发三星索引提示
![image](https://user-images.githubusercontent.com/54339501/150926694-590f64b3-108b-4e7e-ae94-4a5601ac4bd4.png)
