### ISSUE TITLE
插件删除规则后，SQLE平台上仍显示已删除的规则

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1849]
问题现象：
SQLE平台上存在某条规则，更新插件后将这条规则删除，重启SQLE，规则列表仍能看到这条规则，但实际上并不会在审核中生效

复现步骤：
1. 启动SQLE，查看规则
![image](https://github.com/actiontech/sqle/assets/36940986/c7d2544a-e1d6-4b57-9b82-f6e905eaa901)
2. 审核SQL，会触发这条规则
![image](https://github.com/actiontech/sqle/assets/36940986/34b2607e-0199-42e1-b35b-5a8ffaa876b1)
3. 更新MySQL规则代码，删除这条规则，重启SQLE，规则仍然能看到
![image](https://github.com/actiontech/sqle/assets/36940986/c7d2544a-e1d6-4b57-9b82-f6e905eaa901)
4. 但是再次审核，规则没有生效了
![image](https://github.com/actiontech/sqle/assets/36940986/7e5b623b-23c2-4eef-839b-1dc6e978ceb6)

原因：
SQLE启动时同步插件审核规则的时候，没有清理已经不存在的规则的元数据

**Comment by iwanghc** [comment]
解决方案：
1、插件已删除的规则同步删除sqle中的公共模板中规则、项目模板中规则、知识库。
2、历史审核记录中点击已删除的规则给予页面提示该规则已被删除。

**Comment by iwanghc** [comment]
页面效果：
![img_v3_028h_da7b96df-f354-4931-8585-9e487c097f2g](https://github.com/actiontech/sqle/assets/83113746/94573476-e215-4bab-b3d9-51ffee27c852)
