### ISSUE TITLE
MySQL规则 “禁止使用触发器” 在错误场景下触发

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1865]
**SQLe Version**

MySQL规则 “禁止使用触发器” 在错误场景下触发。当SQL解析失败且包含关键字 after 时必然提示
例如提交SQL审核:
```sql
after
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by sjjian** [comment]
#原因
规则 “禁止使用触发器” 是通过正则表达式实现的，匹配创建触发器的正则表达式存在缺陷导致问题

**Comment by Marcus9530** [comment]
UI Version: release-2.2308.x 39bbc2a
Server Version: release-2.2308.x-ee 9dea982031
复现步骤：
输入after点击审核，提示报错
![image](https://github.com/actiontech/sqle/assets/54339501/0e5f6587-8fdc-42ce-a5ff-9126e93add12)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main a25877b
Server Version: main-ee d1c0a3880b
验证步骤：
输入after语句之后，点击审核，没有触发

![image](https://github.com/actiontech/sqle/assets/54339501/68a7d8af-b59b-4740-9e51-e77dc9b3d7d9)
