### ISSUE TITLE
无法通过页面修改不满足平台用户格式的LDAP用户

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#187]
**SQLe Version**
main

**Describe the bug**
无法通过页面修改不满足平台用户格式的LDAP用户，用户格式“名.姓”，不符合创建用户的验证。

**To Reproduce**
1. 配置使用ldap登录
2. 使用ldap用户登录，ldap用户名格式为：san.zhang（也可直接改sqle库来达到同样效果）
3. 通过 admin 用户修改“san.zhang”用户的信息，表单页面有报错，但用户为已存在用户
![I ~%BST3 Y N$O4TEEY} `C](https://user-images.githubusercontent.com/18008452/148013972-269ac97d-a2ad-4a43-949a-e959bc4ff45b.png)

**Expected behavior**
系统已存在的用户在进行更新操作时不会更新用户名，没有对用户的用户名进行校验的必要

**Comment by Marcus9530** [comment]
复现版本1.2112.0
sqle-cc48d26174ad061aefcd600aada7a38a2#
复现步骤：
1.在ldap上创建一个z.test用户
2.sqle开启ladp服务，然后使用ladp的z.test用户进行登录
3.然后切换到admin用户上，对该用户进行修改，前端提示信息无法进行修改
![image](https://user-images.githubusercontent.com/54339501/151096729-3ba55488-644f-42bd-bf95-09076058f73b.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee f134fafd8f
1.在ldap上创建一个z.test用户
2.sqle开启ladp服务，然后使用ladp的z.test用户进行登录
3.然后切换到admin用户上，对该用户进行修改，前端不在给出提示信息，可以正常进行修改
![image](https://user-images.githubusercontent.com/54339501/151098039-d2fd0122-8a8a-41ea-a925-faa015cf7802.png)

![image](https://user-images.githubusercontent.com/54339501/151098018-2cb6b984-1a4d-4936-bb08-88328f8499a1.png)
