### ISSUE TITLE
优化select count()的审核场景

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1872]
## 规则：禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL
像 SELECT count(*) FROM tb11 这类SQL，目的是为了计数，本身比查询数据开销要小，不要求要有有效的where条件

## 规则：SELECT 语句必须带LIMIT
SELECT count(*) FROM tb1 这类SQL本身就是为了计数，没必要使用limit

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main a25877b
Server Version: main-ee d1c0a3880b
验证步骤：
使用SELECT count(*) FROM tb1 进行审核，可以看到没有上述两个审核规则


![image](https://github.com/actiontech/sqle/assets/54339501/b44b5bcb-486a-4d83-8276-c534afa3004b)
