### ISSUE TITLE
优化索引创建建议

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1876]
**规则：** 索引创建建议
**现象：**
select id,name,age from A where name='xiaoming' order by name desc; 其中 A.id 为表主键，该规则给出的建议是为列 name desc,name,age 添加索引

**问题**
1. 提示歧义：name desc指的是为name列创建倒序索引，而不是给名为name desc的列创建索引
2. 提示歧义：让人误以为是要给列name desc,name,age创建联合索引
3. 无意义的索引建议：为select字段age创建索引在大部分情况下没有意义

**修复方案**
1. name desc列的desc描述去掉，只提示为name添加索引
2. 修改描述为在这些列中选取合适的列添加索引
3. 由于涉及场景较复杂，暂时不检查select字段

**注意**
where条件中只检查用了等号的列

**Comment by ColdWaterLW** [comment]
**修复后的效果**
select id from tb11 where name="dd" and age=1
只有id是主键，其他列没有索引
![image](https://github.com/actiontech/sqle/assets/36940986/ca0b8d20-3507-4379-8137-f35289eb4673)

**Comment by Marcus9530** [comment]
复现版本
UI Version: release-2.2308.x 39bbc2a
Server Version: release-2.2308.x-ee 9dea982031
复现步骤：
使用select id,name,age from A
进行审核，触发三星索引审核提示
![image](https://github.com/actiontech/sqle/assets/54339501/a13834b3-2128-45d4-9fb7-ee3606675731)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main a25877b
Server Version: main-ee 155ac78834
验证步骤：
当前后面没有where条件的时候不会触发审核提示，当带有where条件后面的子句可以看到审核提示


![image](https://github.com/actiontech/sqle/assets/54339501/c757b0ed-7a49-4d0e-b1cd-50da6ac72c23)
![image](https://github.com/actiontech/sqle/assets/54339501/72cf6bd6-010c-4867-b236-6f027a24dfe2)
