### ISSUE TITLE
MySQL规则“禁止WHERE条件中使用与过滤字段不一致的数据类型” 在部分场景下无法触发

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1878]
**SQLe Version**

1. 当使用关联表时，若字段名相同则无法正确找到表
2. column IN (v1, v2) 这种IN表达试无法识别

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by Marcus9530** [comment]
复现步骤：
测试表
```
CREATE TABLE table1 (
id INT PRIMARY KEY,
common_column VARCHAR(50),
other_column1 INT
);

CREATE TABLE table2 (
id INT PRIMARY KEY,
common_column INT,
other_column2 VARCHAR(50)
);
```
然后对两张进行关联查询，使用common_column进行等值，没有触发规则
![image](https://github.com/actiontech/sqle/assets/54339501/7f57b84c-6bab-49e6-a249-c05c8fd867d4)

**Comment by Marcus9530** [comment]
UI Version: release-2.2308.x 39bbc2a
Server Version: release-2.2308.x-ee 9dea982031
两张表name字段类型不一样，当进行审核的时候没有触发相关规则
![image](https://github.com/actiontech/sqle/assets/54339501/97f3ddbc-5926-4683-a719-7802754c48da)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main a25877b
Server Version: main-ee d1c0a3880b
验证步骤：
两张表name字段类型不一样，当进行审核的时候可以触发相关规则

![image](https://github.com/actiontech/sqle/assets/54339501/085518ed-0679-46c6-8a19-09ed0426c4e0)
