### ISSUE TITLE
SQL工作台支持最新的CB版本（23.2.1）

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1884]
**Describe**

**Suggestion**

**Why**

**Comment by Marcus9530** [comment]
当前sqle可以支持CB版本（23.2.1）版本，并且可以正常下发sql以及进行审核
![image](https://github.com/actiontech/sqle/assets/54339501/6c96bd59-3196-4aeb-856f-a9a4dbd5ef27)
