### ISSUE TITLE
SQL审核：审核结果显示错误

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1886]
## 问题1
功能：SQL审核
问题描述：审核状态为审核中，但审核结果全部是passed，审核通过率0%，审核评分0

## 问题2
功能：SQL管控
问题描述：SQL审核的最新一条状态为审核中，但审核结果是passed

**Comment by winfredLIN** [comment]
该问题已复现

问题的原因是：如果审核结果中没有审核意见则前端界面会显示passed
这个逻辑在SQL审核结束的状态下是对的。但是如果审核未完成，审核意见也是空的，此时显示passed就是错误的。

解决方案：为了不让前端显示passed，增加一个普通级别的信息，表明该SQL正在审核中，而不是审核通过。

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证通过
