### ISSUE TITLE
规则未触发：建议JOIN字段类型保持一致

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1888]
### 规则:
建议JOIN字段类型保持一致
### 问题：
两表join,关联字段字符集不一样导致规则未触发

### 复现过程：
-- 创建表 t1,字符集为 utf8mb3
CREATE TABLE `t1` (
  `id` int DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3
 
-- 创建表 t2,字符集为 gbk
CREATE TABLE `t2` (
  `id` int DEFAULT NULL,
  `city` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=gbk

-- 查询语句
SELECT t1.id, t1.name, t2.city
FROM
  (SELECT id FROM t1 WHERE id < 100) AS t
  LEFT JOIN t2
  ON CAST(t.id AS CHAR) = t2.id
LIMIT 5;

未能触发规则：建议JOIN字段类型保持一致
![image](https://github.com/actiontech/sqle/assets/31072467/e5cbdb3c-29fe-4403-a48a-8319919d2acd)

**Comment by winfredLIN** [comment]
这里复现的sql语句的未触发该规则的原因不是表字符集不同，而是没有从sql语句中解析出表定义

**Comment by winfredLIN** [comment]
### 解决方案
1. 支持了JOIN语句中使用子查询结果作为临时表，并且使用别名
2. 支持了JOIN中ON语句块中的连接键使用CAST和CONVERT对列进行显式转换，根据转换后的类型进行判断
3. 不支持JOIN连接的表由多表作为来源
4. 不支持JOIN中ON语句块中，一个连接键使用多列组合构成

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc


验证的sql：
原sql：SELECT t.id,t.name FROM (SELECT id,name FROM t1 WHERE id < 100) AS t LEFT JOIN t2 ON CAST(t.id AS CHAR) = t2.id LIMIT 5;

支持的 1 2 3
SELECT t1.name, t2.city FROM t1 JOIN t2 ON t1.id = t2.id;

SELECT t1.name, t2.city FROM (SELECT * FROM t1) AS t1 JOIN (SELECT * FROM t2) AS t2 ON t1.id = t2.id;

SELECT t1.name, t2.city FROM (SELECT id, name FROM t1) AS t1 JOIN (SELECT id, CONVERT(city, CHAR) AS city FROM t2) AS t2 ON CAST(t1.id AS CHAR) = t2.id;

不支持的4 5
SELECT t1.id, t2.city, t3.id FROM t1 JOIN (SELECT t2.id FROM t2 JOIN t3 ON t2.id = t3.id) AS ccc ON t1.id = ccc.id
SELECT t1.name, t2.city FROM t1 JOIN t2 ON t1.id = t2.id AND t1.name = t2.name;

验证结果
![image](https://github.com/actiontech/sqle/assets/44565577/89e8b7ae-a8f7-415a-a9b2-3ae12e2334e2)
![image](https://github.com/actiontech/sqle/assets/44565577/0ea2b1dd-c739-4128-8fc5-74b8395d9996)
![image](https://github.com/actiontech/sqle/assets/44565577/0062550f-44c7-41f8-969d-5601e0e08798)
