### ISSUE TITLE
智能扫描的审核：解析出空的node导致审核请求错误

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1897]
### 触发场景：
智能扫描中的审核
### 具体描述：
在智能扫描上传完sql之后，点击审核，当解析某条SQL返回的node为空时，页面弹出请求错误，审核没有正确完成
### 需求
希望当解析SQL返回的node为空时，审核能够继续

**Comment by winfredLIN** [comment]
问题的原因：
hookAudit中，对parse函数返回的错误直接抛出，导致审核中断

**Comment by winfredLIN** [comment]
解决方案：SQLE端在接收并处理scanner上传的数据时，过滤掉SQL内容为空的SQL

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 29d0840db3
