### ISSUE TITLE
当存在相同rule name的审核规则时，审核结果展示错误

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1899]
## 问题1 @LZS911 
审核结果展示的规则信息可能有误
### 原因
由于默认的规则是双主键存储，rule_name不是唯一值，所以v1/rules通过rule name筛选时可能会得到多个结果

## 问题2 @ColdWaterLW 
v1/rules [get] 接口使用多个条件筛选时，返回的结果不是多条件的交集
### 复现步骤
1. 调用v1/rules [get]接口，同时传filter_db_type 和 filter_rule_names
2. 现象是返回了db_type类型的所有规则
3. 预期是返回filter_db_type 和 filter_rule_names的交集，应该只有一条规则

### 原因
后端处理逻辑问题

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 29d0840db3
