### ISSUE TITLE
点击审核计划的立即审核按钮, 出现 affectRowNum error 报错

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1903]
**SQLe Version**
main

**To Reproduce**
1. 创建自定义审核任务(包含数据源和schema),规则模版必须包含下图的规则
![image](https://github.com/actiontech/sqle/assets/63177450/9abd2036-9c94-4e14-bcec-5fc2cd7544eb)
![image](https://github.com/actiontech/sqle/assets/63177450/3a23b3af-288e-46e1-b37a-7dbc043d0ab0)

2. 上传sql到自定义审核计划(sql 的执行计划 type 必须是 ALL 或 index)

3. 点击扫描计划的立即审核按钮,出现报错
![image](https://github.com/actiontech/sqle/assets/63177450/aa376295-c122-49b5-a8f1-4eca19cee14c)

**Suggestion**
预期不报错

**Comment by taolx0** [comment]
### 引入mysql库的插件需要更新

**Comment by taolx0** [comment]
### 原因
sqle 执行 查询数据量超过阈值，筛选条件必须带上主键或者索引 执行时,会下发一条 SELECT COUNT(1) ... 类型的sql, sqle默认 SELECT COUNT(1) 一定会有结果,遗漏了 SELECT COUNT(1) ...  limit 10,10 这种类型的sql结果可能为空的场景

### 方案
1. 带 limit ?,? 的sql 使用子查询 select count(*) from (输入的sql) as t的方式来获取影响行数
2. 增加兜底检测逻辑,预防 select count(1) 的结果为空

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 32288994f7

验证过程：
工单审核输入sql：select id from sbtest1 limit 10,20

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/725b3438-357d-42d4-8981-f8157a80b502)
