### ISSUE TITLE
取消插件接收的数据量限制

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1909]
目前提供的插件开发包中，grpc接收端的数据量上限为grpc默认的4M，当SQL文件很大时，传输的数据量超过4M，会报错“grpc: received message larger than max (%d vs. %d)”

解决方案：
鉴于插件和SQLE是在同一台服务器上，使用socket通信，受网络限制不会太大，所以取消grpc传输上限

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证步骤：
使用一个36m大小的sql文件，然后进行审核，使用tdsql数据源，可以正常审核，给到相关的审核提示。

![image](https://github.com/actiontech/sqle/assets/54339501/1924db9c-289b-46df-b908-1579126677ba)
![image](https://github.com/actiontech/sqle/assets/54339501/1924db9c-289b-46df-b908-1579126677ba)
![image](https://github.com/actiontech/sqle/assets/54339501/8d2c186f-9717-46b5-8998-b7d7589330ab)
