### ISSUE TITLE
工作台支持TDSQL

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1915]
支持把SQLE的TDSQL数据源同步到SQL工作台使用

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/2b46a91e-6a46-4bc1-92fe-e34d10a95551)
