### ISSUE TITLE
规则未生效：禁止使用全模糊搜索或左模糊搜索

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1917]
### 场景：
SQL审核
### 规则：
禁止使用全模糊搜索或左模糊搜索
### 触发方式：
审核语句：
SELECT * FROM t1 WHERE name LIKE CONCAT('%','a','%');
无法触发该规则

**Comment by winfredLIN** [comment]
### 问题原因
该规则未覆盖使用CONCAT函数的结果作为LIKE的值

### 解决方案
该规则，增加对CONCAT函数结果作为LIKE的值的判断

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/393fc440-b761-4e28-940c-1a1072a723c0)
