### ISSUE TITLE
规则“连库查询对SQL执行计划中使用索引进行区分度分析”可使用MySQL系统表信息统计SQL区分度

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1918]
**Describe**

当前SQLE使用的是数据库查询的方式进行索引区分度的计算，但是当表数据量巨大时可能会存在性能问题
```sql
SELECT DISTINCT column_name)/COUNT(*) FROM table_name
```
因此可采用MySQL系统表来统计索引区分度，当数据量足够多时，这个概率是趋于稳定的，虽然是估计值但差距不会太大，具备一定参考性
```sql
SELECT
	s.TABLE_NAME,
	s.INDEX_NAME,
	(s.CARDINALITY / t.TABLE_ROWS) AS index_selectivity 
FROM
	INFORMATION_SCHEMA.STATISTICS s JOIN INFORMATION_SCHEMA.TABLES t
ON 
	s.TABLE_SCHEMA = t.TABLE_SCHEMA AND s.TABLE_NAME = t.TABLE_NAME
WHERE 
	s.TABLE_SCHEMA = 'sqle' and s.TABLE_NAME = 't1' and s.INDEX_NAME='idx_name';
```

**Comment by winfredLIN** [comment]
### 解决方案
涉及到两条规则的改动：checkIndexOption和checkIndexSelectivity
1. 在检查索引的区分度的时候，使用系统视图的统计信息估计索引区分度（checkIndexSelectivity使用该方法）
2. 在检查列的区分度的时候，使用统计方法估计索引区分度，（checkIndexOption使用该方法）

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 29d0840db3
