### ISSUE TITLE
审核包含特殊字符的sql发生程序卡住现象

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1923]
当审核包含特殊字符的sql时，发生审核无法结束的现象
对应的sql: 
```sql
select * from `scpp_uat`.`tbl_pay_charge` where ((sharding_key = 23) and (open_id = "1232") and (charge_no = "1")) order by 
�E desc limit 1
```
![image](https://github.com/actiontech/sqle/assets/53266479/c24e1923-dede-484c-80e5-17cf24561e8f)

**Comment by hasa1K** [comment]
问题原因：
审核sql前需要解析sql，解析sql使用的是pingcap开源的tidb包中的parser工具，parser工具中解析到特殊字符时发生死循环，无法跳出scanLoop
![image](https://github.com/actiontech/sqle/assets/53266479/716737e7-8349-44a5-8e5c-f2708366ee22)

**Comment by sjjian** [comment]
https://github.com/actiontech/sqle/issues/566

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 32288994f7
验证结果：
包含特殊字符的sql审核不会hang
![image](https://github.com/actiontech/sqle/assets/44565577/fec7f431-af96-4b95-8a1a-a193dba417fd)
