### ISSUE TITLE
解析器优化，支持 MySQL 所有字符集的解析

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1924]
## 问题：
1. 当前SQL解析器无法处理一些不常见的字符集，例如：” armscii8“ ，会解析出错；
2. 当前SQL解析器不支持utf8 别名 utf8mb3，MySQL8 里已默认将 utf8 替换成了 utf8mb3。
## 相关问题： 
1. https://github.com/actiontech/sqle/issues/1888
2. https://github.com/actiontech/sqle/issues/1537
3. https://github.com/actiontech/sqle/issues/488
4. https://github.com/actiontech/sqle/issues/474
## 方案
基于现有定制版的SQL解析器基础上进行修复，暂不使用最新版的TiDB解析；虽然 TiDB 在最新版上支持了UTF8MB3，但是TiDB数据库不支持的字符集在解析时还是会报错，例如:” armscii8“；最新版的TiDB SQL解析库又从独立的项目迁移回TiDB内，升级的成本太高。

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 32288994f7
