### ISSUE TITLE
审核规则panic

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1925]
相关规则：“建议连库查询时，确保SQL执行计划中使用的索引区分度大于阈值”在线审核时，部分场景发生panic

## 复现方法
使用mysql或tdsql测试，以下例子是用tdsql测试
1. 开启审核规则：“建议连库查询时，确保SQL执行计划中使用的索引区分度大于阈值”
2. 测试SQL满足以下条件：
  a. 包含没有from的select语句（可以是子查询）
  b. 执行计划中使用了索引 
  c. 附送一个测试SQL：```SELECT *, (select count(*)) from exist_tb_10 WHERE id=3```
3. 触发动态审核，页面报错
![image](https://github.com/actiontech/sqle/assets/36940986/664386d1-4166-4e0d-8bab-60e0cae1ab6a)
4. 查看日志
![img_v2_306b0574-48b3-4f1d-b53c-7671ec0c0fbg](https://github.com/actiontech/sqle/assets/36940986/b5ab5453-2540-4678-ae64-e0f5e902eef2)

## 原因
未对select语法中的from节点做判空，导致使用空指针

**Comment by ColdWaterLW** [comment]
http://10.186.18.21/sqle/sqle-td-mysql-plugin/-/merge_requests/31

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/d639cb6f-13d5-4dae-90dc-f48b7a0a2948)
