### ISSUE TITLE
白名单触发存在一些问题

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1929]
**SQLe Version**
main-ee eaa90f45a4

**Describe the bug**
执行出现在白名单中的SQL语句，审核结果应均为“白名单”，但变更SQL顺序，会获得不同的审核结果，需要看一下原因

**To Reproduce**

1. 添加两个白名单SQL
- SQL指纹匹配：insert into city values (2,2);
- 字符串匹配：delete from city;
![image](https://github.com/actiontech/sqle/assets/113898890/5cef1da7-ee9e-46fb-af31-84558c1b6757)

2. 变更SQL顺序，获得不同的白名单审核结果
![de1ba484-bc30-41e0-92b9-4265096f650c](https://github.com/actiontech/sqle/assets/113898890/d96a6eb1-b1ca-4866-b793-684f7bb2755a)
![img_v2_e1986be7-2b9e-4126-9281-9fa30117dadg](https://github.com/actiontech/sqle/assets/113898890/81604238-95ee-4ee6-a440-5db3cb40acc0)

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 4597ecfddc

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/9538bb3c-3459-41cd-b7cd-d4406a97f8ec)
