### ISSUE TITLE
Mysql audit failed, when schema like "cmal-test"

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#193]
**SQLe Version**
main

**Describe the bug**
Mysql audit failed, when schema like "cmal-test". error message:
```bash
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-demo' at line 1
```
![image](https://user-images.githubusercontent.com/18008452/148359576-2109bdf4-f744-4a82-b5db-c0cc9004fb23.png)

**To Reproduce**
1. 在上线数据库创建一个schema "test-demo"
```sql
create database `test-demo`
```
2. 在页面进行SQL审核，指定对应的schema "test-demo"
3. 输入SQL进行审核
```
create table t1(id int)
```
4. 审核失败，报错如描述所示

**Expected behavior**
期望审核成功

**Comment by sjjian** [comment]
## 原因
1. MySQL对象命令不包含出现中划线，如果需要使用则对象需要使用反引号包裹起来；
2. 后端进行审核时会实时获取库表结构，使用语句查询未对test-demo 使用反引号包裹，导致查询语句语法错误

**Comment by Marcus9530** [comment]
复现版本 1.2112.0
sqle-cc48d26174ad061aefcd600aada7a38a2
复现步骤：
1.在上线数据库创建一个schema "test-demo"
create database `test-demo`
2.在页面进行SQL审核，指定对应的schema "test-demo"
3.输入SQL进行审核
create table t1(id int)
4.审核失败，报错如描述所示
![image](https://user-images.githubusercontent.com/54339501/151095842-2ca683a0-f885-40bf-bbe6-5f4e2fc18e8d.png)

**Comment by Marcus9530** [comment]
验证版本


验证步骤：
1.在上线数据库创建一个schema "test-demo"
create database test-demo
2.在页面进行SQL审核，指定对应的schema "test-demo"
3.输入SQL进行审核
create table t1(id int)
4.可以成功创建工单，且上线也成功
![image](https://user-images.githubusercontent.com/54339501/151096009-ea0a6f15-fc93-4380-93aa-1b03a904cddf.png)
![image](https://user-images.githubusercontent.com/54339501/151096032-fa33a42f-3971-4fa8-8201-902684fe896d.png)
