### ISSUE TITLE
规则 不建议创建冗余索引 误报错

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#1936]
**SQLe Version**
main

**To Reproduce**
1. 开启规则 不建议创建冗余索引
2. 用以下sql审核
```sql
CREATE TABLE t3
(
    `ID`        BIGINT(11)  NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    ID_NUM      Varchar(20) NOT NULL COMMENT 'TE件号码',
    STATUS      Varchar(20) NOT NULL COMMENT '状态',
    CREATE_TIME DATETIME    NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    KEY `idx_id_status_time` (ID_NUM, STATUS, CREATE_TIME) USING BTREE
);
```
3. 触发审核规则 不建议创建冗余索引
![image](https://github.com/actiontech/sqle/assets/63177450/7ec18fef-ff56-4342-967f-c43a7b4001e1)

**Why**
因为主键ID和联合索引idx_id_status_time里的第一个字段 ID_NUM前缀相同.这是一个代码的bug,代码的逻辑简单使用字符串前缀匹配,导致了这种显然误报的情况
![image](https://github.com/actiontech/sqle/assets/63177450/b911b8e9-7d3b-4383-b9fb-670141d87e97)

**Comment by taolx0** [comment]
### 修复
使用字符串数组来进行完全匹配,不使用简单的字符串前缀匹配

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 32288994f7

验证步骤：
使用上述sql审核

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/95e7bcc8-d0f4-4e31-9c98-2ff834f65add)
