### ISSUE TITLE
当数据源没有绑定审核规则模版的时候，在界面上显示报错

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1945]
添加数据源的时候不设置审核规则模版，然后在界面上就可以看到报错
![c51e5e6b-322d-42de-b4ab-9b67029cd402](https://github.com/actiontech/sqle/assets/54339501/899ddd21-4632-43f2-b64b-1e38228af54c)

**Comment by Gygkimo95** [comment]
**方案预期**

新建数据源页面，新增开关“是否开启SQL审核业务 ”
* 默认开启，此时，用户必填“审核规则模板”
* 支持关闭，关闭时进行弹窗提示，关闭后不再填写“审核规则模板”

**原型参考**
默认状态
![image](https://github.com/actiontech/sqle/assets/113898890/f2f5e49c-d8e2-4218-816b-ca206cf6b604)

关闭时弹窗提示
![image](https://github.com/actiontech/sqle/assets/113898890/4a09b60e-cdae-426f-8aff-55f043ca73bd)

关闭后
![image](https://github.com/actiontech/sqle/assets/113898890/f9ecf49f-cc13-4fd7-8ecf-faf4856aeb21)
