### ISSUE TITLE
SQL工单内”待操作人“显示重复

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1951]
**SQLe Version**

**Describe the bug**
SQL工单内”待操作人“显示重复。
![96a6d833-9335-4b1c-af31-980bc921891a](https://github.com/actiontech/sqle/assets/18008452/5e1517ca-b884-441c-97c4-273cd6633625)
![2c7d5ea9-a051-4663-b44e-4b285ce88cc7](https://github.com/actiontech/sqle/assets/18008452/7d32967d-6201-43db-9c56-f9fec6e2b012)

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by LordofAvernus** [comment]
- 问题复现：
   当用户关联的 成员和成员组 均有审核权限的时候触发bug
