### ISSUE TITLE
优化 SQL 审核结果展示

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#1958]
现状:
当前工单页面以及智能扫描页面的审核结果无法查看审核规则说明. 
![img_v2_e730dca9-38f9-4a9f-8679-004b224c8ddg](https://github.com/actiontech/sqle/assets/42765421/b50a829e-1403-4c1e-900c-41f1079baa5a)

建议: 
移入规则的时候，鼠标变为可点击的样式
点击规则，下拉展示规则说明
再次点击规则，收起说明

**Comment by Gygkimo95** [comment]
展开预期：
* 规则说明布局参考如下
* 规则样式使用 平台已有的说明文字公共组件
![image](https://github.com/actiontech/sqle/assets/113898890/e2de2f7d-ba79-4e2a-9345-a179dac32395)

**Comment by quexiuping** [comment]
验证版本：
UI: main-ee 091463b7
DMS: main-ee f94afb4f97
SQLE: main-ee 836dda4a67
