### ISSUE TITLE
用户中心编辑用户页面，点击提示按钮会触发“禁用用户”

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#1971]
**SQLe Version**
main-ee eaa90f45a4

**Describe the bug**
用户中心编辑用户页面，点击提示按钮会触发“禁用用户”

**To Reproduce**
1.进入用户中心-用户管理，选择一个用户点击“编辑：
2.点击“禁用用户”前的提示按钮，触发了禁用用户
![image](https://github.com/actiontech/sqle/assets/44565577/75bec07a-f871-4164-bdd6-ab8c230b95f9)
3.用户组管理上的禁用提示就不会触发
![image](https://github.com/actiontech/sqle/assets/44565577/16288339-e06d-48e5-ba1a-b390895dfd12)

**Expected behavior**
提示按钮点击只是弹窗提示

**Suggestion**

**Comment by ColdWaterLW** [comment]
和产品达成一致结论：
- 通常认知里，提示按钮是移入的时候展开popover，点击不是预期行为
- 这个feature特征在于点击label就实现了开启的效果，还挺方便的，没有那么死板

由以上原因决定不用修改，个人使用体验不同，如果点击了，然后开了，其实也可以通过再次点击实现关闭，影响不大
