### ISSUE TITLE
创建SQL审核时，创建成功提示不明显，容易反复触发审核

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#1973]
**Describe**
* SQL审核页面，点击审核
* 如果很快出审核结果，且没有看到顶部message提示，会感知不到审核已触发
* 此时，容易重复点击审核，产生多条重复审核记录
![image](https://github.com/actiontech/sqle/assets/113898890/b56ec70e-0f4c-4f08-91ce-6afa54789f22)

**Suggestion**
补充交互预期
* 点击审核，出审核结果后，顶部出现message提示
* 同时，页面自动跳转至审核结果部分
![image](https://github.com/actiontech/sqle/assets/113898890/a1c52561-9394-407f-b139-34fc301daa17)

**Comment by quexiuping** [comment]
验证版本：
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217
