### ISSUE TITLE
规则：禁止使用全模糊搜索或左模糊搜索，对特定SQL未生效

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1974]
1. 对使用Upper函数的结果作为模糊搜索的关键字时，该规则不生效
2. SQL的外层Select没有Where，内层子Select带有Where中使用了全模糊搜索或左模糊搜索时，该规则不生效

**Comment by winfredLIN** [comment]
### 解决两个问题：
规则DMLCheckFuzzySearch不支持上层函数
当SQL语句的外层没有where时，将不会检查子查询的where语句
### 涉及四条规则：
1. DMLCheckWhereIsInvalid
2. DMLCheckWhereExistNot
3. DMLCheckWhereExistScalarSubquery
4. DMLCheckFuzySearch
### 解决方案
1. 规则DMLCheckFuzzySearch支持upper函数
2. 当SQL语句外层没有WHERE但其子查询中有WHERE语句的时候，也会检查子查询中的WHERE语句

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 9847276d6a
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/1185f4fe-8423-4ca9-94fd-8f5cd736f35f)
