### ISSUE TITLE
where条件为exist时，会触发规则“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1980]
当where条件中只有exists时，会触发“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”
![img_v2_474f4600-bbc6-45ff-a7d5-399dba6576ag](https://github.com/actiontech/sqle/assets/53266479/74c0069d-d563-47e9-b2be-de1357fa0c4d)

**Comment by quexiuping** [comment]
验证版本：
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/0023692d-94fc-492f-8463-9e1d91fad0ab)
