### ISSUE TITLE
规则：避免使用count(col)若使用distinct则不触发规则

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1983]
审核规则:避免使用count(COL)
建议：对于count(distinct COL)场景过滤

**Comment by winfredLIN** [comment]
## 解决两个问题
1. 改进：COUNT()函数如果使用DISTINCT，则不触发规则
2. 修复：之前，该规则只对SELECT中的第一列进行规则检查。现在，支持了对SELECT的每一列都进行规则检查。

**Comment by quexiuping** [comment]
验证版本：
UI Version: main ad12569
Server Version: release-2.9999.x-ee 0f9c11c5b8
