### ISSUE TITLE
工单审核报错

### ISSUE THREAD

**Issue by xiaoxiaoxiaomo** [actiontech/sqle#1991]
**SQLe Version**

release-3.2310.x 2ab6c3fa2eea57721343b2f9cec27681ff5f358b

**Describe the bug**
在工单创建完成后、审核人员在面板点击“审核通过”按钮 会提示错误
错误内容：“update workflow status failed, Error 1292 (22007): Truncated incorrect DECIMAL value: ”

![image](https://github.com/actiontech/sqle/assets/29282134/9af235d6-267f-4ceb-b3aa-348c69753d9a)

**Comment by sjjian** [comment]
截图与报错内容不一样

**Comment by xiaoxiaoxiaomo** [comment]
> 截图与报错内容不一样

选错了图片、已更新

**Comment by LordofAvernus** [comment]
使用MariaDB作为后端数据库触发该问题
已修复:
https://github.com/actiontech/sqle/commit/d1dc01fe2e7f30209309ffd60094b4547a9639de#

**Comment by sjjian** [comment]
建议使用MySQL5.7 或 8.0 作为后端库
