### ISSUE TITLE
where条件判断错误，有where条件，且条件恒为false触发了规则

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#1994]
审核select * from users where 0=1;  触发了规则`禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL`
预期：0=1不应该触发该规则
![image](https://github.com/actiontech/sqle/assets/53266479/1f3ca444-4c66-4293-9bfc-4b33889fd0d9)

**Comment by hasa1K** [comment]
支持的判断：
支持相同数据类型的比较大小，不支持需要隐式转换的比值，例如：1='1'
支持的比值符号：>, <, >=, <=, =, != , <>。不支持使用1 in (1, 1)

**Comment by hasa1K** [comment]
where条件内存在纯数字比值符号时：
仅支持单个比值判断，例如：
select * from users where 1=0; 
select * from users where 1 > 0;
不支持and和or连接符，例如：
select * from users where 1=0 and 1=1;
select * from users where 1=0 or 1=1;

**Comment by quexiuping** [comment]
验证版本：
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/90f8099c-376b-4476-9a43-7be69288b1cb)
