### ISSUE TITLE
审核创建或修改索引的SQL语句时，报错获取索引选择性失败

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2015]
如图，审核一条创建或修改索引的SQL语句时，报错：get selectivity by index error: Error 1146: Table '<name of table>' doesn't exist
![image](https://github.com/actiontech/sqle/assets/31072467/9a5831e0-9ecc-457b-8b63-7e621477a166)

**Comment by winfredLIN** [comment]
## 问题原因
在获取列选择性的时候，会向MySQL发送请求，获取列对应表的统计信息，当表不存在的时候，MySQL会返回Error 1146: Table '' doesn't exist的错误
## 解决方案
在获取列选择性的时候，检查列对应表是否存在，若不存在，直接返回

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 9847276d6a
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/f61f1dfe-22fd-419e-aecb-a46bf0cedcc3)

**Comment by quexiuping** [comment]
验证版本：
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/3ca7ccd4-1294-43b0-aea9-f9b805a67089)
UI Version: main 3eec557
Server Version: release-2.9999.x-ee 9f92d9b95e
