### ISSUE TITLE
规则描述使用委婉的说法

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2022]
**Describe**
现在大部分规则描述使用了“禁止”，“必须”等词眼，需要换成委婉的说法，比如“建议”等词眼。除非是非常确定的情况下，可以使用强硬的说法
主要是为了体现专业性，不要被使用者质疑。

**Suggestion**

**Why**

**Comment by quexiuping** [comment]
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217
