### ISSUE TITLE
规则：应避免在 WHERE 条件中使用函数或其他运算符，使用不作用在列上的函数，会触发该规则

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2027]
### 问题描述
在WHERE中使用不作用在列上的函数，会触发该规则，应该不触发该规则
### 该规则的目的
避免WHERE条件中使用函数，因为函数作用在列上，导致查询无法利用表中的索引，该查询将会全表扫描，性能较差，但有一些函数例如：sysdate()、now() 未作用在某列上，因此不会导致全表扫描，因此不应触发该规则
### 复现该问题的SQL：
``` bash SQL
select * from table_1 where update_time < sysdate();
```
![image](https://github.com/actiontech/sqle/assets/31072467/fccfecbe-abd1-45f8-9e9f-dfa555a2adc1)

**Comment by winfredLIN** [comment]
## 解决方案
在检查函数的时候，检查函数中是否涉及表中的列，若不涉及，则不触发该规则。
不触发该规则的函数有两种：
1. 如now()这种不包含任何参数的函数
2. 如DATE('2023-01-01')这样不包含列但包含参数的函数用法

**Comment by quexiuping** [comment]
验证版本：
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217

验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/85461099-ddf2-44b4-95b3-a3a61b7d93d9)
