### ISSUE TITLE
规则：建议主键命名为"PK_表名“，当未为主键命名的时候，不触发该规则

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2028]
### 问题描述
在审核创建表的SQL时，DDL语句中，未给主键命名，不会触发该规则
### 复现该问题的SQL
``` bash SQL
CREATE TABLE  `tt1` (    
    `id` int NOT NULL,   
    `name` varchar(10) DEFAULT NULL, 
    PRIMARY KEY (`id`) 
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci
```
![image](https://github.com/actiontech/sqle/assets/31072467/d3ddc66b-ae52-4804-b968-b622b5fde30c)

**Comment by winfredLIN** [comment]
## 解决方案
对增加或修改主键，但不对主键命名时，触发规则

**Comment by quexiuping** [comment]
验证版本：

UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/49e69fca-660e-488f-b0a1-cf9904d1ccb3)
