### ISSUE TITLE
规则列表需要新增检索框

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2030]
### 现状：
规则列表如果全部渲染，会导致加载很慢，所以规则列表一次只会渲染20个

### 问题：
用户可能会使用ctrl/command+F查找规则，如果规则不在已渲染的范围内，会找不到规则，但实际规则存在

### 预期：

筛选操作栏增加一个搜索框，支持对规则做模糊搜索

### 调整：

项目规则
/v1/projects/${project_name}/rule_templates/${rule_template_name}
全局规则
/v1/rule_templates/${rule_template_name}
默认数据类型下规则列表
/v1/rules?filter_db_type=MySQL

支持模糊搜索字段：desc、annotation

**目前只有“查看规则”页面支持**

**Comment by quexiuping** [comment]
UI: main-ee 42bdca9f
DMS: main-ee 7f35dd7217
PROVISION: main 4135bf43ed
SQLE: main-ee 1ff8d69cab
