### ISSUE TITLE
规则：建议列与表使用同一个字符集

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2043]
审核DDL建表语句时，声明了列字符集与表字符集，若列字符集与表字符集相同，还会触发该规则。
复现该问题的SQL：
``` bash SQL
CREATE TABLE `t` ( `id` varchar(10) CHARACTER SET utf8mb4) CHARACTER SET utf8mb4;
```

**Comment by winfredLIN** [comment]
## 解决方案
支持检查建表语句中列字符集和表字符集的异同。
## 目前支持触发的场景
### 若DDL语句是建表语句：

1. 若列和表都声明了字符集。列的字符集与表字符集不同，触发规则。
2. 若列声明了字符集，表未声明字符集只声明排序规则。排序规则对应字符集与列字符集不同，触发规则。
3. 若列声明了字符集，表未声明字符集和排序规则。列字符集和数据库默认字符集不同，触发规则。

### 若DDL语句是修改表语句

1. 若只修改列字符集。字符集与原表不同，触发规则。
2. 若先修改表的字符集，再修改列的字符集。新列字符集与新表字符集不同，触发规则。
3. 若先修改列的字符集，再修改表的字符集。表中列的字符集会统一为新字符集，不触发规则。

**Comment by winfredLIN** [comment]
## 增加支持
1. 建表语句列声明排序但未声明字符集的情况，若排序对应字符集和表字符集不同则触发规则。

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 315e815
Server Version: release-2.9999.x-ee ca06e19f15
