### ISSUE TITLE
新增6条规则

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2049]
- [x] 禁止char, varchar类型字段字符长度总和超过阈值 @hasa1K 
- [x] 禁止使用空间字段和空间索引 @hasa1K 
- [x] 禁止使用全文索引 @hasa1K 
- [x] 禁止全表扫描（改描述）-> "全表扫描时，扫描行数不建议超过指定行数（默认值：10000）" @hasa1K 
- [x] "SQL执行计划中type字段建议满足规定的级别" @hasa1K 
- [x] WHERE子句禁止出现NULL值计算COLUMN_A=NULL可以写成COLUMN_A IS NULL
- [x] 禁止使用event

**Comment by BugsGuru** [comment]
规则：禁止使用event
开头可能存在修改分隔符的DELIMITER语句

存在DELIMITER语句时，无法触发：
![Image](https://github.com/user-attachments/assets/669cd0a0-948c-4d04-8e80-e08eb2303bab)
不存在DELIMITER语句时，可以触发：
![Image](https://github.com/user-attachments/assets/b525065c-b0a4-49db-873b-cb1e216b2f64)
