### ISSUE TITLE
审核结果处展示SQL来自于哪个文件

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2054]
## 需求背景
SQL审核和工单审核支持zip文件/git仓库审核，用户想要在审核的时候知道SQL是来自zip文件/git仓库里的具体哪个文件

## 需求方案
在审核结果弹窗中，SQL语句部分新增来源标签，展示SQL文件来源

## 限制：
本期只展示ZIP/git仓库审核时SQL的来源文件
非ZIP文件/git仓库不展示SQL来源

## 原型参考
![image](https://github.com/actiontech/sqle/assets/36940986/6acb61d9-dbdf-4f10-86cc-1075f1b5dc3a)

非ZIP文件/git仓库来源
![image](https://github.com/actiontech/sqle/assets/36940986/8625add8-6c6e-4a30-94e7-574d7611a9cb)

## 增加功能的页面
SQL审核
- 创建审核页面，查看审核结果
- 审核记录详情页面，查看审核结果

SQL工单
- 创建工单页面，查看审核结果

## 需要额外验证的点
- 上传ZIP文件，ZIP文件内包含多层目录结构，sql、xml文件存在放不同目录结构下，SQL解析结果是否正确。涉及：
  - SQL审核
  - 工单审核（需要验证“相同SQL”和“不同SQL”）
- 审核git仓库，仓库内包含多层目录结构，sql、xml文件存在放不同目录结构下，SQL解析结果是否正确。涉及：
  - SQL审核

**Comment by ColdWaterLW** [comment]
## 后端方案
### 表结构变更
execute_sql_detail表增加一个字段保存每条SQL的来源文件

### 流程变更
1. 原有逻辑是把所有文件的SQL都读区出来后调用一次插件解析，这样导致无法准确得知解析后的SQL来自哪个文件；修改为：每解析一个文件调用一次插件解析SQLs，解析出来的SQLs和来源文件一一对应
2. 创建审核task对象的时候保存SQL来源文件

**Comment by quexiuping** [comment]
数据去重需要考虑展示来源哪个？ @ColdWaterLW

**Comment by quexiuping** [comment]
UI: main-ee 6d5aa52b
DMS: main-ee 7f35dd7217
SQLE: main-ee 3ad4836671
