### ISSUE TITLE
规则：避免使用 COUNT(COL)，增加对使用子查询结果作为临时列的情况的支持

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2062]
#1983 
**SQLe Version**
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217

**Describe the bug**
sql：
SELECT
    (SELECT COUNT(DISTINCT col1) FROM table_name1 ) AS count1,
    (SELECT COUNT(DISTINCT col2) FROM table_name2 ) AS count2,
    (SELECT COUNT(DISTINCT col3) FROM table_name3 ) AS count3,
    (SELECT COUNT(col3) FROM table_name3 ) AS count4
FROM dual;

**To Reproduce**
预期：触发规则：避免使用 COUNT(COL)

**Comment by winfredLIN** [comment]
### 解决方案
增加规则覆盖率，覆盖了SQL中的子查询

**Comment by hasa1K** [comment]
sqle version: release-2.9999.x d89e154e4f594e72bc7e91d8b0acc72f1d15dc4d
![image](https://github.com/actiontech/sqle/assets/53266479/ba8c263f-aac9-49db-873c-db511aef49f8)
