### ISSUE TITLE
数据源页面，切到非第一分页，搜索任意数据源，结果为空

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2074]
**SQLe Version**
UI Version: main a5fa134
Server Version: release-2.9999.x-ee 9917a24217

**Describe the bug**
数据源举例：
![img_v3_025f_0e42a077-b786-4a0b-8bf5-8dae0f4b530g](https://github.com/actiontech/sqle/assets/44565577/df55d621-2de6-4eac-b9f3-8fd06dc6ccd2)
![img_v3_025f_0753d570-8b0b-43f2-a21c-0d753141272g](https://github.com/actiontech/sqle/assets/44565577/eecfeea2-9632-4ba2-a23b-43a568852351)

切到非第一分页，搜索任意数据源，结果数量比分页数量小，结果都是错误的
有搜索的页面都是这样的表现

**Comment by anny1021** [comment]
测试时：

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 411a376
Server Version: release-2.9999.x-ee 0f9c11c5b8
