### ISSUE TITLE
智能扫描任务支持华为RDS MySQL慢日志类型

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2078]
增加对华为RDS MySQL慢日志的智能扫描任务

**Comment by winfredLIN** [comment]
## 解决方案
调用华为云获取慢日志的接口
## 支持功能
支持智能扫描功能中，选择任务类型为华为云RDS MySQL慢日志
需要输入项目ID、实例ID、Access Key ID、Access Key Secret、拉去日志的时间范围以及当前实例所在的地区
即可获取华为云慢日志
![image](https://github.com/actiontech/sqle/assets/31072467/7c592bb6-b91d-4455-b57f-35260167f16a)

**Comment by winfredLIN** [comment]
## 补充信息
项目ID：实例所在项目ID
实例ID：实例ID
Access Key ID：在步骤3中获取的访问密钥 ID
Access Key Secret：在步骤3中获取的访问密钥Secret
启动慢日志时拉取慢日志时间范围（小时）：由于开启明文显示后，华为云平台会自动删除30天前的日志，所以时间范围上限是30天

访问密钥可以参考
![image](https://github.com/actiontech/sqle/assets/31072467/b64089d3-b5a4-413f-8515-a6ad5ea74060)

实例ID可以参考
![image](https://github.com/actiontech/sqle/assets/31072467/28265f44-66d2-427e-b6ce-d9716de2e26b)

当前API开放的地区可以参考
https://developer.huaweicloud.com/endpoint?RDS
![image](https://github.com/actiontech/sqle/assets/31072467/7e95d5e5-0482-4bb8-af04-f3b5ba6801ed)

项目id和当前API开放的地区也可以参考：
我的凭证-API凭证
![image](https://github.com/actiontech/sqle/assets/31072467/220cc449-3828-48c4-a33b-fa735572b322)

**Comment by quexiuping** [comment]
UI: main-ee 6d5aa52b
DMS: main-ee 7f35dd7217
SQLE: main-ee 3ad4836671
