### ISSUE TITLE
support MySQL lower_case_table_names

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#208]

**Comment by sjjian** [comment]
![4(`8U$H_HHH3GAA3`YX5 IY](https://user-images.githubusercontent.com/18008452/150918105-942c75bf-3934-485d-9625-69f4f3809b27.jpg)

**Comment by sjjian** [comment]
字段大小写支持：
![UHZ)1)J(43LI7SSPZ32 ~I](https://user-images.githubusercontent.com/18008452/150926297-d9cf507d-ae06-40ee-9b6d-823ab267cb23.jpg)
![PPDLNCJ}S(440T@QB}HE}1](https://user-images.githubusercontent.com/18008452/150926311-ca111264-191e-497e-a1bb-5f669dba1581.jpg)

**Comment by sjjian** [comment]
### 社区反馈问题：
when lower_case_table_names=1, if the case of the table name in SQL is inconsistent with that specified during table creation, panic will be caused
## **panic截图**
![3CNM@ JL5 J}J14TPV{K6QT](https://user-images.githubusercontent.com/37464327/149457017-15ad931e-f66b-4f40-a13c-c11d99da7a35.png)

### **复现状态** 
稳定复现

### **触发方式**
1. mysql设置lower_case_table_names=1
2. 创建一个表名小写的表
3. 创建一个新的工单, 工单sql中的表名使用大写(表名就是2中建的表)
4. 点击审核, 发现sqle停止工作

### **原因分析**
sqle中记录的表名是区分大小写的, 但mysql开启了忽略大小写, 导致getCreateTableStmt() 中 i.isTableExist()验证通过, 但i.getTableInfo() 取出的info为nil, 从而导致info.MergedTable触发panic

### **临时绕过办法**
提交工单时保证要审核的sql中的表名大小写跟当时建表时的表名大小写一致即可

**Comment by sjjian** [comment]
https://github.com/actiontech/sqle/issues/258

**Comment by Marcus9530** [comment]
复现版本：
SQLe Version:"release-1.2112.x-ee cc48d26174ad061aefcd600aada7a38a2e5f8ec9"
复现步骤：
1.mysql设置lower_case_table_names=1
2.创建一个表名小写的表
3.创建一个新的工单, 工单sql中的表名使用大写(表名就是2中建的表)
4.点击审核, 出现未知错误请求，复现成功
![image](https://user-images.githubusercontent.com/54339501/155661479-03574753-8a6a-40e9-8778-6dbd21ad1eb6.png)
![image](https://user-images.githubusercontent.com/54339501/155662007-e9450db5-c23a-494d-a253-d6979b778d9e.png)

![image](https://user-images.githubusercontent.com/54339501/155661996-c6cd9806-c57a-4723-88ad-f9cc15231f3e.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 1651c64
Server Version: main-ee 08784304bf
验证步骤：
1.mysql设置lower_case_table_names=1
2.创建一个表名小写的表
3.创建一个新的工单, 工单sql中的表名使用大写(表名就是2中建的表)
4.点击审核, 没有出现未知错误请求，验证成功

![image](https://user-images.githubusercontent.com/54339501/155662418-0a83b75f-ee11-48e2-964f-f3f5dcc36c7d.png)

![image](https://user-images.githubusercontent.com/54339501/155662352-5a4c637c-c2e9-4786-a497-cc9cbce7f7e4.png)

**Comment by Marcus9530** [comment]
补充复现
release-1.2201.x-ee 658ec45d5a
复现步骤
1.创建一个工单，对一个sql语句进行审核，且指定字段为大写，可以看出当字段为大写时提示不存在，为小写时提示存在
![image](https://user-images.githubusercontent.com/54339501/155670734-3c5de830-4e96-4611-9f7f-d76af4e11578.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 1651c64
Server Version: main-ee 08784304bf
验证步骤：
1.创建工单，输入一个sql语句，指定字段大写和小写，然后点击审核，并没有提示大写字段不存在


![image](https://user-images.githubusercontent.com/54339501/155670858-db6c95bd-a4ae-4a92-8705-983b049a4d53.png)
