### ISSUE TITLE
sql管控页面，复制sql指纹到sql指纹搜索框搜索，提示报错

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2100]
**SQLe Version**
UI Version: main 411a376
Server Version: release-2.9999.x-ee 0f9c11c5b8

**Describe the bug**
sql：CREATE TABLE `tasks` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `instance_id` int(10) unsigned DEFAULT NULL,
  `instance_schema` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass_rate` double DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `audit_level` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sql_source` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `db_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'mysql',
  `status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'initialized',
  `group_id` int(10) unsigned DEFAULT NULL,
  `create_user_id` int(10) unsigned DEFAULT NULL,
  `exec_start_at` datetime DEFAULT NULL,
  `exec_end_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tasks_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
![img_v3_025l_1b1dc60d-452c-4233-aa73-1cf27e1dbdcg](https://github.com/actiontech/sqle/assets/44565577/6b6fd988-f184-4979-a150-688e9be9fd62)
![img_v3_025l_5e55d181-2e4c-42f8-aaa3-7563ada3c45g](https://github.com/actiontech/sqle/assets/44565577/3734623b-a3a7-43f8-9f45-492e2573f4b2)

参数信息：

http://127.0.0.1:10000/v1/projects/default/sql_manages?page_index=1&page_size=10&fuzzy_search_sql_fingerprint=CREATE+TABLE+%60tasks%60+(+++%60id%60+int(10)+unsigned+NOT+NULL+AUTO_INCREMENT,+++%60created_at%60+datetime+DEFAULT+CURRENT_TIMESTAMP,+++%60updated_at%60+datetime+DEFAULT+CURRENT_TIMESTAMP+ON+UPDATE+CURRENT_TIMESTAMP,+++%60deleted_at%60+datetime+DEFAULT+NULL,+++%60instance_id%60+int(10)+unsigned+DEFAULT+NULL,+++%60instance_schema%60+varchar(255)+COLLATE+utf8mb4_unicode_ci+DEFAULT+NULL,+++%60pass_rate%60+double+DEFAULT+NULL,+++%60score%60+int(11)+DEFAULT+NULL,+++%60audit_level%60+varchar(255)+COLLATE+utf8mb4_unicode_ci+DEFAULT+NULL,+++%60sql_source%60+varchar(255)+COLLATE+utf8mb4_unicode_ci+DEFAULT+NULL,+++%60db_type%60+varchar(255)+COLLATE+utf8mb4_unicode_ci+DEFAULT+%27mysql%27,+++%60status%60+varchar(255)+COLLATE+utf8mb4_unicode_ci+DEFAULT+%27initialized%27,+++%60group_id%60+int(10)+unsigned+DEFAULT+NULL,+++%60create_user_id%60+int(10)+unsigned+DEFAULT+NULL,+++%60exec_start_at%60+datetime+DEFAULT+NULL,+++%60exec_end_at%60+datetime+DEFAULT+NULL,+++PRIMARY+KEY+(%60id%60),+++KEY+%60idx_tasks_deleted_at%60+(%60deleted_at%60)+)+ENGINE%3DInnoDB+DEFAULT+CHARSET%3Dutf8mb4+COLLATE%3Dutf8mb4_unicode_ci

Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysql', `status` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'initialized'' at line 32

**Comment by hasa1K** [comment]
问题原因：
查询的sql指纹语句携带单引号，导致sql查询发生语法错误
`DEFAULT 'mysql'`
