### ISSUE TITLE
数据库名称带中划线，sql审核报错

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2104]
**SQLe Version**
UI Version: main ad12569
Server Version: release-2.9999.x-ee 0f9c11c5b8

**Describe the bug**
sql审核 选择带了横线的数据库，报错

![image](https://github.com/actiontech/sqle/assets/44565577/c05094f8-c825-47ec-8841-1f4a103252ef)

包括：
扫描任务页面

**Comment by winfredLIN** [comment]
### 原因
在MySQL中，不建议在数据库和列名中包含-，但可以包含-。
如果要使用-，则需要在数据库和列名上添加反引号``，否则MySQL将返回错误
此外，字符串通过双引号""或单引号''进行区分
### 解决方案
在SQLE中对MySQL的请求的SQL中，有必要确保数据库和表名都使用反引号括起``，字符串使用双引号""或单引号''括起

**Comment by quexiuping** [comment]
UI Version: main ad12569
Server Version: release-2.9999.x-ee b19560c258
