### ISSUE TITLE
扫描任务没有触发白名单

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2105]
**SQLe Version**
UI Version: main ad12569
Server Version: release-2.9999.x-ee 0f9c11c5b8

**To Reproduce**
1.sql加入白名单
<img width="1423" alt="image" src="https://github.com/actiontech/sqle/assets/44565577/e3f749cc-7a2b-46a2-af81-d4274b4de2e5">
2.创建扫描任务-立即审核
![img_v3_025l_3e3f0263-1749-491b-8673-eeae21cf018g](https://github.com/actiontech/sqle/assets/44565577/9d2f906f-a82f-425e-a330-b2bb3838d81e)
3.查看审核结果
![img_v3_025l_1b36293f-9e6e-4aad-bef2-21010346e10g](https://github.com/actiontech/sqle/assets/44565577/80444e07-e5c4-4c25-8406-20fa0793ce73)
  预期：sql审核结果：白名单

**Comment by taolx0** [comment]
UI Version: main 5d253059
Server Version: release-2.9999.x-ee 776b76dff1
![20240131163137](https://github.com/actiontech/sqle/assets/63177450/c2703eed-00f3-4f08-90d8-ae5f785f6c2f)
