### ISSUE TITLE
白名单内的sql，动态审核和静态审核的表现不一致

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2107]
**SQLe Version**
UI Version: main ad12569
Server Version: release-2.9999.x-ee 0f9c11c5b8

**To Reproduce**
1.sql加入到白名单内
2.SQL审核-动态审核
显示白名单
![image](https://github.com/actiontech/sqle/assets/44565577/0669dfe2-fe76-46be-af3d-068904202fc6)

3.SQL审核-静态审核
触发了审核规则
![image](https://github.com/actiontech/sqle/assets/44565577/c5dd5933-ebf1-4bff-9c5c-f18653db94ec)

**Comment by rocky114** [comment]
动态审核关联instance，通过instance能够获取project_id，通过project_id获取白名单列表
静态审核没有关联instance，取不到project_id造成取不到白名单列表

![image](https://github.com/actiontech/sqle/assets/13433110/4b6fa441-740c-4d6c-98b4-c96474b57204)

**Comment by rocky114** [comment]
静态审核报错是因公共方法检测instance是否存在，不存在instance返回的错误信息
