### ISSUE TITLE
整体优化MySQL索引建议

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2117]
在客户使用SQL审核的过程中，发现不少关于索引优化建议的问题，检查下来，除了建议本身，代码逻辑上也有优化的地方
因此，我们计划整体优化MySQL索引建议

**Comment by winfredLIN** [comment]
## 解决方案
### 代码结构上
对代码进行了整体重构，使得不同建议相互独立，有利于未来在索引建议上的更新升级

### 优化建议上

- 重新编辑了建议的内容，现在会在建议中指出给出建议针对的SQL内容
- 对于同一SQL和同一张表，现在会给出不同角度的建议，以供使用者参考
- 修复了三星索引建议中，在有排序列的情况下，WHERE等值列会出现在建议的最后一列的错误情况
- 三星索引建议，增加了对SELECT选择的列的判断，增加覆盖索引的判断，结果更符合三星索引设计原则
- 添加函数索引或虚拟列索引的建议，修复了当无法解析mysql版本号时建议不触发的问题
- 对于使用了前缀模式匹配的建议，增加了建议的覆盖率，支持了CONCAT和UPPER函数

**Comment by hasa1K** [comment]
sqle-ee: 925f4b996872577731c4e222dae6b166838962ef
![image](https://github.com/actiontech/sqle/assets/53266479/62ff9f6d-008d-4c5d-81cc-ab2e10e89bd5)
![image](https://github.com/actiontech/sqle/assets/53266479/86ec1990-d6e3-4cda-a2af-5c9f0ecd06f6)
![image](https://github.com/actiontech/sqle/assets/53266479/5e7a77d6-1754-4802-b1b3-487bbe2edbd0)
