### ISSUE TITLE
安装文档-源码安装-编译源码找不到'rgplane/pnpm:8.3.1' 

### ISSUE THREAD

**Issue by SunshineWangz** [actiontech/sqle#2120]
![1701679523530](https://github.com/actiontech/sqle/assets/50853564/f52d4073-60ac-46e7-8590-63a4f3128cbf)

编译源码镜像名称有问题，不是rgplane/pnpm:8.3.1，应该是gplane/pnpm:8.3.1

**Comment by sjjian** [comment]
done
