### ISSUE TITLE
sql审核同步到sql管控页面的数据，通过数据源筛选的结果不应为空

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2122]
**SQLe Version**
UI: main-ee 42bdca9f
DMS: main-ee 7f35dd7217
PROVISION: main 4135bf43ed
SQLE: main-ee 1ff8d69cab

**To Reproduce**
1.sql审核列表的数据通过添加标签同步到sql管控页面
![img_v3_025q_bd160439-4f3f-43a0-bbcc-822414e88d5g](https://github.com/actiontech/sqle/assets/44565577/c0127daa-f63c-4c52-a38f-b64eb50bf9e0)
![img_v3_025q_d2348905-5d6a-4924-bfdf-f7a9e2abe7ag](https://github.com/actiontech/sqle/assets/44565577/384d496e-773b-4a21-bd1f-e342ef8dd948)

2.sql管控页面通过数据源筛选数据

3.预计：有对应的数据展示

4.实际：结果为空
![img_v3_025q_da9356da-7dd1-4e17-a24a-ee07d494635g](https://github.com/actiontech/sqle/assets/44565577/924e11be-b6b5-482f-969c-567f17a45965)

**Comment by rocky114** [comment]
![image](https://github.com/actiontech/sqle/assets/13433110/13c15496-5a32-4509-bf53-f21c6fb61c21)
![image](https://github.com/actiontech/sqle/assets/13433110/49b257b0-2bfc-44c5-8d1d-58752064ad25)

原有GetSQLAuditRecordById方法会获取task, task.instance，v3版instance数据来自dms，InsertOrUpdateSqlManage方法缺失了instanceName
