### ISSUE TITLE
无法审核包含特殊字符的SQL

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2125]
### 现象1 审核报错
打开SQL审核页面，输入包含特殊字符的SQL，如下：
![image](https://github.com/actiontech/sqle/assets/36940986/04114181-70dd-4feb-a906-c27b452f5ddd)

**现象**：审核失败，页面报错

### 现象2 修改工单说明报错
打开一个gong工单，修改审核结果说明
![image](https://github.com/actiontech/sqle/assets/36940986/67889796-858f-47ef-a4e3-59e91090e578)

### 环境说明
SQLE业务库、相关表的字符集均为utf8mb4：
<img width="791" alt="image" src="https://github.com/actiontech/sqle/assets/36940986/7377369c-6e58-48ec-b229-1cdb4466b9dd">

<img width="758" alt="image" src="https://github.com/actiontech/sqle/assets/36940986/be344824-77f8-4d15-a655-6b3aaa4543cc">

## 原因
SQLE连接到元数据库时，使用的connection character set是utf8，不支持部分特殊字符

## 解决方案
SQLE连接到元数据库时，设置connection character set为utf8mb4

**Comment by hasa1K** [comment]
DMS-ee: 6439889b99e2e815592d5fcc9f55ee2e0303f2d6
sqle-ee: v3 b45932a6190e75415fb0f7f5bfacfc5729fb50ce
可以审核带emoji表情字符的sql
![image](https://github.com/actiontech/sqle/assets/53266479/2c0c3010-b167-417f-ac53-5f3dd375cfb2)
