### ISSUE TITLE
创建工单时, 获取数据源时缺失参数, 导致获取的数据源列表异常

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2127]
**SQLe Version**
UI: main-ee 29c44d33
DMS: main-ee 9c1b1d16fb
SQLE: main-ee ec483c2d57

**Describe the bug**
创建工单时, 获取数据源时缺失参数, 导致获取的数据源列表异常

**To Reproduce**

1. 登陆并选择项目进入SQL工单页面
2. 点击创建工单
3. 选择数据源下拉列表
4. 数据源列表异常, 原因为接口请求参数缺失 functional_module=create_workflow

![image](https://github.com/actiontech/sqle/assets/42765421/40f6bc70-45e6-4927-8359-584306e26270)

**Comment by hasa1K** [comment]
DMS-ee: 6439889b99e2e815592d5fcc9f55ee2e0303f2d6
SQLE-ee: v3 e32f03d615e71dde2361edd5ee74adf029240ea6
![image](https://github.com/actiontech/sqle/assets/53266479/c80ca5e4-ffed-43aa-a449-de465e0a9ad0)
