### ISSUE TITLE
使用rpm升级配置文件错误

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2136]
**SQLe Version**
UI: main-ee 6ff91fdf
DMS: main-ee dbfb686496
SQLE: main-ee 2b6a96bccb

**Describe the bug**
使用rpm -Uvh sqle*.rpm 后，旧版本的sqle配置文件被强制更新

**Suggestion**
rpm包升级后能保留原先的配置文件内容

**Comment by quexiuping** [comment]
UI: main-ee 6d5aa52b
DMS: main-ee 7f35dd7217
SQLE: main-ee 3ad4836671
