### ISSUE TITLE
当扫描任务去扫描没有开启审核规则的数据源的时候报错

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2138]
**SQLe Version**
UI: main-ee 5b4d1946
DMS: main-ee dbfb686496
PROVISION: main 4135bf43ed
SQLE: main-ee

**To Reproduce**
1.数据源有且只有一个，但是关闭了审核规则
![image](https://github.com/actiontech/sqle/assets/44565577/58114b3c-0c10-4d56-a101-5018ac2d2339)

2.创建一个关于mysql的扫描任务
![image](https://github.com/actiontech/sqle/assets/44565577/e5895242-5de0-4b7a-a33c-d51605ded587)

报错信息：
    "message": "convert instance error: strconv.ParseInt: parsing \"\": invalid syntax"

**Comment by rocky114** [comment]
扫描任务没有选择数据源，查询数据源参数instance_name==''，取出了instances的第一条数据

**Comment by hasa1K** [comment]
dms: 3c195538e6a1f9c774aafd016ce0371cd24e7bff
sqle: v3 4ebfeaa6dc34fe39f23e649c67422723adcf8dc9
关闭sql审核
![image](https://github.com/actiontech/sqle/assets/53266479/a849cdd2-c2e9-46b9-be76-8eb97e09ec57)
成功创建扫描任务
![image](https://github.com/actiontech/sqle/assets/53266479/95d037dc-b2a1-43c6-8c20-e30b3120bb79)
