### ISSUE TITLE
扫描任务-新建华为云rds慢日志的任务，其中默认的当前API开放的地区删除

### ISSUE THREAD

**Issue by quexiuping** [actiontech/sqle#2141]
**SQLe Version**
UI: main-ee 6d5aa52b
DMS: main-ee 7f35dd7217
SQLE: main-ee 3ad4836671

**To Reproduce**
![image](https://github.com/actiontech/sqle/assets/44565577/af48817c-c376-4f42-89b8-69719c2cf249)

另外：
必填项的标记也打上吧

**Comment by hasa1K** [comment]
v3
dms-ui:c10dabbf64ce4f8f3f84d80603443ec797b7ca02
![image](https://github.com/actiontech/sqle/assets/53266479/cff157e9-1bba-4f8f-a934-b8a3ddae2a38)
