### ISSUE TITLE
审核没有WHERE的SQL，索引优化panic

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2145]
#2117
审核SQL
```bash
SELECT * FROM table_1;
```
索引优化Panic

**Comment by winfredLIN** [comment]
## 解决方案
在给出优化建议前，先判断where存不存在，若不存在，无法给出建议

**Comment by hasa1K** [comment]
开启规则：索引创建建议
审核语句没有where条件，没有发生报错
![image](https://github.com/actiontech/sqle/assets/53266479/3cf1ae5d-fac7-4758-93de-529090d9c32b)
