### ISSUE TITLE
优化索引优化建议的内容展示

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2146]
#2117 
索引优化的内容展示包含SQL，当SQL很长会导致展示内容过多，影响查看

**Comment by winfredLIN** [comment]
## 解决方案
取消在建议中展示SQL，并调整了建议的内容

**Comment by hasa1K** [comment]
DMS-ee: 6439889b99e2e815592d5fcc9f55ee2e0303f2d6
sqle-ee: v3 e32f03d615e71dde2361edd5ee74adf029240ea6
审核建议中已不带sql内容
![image](https://github.com/actiontech/sqle/assets/53266479/5cbee1de-d64e-415d-a355-cd98ccf53ac1)
![image](https://github.com/actiontech/sqle/assets/53266479/61b0497b-cc65-4e89-ad2d-bd703b68cb24)
