### ISSUE TITLE
三星索引建议，增强功能，修复问题

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2154]
#2117 

1. 增加功能：字段区分度低的列不适合建索引， 新增索引区分度小于2则不添加为索引列

1. 修复问题：覆盖索引判断不准：

`SELECT id, col_1, text_col_1,col_2 from table_1 where (col_2 IN (1,2,3,4));`

```
id int primary key
col_1 varchar
text_col_1 text/blob
col_2 int
```

应该给出单列索引建议：`col_2`, 但给出了错误的复合索引建议：`col_1,col_2`

3. 增加覆盖：字段太长不适合建索引，需要增加过滤JSON类型

**Comment by winfredLIN** [comment]
### 解决方案

1. 将in语句的列视为非等值列
2. 从SQL语句中提取列时填充选择性
3. 增加：JSON类型的字段不作为作为索引的一部分
4. 修复：覆盖指数判断不准确的问题
5. 当三星索引建议提供单列索引时，增加了单列索引的显示

**Comment by hasa1K** [comment]
sqle-ee
索引区分度小于2
![image](https://github.com/actiontech/sqle/assets/53266479/95238d27-49ed-4d8b-aeb9-64831d506e22)
![image](https://github.com/actiontech/sqle/assets/53266479/8badaa5c-e298-436b-ad48-bf69ffe945e1)
