### ISSUE TITLE
规则模板详情新增规则名模糊查询

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2155]
![image](https://github.com/actiontech/sqle/assets/42765421/574596f4-3429-4fb1-934a-06441f0fd144)

希望能在规则模板详情页面新增类似查看规则页面中的模糊搜索框

![image](https://github.com/actiontech/sqle/assets/42765421/09ef4508-8cd7-4af3-a389-7d79e6889642)

影响面: 规则管理页面、规则模板页面

**Comment by hasa1K** [comment]
dms-ui:6b1beb0
创建规则模版
![image](https://github.com/actiontech/sqle/assets/53266479/77977d20-bf4a-430d-8959-33e88f7f5093)
修改规则模版
![image](https://github.com/actiontech/sqle/assets/53266479/1c56ba1c-5791-4ea9-8105-0dbe3f15e947)
查看规则
![image](https://github.com/actiontech/sqle/assets/53266479/e38fef1d-a115-4efb-82b1-2843d757f133)
导入规则模版
![image](https://github.com/actiontech/sqle/assets/53266479/b6af424a-804f-4cba-bf0a-6ed83d110869)
