### ISSUE TITLE
sqle v3工单定时上线任务失败

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2157]
修复版本3.2311.2、3.2312.0

**SQLe Version**

**Describe the bug**
工单设置定时上线，上线时间2023-12-15 09：58：00
![image](https://github.com/actiontech/sqle/assets/53266479/cb8de382-44ca-4ef1-97d9-295e0b333e84)
页面表现：
本机时间为09:59:00工单状态没有发生改变，还处于定时上线状态
![image](https://github.com/actiontech/sqle/assets/53266479/d128aca9-216c-4b73-8fa2-6bc8764bbc19)
![image](https://github.com/actiontech/sqle/assets/53266479/7826344b-ac4c-4eba-8962-bc62f57279a2)

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by hasa1K** [comment]
问题原因：
sqled.log存在大量error log，通过log定位到
通过WorkflowSchedule定时上线函数以及sqled.log中的log，可以定位到GetWorkflowDetailByWorkflowId函数出现问题
![image](https://github.com/actiontech/sqle/assets/53266479/22d7b34c-5064-4368-9cd6-f027fcdd2464)
![image](https://github.com/actiontech/sqle/assets/53266479/c7b4e2fe-07f4-43bf-826b-1b3c4c91b255)

GetWorkflowDetailByWorkflowId函数需要传入WorkflowId，但是workflow结构体中的WorkflowId为空导致查询不到需要上线的workflow
![image](https://github.com/actiontech/sqle/assets/53266479/a27fdac8-b538-4c31-9acb-69e060824ff3)

**Comment by ColdWaterLW** [comment]
需要确认v3上还有没有其它在改造时传错参数的地方

**Comment by LordofAvernus** [comment]
# 解决方案：
  问题本质是使用了指定字段查询结果，指定字段中遗漏了后续流程的必要参数（workflow_id）。所以在查询SQL中增加查询字段workflow_id
