### ISSUE TITLE
新增sql审核工单后返回列表，创建的工单直接无了，演示环境也有这个BUG

### ISSUE THREAD

**Issue by lovefqy** [actiontech/sqle#2162]
如题，bug有点多

**Comment by sjjian** [comment]
是点击审核后，在审核结果界面点返回列表吗
![image](https://github.com/actiontech/sqle/assets/18008452/b1dbea0d-6016-4ce8-9e75-1d2d38cdb950)

**Comment by winfredLIN** [comment]
@herofqy

您好，请参照SQLE用户手册中，创建工单部分的四个步骤创建工单
https://actiontech.github.io/sqle-docs/docs/user-manual/project/workflow/create-workflow
在点击`创建工单`和`审核`过后，还需要点击`提交工单`，工单才会创建，若未点击提交工单就返回了，是不会在工单列表中查看到未创建的工单的。
![image](https://github.com/actiontech/sqle/assets/31072467/2b56ed6e-187c-4e19-a555-9f1f39843b45)
