### ISSUE TITLE
当浏览器版本过低时，弹窗提醒客户

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2165]
**Describe**
工单页面需要使用前端queueMicroTask函数接口，在版本过低的浏览器上会发生报错，导致打开工单页面没有显示内容
打开工单页面：
![img_v3_0263_891aa814-7709-4090-8085-de752cd04bag](https://github.com/actiontech/sqle/assets/53266479/70e44dbc-77bf-4945-bc70-f6d74fc24f8b)
报错内容：
![img_v3_0263_20445ac5-6f94-4ab4-9be1-d6109b96febg](https://github.com/actiontech/sqle/assets/53266479/2b88ed77-68af-4b4f-b3f7-b3f7885dcf5e)
queueMicroTask支持的版本
![img_v3_0263_41a5cce4-955a-4014-ac47-3f1b535e244g](https://github.com/actiontech/sqle/assets/53266479/0754dfa9-4e4d-46ae-811a-9f25cc1ab15f)

**Suggestion**
在客户使用sqle时，检测浏览器版本，如果浏览器版本过低时弹窗提醒客户

**Why**

**Comment by Gygkimo95** [comment]
需求预期
* 提示出现场景
  * chrome version<80
  * 使用了非chrome内核的浏览器
* 提示方式：右上角错误提示通知
  * 不区分场景，登录页面也会提示
  * 如果没有关闭，就一直展示
* 提示文字：为了正常使用平台功能，请使用 Chrome 80 或更高版本进行访问。
