### ISSUE TITLE
规则：查询数据量超过阈值，筛选条件必须带上主键或者索引；发生报错Duplicate column name ''

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2175]
**SQLe Version**

**Describe the bug**
开启规则`查询数据量超过阈值，筛选条件必须带上主键或者索引`，进行审核语句时发生报错 `Duplicate column name:clusterType`

从日志中可以看出子查询中存在相同列名导致发生这个报错
![image](https://github.com/actiontech/sqle/assets/53266479/f8ec64ec-b925-4b88-a68e-2ff2e3a4306f)

规则`查询数据量超过阈值，筛选条件必须带上主键或者索引`中会调用`util.GetAffectedRowNum`函数查看被审核语句的sql影响行数。

util.GetAffectedRowNum函数中对存在order by和limit的sql语句采用`select count(*) from (被审核sql) t`的方式获取影响行数

![image](https://github.com/actiontech/sqle/assets/53266479/ac54d47b-cbf8-4509-88be-2fd69ef740db)

### 复现步骤
1. 开启规则:查询数据量超过阈值，筛选条件必须带上主键或者索引
2. 使用带有相同列名并且有limit语句的sql进行审核，发生报错
select id, email as id from users limit 10
![image](https://github.com/actiontech/sqle/assets/53266479/b886d9c7-52f3-4cf7-8839-a49c51d46abf)

### 问题原因
被审核的sql语句包含limit条件，该规则获取影响行数时使用了`select count(*) from (被审核的sql) t`，但是被审核的sql中存在相同的列名导致最后报错`Duplicate column name:clusterType`

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by hasa1K** [comment]
解决方案：
方案一：
检查审核sql中的列名，如果存在相同的列名或别名，修改其别名，在别名后添加`_1`
例如：
`select count(*) from (select id, **workflow_id as id** from workflows limit 0, 10) t`
修改后：`select count(*) from (select id, **workflow_id as id_1** from workflows limit 0, 10) t`

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/sqle/assets/63177450/61418039-5173-45d2-acd8-ab88861495d9)

![20240130161516](https://github.com/actiontech/sqle/assets/63177450/483f802b-d2df-405a-bcba-601cdc90f125)
