### ISSUE TITLE
适配jetbrains插件兼容V3版本SQLE

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2185]
**Describe**
升级jetbrains插件,兼容V3版本SQLE

**Comment by hasa1K** [comment]
sqle-ee:925f4b996872577731c4e222dae6b166838962ef
插件版本:sqle-jetbrains-plugin-v3.2312.1
普通审核
![image](https://github.com/actiontech/sqle/assets/53266479/568f3a55-431f-4312-a79f-47045d9c9d19)
xml审核
![image](https://github.com/actiontech/sqle/assets/53266479/60d050f7-188f-4626-bfc4-858e063ac106)
sql文件审核
![image](https://github.com/actiontech/sqle/assets/53266479/8f401883-3747-42ad-89bb-2f3ec050b5d9)
