### ISSUE TITLE
索引优化-三星索引建议：非等值条件未排除类型不合适的列

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2190]
https://github.com/actiontech/sqle/issues/2154
对于下列SQL，会错误的把`blob_field`作为索引建议中的列
``` SQL
select * from your_table_name where blob_field in ('Name73', 'Name79')
```
建表语句
``` SQL
CREATE TABLE your_table_name (
    id INT PRIMARY KEY AUTO_INCREMENT,
    blob_field BLOB,
    text_field TEXT,
    json_field JSON
);
```

**Comment by winfredLIN** [comment]
## 解决方案
复用判断列类型的函数，在添加非等值条件列时判断

**Comment by taolx0** [comment]
![d-2](https://github.com/actiontech/sqle/assets/63177450/1dd024f1-04a3-4f79-9bdb-8324e0437cca)
![d-1](https://github.com/actiontech/sqle/assets/63177450/9ea4374d-2476-44ee-a36c-a5599781626c)
