### ISSUE TITLE
自动更新模板失败

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2192]
sqle插件规则变化后，会自动更新模板
但未成功更新自定义模板

关联issue #1849

**Comment by iwanghc** [comment]
1.插件规则描述修改后，公共模板和项目模板会同步更新（未复现自动更新模板但未成功更新自定义模板问题）
2.插件规则参数修改后，公共模板和项目模板都未更新
3.插件规则删除后，公共模板和项目模板在模板列表中未同步删除

**Comment by iwanghc** [comment]
历史审核记录中，已删除的规则页面展示效果：
![img_v3_028h_da7b96df-f354-4931-8585-9e487c097f2g](https://github.com/actiontech/sqle/assets/83113746/d8c87c08-bc1b-4608-8de5-9cf348d18b98)

**Comment by winfredLIN** [comment]
## 版本信息
CE：
UI: main db262599
DMS: main e86623c485
SQLE ed64378429
EE：测试SQL审核部分
UI: main fd4bbd8a
DMS: main-ee 144d20f4fd
SQLE: main-ee c0cb926a9f
## 测试计划
功能1：插件已删除的规则同步删除sqle中的公共模板中规则、项目模板中规则、知识库。
  1. 创建项目模板
  2. 添加知识库
  3. 删除插件的部分规则
功能2：历史审核记录中已删除的规则给予页面提示该规则已被删除。
  1. 审核一些SQL
  2. 删除触发的规则
功能3：根据插件规则参数中Key对应到sqle规则参数中的Key，若描述或类型有变化则更新更新描述和类型
  1. 变化描述
  2. 变化类型
功能4：若插件参数中有新的Key，则认为此参数为新增参数，同步新增到sqle规则参数中
  1. 新增key
功能5：删除sqle规则参数数组中不在插件中的参数
  1. 删除key
## 测试内容与结果
删除规则：建议给表添加注释
规则删除后SQL审核结果详情：
![image](https://github.com/actiontech/sqle/assets/31072467/5680a9a1-7e2a-4ebe-b05d-d3816cefd014)
规则删除前，知识库：
![image](https://github.com/actiontech/sqle/assets/31072467/1e7f36fc-454a-420b-a928-3f0413fde6dc)
规则删除后，知识库：
![image](https://github.com/actiontech/sqle/assets/31072467/c2339acf-b3ef-4e9a-bc62-944433cc335e)
规则删除后，SQL工单中审核结果：（需要跟进是否做了这部分的改动）
![image](https://github.com/actiontech/sqle/assets/31072467/cd88229e-ed43-4c90-957c-edf454fb51de)
修改规则描述：建议避免使用select for update
修改为：MODIFY RULE DESC 建议避免使用select for update
![image](https://github.com/actiontech/sqle/assets/31072467/d9b52245-43d6-45f9-b50e-da4148b85717)
![image](https://github.com/actiontech/sqle/assets/31072467/40f2a148-2976-4922-9d1e-85192c2fd562)
规则：From子句中存在多层嵌套 
规则描述：嵌套越深，需要扫描的行数、生成的结果集就越大，SQL的执行效率越低
修改为：MODIFY ANNOTATION 嵌套越深，需要扫描的行数、生成的结果集就越大，SQL的执行效率越低
参数默认值：3
修改为：6 
参数描述：最大嵌套层数
修改为：MODIFY PARAM DESC最大嵌套层数
![image](https://github.com/actiontech/sqle/assets/31072467/f6b2ffd8-e021-4e45-9605-ef9c428c935d)
![image](https://github.com/actiontech/sqle/assets/31072467/59353c44-3cf9-477c-b034-0e01580407c4)
规则：查询的扫描不建议超过指定行数（默认值：10000）
修改类型：params.ParamTypeInt
修改为：ParamTypeBool
修改默认值：10000 
修改为：false
![image](https://github.com/actiontech/sqle/assets/31072467/def4c28f-92c5-4d5a-8241-063c392ccc09)
![image](https://github.com/actiontech/sqle/assets/31072467/e0e217c0-1553-4251-8184-e29525a8410c)
修改规则：表字段不建议过多
修改message：表字段不建议超过%d个，目前有%d个
修改为：MODIFY MESSAGE表字段不建议超过%d个，目前有%d个
![image](https://github.com/actiontech/sqle/assets/31072467/1689c77b-5b74-43ba-abbe-1aa05af06f60)
修改规则：在 DML 语句中预计影响行数超过指定值则不回滚
新增key：
```
&params.Param{
                    Key:   "mix_affected_rows",
                    Value: "9999",
                    Desc:  "NEW KEY 回滚语句影响行数",
                    Type:  params.ParamTypeInt,
                },
```
![image](https://github.com/actiontech/sqle/assets/31072467/ce6406b4-2c8c-4757-b97b-0251dd6dfd82)
![image](https://github.com/actiontech/sqle/assets/31072467/8c97690d-0e1c-4cf4-83b3-c336c615227c)
修改规则：普通索引必须使用固定前缀
删除key：
```
&params.Param{
                    Key:   "expect_index_name_prefix",
                    Value: "idx_",
                    Desc:  "索引前缀",
                    Type:  params.ParamTypeString,
                },
```
新增key：
```
 &params.Param{
                    Key:   "modify_expect_index_name_prefix",
                    Value: "dxii_",
                    Desc:  "索引前缀",
                    Type:  params.ParamTypeString,
                },
```
![image](https://github.com/actiontech/sqle/assets/31072467/7cb02d12-bdba-4ea6-94ed-33c98e07d50d)
![image](https://github.com/actiontech/sqle/assets/31072467/4ca57a6f-7138-4a4e-913e-3f361ecfd602)
