### ISSUE TITLE
规则 使用联合索引时，必须使用联合索引的首字段 误报

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2208]
**SQLe Version**
2.9999.x

**To Reproduce**
对如下的SQL进行审核,会触发规则 使用联合索引时，必须使用联合索引的首字段
![image](https://github.com/actiontech/sqle/assets/63177450/ca922b67-91f6-4687-95af-724aab0a3fc7)

**不应该触发该规则的原因**
age字段已经走了单独的索引 idx_age,此时不使用联合索引的首字段,是符合逻辑的,不应该报错
![image](https://github.com/actiontech/sqle/assets/63177450/1a85f4ed-61dc-4eea-a2aa-f9c9f349bd87)

**Expected behavior**
不触发

**Comment by hasa1K** [comment]
### 解决方案
规则：使用联合索引时，必须使用联合索引的首字段
在代码中，在判断是否使用联合索引首字段时，遇到单列索引会直接跳过
![image](https://github.com/actiontech/sqle/assets/53266479/09b02185-db0f-435e-bf8d-6a37c4a2ff43)

现改为：遇到单列索引进行判断是否使用了单列索引，如果使用不触发规则

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/sqle/assets/63177450/8e04a3f5-381a-4e6e-8dda-1ad8b0a41583)

![20240130155628](https://github.com/actiontech/sqle/assets/63177450/cf138eac-92c8-4516-8ed6-8b88feac8edc)
