### ISSUE TITLE
新增Eclipse审核插件

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2215]
**Describe**
开发eclipse编辑器的插件进行sql审核，功能需要与idea插件功能一致

- [ ] 选中需要审核的SQL, 可以同时选中多条SQL.点击右键, 选中 [SQLE] - [Audit] , 也可以使用快捷键 [Ctrl] + [Shift] + [H], 插件会以弹窗的形式将审核结果进行展示
- [x] 审核mybatis xml文件,选中mybatis xml文件,鼠标右击点击 MyBatis Audit
- [x] 审核sql文件,选中sql文件,鼠标右击点击 SQL file Audit

**插件代码**
https://github.com/actiontech/sqle-eclipse-plugin

**Comment by ColdWaterLW** [comment]
插件代码仓库  https://github.com/actiontech/sqle-eclipse-plugin

**Comment by hasa1K** [comment]
# 关于Eclipse插件如何适配MyEclipse编辑器
## Java版本
Eclipse插件最高支持Java SE22版本，但是MyEclipse最高仅支持Java SE17版本，需要使用Java17版本进行开发插件
## 关于第三方库
引用了gson，json-java和lombok三个第三方库
gson和lombok都使用官方下载的jar包，适配Java22和17版本
json-java需要手动编译jar包，所以需要使用Java17进行编译

**Comment by taolx0** [comment]
## 版本
![image](https://github.com/actiontech/sqle/assets/63177450/8c934d3d-8ca2-4b50-9ee0-6f3791fdeaf3)

## 验证
![image](https://github.com/actiontech/sqle/assets/63177450/5883312a-264f-4e80-9cf6-eaf1536dfca0)
![image](https://github.com/actiontech/sqle/assets/63177450/8ec73202-a7e1-42b1-9844-c46641f66d3f)
![image](https://github.com/actiontech/sqle/assets/63177450/57775a49-d1c5-4485-811c-63355c47dd99)
