### ISSUE TITLE
SQL审核权限校验逻辑调整

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2220]
## 背景
   SQL审核功能存在静态审核，静态审核无法收到数据源权限管控，会导致权限校验panic.考虑调整SQL审核的权限控制

**Comment by hasa1K** [comment]
目前sqle的权限范围的维度是数据源，静态审核不会绑定数据源。现在在获取sql审核记录前会判断task是否绑定数据源，未绑定数据源不做权限校验，符合预期。
