### ISSUE TITLE
MySQL审核的问题SQL定位到行数

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2222]
### 需求1
当审核的SQL来源是文件时，根据审核结果不容易定位到文件里的内容，所以将问题SQL的定位详细到文件的行数
![img_v3_0276_122b918b-0f34-4065-9542-0bef56ccda0g](https://github.com/actiontech/sqle/assets/36940986/ebd93149-1155-4632-b136-9a65e1230beb)

### 需求2
完善所有上传方式的SQL定位信息：
1. 单个SQL文件或XML文件上传时，也支持展示上传的文件名

相关issue：https://github.com/actiontech/sqle/issues/2054

## 目标
1. 在查看SQL审核、工单审核的SQL审核结果时增加展示SQL行号
2. 所有SQL上传方式（包括页面输入）支持展示行号
3. 单个SQL文件或XML文件上传时，也支持展示上传的文件名，通过页面输入的SQL文件名显示“-”

### HTTP接口
/v2/tasks/audits/{task_id}/sqls [get] 新增返回字段sql_start_line
当sql_start_line字段值为0时，展示“-”

### SQL文件定位
修改语法解析器，将每条SQL的起始行号记录到语法树

### XML文件定位
1. 修改xml解析器，将select、delete、update、insert类型的元素ID所在的行号记录为对应SQL的行号
4. 在解析器接口中返回行号

#### SQL审核页面功能
需要验证所有方式上传的SQL是否能完整解析
#### 工单
需要验证创建工单前，对所有方式上传的SQL使用自动审核，是否能完整解析
#### SQL展示顺序
在审核结果中，SQL展示顺序发生变化。如果是审核ZIP或GIT仓库，同时包含SQL文件、Java文件、XML文件，展示的SQL按来源文件排序：SQL文件、Java文件、XML文件

**Comment by taolx0** [comment]
UI: main aeee2f9d
DMS: main-ee 19ee2c1ea2
SQLE: main-ee 342c635080

![20240131101556](https://github.com/actiontech/sqle/assets/63177450/88b89241-f7f0-4713-9950-f27e0cd506e2)
