### ISSUE TITLE
使用sqle审核mysql含有子查询的sql后台出现panic

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2231]
**SQLe Version**
main-ee 5da439b28d06a6d75ce8dc9cb02192f0d11732b2

**Describe the bug**
使用sqle审核时，使用mysql语句where in中含有子查询的sql时后台出现panic
（当in中子句表作为驱动表时）

**To Reproduce**
表结构：
![image](https://github.com/actiontech/sqle/assets/83113746/8b02eb57-c85f-4fb0-9b68-66d9ce768a19)
1、创建工单
2、输入选择数据库sql并输入sql语句SELECT  * FROM  fruits WHERE  name IN (    SELECT      md5 (c)    FROM      t16  );
3、点击审核
![image](https://github.com/actiontech/sqle/assets/83113746/245bf7b7-237a-47d1-bbab-f369f11b4ab9)

**Expected behavior**
返回审核结果

**Suggestion**
提示报错，查看后台出现panic
![image](https://github.com/actiontech/sqle/assets/83113746/ac0b3221-1e24-4d06-8922-783710de1cdc)

`goroutine 128 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/actiontech/sqle/sqle/server.hookAudit.func1()
	/home/sqledevelop/ee/sqle-ee/sqle/server/audit.go:125 +0x5e
panic({0x22b9780, 0x459f2d0})
	/usr/local/go/src/runtime/panic.go:890 +0x267
github.com/actiontech/sqle/sqle/driver/mysql.(*threeStarIndexAdvisor).Enter(0xc001426000, {0x28364d0, 0xc0005c8240})
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/advisor.go:518 +0x248
github.com/pingcap/parser/ast.(*PatternInExpr).Accept(0xc0005c8240, {0x2823b28, 0xc001426000})
	/home/sqledevelop/ee/sqle-ee/vendor/github.com/pingcap/parser/ast/expressions.go:742 +0x83
github.com/actiontech/sqle/sqle/driver/mysql.(*threeStarIndexAdvisor).extractColumnInSelect(0xc001426000)
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/advisor.go:424 +0xf5
github.com/actiontech/sqle/sqle/driver/mysql.(*threeStarIndexAdvisor).GiveAdvices(0xc001426000)
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/advisor.go:340 +0x265
github.com/actiontech/sqle/sqle/driver/mysql.optimize(0xc00034c9a0, 0xc00041cf80, {0x2836950, 0xc001304ea0}, {0xc001264f90, 0x2, 0x2})
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/advisor.go:53 +0x234
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).audit(0xc001684900, {0x282e968, 0xc0001b8028}, {0xc001318d20, 0x53})
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/mysql.go:376 +0x1311
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).Audit(0xc001684900, {0x282e968, 0xc0001b8028}, {0xc0012782d0, 0x1, 0x1})
	/home/sqledevelop/ee/sqle-ee/sqle/driver/mysql/mysql.go:285 +0x252
github.com/actiontech/sqle/sqle/server.hookAudit(0xc0003fa3f0, 0xc0002e0e00, {0x2840a80, 0xc001684900}, {0x2823f60, 0x463d6c8}, {0x463d6c8, 0x0, 0x0})
	/home/sqledevelop/ee/sqle-ee/sqle/server/audit.go:193 +0x6c3
github.com/actiontech/sqle/sqle/server.audit(0xc0003fa3f0, 0xc0002e0e00, {0x2840a80, 0xc001684900}, {0x463d6c8, 0x0, 0x0})
	/home/sqledevelop/ee/sqle-ee/sqle/server/audit.go:108 +0xab
github.com/actiontech/sqle/sqle/server.(*action).audit(0xc00045e900)
	/home/sqledevelop/ee/sqle-ee/sqle/server/sqled.go:295 +0xe8
github.com/actiontech/sqle/sqle/server.(*Sqled).do(0xc000337360, 0xc00045e900)
	/home/sqledevelop/ee/sqle-ee/sqle/server/sqled.go:177 +0x71
github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop.func1()
	/home/sqledevelop/ee/sqle-ee/sqle/server/sqled.go:165 +0x45
created by github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop
	/home/sqledevelop/ee/sqle-ee/sqle/server/sqled.go:164 +0x171`

**Comment by winfredLIN** [comment]
## 问题的实际原因
三星索引中判断SELECT语句中列是否属于驱动表时，由于该SQL的驱动表在子查询中，不在SELECT语句的最上面层级，导致将name列误判为驱动表中的列，去驱动表中获取该列后，导致panic
## 解决方案
1. 修复了三星索引中，判断列是否属于驱动表，判断错误的问题
2. 修复了三星索引中，`SELECT *`时，判断`*`对应的表错误的问题
3. 对于SELECT语句，最上层级未引用驱动表时，不再给出三星索引建议
## 判断列属于驱动表的推导过程
![image](https://github.com/actiontech/sqle/assets/31072467/57220dd2-9d3f-438c-bcbc-87510f1a476b)

**Comment by iwanghc** [comment]
UI: main a90486ba
DMS : main ff4e0d4

### 问题复现
SQLE : main https://github.com/actiontech/sqle/commit/5da439b28d06a6d75ce8dc9cb02192f0d11732b2
新建sql审核
填入sql语句（保证子查询的表为驱动表）
![image](https://github.com/actiontech/sqle/assets/83113746/ef717fca-0702-413a-a5d4-8c2c95d87617)
![image](https://github.com/actiontech/sqle/assets/83113746/b9cb68da-3d6a-47d0-8812-63f4a03c4cbb)
点击审核
页面出现报错，后台panic
![image](https://github.com/actiontech/sqle/assets/83113746/321d074e-c414-4b48-b337-550e217ef8e9)
![image](https://github.com/actiontech/sqle/assets/83113746/3ec0dad8-5910-42f3-8844-1c4a5125ee79)

### 修复验证
SQLE : main a4c4a111
新建审核，填入子查询表为驱动表的sql语句
![image](https://github.com/actiontech/sqle/assets/83113746/6ad4821b-bbe2-49b2-8fe9-35085f56ed82)
![image](https://github.com/actiontech/sqle/assets/83113746/e85d3b64-8980-4639-8d8a-bf47059ef30b)
点击审核，获取审核结果正常
![image](https://github.com/actiontech/sqle/assets/83113746/5902045c-5edb-40a0-8dff-b37475b4faa0)
同样的sql创建工单
![image](https://github.com/actiontech/sqle/assets/83113746/194fb063-e8b3-471f-b6f4-82a784c74428)
点击审核，工单获取审核结果正常
![image](https://github.com/actiontech/sqle/assets/83113746/6a03e692-7801-4f93-961f-2b8048216d20)

验证点：
语句为子查询、驱动表为子表的sql
sql审核
sql工单，提交审核
