### ISSUE TITLE
优化项目中长SQL语句的展示

### ISSUE THREAD

**Issue by anny1021** [actiontech/sqle#2233]
如题:
更换的模块有：
- 扫描任务-任务详情
  现状：
![image](https://github.com/actiontech/sqle/assets/42765421/3af6fce1-0bae-476b-8672-8e777961420a)
  预期：
![image](https://github.com/actiontech/sqle/assets/42765421/055b3d4c-67c1-4be6-904d-ff327737e26d)

- SQL上线工单、扫描任务对应的SQL分析页面，预计效果如上

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/sqle/assets/63177450/ef77cca5-0093-48be-850c-62b133630cff)
![20240130151744](https://github.com/actiontech/sqle/assets/63177450/39bde3da-37d2-42a0-9fc3-43a4dce19d6c)
![20240130151819](https://github.com/actiontech/sqle/assets/63177450/57d241ef-d971-43c2-a84b-5427a6bb11b2)
