### ISSUE TITLE
SQLE工单的Webhook支持携带更多信息

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2238]
SQLE工单中Webhook的可以将工单的一些基础信息推送给其他服务，这些服务再根据这些信息做相应的业务处理。为了帮助Webhook对接的服务进行更多的业务处理，可以开放更多工单相关的信息，从Webhook传递出去。
### 建议增加的信息有

1. 工单对应数据源实例基础信息
2. 创建工单的用户基础信息
3. 工单中SQL的基础信息

**Comment by winfredLIN** [comment]
### 主要改动
工单的webhook增加了一些返回信息，包括：
1. 三方用户信息
2. 当前阶段id
3. 数据源信息
4. 工单审核任务id
5. 工单描述
6. 工单包含的sql类型
### 需要测试验证的内容
1. 工单webhook是否包含上述内容

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/sqle/assets/63177450/78365241-1a21-45b7-b432-4eab1496966e)

![image](https://github.com/actiontech/sqle/assets/63177450/90319e00-7bf8-429e-92a7-e01889da5caf)

**Comment by winfredLIN** [comment]
https://github.com/actiontech/sqle-ee/issues/1367
