### ISSUE TITLE
安装部署问题

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2242]
# 场景一：
1. docker部署的配置文件重写了一份配置，导致配置变更需要同时修改多处代码。
2. docker部署将config.yml文件作为配置文件，与rpm部署的方式不统一

## 预期
 将docker部署的配置文件 在rpm打包后的config.yaml 基础上做变更，统一了配置来源和配置文件位置

### 修复前：
   - [使用docker 镜像安装sqle容器](https://actiontech.github.io/sqle-docs/docs/deploy-manual/Docker)
   - 查看配置文件   
![img_v3_027l_bb67bbc2-2a52-470d-9c3f-c7110cb683fg](https://github.com/actiontech/sqle/assets/24822803/1d3dbce5-502a-43f0-9ffd-1d1c57ab1020)

### 修复后
   - [使用docker 镜像安装sqle容器](https://actiontech.github.io/sqle-docs/docs/deploy-manual/Docker)
   - 查看配置文件 
![8ef71c5d-9c7d-461d-abd4-bf290bde4c4c](https://github.com/actiontech/sqle/assets/24822803/39d6f515-dae2-4c30-9958-3d0a6feb69a0)

# 场景二：
dms出现异常退出场景下，没有异常退出的日志（包括docker安装和rpm安装）

## 预期
dms出现异常退出，将错误信息输出到统一文件下std_dms.log

### rpm方式
1.   将配置文件config.yaml 属主修改为root/root
2.   使用systemctl 重新启动dms【systemctl restart dms】
3.    进程启动失败后，查看std_dms.log

### docker 方式
1.   将配置文件config.yaml 属主修改为root/root
2.   重启docker【docker restart sqle-server]
3.    进程启动失败后，登入容器查看std_dms.log

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/sqle/assets/63177450/b37ff86e-28a1-4c98-955f-82ffa5e2ac40)
