### ISSUE TITLE
开放企业版sql分析功能

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2249]
**Describe**
开放企业版sql分析功能
SQL分析，涉及以下功能模块

- [x] 扫描任务
- [x] 工单
- [x] SQL审核
- [x] sql管控

**Suggestion**

**Why**

**Comment by iwanghc** [comment]
### SQL审核：
![image](https://github.com/actiontech/sqle/assets/83113746/5d3146a8-12fd-4bcf-a2d1-76f24afefced)
分析结果：
![image](https://github.com/actiontech/sqle/assets/83113746/94cc09ba-248e-4517-aa28-0fc9c27070ba)

### 工单：
![image](https://github.com/actiontech/sqle/assets/83113746/bce5a4c8-1d3b-4e7a-bba9-5f631e507d69)
分析结果：
![image](https://github.com/actiontech/sqle/assets/83113746/59631d6f-b46d-4a79-90e7-961fb963f984)

**Comment by iwanghc** [comment]
UI: main a90486ba
DMS: main ff4e0d4
SQLE: main a4c4a111

问题点修复验证
智能扫描：
mybatis扫描
![image](https://github.com/actiontech/sqle/assets/83113746/5a0edf89-a740-4129-9a7a-7cf62721c11b)
慢日志：
![image](https://github.com/actiontech/sqle/assets/83113746/59a0e25d-df01-41b5-a8f9-2ba2b7e505b6)
分析结果：
![image](https://github.com/actiontech/sqle/assets/83113746/a8e0d5f9-c857-40cf-b326-52714992e910)
库表元数据：
![image](https://github.com/actiontech/sqle/assets/83113746/5ac0ab00-3a92-45d8-ab2c-2b87dbf72490)
验证点
智能扫描：mybatis扫描审核结果页面、慢日志审核结果页面、库表元数据扫描审核结果页面
