### ISSUE TITLE
When creating or modifying the sql statement of the work order from the wrong audit level to normal, it still cannot be submitted

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#225]
**SQLe Version**
sqle-ui: main - 9055e77

**Describe the bug**
When creating or modifying the sql statement of the work order from the wrong audit level to normal, it still cannot be submitted

**To Reproduce**
1. 
![image](https://user-images.githubusercontent.com/42765421/150262813-c4218a92-5aec-4535-8860-d4b0ce610be5.png)
2. 
![image](https://user-images.githubusercontent.com/42765421/150262895-309989dc-1a4c-4ea4-b933-6a4f10e42904.png)
3. 
![image](https://user-images.githubusercontent.com/42765421/150262915-d6ce7bda-29c6-4865-ace9-9ef1b455be7f.png)
4.
![image](https://user-images.githubusercontent.com/42765421/150262962-cf8a0187-3839-485a-9166-851b8b6a9041.png)
5.
![image](https://user-images.githubusercontent.com/42765421/150263090-33a7c952-26c0-4ce1-943d-78358538b0ee.png)

**Expected behavior**
When the audit level meets the conditions, the button state should be restored.

**Comment by Marcus9530** [comment]
该现象为中间版本的现象，无法复现，故直接验证

验证版本：
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 658ec45d5a

验证步骤：
1.创建工单，输入一个能够触发error级别的sql语句点击审核之后，无法创建工单
2.然后换另一个sql语句不会触发error级别的sql语句，然后可以创建工单
![image](https://user-images.githubusercontent.com/54339501/155684167-671f71c3-3755-43c1-9aeb-0b9426a73cd1.png)
![image](https://user-images.githubusercontent.com/54339501/155684212-f20471a1-ce2a-45b0-82ae-335d4e2eb988.png)
