### ISSUE TITLE
翻页和扫描中止问题

### ISSUE THREAD

**Issue by windking1125** [actiontech/sqle#2254]
**SQLe Version**
main 1ba554527d4320646c7bb29a0bb14996f87b5fb0

**Describe the bug**
1.sql审核页面，审核结果无法翻页
2.执行sql审核时（扫描mybatis文件），异常中止：failed to upload sql: audit result error

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by winfredLIN** [comment]
## 补充信息
问题1
现象：SQL审核结果有4页，翻到第四页后再点前面几页就点不动了
尝试：刷新浏览器缓存，解决不了，分页控件都点不动
浏览器版本：
![Uploading 2e8655a5fbf2644ea51aec824e88a44.png…]()
UI: main aeee2f9d

**Comment by winfredLIN** [comment]
@windking1125
## 问题2
执行sql审核时（扫描mybatis文件），异常中止：failed to upload sql: audit result error
## 排查方案
可以尝试，使用scanner时加上 skip-audit=true，不在扫描阶段审核

**Comment by winfredLIN** [comment]
1. 问题1，未能复现
2. 问题2，报错的原因是sql审核不通过因此不上传，需要添加skip-audit=true来跳过在采集时的审核
