### ISSUE TITLE
钉钉审批点击拒绝，sqle发生panic

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2255]
**SQLe Version**

**Describe the bug**
1. 配置钉钉审批流程
![image](https://github.com/actiontech/sqle/assets/53266479/ffea1cff-5eee-46a5-b025-bd599909616c)
2. 创建工单
![image](https://github.com/actiontech/sqle/assets/53266479/a9dfcf43-135b-4238-b5b2-56f8f3b32021)
3. 钉钉驳回审批
![image](https://github.com/actiontech/sqle/assets/53266479/18bc193d-0dd5-4b40-af4a-51778ecb30b1)
4. sqle发生panic
![image](https://github.com/actiontech/sqle/assets/53266479/7ca13d19-7eb5-455b-ad8e-a4cb0ae779aa)

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by hasa1K** [comment]
问题原因：
钉钉审批流程中，在钉钉上将工单拒绝后，会将工单的`CurrentWorkflowStepId`设置为0
![image](https://github.com/actiontech/sqle/assets/53266479/ccfdb502-fc15-4cc2-88df-c90a143d7993)
webhook模块在发生工单请求时，会将`CurrentStep.ID`值添加在请求体中。但是被钉钉拒绝后的工单，`CurrentWorkflowStepId`的值已经为0，导致发生panic
![image](https://github.com/actiontech/sqle/assets/53266479/a2eab336-68ea-4ba0-882b-41220f2e917d)

**Comment by winfredLIN** [comment]
## 补充
该问题，在通过后，点击批量上线、工单驳回会发生panic
![image](https://github.com/actiontech/sqle/assets/31072467/3a780b3d-5bd3-4d6c-90b1-9c97cff84f3a)
或者在审核节点点击全部驳回也会发生panic
![image](https://github.com/actiontech/sqle/assets/31072467/665d0d36-c0c1-4bc9-9f31-f8c0dbc5aefe)

**Comment by iwanghc** [comment]
说明：由于新社区版sqle已移除对接钉钉功能，以下测试由企业版进行
UI: main ee c771ee92
DMS: main ee 186d7ef

开启钉钉审批
![image](https://github.com/actiontech/sqle/assets/83113746/e82f5ab4-e702-401d-887e-6814ba3b781f)

问题复现### 
SQLE: main ee 29107df
执行全部驳回：
![image](https://github.com/actiontech/sqle/assets/83113746/1188d396-2807-4d79-943e-348d30ed0bd6)
![image](https://github.com/actiontech/sqle/assets/83113746/52ef0811-1b60-4196-af20-f63db7616755)
![image](https://github.com/actiontech/sqle/assets/83113746/139eb279-58f6-4b57-96bb-f41d80a45ceb)
![image](https://github.com/actiontech/sqle/assets/83113746/d744bb9f-a910-49bc-86fc-d655fc386b32)
执行批量上线
![image](https://github.com/actiontech/sqle/assets/83113746/4ef477e5-73e3-4dda-bfde-60a0b1e31418)

程序报错退出：
![image](https://github.com/actiontech/sqle/assets/83113746/84d0347b-937a-48ed-b177-e405799f29af)

### 修复验证：
SQLE: main ee c0cb926a9
执行驳回
![image](https://github.com/actiontech/sqle/assets/83113746/c928ca8a-1dca-4b01-9be9-e676ba3ab1ec)
驳回成功后台无异常
![image](https://github.com/actiontech/sqle/assets/83113746/75aba8ea-0f56-46b1-9f72-b579c5964aca)
审批通过后驳回
![image](https://github.com/actiontech/sqle/assets/83113746/c77a3aea-b037-4cab-bae7-3b445703bd48)
驳回成功后台无异常
![image](https://github.com/actiontech/sqle/assets/83113746/de886ec9-5992-4ea1-9816-0d80d1d8246e)
批量上线成功
![image](https://github.com/actiontech/sqle/assets/83113746/22381aff-53da-4ca3-af69-1b7d8bc59b5d)


验证点：
工单创建提交后驳回
工单审批通过后驳回
批量上线

**Comment by hasa1K** [comment]
## 解决方案
在发生webhook请求前，校验当前工单步骤，如果工单步骤为nil，手动赋予`0`值
