### ISSUE TITLE
When index optimization is started, panic will be caused when the select statement forms multiple tables

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#226]
**SQLe Version**
all

**Describe the bug**
select * from 多个表的时候会panic

**To Reproduce**
1. 打开索引优化规则
2. 在工单sql处填写 select * from table1, table2; 表名根据实际情况调整
3. 点击审核, 发现sqle停止工作

**Expected behavior**
不应该停止工作

**Suggestion**
经初步排查,这是由于索引优化前会检查表是否在数据库中(关键词: exist, err := i.Ctx.IsTableExistInDatabase(ss.From.TableRefs.Left.(*ast.TableSource).Source.(*ast.TableName))) , 当select 多张表时, Left 的类型为 *ast.Join, 而非 *ast.TableSource , 从而导致类型断言失败panic

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 658ec45d5a
复现步骤：

1.打开索引优化规则
2.在工单sql处填写 select * from table1, table2; 表名根据实际情况调整
3.点击审核, 发现sqle停止工作

![image](https://user-images.githubusercontent.com/54339501/155475469-d9b5e473-86d1-4183-a173-c341f3aefe76.png)

![image](https://user-images.githubusercontent.com/54339501/155475447-002d22cd-e47c-408e-880d-85103801b60c.png)
![image](https://user-images.githubusercontent.com/54339501/155475550-8f62ac1d-54d9-444d-9034-be31decf89a1.png)
![image](https://user-images.githubusercontent.com/54339501/155475557-12b604b9-c399-4604-81bf-9cad9e625d19.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 1651c64
Server Version: main-ee 8066a53e88

验证步骤：

1.打开索引优化规则
2.在工单sql处填写 select * from table1, table2; 表名根据实际情况调整
3.点击审核, 正常对sql语句进行审核且sqle并未重启

![image](https://user-images.githubusercontent.com/54339501/155475688-506b7391-1ce9-4c54-91ad-3321b3fe60f7.png)
![image](https://user-images.githubusercontent.com/54339501/155475764-d5a62e4b-91f4-4dbc-9416-fd0964dcfb51.png)
![image](https://user-images.githubusercontent.com/54339501/155475813-3e13540d-c4a9-449c-bc10-7ceb55a58237.png)
![image](https://user-images.githubusercontent.com/54339501/155475830-f75b384a-3f05-4b8c-8194-cf94bfef6b1e.png)
