### ISSUE TITLE
社区版前端页面调整

### ISSUE THREAD

**Issue by zzyangh** [actiontech/sqle#2261]
**Describe**

issue：https://github.com/actiontech/sqle/issues/2252
社区版删除以下功能：

- [x] 审批流程模板
- [x] 钉钉流程对接（合并钉钉与飞书社区版描述文案）

审批流程具体改动：
隐藏修改审批流程模板按钮
![image](https://github.com/actiontech/sqle/assets/39512256/e7ef40e3-f1c9-40b9-bda3-135f9e8e961d)
引导页中配置审批流程模板改为查看审批流程模板
![image](https://github.com/actiontech/sqle/assets/39512256/e3f50508-24f9-45aa-8e10-3139964606c4)

issue： https://github.com/actiontech/sqle/issues/2249
开放企业版sql分析功能，前端页面涉及以下功能模块

- [x] 扫描任务
- [x] 工单
- [x] SQL审核

**Suggestion**

**Why**

**Comment by iwanghc** [comment]
开放sql分析测试验证：https://github.com/actiontech/sqle/issues/2249
