### ISSUE TITLE
编辑审核规则模板时，规则搜索结果不符预期

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#2274]
**SQLe Version**
UI: main-ee 2f3305df
DMS: main-ee 90e25f49f7
PROVISION: main 1597dd5d2b
SQLE: main-ee 47ba2b1a56

**Describe the bug**

1. 编辑规则模板的情况
已有规则模板，点击编辑
![image](https://github.com/actiontech/sqle/assets/113898890/d4613ec5-1829-49ee-b6b2-eb62ad323053)
禁用全部规则后，启用规则“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”
![image](https://github.com/actiontech/sqle/assets/113898890/0cdaa036-8978-4ce3-ae07-9bb2cbe5e704)
输入关键词where，查询结果为空，不符合预期
![image](https://github.com/actiontech/sqle/assets/113898890/6a3afd9e-8644-4f7a-b952-bdc806a5ed18)

2. 创建规则模板的情况
点击创建规则模板
禁用全部规则后，启用规则“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”
![image](https://github.com/actiontech/sqle/assets/113898890/c9284ef7-9b72-4368-887c-c76a0168986a)
输入关键词where，查询结果有8个，不符合预期
![image](https://github.com/actiontech/sqle/assets/113898890/6e389869-8695-46e1-ac74-845b8c6fcf73)

**Comment by iwanghc** [comment]
DMS ee: main https://github.com/actiontech/dms-ee/commit/144d20f4fd76edcc14dcadce4e329130e812565f
SQLE ee: main c0cb926a9

### 问题复现：
UI: main f676b972
**编辑模板**
![image](https://github.com/actiontech/sqle/assets/83113746/21036441-ef9c-4866-a3be-80ae9737e229)
禁用全部规则
![image](https://github.com/actiontech/sqle/assets/83113746/daf8fca2-9379-440b-ba48-6a7c22e5abb4)
启用“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”规则
![image](https://github.com/actiontech/sqle/assets/83113746/9e301707-4181-4863-8b0a-3cf3b43067f9)
搜索where 结果为空
![image](https://github.com/actiontech/sqle/assets/83113746/4d926546-d35c-4210-8583-40a993b34334)
**新增模板**
禁用全部规则并搜索where
![image](https://github.com/actiontech/sqle/assets/83113746/b1bb6734-7d99-4b34-aed9-9b16187730db)
![image](https://github.com/actiontech/sqle/assets/83113746/fe8bd223-6ac2-4b4b-a243-e5e476c9d049)
### 修复验证
UI: main a90486ba
编辑模板禁用全部规则
![image](https://github.com/actiontech/sqle/assets/83113746/b1cf8b79-d32b-47c8-9d64-57ebb7455c3c)
启用“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”规则，搜索where
![image](https://github.com/actiontech/sqle/assets/83113746/668df116-7153-48b5-be83-7727e2ccad0a)
![image](https://github.com/actiontech/sqle/assets/83113746/add6efcc-f46c-4bd0-88df-8df4330f3b5f)
创建模板
禁用全部规则并启用“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”规则
![image](https://github.com/actiontech/sqle/assets/83113746/c7b8bb70-6f6e-4757-85f4-99af9679f93f)
搜索where，启用列表显示正常
![image](https://github.com/actiontech/sqle/assets/83113746/89ffeed2-c81d-457c-aabc-ffd3a5c6ad24)
禁用列表显示正常
![image](https://github.com/actiontech/sqle/assets/83113746/6504bf34-a182-42e9-a124-5fa408de1b7f)

验证点
创建模板、编辑模板分别测试
规则在全禁用情况下启用某条规则，然后搜索
规则在启用情况下，禁用再启用某条规则，然后搜索
启用规则页面
禁用规则页面
