### ISSUE TITLE
scanner请求接口发送给dms

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2276]
**Describe**

scanner将请求都发送至sqle端口，目前遇到客户在部署sqle时，只暴露了dms端口没有暴露sqle端口，导致无法使用scanner。
现在将scanner修改为往dms服务发送请求再由dms进行转发至sqle。

**Suggestion**

**Why**

**Comment by hasa1K** [comment]
scanner使用说明修改
![image](https://github.com/actiontech/sqle/assets/53266479/456c7ae2-5b08-44d4-9f1d-e762a9d5c8c6)

**Comment by iwanghc** [comment]
UI: main c771ee92
DMS: main e86623c
SQLE: main https://github.com/actiontech/sqle/commit/9eb009be16511755aa8429ba48307067c1eb20a2

编译scannerd：
![image](https://github.com/actiontech/sqle/assets/83113746/2b935244-09c0-4fc1-8c3e-969a830eb9c7)

### 问题点：
执行扫描mybatis文件提示401
![image](https://github.com/actiontech/sqle/assets/83113746/c3f9ca6f-fbe7-4a5c-a309-78dc404a73e1)

**Comment by iwanghc** [comment]
修复：https://github.com/actiontech/dms/issues/223
