### ISSUE TITLE
社区版的页面形态对比修改

### ISSUE THREAD

**Issue by zzyangh** [actiontech/sqle#2287]
**Describe**

社区版的页面形态对比需要替换跳转链接：点击立即申请，跳转链接变更为  https://www.actionsky.com/sqle?question=true
![img_v3_028h_3627e6ff-490a-459a-8767-5beddd98adeg](https://github.com/actiontech/sqle/assets/39512256/a02f63ea-d30a-4edf-8127-86ce53ccf999)

图中所示部分，需要改成中文
免费、免费、定制
**Suggestion**

**Why**

**Comment by iwanghc** [comment]
UI: main 64376600
DMS: main e86623c
SQLE: main https://github.com/actiontech/sqle/commit/9e0b7ffe8421ca47f71df96271b1a14353e57e8c

https://github.com/actiontech/sqle/assets/83113746/1e2eb2cc-9d55-4220-b79d-4cb90f28df91


### 验证点
菜单：
外部数据源
操作与审计
数据导出
白名单
sql管控
系统设置：
流程对接
登录对接
其他：
查看版本号
报表统计
