### ISSUE TITLE
工单没了

### ISSUE THREAD

**Issue by zhaobingss** [actiontech/sqle#2288]
**SQLe Version**
UI Version: release-2.2306.x 41c81a1
Server Version: release-2.2306.x 42364c019f

**Describe the bug**
之前的工单都没了

**To Reproduce**
库里面就剩4数据了，但最大的工单ID都110了
<img width="1442" alt="image" src="https://github.com/actiontech/sqle/assets/14836112/9c4f8072-bd5d-48ee-a5bc-3a011fd38e20">

**Expected behavior**

**Suggestion**

**Comment by ColdWaterLW** [comment]
SQLE有自动清理工单的机制，可在系统配置里设置
![image](https://github.com/actiontech/sqle/assets/36940986/7f89fb04-815b-4f23-9bae-bfd655f5a4a9)
