### ISSUE TITLE
scanner触发审核接口发生报错

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2298]
**SQLe Version**
sqle: 9eb009be16511755aa8429ba48307067c1eb20a2
**Describe the bug**
## 现象
1. 第一种情况
sqle未开启webhook通知
![image](https://github.com/actiontech/sqle/assets/53266479/be5f6aa4-4589-4faa-b502-97a17aec9675)

scanner扫描器触发审核时，发生报错
![image](https://github.com/actiontech/sqle/assets/53266479/1a6d7755-21d1-4e99-95f2-ffefd653ddf5)
2. 第二种情况
sqle开启webhook通知
![image](https://github.com/actiontech/sqle/assets/53266479/f5c2c7ac-f3a4-4d10-983d-06bc8942523c)

dms推送webhook消息失败，发生报错
![image](https://github.com/actiontech/sqle/assets/53266479/5b03d527-0923-48eb-928b-77fc01240b5e)

## 报错原因
scanner触发审核任务之后，会推送webhook消息。如果webhook消息推送失败，就会导致scanner审核失败，不符合预期

**Comment by iwanghc** [comment]
UI: main c771ee92
DMS: main e86623c

### 问题复现
SQLE: main https://github.com/actiontech/sqle/commit/a4c4a111113819da32285abc4f4d053653abbd7f
不开启webhook：
![image](https://github.com/actiontech/sqle/assets/83113746/45f18303-7dfd-4b14-aede-7dd07dadba9e)
![image](https://github.com/actiontech/sqle/assets/83113746/ca57d527-817c-4ee1-8f32-5ea9627f3b9f)
开启webhook：
![image](https://github.com/actiontech/sqle/assets/83113746/b5943905-d4ba-4700-8d61-99cfb98fc3c0)
![image](https://github.com/actiontech/sqle/assets/83113746/ae0612d0-56fa-4a99-a5db-d55de63c8891)

### 修复验证
SQLE: main 9eb009be16511755aa8429ba48307067c1eb20a2
不开启webhook启动scanner：
![image](https://github.com/actiontech/sqle/assets/83113746/d7fd9f6b-ff20-4c60-aeee-9aaedf0f6222)
开启webhook启动scanner：
![image](https://github.com/actiontech/sqle/assets/83113746/690d4fcb-cd06-467a-ad22-86964758c58a)

查看扫描结果
![image](https://github.com/actiontech/sqle/assets/83113746/26c41707-dcb4-41eb-a43e-40da2da11d4f)
![image](https://github.com/actiontech/sqle/assets/83113746/4e82f02d-4613-4017-b410-554cb8220889)

验证点：
不开启webhook扫描
开启webhook扫描
扫描结果
审核结果
