### ISSUE TITLE
新增个人访问令牌

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2309]
**Describe**
## 背景
用户使用OAuth 2.0并启用自动创建并绑定用户功能后，登录时会自动生成一个随机密码。然而，这个随机密码可能会导致用户无法在Eclipse插件中使用SQL审核功能。

#### sqle侧
在sqle个人中心中新增获取个人令牌功能，用户可以自定义访问令牌过期时间

前端个人中心展示页面
![image](https://github.com/actiontech/sqle/assets/53266479/a23fffa4-80ee-4252-be43-d4382975cf75)

新增个人令牌页面
![image](https://github.com/actiontech/sqle/assets/53266479/e389b872-2cc7-46ed-8ff4-20c1fa435059)

每次生成访问令牌时，旧的令牌将自动失效，只有最新生成的令牌才能被系统接受并使用。这确保了每个用户只能使用最新的令牌进行访问，增强了安全性和控制性。

#### eclipse插件
需要新增token登录方式
![image](https://github.com/actiontech/sqle/assets/53266479/269679a4-a933-49d6-ae06-cb789fe9c08d)

**Suggestion**

**Why**

**Comment by iwanghc** [comment]
UI: main 64376600
DMS: main e86623c
SQLE: main https://github.com/actiontech/sqle/commit/9e0b7ffe8421ca47f71df96271b1a14353e57e8c
获取token：
![image](https://github.com/actiontech/sqle/assets/83113746/3f44e733-a4f5-4ae7-b974-817d23c949d4)
![image](https://github.com/actiontech/sqle/assets/83113746/062d7703-e819-4fe9-ae35-2f4a99b2e6dc)
eclipse插件token登录：
![image](https://github.com/actiontech/sqle/assets/83113746/5083dcf8-9397-4fa5-9935-c8be9334ce69)
test connection：
![image](https://github.com/actiontech/sqle/assets/83113746/12c8c82b-d18a-4205-9235-49f327124266)
重新生成token：
旧的token失效
![image](https://github.com/actiontech/sqle/assets/83113746/5caf3a3e-9d30-4971-ae8f-d00a0c3b2f75)
新的token生效
![image](https://github.com/actiontech/sqle/assets/83113746/bea3c330-4345-49f6-87a9-be580c26a9e4)
验证点：
生成token
eclipse插件token登录
新旧token生效与失效
