### ISSUE TITLE
项目概览-扫描任务数据统计显示错误

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2312]
## 问题描述与复现方法
1. 在智能扫描中，我们为同一个数据源创建了三个扫描任务，两个库表元数据，一个慢日志
![image](https://github.com/actiontech/sqle/assets/31072467/09e1d351-a46c-44ad-a3ab-b51cf1ce31a7)
2. 在项目概览的扫描任务模块中，扫描MySQL数据源类型的扫描任务总数显示为2，预期是3
![image](https://github.com/actiontech/sqle/assets/31072467/2abe0026-45cc-42ee-ba37-18822029fd20)
3. 扫描任务详情的环形图中，当选择所有的扫描任务类型时，数据统计符合预期
![image](https://github.com/actiontech/sqle/assets/31072467/07cb675f-99da-42bf-ae47-20802e689b80)
4. 取消其中某个扫描任务类型时，数量统计不符合预期，这里取消库表元数据，只保留扫描任务，显示3预期1，显示占比为33.3%，预期为100%
![image](https://github.com/actiontech/sqle/assets/31072467/764b7e5c-1b5b-427c-b7ae-a8b7c7900826)
对应模块的响应体
```
{
    "code": 0,
    "message": "ok",
    "data": [
        {
            "db_type": "MySQL",
            "data": [
                {
                    "audit_plan_type": "mysql_schema_meta",
                    "audit_plan_count": 2,
                    "audit_plan_desc": "库表元数据"
                },
                {
                    "audit_plan_type": "mysql_slow_log",
                    "audit_plan_count": 1,
                    "audit_plan_desc": "慢日志"
                }
            ]
        }
    ]
}
```
## 需要解决的问题点
1. 在项目概览的扫描任务模块中，扫描MySQL数据源类型的扫描任务总数显示数量不符合预期
2. 取消其中某个扫描任务类型时，数量统计不符合预期
## 影响面
影响前端界面显示
## 需要验证的点
1. 扫描MySQL数据源类型的扫描任务总数显示是否与同一类型数据源的扫描任务总数相同
4. 扫描任务详情的环形图中，取消其中某个扫描任务类型时，数量统计是否随之变化
环形图统计信息计算方法：
数据源总计=所有勾选的扫描任务类型对应扫描任务数量的总和
数据源占比=（当前扫描任务类型对应扫i奥任务数量/数据源总计）x100%

**Comment by zzyangh** [comment]
报表统计-按数据库类型的数据源构成 图表展示错误，会一起处理
![img_v3_0293_5b6d51be-c6dc-4891-8bae-e96e0853452g](https://github.com/actiontech/sqle/assets/39512256/1f54893d-fa40-4438-a7fc-7285a42196c0)
