### ISSUE TITLE
自动发送邮件完善

### ISSUE THREAD

**Issue by huangkaili-c** [actiontech/sqle#232]
**Describe**
当前自动发送邮件功能仅在工单申请人提交工单时自动发送邮件给管理员

**Suggestion**
建议在工单审核完成或驳回、工单上线成功或失败（包括定时执行）等工单状态发生变化的情况下，自动发送给工单申请人

**Why**
工单申请人可以及时知晓自己申请的工单是否被允许执行、是否上线成功

**Comment by sjjian** [comment]
## 优化项
1. 新增推送场景
2. 丰富推送的内容
### 新增推送场景
1. 工单发起，或者下一步审批，发送消息提示待操作的审批人
2. 工单审批通过，进行SQL上线，发送消息提示待操作的执行者
3. 工单被驳回，发送消息提示创建者
4. 工单上线成功/失败，发送消息给工单创建者和执行者

### 丰富推送的内容
#### 工单待审批或待上线
- 工单主题
- 工单描述
- 申请人
- 创建时间
- 数据源
- schema
- 工单审核得分
- 工单审核通过率

#### 工单被驳回
- 工单主题
- 工单描述
- 申请人
- 创建时间
- 数据源
- schema
- 驳回原因

#### 工单上线成功/失败
- 工单主题
- 工单描述
- 申请人
- 创建时间
- 数据源
- schema
- 上线开始时间
- 上线结束时间
