### ISSUE TITLE
版权信息遮盖分页切换和扫描任务详情列表中sql分析操作未开放问题

### ISSUE THREAD

**Issue by zzyangh** [actiontech/sqle#2322]
**Describe the bug**

1.CE和体验版本会显示版权信息，现在的版权信息展示在分页上时，会导致无法切换分页
![image](https://github.com/actiontech/sqle/assets/39512256/b1624e7f-dcd7-4bac-a4b3-aada62cd184b)

2. 开发企业版sql分析功能，但是扫描任务详情列表中的分析未放开
  issue：https://github.com/actiontech/sqle/issues/2249
![img_v3_0297_acde5ad6-f497-4bd1-89d8-b5232185af6g](https://github.com/actiontech/sqle/assets/39512256/405bda2f-8a38-41c9-8491-37fe49958342)

**To Reproduce**

**Expected behavior**

1. 版权信息不影响分页操作
2. CE版本扫描任务详情列表可进行分析操作

**Comment by LZS911** [comment]
扫描任务详情列表可进行分析操作来源：https://github.com/actiontech/sqle/issues/2261
