### ISSUE TITLE
SQLE支持保存原始文件

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2323]
## 需求分析
存在需求：保存通过SQLE上传的原始文件，并且能够拿到原始文件
分析
1. 首先，为了满足需求，SQLE应该要增加保存原始文件和获取原始文件的功能
2. 防止过多文件导致SQLE所处的主机存储空间不足，需要增加删除原始文件的机制（定时任务）
3. 需要满足SQLE集群模式
### 新增接口
```
GET 
sqle/v1/tasks/audits/:task_id/origin_file
```
### 支持下载原始文件的类型
目前仅支持在SQL工单功能中保存下载.zip和.sql文件
### 数据表设计
![image](https://github.com/actiontech/sqle/assets/31072467/34b4b2f8-8a38-4462-b208-458ae94e31bb)
### 定时任务机制
1. 每小时，删除未绑定SQL工单的24小时前的文件
2. 每小时，删除过期文件7*24小时前的文件
## 需要验证的点
1. SQL工单功能中是否能保存下载.zip和.sql文件
2. 定时任务是否生效
3. 是否能从新增的接口中获取到文件，文件名和文件内容与上传时保持一致
4. 上述三点在集群模式下，不同主机的sqle上都需要验证
## 变更
1. 增加表audit_files
2. sqle配置文件增加配置项report_host，需要满足以下条件：
    - 当启动集群模式时，该配置项必填，非集群模式下推荐填写，
    - 配置项应填写`sqle部署的主机对外暴露的ip:sqle向外暴露的端口`，
    - sqle应监听`0.0.0.0`
3. 新增接口 `GET sqle/v1/tasks/audits/:task_id/origin_file`

**Comment by iwanghc** [comment]
UI: main c771ee92
DMS: main e86623c
SQLE: main a4c4a111

创建工单并上传文件
![image](https://github.com/actiontech/sqle/assets/83113746/1bd78b33-de08-4b1b-bd33-92157cf20cbc)
### 单机模式：
因目前没有前端按钮，测试由浏览器直接访问接口下载
sql文件
![image](https://github.com/actiontech/sqle/assets/83113746/2904794e-39d8-4414-b087-d2e9f4a5c792)
查看文件内容
![image](https://github.com/actiontech/sqle/assets/83113746/9d9408bd-43b5-4cfe-b647-e711167eb35b)
zip文件
![image](https://github.com/actiontech/sqle/assets/83113746/806e64f5-89b6-4b41-aab4-825450613cd5)
文件内容
![image](https://github.com/actiontech/sqle/assets/83113746/cac4a65c-df33-4234-b154-9ffe0f6a837f)
### 集群模式
server_1分别创建工单，上传zip和sql文件
![image](https://github.com/actiontech/sqle/assets/83113746/0e4648ed-2a07-418c-a803-96c851ed2625)
server_1测试下载zip和sql原文件
![image](https://github.com/actiontech/sqle/assets/83113746/6360508e-7e70-4a2a-8eaa-61778e1e7c82)
server_2测试下载zip和sql原文件
![image](https://github.com/actiontech/sqle/assets/83113746/27aa81ba-ede5-4791-b396-59e7c1772a1b)

验证点
单机模式
工单下载zip和sql原文件
验证下载的zip和sql原文件内容
集群模式
选取随机1节点在工单上传sql和zip
分别验证：
节点1下载zip和sql原文件
节点2下载zip和sql原文件
