### ISSUE TITLE
工单详情中的审核结果展示有误

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2325]
## 复现步骤

1. 在流程模板把“允许创建工单的最高审核等级”调整到 error
   ![image](https://github.com/actiontech/sqle/assets/36940986/13d425ce-9778-4f53-a1f9-5ac9550c0d07)

2. 创建工单时，触发数据库已存在的审核规则
   ![image](https://github.com/actiontech/sqle/assets/36940986/379febb8-b272-499b-8fdf-7ece954f8e43)

![image](https://github.com/actiontech/sqle/assets/36940986/7722db52-44d0-4d07-a5d8-c434dfafc333)

3. 点击创建工单
4. 查看工单详情
   审核结果展示为空
   ![image](https://github.com/actiontech/sqle/assets/36940986/b15e0e47-b9bc-43cf-9b25-35b475e3c4eb)

## 预期效果

执行完以上复现步骤后，审核结果应该展示 数据库已存在 的信息

## 问题原因

因为前端需要根据 rule_name 去后端获取审核结果annotation, 但是后端返回的 rule_name
值是空的，导致前端无法通过rule_name获取到审核结果annotation, 所以审核结果展示为空.

后端 rule_name 为空的原因是预检查不属于任何审核规则，所以没有 rule_name
![image](https://github.com/actiontech/sqle/assets/63177450/64bf967f-32f6-4337-b4ed-9a9bca7e6686)

## 解决方案

后端返回的 rule_name 为空时，前端不再根据 rule_name 去后端获取审核结果annotation, 而是直接展示审核结果

## 影响面

前端能正确展示预检查错误

**Comment by iwanghc** [comment]
DMS: main ee 9976824
SQLE: main ee 0529703a0

修改流程审批模板，等级设置为“错误”：
![image](https://github.com/actiontech/sqle/assets/83113746/afc0646e-0172-4501-b533-c6d3374d0a5a)
创建工单，触发已存在的数据库规则提示：
![image](https://github.com/actiontech/sqle/assets/83113746/9fdb4678-9651-4d86-90b6-86bac2b788ec)
![image](https://github.com/actiontech/sqle/assets/83113746/288df348-07d3-4fa6-ad4b-026af9c681bf)
### 问题复现
UI: main ee e2d70356
点击查看刚创建的工单，发现审核结果为空：(前提：只触发了已存在的数据库规则，若有其他规则触发此处不会出现该问题)
![image](https://github.com/actiontech/sqle/assets/83113746/aa26df2c-b79e-426a-b31b-6918ff70e754)

### 问题修复验证：
UI: main ee 08f7de1a
点击查看刚创建的工单，可以显示已存在数据库规则审核结果
![image](https://github.com/actiontech/sqle/assets/83113746/4ccb756f-ddcf-43c8-bf81-83db679b9393)

验证点：
sql审核 ，触发已存在的数据库规则err错误
审核结果
