### ISSUE TITLE
BUG：定时任务无法清除过期文件

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2337]
#2323 
## 版本信息（Version）
SQLE：67666f1bc5295402138dd71516dfea10cff40c28
## 问题描述（Describe）
由于修改了保存文件的表名，但筛选过期文件的SQL没有修改对应表名，导致获取过期文件的SQL执行错误。
## 截图或日志（Log）
``` bash
time="2024-04-07T05:29:17Z" level=error msg="get expired file with no workflow error: Error 1054 (42S22): Unknown column 'files.deleted_at' in 'where clause'" job=clean_for_all_nodes thread_id=2OS type=server_job
```
## 如何复现（To Reproduce）
在SQL工单中通过sql文件、xml文件或zip文件上传然后审核，但不提交该工单，预期24h后，不属于任何工单的文件将被清除。但这里的现象是工单文件将不会清除，并且在日志上报错，日志内容如上。
在SQL工单中通过sql文件、xml文件或zip文件上传然后审核，并且提交工单，预期7*24h后，属于工单的文件将被清除。但这里的现象是工单文件将不会清除。
## 实现方案
修改SQL中的`files`为`audit_files`，与当前的表名保持一致
## 变更影响面
修复前：定时任务无法正确删除过期文件，同时输出错误日志。
修复后：定时任务会正确地删除过期文件，不输出错误日志。
## 需要测试验证的点

- [ ] 上传文件后审核，不提交该工单，24h后工单文件是否被清除。
- [ ] 上传文件后审核，提交该工单，7*24h后工单文件是否被清除。

**Comment by iwanghc** [comment]
UI：mian d92f82dd
SQLE：main 1eaace89
DMS：main 0f4273b

上传sql文件，不提交工单×2
![image](https://github.com/actiontech/sqle/assets/83113746/30e14bcb-0df7-4e47-b2b0-c73790dd3188)
上传zip文件，提交工单×2
![image](https://github.com/actiontech/sqle/assets/83113746/998d7ee2-92f5-4897-9ed3-29827aaf9aa1)
文件已保存到服务器：
![image](https://github.com/actiontech/sqle/assets/83113746/32fac74c-862f-4b54-b8c2-3615af6e21d7)
数据库也有上传记录：
![image](https://github.com/actiontech/sqle/assets/83113746/7dd335c3-9803-49da-bf74-d324c614f362)
问题修复验证：
通过修改修改文件创建时间验证
### **情况1**
提交工单文件减去1天
不提交工单文件减2
证明仅可以删除1天以前的未提交工单的文件
![image](https://github.com/actiontech/sqle/assets/83113746/0cfdca94-917f-4992-b224-dd51c8fb6f0f)
时间到后未关联工单文件被删除，符合预期
![image](https://github.com/actiontech/sqle/assets/83113746/2c6780a4-5e28-4ff2-84b4-60870af45080)
![image](https://github.com/actiontech/sqle/assets/83113746/a293f7ce-e66d-4c25-a96e-a0c43591aa8b)
### **情况2**
不提交工单文件减7
证明可以删除7天前的关联工单的文件
![image](https://github.com/actiontech/sqle/assets/83113746/46982779-42dd-4ed3-a2a2-b35ba483f624)
文件被删除符合预期
![image](https://github.com/actiontech/sqle/assets/83113746/c2588bb2-305c-4634-b88a-3604a965a1df)
![image](https://github.com/actiontech/sqle/assets/83113746/0bb7cbfc-91fb-47ef-96ac-093dc9bd7225)
### **情况3**
提交工单文件减去1天
不提交工单文件减7
证明可以两种情况同时存在时也可删除
![image](https://github.com/actiontech/sqle/assets/83113746/93157464-14c3-41d3-b43c-b9b91b3a47ae)
文件被删除符合预期
![image](https://github.com/actiontech/sqle/assets/83113746/96222eee-887b-42cc-9936-b694d19a54f0)
![image](https://github.com/actiontech/sqle/assets/83113746/fadb8cb7-bd4a-431f-a1e4-e607b59e1644)

验证点：
当上传文件提交工单后，超过7天会被删除
当上传文件仅审核未提交工单，超过1天会被删除
