### ISSUE TITLE
sqle异常退出后重新拉起，会有多个插件进程存在

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2348]
## 版本信息（Version）
SQLE：main ee 815ad05f8
DMS：main ee a8a69c2
UI：main ee 36559656

## 问题描述（Describe）
sqle进程异常终止或强制退出后（如kill -9），sqle会自动重新拉起，此时会重新启动插件进程，但是老的插件进程不会被关闭，消耗资源。

## 如何复现（To Reproduce）
1、启动sqle，此时有pg的插件进程正在运行
![image](https://github.com/actiontech/sqle-ee/assets/83113746/4fe52687-2b5e-45f1-980a-06be6e0a22c4)
2、kill -9 强制退出sqle
![image](https://github.com/actiontech/sqle-ee/assets/83113746/80270780-7004-4acb-9a36-c2c90ac40969)
3、待sqle重新拉起后发现pg有两个进程存在
![image](https://github.com/actiontech/sqle-ee/assets/83113746/82ae55e6-39da-4ca9-8065-d29da005800d)

## 实现方案
**方案一**：【sqle启动时kill插件进程】sqle启动插件时，通过插件名称判断当前插件是否已有进程存在，若有则kill
**方案二**：【由sqle管理插件进程，sqle创建插件进程pid文件】当sqle启动插件时，判断插件pid文件内容，若不为空则发送退出进程信号。
**方案三**：【由插件自身管理进程，插件创建自身进程pid文件】当插件启动时判断对应pid文件内容，若不为空则kill进程。

### 最终方案
方案二，

方案一
优点：操作进程比较直接，省去文件操作，速度较快。
缺点：风险高，使用插件名称查进程，存在误杀进程的可能
方案二：
优点：仅操作文件记录的pid，风险和影响相对较小，又因插件由sqle启动，所以管理其进程也符合当前逻辑。
缺点：需要修改sqle启动插件逻辑，若杀残留进程panic，会导致sqle启动失败。
方案三：
优点：不需要修改sqle启动逻辑，对sqle影响小。
缺点：影响范围大，当前插件数量较多，需每个都修改，还涉及到不同语言开发的插件，修改成本较高

选择方案二原因：
综合来看方案二影响小，风险小，后期扩展性也较高，可实现统一管理插件进程（假设后期有个插件管理功能，控制插件的启停），就缺点来讲，即使插件自身panic，sqle也会启动失败，所以方案二更适合。

## 变更影响面
若插件pid文件手动删除，sqle异常终止重新拉起后插件会残留，因为sqle会读取插件文件记录的pid kill进程。
插件进程手动kill，sqle重新拉起pid文件记录是最新的插件pid。
sqle正常退出，插件进程随之退出，插件pid文件也随sqle停止而删除。

**Comment by iwanghc** [comment]
提升插件pid文件夹的权限，修复创建pid文件时权限不足问题
问题原因：
插件pid文件夹为0644，没有执行权限，导致无法open该文件夹创建pid文件
解决：提升pid文件夹权限至0755

**Comment by BugsGuru** [comment]
### 企业版本
sqle-ee: `9d9316d4adbe14b1546d96ee6a36f3497005dc05`
dms-ee: `1acc1ea45b5998654e56db0825a63e05ae0da470`
dms-ui: `d02dd39fd4641f172eabdd71e4d50e76d03afb7d`

### 验证
1. 启动sqle时生成插件pid文件
![image](https://github.com/actiontech/sqle/assets/53931124/7c329850-29f1-4781-9ded-144ee937668e)

**Comment by BugsGuru** [comment]
### 复现
版本：
DMS: main-ee 9025ba5e3f
SQLE: main-ee 6cee525631

环境：
centos7 rpm包部署 systemd管理服务

1. 正常启动sqle
2. 强制退出sqled进程
3. systemd自动重启sqled
4. 每种（DB2、PG）插件存在两个进程
![image](https://github.com/actiontech/sqle/assets/53931124/86655e85-5a48-4a0b-ab64-a0635c790684)
