### ISSUE TITLE
SQL审核出现panic

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2351]
## 版本信息（Version）

3.2403.0

## 问题描述（Describe）

使用SQL审核MYSQL数据源时，特殊SQL会出现审核失败，同时sqle会panic

## 截图或日志（Log）

<img width="792" alt="1713149886267" src="https://github.com/actiontech/sqle/assets/24822803/625e7c82-6a4f-4052-9cd9-e7c55a41336d">

## 如何复现（To Reproduce）

确保不进入下列条件分支需要开启规则:在 DML 语句中预计影响行数超过指定值则不回滚,数据源选择,审核如下SQL
`
SET @aesKey = 'xxxxxx';
UPDATE users SET business = 2 WHERE id = @aesKey;
`

![image](https://github.com/actiontech/sqle/assets/63177450/374b0a79-5467-4c94-ae76-82a43c567818)
![7b3761f4-aafc-48ed-a81d-7dc11d124f51](https://github.com/actiontech/sqle/assets/24822803/4a67fd82-a32e-4f2b-99cd-d3f5e25a32dd)
![image](https://github.com/actiontech/sqle/assets/63177450/69aeb037-8176-49e5-8436-a5cfe33df46b)

## 原因

将 where card_code = CONCAT("E|", HEX(AES_ENCRYPT('LMJS00063', @aesKey, @rb ))); 由语法树转为sql时报错
![image](https://github.com/actiontech/sqle/assets/63177450/d96788c6-83fd-4f66-9f05-2038de583c78)
![image](https://github.com/actiontech/sqle/assets/63177450/7a6b4751-bf4a-4034-8664-c31988784afb)

## 实现方案

遇到包含变量表达式的DML语句,直接跳过,不生成回滚语句

## 变更影响面

包含变量表达式的DML语句不会生成回滚语句,UI页面出现不生成回滚语句的规则告警
![image](https://github.com/actiontech/sqle/assets/63177450/7c0e4d55-a515-4162-ba43-12e0be11eb79)

**Comment by iwanghc** [comment]
UI: main 08f7de1a
DMS: main 0f4273b
开启规则：
![image](https://github.com/actiontech/sqle/assets/83113746/2c840a8f-aa06-46de-bb19-936915838247)
创建审核：
sql语句：SET @aesKey = 'xxxxxx'; UPDATE tb1 SET column1 = '2' WHERE id = @aesKey;
![image](https://github.com/actiontech/sqle/assets/83113746/adbdd47e-4635-4585-bd2d-b67fcac47acb)
### 问题复现：
SQLE: main 86cd961a
点击审核后台出现panic：
![image](https://github.com/actiontech/sqle/assets/83113746/19727b26-5108-410a-aee1-c96a1c548f2e)
### 问题修复验证：
SQLE: main 1d533b65
点击审核后审核成功，审核结果正常：

验证点：
特殊sql审核
