### ISSUE TITLE
上线的问题SQL需要定位

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2352]
## 描述（Describe）
原始需求： http://10.186.18.11/confluence/pages/viewpage.action?pageId=143589961

## 实现方案

使用接口 /v2/tasks/audits/{task_id}/sqls 提供的  sql_source_file、sql_start_line 字段在审核结果界面（审核、上线阶段）展示文件名称以及sql所在行

## 变更影响面

审核结果界面（审核、上线阶段）

**Comment by ColdWaterLW** [comment]
相关问题：
#2240
#2354

**Comment by iwanghc** [comment]
UI: main 08f7de1a
DMS: main 0f4273b
SQLE: main a537de5c

### zip文件测试：
准备sql的zip文件
文件内容：
![image](https://github.com/actiontech/sqle/assets/83113746/d4843fab-4dc7-4de8-9755-7843c99d226f)
![image](https://github.com/actiontech/sqle/assets/83113746/3aef9828-11c1-45a5-8a9a-bb912b98bdff)
![image](https://github.com/actiontech/sqle/assets/83113746/c37d13e7-e52c-4f25-8407-b94d2719c55f)

新建工单并上传zip文件：
![image](https://github.com/actiontech/sqle/assets/83113746/8db91021-3394-41e9-90e1-0d4265e3f611)
审核通过并上线：
可正确展示上线的sql所在文件和所在行
![image](https://github.com/actiontech/sqle/assets/83113746/5462d690-c208-44a9-be7c-ed0e08738ca6)

### sql文件测试：
文件内容
![image](https://github.com/actiontech/sqle/assets/83113746/52061e83-bffd-49cb-b271-e79f58861fb7)

创建工单并上传sql文件
![image](https://github.com/actiontech/sqle/assets/83113746/ac002a59-cf8d-4486-b416-76d908fa2c38)
可正常显示sql所在文件的位置
![image](https://github.com/actiontech/sqle/assets/83113746/92544e7c-61f9-46be-a15d-31296612d3b1)

相关问题：https://github.com/actiontech/sqle/issues/2240
错误sql显示的是报错行数
![image](https://github.com/actiontech/sqle/assets/83113746/96987065-c948-4ff6-93fc-a2cc17bc5dd7)

验证点：
sql文件和zip文件审核上线， 显示sql所在文件和位置
