### ISSUE TITLE
审核结果页面分页时无法跳转

### ISSUE THREAD

**Issue by banlilin** [actiontech/sqle#2363]
## 版本信息（Version）
3.2403.0
## 问题描述（Describe）
审核结果页面超过20条后分页无法跳转
## 截图或日志（Log）
<img width="1184" alt="image" src="https://github.com/actiontech/sqle/assets/37362792/fdeeec74-e0c0-4e70-b5c0-e08dfb237738">

**Comment by hasa1K** [comment]
## 结论
审核结果页面分页功能正常
![image](https://github.com/actiontech/sqle/assets/53266479/e30873a8-1c92-43dd-a683-acfa0c9a2778)
![image](https://github.com/actiontech/sqle/assets/53266479/1c464c07-59d0-4b3b-ae9f-a0c24baabd1d)
