### ISSUE TITLE
SQL工单下载审核报告参数错误

### ISSUE THREAD

**Issue by zzyangh** [actiontech/sqle#2371]
## 问题描述（Describe）
sql工单-工单详情 点击下载审核报告接口参数no_duplicate错误
## 截图或日志（Log）
![image](https://github.com/actiontech/sqle/assets/39512256/ba3ebe69-7e53-4ae5-ad84-d6b500f42072)

**Comment by iwanghc** [comment]
DMS: main b7c4536
SQLE: main 1d533b65

### 问题复现：
UI: main 3ad0046a
选择工单-导出审核报告
不选择数据去重时：
![image](https://github.com/actiontech/sqle/assets/83113746/d64df127-787f-4f7c-b315-5cf160b95079)
请求入参：
no_duplicate: true
![image](https://github.com/actiontech/sqle/assets/83113746/7265957b-cbfd-49ea-b4de-da245dc6f5d6)
选择数据去重时：
![image](https://github.com/actiontech/sqle/assets/83113746/b7befd36-4724-41cc-a749-dfcbd0ae8179)
请求入参：
no_duplicate: true
![image](https://github.com/actiontech/sqle/assets/83113746/8c3853c1-c310-4d65-84ad-61e4edf7ef5d)

### 问题修复验证：
UI: main 3ad0046a
选择工单-导出审核报告
不选择数据去重时：
![image](https://github.com/actiontech/sqle/assets/83113746/29b95f75-43dc-46fe-a866-28a947700b19)
请求入参：
no_duplicate: false
![image](https://github.com/actiontech/sqle/assets/83113746/d1c2751d-e611-4e64-9691-47f5e7d02a92)
选择数据去重时：
![image](https://github.com/actiontech/sqle/assets/83113746/e3a473d6-778d-4c32-a388-a7c150b46d1b)
请求入参：
no_duplicate: true
![image](https://github.com/actiontech/sqle/assets/83113746/02829de4-0625-4837-a852-26f623ac9f14)

验证点：
审核报告导出，请求参数
