### ISSUE TITLE
无法提交SQL工单，且页面没有明确的错误信息

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2382]
## 版本信息（Version）
![image](https://github.com/actiontech/sqle/assets/42765421/d12c7688-a84c-449f-8443-a8c7310a18f8)

## 问题描述（Describe）
当在创建工单时，填入不符合要求的工单名称，虽然页面会有错误信息，但是仍然能够进行审核。审核完成后进入提交工单页面，点击提交按钮无法提交，并且没有任何响应。控制台出现以下报错

## 截图或日志（Log）
![img_v3_02a8_2aba4cd0-e7c8-448c-87d4-0814be81362g](https://github.com/actiontech/sqle/assets/42765421/92eb15a4-d58d-4b5f-8ae4-6d6c5ad195fe)

## 如何复现（To Reproduce）
参考问题描述

## 实现方案

提交审核时也进行下工单基本信息的字段校验

## 变更影响面

创建工单

**Comment by iwanghc** [comment]
SQLE：main 1eaace89
DMS：main 0f4273b
创建工单，并输入不符合规范的工单名称
![image](https://github.com/actiontech/sqle/assets/83113746/7b4c6889-65c2-43ea-885e-a2acb4b79d53)
### 问题复现：
UI：main 08f7de1a
点击审核
可以进行审核
![image](https://github.com/actiontech/sqle/assets/83113746/f7901579-8a86-45ca-98c6-c18b5c53e398)
点击提交工单
控制台console出现报错：
![image](https://github.com/actiontech/sqle/assets/83113746/e41455bc-de59-4ecf-9c4b-51ce6060af95)

### 问题修复验证：
UI：main d92f82d
点击审核时不能进行审核且工单名称下持续有红色提示：
![image](https://github.com/actiontech/sqle/assets/83113746/de76bcdd-8c79-4a72-8bb3-0db206931b88)
修改正确后可正常进行审核和提交工单
![image](https://github.com/actiontech/sqle/assets/83113746/84afe6c1-71d6-4961-979e-944563540934)
![image](https://github.com/actiontech/sqle/assets/83113746/c889af25-68d5-4685-80fd-3213120966d8)
![image](https://github.com/actiontech/sqle/assets/83113746/094743fb-46d9-410b-b547-e756f28722c2)



验证点：
填写不符合规范的工单名称进行：
工单审核
工单提交
