### ISSUE TITLE
索引创建建议规则空指针报错

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2387]
## 版本信息（Version）

ee 2.9999 

## 问题描述（Describe）

用户审核扫描任务sql时,审核规则索引创建建议规则空指针报错

## 截图或日志（Log）

![image](https://github.com/actiontech/sqle/assets/63177450/bdf91ce0-5787-41a3-99db-e07239290f3b)
![img_v3_02a8_5718b986-f7cb-4177-aadb-eab863d7899g](https://github.com/actiontech/sqle/assets/63177450/04ab5449-2902-42a1-8a12-f24602f0df7b)

## 如何复现（To Reproduce）
1. 关闭其他规则,只打开索引创建建议规则
![image](https://github.com/actiontech/sqle-ee/assets/63177450/836a9cdc-8de9-49fc-a304-95af88839997)

2. 创建复现所需的库表结构

```
CREATE TABLE test
(
    id   int,
    name varchar(255)
);

INSERT INTO test (id, name)
VALUES (1, 'a'),
       (2, 'b'),
       (3, 'c');
```

3. 审核以下sql,出现空指针报错

```
SELECT name name_t
FROM test
ORDER BY name_t DESC;
```

![image](https://github.com/actiontech/sqle-ee/assets/63177450/85f8a1de-0536-462d-9e00-4a9ae88a9a2d)
![image](https://github.com/actiontech/sqle-ee/assets/63177450/525a13d3-c2a6-4a1a-95c1-d3fc95e51176)

## 实现方案

跳过不存在的列
![image](https://github.com/actiontech/sqle-ee/assets/63177450/d0356ef7-3791-4405-b81a-4c86afae2864)

#### 受影响的模块或功能

对于下列带别名的sql,索引创建建议规则不会给出对 name 列添加索引的建议

```
SELECT name name_t
FROM test
ORDER BY name_t DESC;
```
#### 外部引用的潜在问题或风险

无风险

#### 版本兼容性

兼容

**Comment by iwanghc** [comment]
DMS：main ee 9976824
UI：main ee 08f7de1a
准备表：
![image](https://github.com/actiontech/sqle/assets/83113746/489cf55f-812e-4330-8644-13097a249138)
使用tdsql-for-mysql插件
开启规则：
![image](https://github.com/actiontech/sqle/assets/83113746/ee5adc20-37b5-4aa9-8c60-08796c5097b3)
创建工单
![image](https://github.com/actiontech/sqle/assets/83113746/363b96e6-0de3-4f75-a0e8-84d20dfcac49)
审核语句：
`SELECT name name_t
FROM test
ORDER BY name_t DESC;`
### 问题复现：
SQLE：main ee d1becdd61
点击审核后台报错
![image](https://github.com/actiontech/sqle/assets/83113746/15154a4e-ee5b-44a5-8a87-ebb1a379cf99)
### 问题修复验证：
审核成功：
SQLE：main ee 7331d6728
![image](https://github.com/actiontech/sqle/assets/83113746/c3f8620d-c8b9-4733-a58f-c53f8c08ca1a)

验证点：
tdsql for mysql审核
审核字段有别名并order by别名的sql语句
