### ISSUE TITLE
sql工单页面前端代码重构

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2429]
## 描述（Describe）

由于需求迭代原因，导致工单页面部分组件逻辑非常混乱，维护困难，所以产生了代码重构的需求。

### 列表
无变动

#### 缺陷修复

1. 创建工单时，切换选择的数据源时，在已选择了数据库的情况下，不会清空选择数据库

现状：![image](https://github.com/actiontech/sqle/assets/42765421/c6e0f5cd-176b-4bb7-bb15-15fee78788d9)

预期：![image](https://github.com/actiontech/sqle/assets/42765421/79397dd1-b1d4-4e19-ac83-b4134169dcc1)

2. 创建工单时，切换选择的数据源时，在网络较差的情况下，对应的数据库数据依旧会显示上一个数据源的数据，而不是 Loading 效果

现状：![image](https://github.com/actiontech/sqle/assets/42765421/b23f574a-a6bb-4064-a4c1-71c110e9da32)

预期：![image](https://github.com/actiontech/sqle/assets/42765421/0120f5ca-3f57-4cc1-9e56-e72c6db5fd11)

3. 在编辑工单信息时，选择不同类型的数据源不会自动切换到不同 sql 模式下

现状：![image](https://github.com/actiontech/sqle/assets/42765421/ecad7e26-aaee-4d62-b35d-9bfece22cb6c)

预期：![image](https://github.com/actiontech/sqle/assets/42765421/1a10086b-be9e-4dfb-ac19-ab6b1a0e10bd)

#### 优化

1. 当审核工单后未提交便离开页面的情况下，给出提示。对应 issue：https://github.com/actiontech/sqle/issues/2162

![image](https://github.com/actiontech/sqle/assets/42765421/cdd45038-0a44-4a46-ad4f-b83acdd3a529)

2. 数据源对应的规则模板的跳转方式调整为新开页面。 对应 issue：https://github.com/actiontech/sqle/issues/2121

![image](https://github.com/actiontech/sqle/assets/42765421/92e52678-365b-41cb-853a-d849478cbfe3)

3. 创建工单时的数据源名称显示优化。对应 issue：https://github.com/actiontech/sqle/issues/2129

![image](https://github.com/actiontech/sqle/assets/42765421/12f196b6-45b9-4228-967c-6230ed88dd73)

#### 页面调整

1. 选择文件上线模式表单样式调整。 理由：在多数据源不同SQL模式下，文件模式选择上线字段对应的应该是某一个数据源下，现有的样式更像是单独的一个模式。

现状：![image](https://github.com/actiontech/sqle/assets/42765421/a8bed84d-b333-4b17-aac4-b4b949c93b48)

调整后：![image](https://github.com/actiontech/sqle/assets/42765421/b3e67643-2d93-4f34-8916-5dd4b88c4125)

其他建议优化：感觉现在这个功能隐藏得有点太深了，是否考虑在界面加些提示告知用户这个功能。例如哪些数据源支持，以及sql上传模式得选择 sql文件上传方式或者 zip 文件上传方式。

2. 建议优化：多数据源不同SQL模式下sql上传方式的展示方式
目前采用的是通过 tab 来切换不同数据源对应的 sql 上传方式，当点击审核后会一起对所有数据源一起审核。这里存在一个问题是由于对每个数据源的审核都会发送一次接口，所以可能会出现部分成功、部分数据源失败的情况。这个问题在 v2 to v3 时同步过，但当时并没有提供解决方案
建议将 tab 展示方式调整为页面直接展示出每一个数据源对应的 sql 上传方式，每一块对应一个 审核 按钮。当所有数据源对应的信息都审核完成后，才能跳转至审核结果页面。（待细节优化以及编辑工单信息时是否需要对应的调整）

#### 优化
1. 驳回工单信息展示优化

现状：![image](https://github.com/actiontech/sqle/assets/42765421/1651679a-dccc-4296-8d7a-bf3ce6a2969d)

调整后：![image](https://github.com/actiontech/sqle/assets/42765421/071ba7ed-2840-4155-b2c2-52ca729a774c)

2. 工单详情信息出现以及隐藏时添加动画效果

对应界面：![image](https://github.com/actiontech/sqle/assets/42765421/0811870c-714a-4727-a08c-82dec0a341cb)

3. 驳回工单后修改 sql 信息限制sql上传方式为创建时的方式有隐藏改为禁用

现状：![image](https://github.com/actiontech/sqle/assets/42765421/88aac1f2-04a9-43aa-90c5-5678f1e137fc)

调整后：![image](https://github.com/actiontech/sqle/assets/42765421/7ec22506-94bc-41f4-b099-bc13cb60ed18)

4. 驳回工单后修改sql信息后进行了审核且审核成功但未提交离开页面时给出提示

![image](https://github.com/actiontech/sqle/assets/42765421/c8ea3ca1-d53f-4ce5-9216-aef5e801c3a3)

**Comment by hasa1K** [comment]
dms-ui:73ff4e6bc29b2bc965c919ece2dab9d1bd7466f5
dms:7ebf3da28e3f0558d120fd1fd04c24a071f174e3
sqle:4a5e6c84549f209380ba4cfaba41c364158b19b2

验证：
1. 创建工单时，切换选择的数据源时，在已选择了数据库的情况下，清空选择的数据库
![20240527143252_rec_](https://github.com/actiontech/sqle/assets/53266479/0b284cd5-1841-4bd9-b95b-42d67a4a0be3)
2. 创建工单时，切换选择的数据源时，在网络较差的情况下，出现Loading 效果
![20240527143658_rec_](https://github.com/actiontech/sqle/assets/53266479/10f77fce-87d4-41a4-8e6b-35839d648828)
3. 在编辑工单信息时，选择不同类型的数据源会自动关闭`选择相同sql`功能
![20240527144443_rec_](https://github.com/actiontech/sqle/assets/53266479/5107b3ad-0d47-4873-84ff-b7dcd93e89d4)
4. 当审核工单后未提交便离开页面的情况下，给出提示
![image](https://github.com/actiontech/sqle/assets/53266479/7475c125-8de8-4f8e-843e-43f70cd0e329)
5. 数据源对应的规则模板的跳转方式调整为新开页面
![20240527145010_rec_](https://github.com/actiontech/sqle/assets/53266479/35caa3b2-7f6a-44cd-a28a-e4cd8f068acc)
6. 创建工单时的数据源名称显示优化
![image](https://github.com/actiontech/sqle/assets/53266479/f8b33c55-628f-44dc-8cf6-af29ee24ca4d)
7. 选择文件上线模式表单样式调整
![image](https://github.com/actiontech/sqle/assets/53266479/ba44cad4-324f-44f6-abe1-d052a9699e1a)
8. 驳回工单信息展示优化
![image](https://github.com/actiontech/sqle/assets/53266479/674ac431-370f-492b-90e5-013d3ffe2cb9)
9. 工单详情信息出现以及隐藏时添加动画效果
![20240527145943_rec_](https://github.com/actiontech/sqle/assets/53266479/1e74481a-9fbc-4a6d-8e74-6789d7079fa1)
10. 驳回工单后修改 sql 信息限制sql上传方式为创建时的方式有隐藏改为禁用
![20240527150101_rec_](https://github.com/actiontech/sqle/assets/53266479/2b786b13-8c7b-4f44-b197-f69ded0d9675)
11. 驳回工单后修改sql信息后进行了审核且审核成功但未提交离开页面时给出提示
![20240527150440_rec_](https://github.com/actiontech/sqle/assets/53266479/5f27d290-a3f2-471c-a1f3-68cbb8da4dbe)
