### ISSUE TITLE
文件模式上线支持MySQL

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2442]
## 描述（Describe）
原始issue：https://github.com/actiontech/sqle-ee/issues/1468
文件模式上线，需要支持MySQL

## 实现方案
1、 实现mysql插件ExecBatch方法
2、补充插件可选模块，GetDriverMetas()函数中增加返回值：driverV2.OptionalExecBatch
3、对sql执行的BatchId赋值，Parse()函数中增加对Node的赋值：n.ExecBatchId = uint64(idx)
（mysql从文本文件执行 SQL 语句，其原理是从文件中读取sql并依次执行，所以可将文件中单条sql语句为一个BatchId）
https://dev.mysql.com/doc/refman/5.7/en/mysql-batch-commands.html
https://dev.mysql.com/doc/refman/5.7/en/batch-mode.html

#### 受影响的模块或功能

不对其他模块产生影响
#### 外部引用的潜在问题或风险

无外部引用
#### 版本兼容性

兼容其他版本
#### 测试建议

文件尽量包含多种sql语句，如测试上线DDL，DML和存储过程。

**Comment by ColdWaterLW** [comment]
2406

**Comment by BugsGuru** [comment]
### 社区版本
sqle-ce: `65ec0a171ac366cc0345a0271b53563e63518f8a`
dms-ce: `e1bd3f7ab52ffcb77aa772a36b9017a8ccf29a88`
dms-ui: `d02dd39fd4641f172eabdd71e4d50e76d03afb7d`

### 验证
在MySQL数据源上创建工单，上传sql文件，以文件模式上线，执行成功
![image](https://github.com/actiontech/sqle/assets/53931124/f6a91ac6-da45-4614-8552-cbd36b2978a0)

**Comment by BugsGuru** [comment]
### 企业版本
sqle-ee: `65ec0a171ac366cc0345a0271b53563e63518f8a`
dms-ee: `1acc1ea45b5998654e56db0825a63e05ae0da470`
dms-ui: `d02dd39fd4641f172eabdd71e4d50e76d03afb7d`

### 验证
![image](https://github.com/actiontech/sqle/assets/53931124/1abbc3e1-7b4a-4c7b-b565-2f9aa9309f5c)
