### ISSUE TITLE
目前部分功能使用方式不明确，建议添加提示性语句

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2459]
## 描述（Describe）
1. SQL文件上线功能
 现状： ![image](https://github.com/actiontech/sqle/assets/42765421/1388003a-3965-41be-9a97-8210fe3498e8)
 该功能目前仅支持部分数据源类型，当选中的数据源类型不支持时，页面并不会体现该功能，导致该功能无法被用户感 
  知
 预期：不支持的数据源类型，也要展示文件模式上线

-  按钮置灰，默认选中SQL模式上线
-  鼠标移入置灰按钮时，提示“当前支持MySQL、Oracle、PG类型数据源类型按文件模式上线”

      
2. 快捷审核 Git 仓库功能
    现状：![image](https://github.com/actiontech/sqle/assets/42765421/d6d14103-ab7c-47ce-aa08-a975de9bcd12)
    Git仓库的填写内容没有任何提示，希望能新增提示告知
 
预期：新增提示：请输入git仓库的HTTP(S)克隆地址

3. 新增成员功能
    现状：![image](https://github.com/actiontech/sqle/assets/42765421/6f13a128-32fe-4949-b070-faa54b8394c4)
    目前新增成员功能的数据来源没有任何提示，希望能新增提示告知
预期：新增提示：需要先在系统设置-用户中心处新增用户

**Comment by BugsGuru** [comment]
### 版本
sqle-ce: `65ec0a171ac366cc0345a0271b53563e63518f8a`
dms-ce: `e1bd3f7ab52ffcb77aa772a36b9017a8ccf29a88`
dms-ui: `d02dd39fd4641f172eabdd71e4d50e76d03afb7d`

### 验证
1. 提示“当前支持MySQL、Oracle、PG类型数据源类型按文件模式上线”，社区版只有MySQL是支持文件模式的未提示
    ![localhost_10000_sqle_project_700300_exec-workflow_create (1)](https://github.com/actiontech/sqle/assets/53931124/e5198373-bf79-436a-9fab-204337fb803d)

2. 新增提示：请输入git仓库的HTTP(S)克隆地址
    ![image](https://github.com/actiontech/sqle/assets/53931124/2306b7b6-1d35-4532-9c13-d491a25064e2)

3. 新增提示：需要先在系统设置-用户中心处新增用户
    ![image](https://github.com/actiontech/sqle/assets/53931124/4a8848f9-1923-4a27-ab6b-a81221657853)

4. 添加提示：为了提高调优结果的准确度，系统将执行数据库分析操作，社区版不支持智能调优

**Comment by BugsGuru** [comment]
### 版本
sqle-ee: `65ec0a171ac366cc0345a0271b53563e63518f8a`
dms-ee: `1acc1ea45b5998654e56db0825a63e05ae0da470`
dms-ui: `d02dd39fd4641f172eabdd71e4d50e76d03afb7d`

### 验证
1. 提示“当前支持MySQL、Oracle、PG类型数据源类型按文件模式上线”
    ![image](https://github.com/actiontech/sqle/assets/53931124/ac0a056f-30f9-4872-8307-376f9b65745e)

2. 新增提示：请输入git仓库的HTTP(S)克隆地址
    ![image](https://github.com/actiontech/sqle/assets/53931124/89fd259d-27b3-4aea-94b1-1b422302eb34)

3. 新增提示：需要先在系统设置-用户中心处新增用户
    ![image](https://github.com/actiontech/sqle/assets/53931124/6156ad6c-ef16-4103-9078-0692c9f01810)


5. 添加提示：为了提高调优结果的准确度，系统将执行数据库分析操作
    ![image](https://github.com/actiontech/sqle/assets/53931124/d7ac68a5-9480-43ee-89b7-dc7fa580ab22)
