### ISSUE TITLE
MySQL添加规则 "MySQL 自增字段禁止手动插值"

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#2473]
## 描述（Describe）
本issue为开源之夏项目：https://summer-ospp.ac.cn/org/prodetail/240780099?lang=zh&list=pro
项目内容为：在sqle内置的MySQL审核规则集中，添加“禁止手动设置自增字段值”的规则
![image](https://github.com/actiontech/sqle/assets/61675635/61afc3a4-b1b9-456a-9d65-d884b4fc15de)

## 实现方案
sqle内部已经封装了一套SQL解析、在线获取数据库表数据以及测试的框架，添加规则需要修改的文件为：
- `sqle/driver/mysql/rule/rule.go`: 规则名常量和审核函数。

- `sqle/driver/mysql/rule/rule_list.go`: 规则体声明。sqle会在启动时将代码中的内置规则与`sqle`数据库中的`rules`表做比较并更新表中规则，因此只要修改此处规则声明并重启sqle服务即可更新规则。

- `sqle/driver/mysql/audit_test.go`: 进行审核函数的测试。

- `sqle/driver/mysql/session/mock_context.go`:  sqle采用`go-sqlmock`模拟数据库环境以便本地单元测试，此文件内含mock出的数据库表结构。
- 
  该审核函数过程如下：

  ```mermaid
  graph LR
      id1([进入审核函数])-->id2{{根结点类型是否为<br>InsertStmt或UpdateStmt?}}
      id2--是-->id20[获取指定了值的字段]
      id20-->id3[获取表名]
      id2--否-->id4([审核通过])
  	id3-->id6[获取表的元数据]
  	id6-->id8[从元数据获取<br>自增字段名称]
  	id8-->id9{{被指定值的字段<br>是否包含自增字段?}}
  	id9--是-->id10([审核不通过])
  	id9--否-->id4
  ```

  获取自增字段的方法如下：

  ```go
  var table *ast.TableName
  ...
  // 获取自增字段
  // MySQL中每张表最多一个自增字段
  incrName := ""
  info, _ := input.Ctx.GetTableInfo(table)
  for _, c := range info.OriginalTable.Cols {
      for _, option := range c.Options {
          if option.Tp == ast.ColumnOptionAutoIncrement {
              incrName = c.Name.OrigColName()
              break
          }
      }
      if incrName != "" {
          break
      }
  }
  ```
注意有以下三种INSERT，获取插值字段的方式都不相同
- `INSERT tb VALUES(...)`
- `INSERT tb(c1,c2) VALUES(v1,v2)`
- `INSERT tb SET c1=v1`

对于单元测试，只需参考`mock_context.go`中展示的表结构，在`audit_test.go`中使用这些表和字段进行测试即可。需要注意在测试时，对于违反规则的用例，测试PASS，而SQL未违反规则时则会FAIL。

最终在本地重新打包部署项目，访问前端界面，在默认规则模板中启用该规则，配置一个数据源，在快捷审核中进行动态审核，查看系统是否审核到输入的SQL违反了规则。

#### 受影响的模块或功能

仅新增了一个内置规则，以及添加了一个供测试用的数据库mock表，对用户使用流程和后台工作流无影响
#### 外部引用的潜在问题或风险

无风险
#### 版本兼容性

均基于现成的工具实现，兼容性与整体系统一致

#### 测试建议

先前的mock表自增字段均为主键，对于本规则可添加一个id字段上的约束不是`PRIMARY KEY`，而为`NOT NULL UNIQUE AUTO_INCREMENT`。使用两种表结构，对INSERT和UPDATE进行测试。由于被设置值的字段是从SQL最外层结构中获取，所以无需关心内层的子查询等语句，可以简化测试用例。

**Comment by hasa1K** [comment]
## 版本
sqle main-ee:5d6bc2d1bd4f8c2eb2fee3a93ed70de9d5dbdb86

## 测试
开启该规则
![image](https://github.com/user-attachments/assets/c7d9d7d1-6fe1-48e0-9f0a-0a837e71420b)
表结构中id为自增主键
![image](https://github.com/user-attachments/assets/27669837-d5a8-496a-b7f6-7f478d207802)
insert语句触发成功
![image](https://github.com/user-attachments/assets/e6910539-1eaf-4bb4-b461-667f1bd0bb83)
update语句触发成功
![image](https://github.com/user-attachments/assets/4c0698cf-ec1d-4213-80f8-67300381ca13)
