### ISSUE TITLE
sqle支持ob for mysql作为存储库

### ISSUE THREAD

**Issue by hasa1K** [actiontech/sqle#2475]
## 描述（Describe）
SQLEV3使用ob for mysql作为后端数据库

## 实现方案
http://10.186.18.11/confluence/pages/viewpage.action?pageId=160072235

## 变更影响面
影响面记录在方案中

**Comment by hasa1K** [comment]
## Ob for MySQL与MySQL的区别
| Sql语句 | Ob for MySQL | MySQL |
| ------------- | ------------- | ------------- |
| Show tables from `oceanbase` where `Tables_in_oceanbase` = ? | 不支持 | 支持 |
| ALTER TABLE workflows MODIFY COLUMN workflow_id varchar(255) UNIQUE alter语句中同时修改表字段类型和索引 | 4.x版本支持，3.x版本不支持 | 支持 |
| enum字段作为索引 | 4.x版本支持，3.x版本不支持 | 支持 |
| json字段 | 3.1.3以下版本不支持json字段 | 支持 |

**Comment by hasa1K** [comment]
## Gorm v1与v2版本的差异
  | v1 | v2 | 备注
-- | -- | -- | --
创建联合索引 | 使用DB.AddUniqueIndex/DB.AddIndex 函数创建 | 使用结构体中的标签v2文档：https://gorm.io/docs/indexes.html#Fields-Priority | 影响面：由于sqle存在嵌套结构体，例如`SqlManage`表，该表存在联合索引字段分散在不同结构体中的现象。所以不能直接使用结构体中的标签创建联合索引。需要手动执行sql创建联合索引
count函数 | count函数传递interface类型 | count函数必须传递int64类型源码截图 | 修复方案：所有count函数都需要传递int64类型的参数 影响面：需要修改部分查询函数返回值，会影响到接口函数。
update函数 |   | 更新多个值时，需要使用updates函数 |  
子查询 | v1需要标明这条sql语句是子查询示例： | v2中不需要指明该sql为子查询v2文档：https://gorm.io/docs/advanced_query.html#SubQuery |  
BeforeSave/AfterFind函数 | v1中，两个函数都不需要进行传参 | v2中，两个函数都需要传递*gorm.DB。BeforeSave 用法发生改变，需使用gorm.DB.Statement.SetColumn("EncryptedPassword", pw)方法更新值 v2文档：https://gorm.io/docs/update.html#Change-Updating-Values | 测试建议：1. 修改之后，保存数据和查询数据的结果是否和修改之前保持一致
AutoMigrate函数 | 创建表时，不创建外键关系，如果没有声明string字段的具体类型，默认创建varcahr(255)类型的字段以sql_manages表举例结构体内容： v1创建出的表: | 创建表时，自动创建外键关系。需要在结构体中声明具体的字段类型，不然string字段就使用longtext类型字段创建以sql_manages表举例v2创建出的表: | 修复方案：1. 使用gorm v2之后，禁用自动创建外键关系功能，数据结构上与v1保持一致2. 结构体中string字段申明具体数据库字段类型 测试建议：1. 检测索引创建是否符合预期2. 指明字段类型之后，检测字段类型是否符合预期
Find函数 | 在没有查询到值时，会返回ErrRecordNotFound | 在没有查询到值时，不返回ErrRecordNotFoundv2文档：https://gorm.io/docs/query.htmlissue链接：https://github.com/go-gorm/gorm/issues/3849 | 解决方案1. 使用RowsAffected来判断是否取到值Goresult := s.db.Model(AuditPlan{}).Where("project_id = ? AND name = ?", projectId, AuditPlanName).Find(ap)if result.RowsAffected == 0 {    return ap, false, nil}2. 使用First函数替代Find函数 |
delete_at字段 | 当表中存在deleted_at字段，将开启软删除，以及查询时判断delete_at is null文档：https://v1.gorm.io/docs/delete.html#Soft-Delete | 需要结构体中包含gorm.DeletedAt 类型的字段才会开启软删除例如Gotype User struct {  ID      int  Deleted gorm.DeletedAt  Name    string}文档：https://gorm.io/docs/delete.html#Soft-Delete | Gotype User struct {  ID      int  Deleted gorm.DeletedAt  Name    string} | 解决方案将现有表中的deleted_at字段的类型替换为gorm.DeletedAt 影响面：1. 之前的deleted_at字段为time.Time类型，替换为gorm.DeletedAt之后，会对之前有关deleted_at字段的使用方式发生改变2. 如果sqle存在查询已删除数据的函数，deleted_at 字段类型替换之后，是否还生效

**Comment by hasa1K** [comment]
关联ee的issue：
https://github.com/actiontech/sqle-ee/issues/1597

**Comment by taolx0** [comment]
表创建成功
![image](https://github.com/user-attachments/assets/15c68abd-48aa-42f7-8c3b-c0264ea340d2)
功能正常
![image](https://github.com/user-attachments/assets/56a0bc88-15ec-40e7-b374-1ce730cd0da5)
