### ISSUE TITLE
项目-业务-数据源的层级结构不明确

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2478]
## 问题描述（Describe）

项目-业务-数据源的层级结构不明确

预期：在创建项目时添加以下描述
![image](https://github.com/actiontech/sqle/assets/42765421/307f0e09-a3b9-494a-8ec4-8729e2a6b0ac)

我们的平台采用项目-业务-数据源的层级结构，为您提供清晰、有序的数据资源管理方式。
![image](https://github.com/actiontech/sqle/assets/42765421/3916376a-3662-4081-93d2-4fda388ba111)
- 项目：每个项目代表一个独立的产品环境，作为资源隔离的单元，确保数据安全和产品独立性。在项目层面，您可以聚合和管理相关的业务模块。
- 业务：在项目的基础上，业务作为子项目或特定业务领域的标签，帮助您进一步组织和细化数据资源。业务层使您能够针对特定需求进行数据的集中管理和操作。
- 数据源：数据源是构建在业务基础上的实际操作对象。您可以在数据源层面执行具体的数据操作，如查询、更新和管理数据。

**Comment by taolx0** [comment]
![image](https://github.com/user-attachments/assets/17a7ab95-506e-4c37-a524-d70086f4059f)
![image](https://github.com/user-attachments/assets/831c0dc2-00a0-43cd-b74b-2c4fb9d1a2b9)
