### ISSUE TITLE
执行工单上线，上线成功后，SQLE需要手动刷新界面

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2482]
## 描述（Describe）
SQL工单上线存在中间状态：正在上线。当上线成功后页面无法即使感知，需要手动点击刷新工单来刷新页面
![image](https://github.com/user-attachments/assets/5c070278-c587-4045-8843-2ac03ee62dc0)

## 预期

1. 希望在工单为**正在上线**状态时 开启页面自动刷新功能。
2. 需要排查一下其他需要手动刷新的界面，一起调整。

## 实现方案
当处于中间状态时，前端开启轮询。

## 变更影响页面

1. SQL工单上线页面
2. 待排查

**Comment by zzyangh** [comment]
- 影响页面：SQL工单详情页面

- 轮询触发条件：只有当工单状态为正在上线时才会开始轮询请求，其他状态不会触发

- 轮询时间间隔：1000ms

- 轮询接口
   1. 工单详情接口（/sqle/v2/projects/{project_name}/workflows/{workflow_id}/）
   2. 工单业务概览接口（/sqle/v2/projects/{project_name}/workflows/{workflow_id}/tasks）

**Comment by taolx0** [comment]
![image](https://github.com/user-attachments/assets/7ca94bfa-191d-49e7-bf38-9e782c5a406e)
![image](https://github.com/user-attachments/assets/6f847a69-e0cf-4b2f-9177-5aa752816b77)
