### ISSUE TITLE
新增工单克隆功能

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2486]
## 描述（Describe）
需求目标
工单支持上线到其他数据源

预期
- 找到开发环境的上线工单
不区分工单状态
- 点击“上线到其他实例”，完全复制工单信息（除了数据源和工单名称）
- 选择需要上线的数据源和数据库，填写工单名称
- 预审通过后，创建工单，执行变更流程

入口
工单详情页，右上方新增“上线到其他数据源”按钮

交互
点击“上线到其他数据源”，跳转到工单创建页面，并同时复制所有工单信息
注意：页面需要提示修改工单名称和需要上线的数据源

## 实现方案

1. 新增获取工单task附件的接口 
获取工单中以sql文件或zip文件方式上传sql的原始文件
3. 获取task接口补充返回值：上线模式、文件排序方式
5. 修复工单提交sql审核时，sql上传方式未保存bug（需考虑存量工单数据处理）

#### 受影响的模块或功能

工单提交sql审核时，save task的sql上传方式（遗留bug）
#### 外部引用的潜在问题或风险
无

#### 版本兼容性
不兼容旧版本单数据源、多数据源相同sql工单的克隆，需配合升级方案补充sql上传方式。
#### 测试建议
无

**Comment by zzyangh** [comment]
目前需接口支持内容：

1. 文件排序方式数据目前没有接口返回，需要支持返回
2. 上线模式返回错误，需要返回对应数据源下的上线模式
3. /v1/tasks/audits/${task_id}/ 接口返回的sql_source错误，选择输入sql语句的方式创建工单时，相同sql模式会返回sql_source: 'form_data', 不同sql模式会返回sql_source: ''，希望统一
4. /v1/projects/${project_name}/workflows/${workflow_id}/attachment  新增的获取文件内容接口，需要支持获取不同数据源下上传的文件内容，还需要和其他的文件导出接口做一下区分

**Comment by iwanghc** [comment]
由于历史工单数据未保存sql上传方式，导致工单克隆无法正确的将sql写入对应的输入框内，现执行以下sql可补充历史工单数据中缺失的sql上传方式：
```
UPDATE tasks t
LEFT JOIN (
    SELECT task_id, 
           CASE 
               WHEN file_name LIKE '%.sql%' THEN 'sql_file'
               WHEN file_name LIKE '%.zip%' THEN 'zip_file'
               ELSE 'form_data'
           END AS new_sql_source
    FROM audit_files
    WHERE parent_id = 0
) af ON t.id = af.task_id
SET t.sql_source = COALESCE(af.new_sql_source, 'form_data')
WHERE t.sql_source IS NULL OR t.sql_source='';
```
