### ISSUE TITLE
工单驳回后无法修改SQL语句

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#2493]
## 版本信息（Version）
main fd056fb87a292bc11289e0368c0120f0e3121266

## 问题描述（Describe）
工单驳回后无法修改SQL语句，没有输入框，按钮无法点击

## 截图或日志（Log）
![img_v3_02d5_b469f480-d0ef-4c0a-929e-ac283fb1882g](https://github.com/user-attachments/assets/5ff01e40-b091-4d73-b5f6-ef3d2303f6bf)

![image](https://github.com/user-attachments/assets/41ef2a7f-7c33-4b79-98a3-aec9aaa4e1ae)

## 如何复现（To Reproduce）
1. 创建工单并自动审核通过
2. 人工驳回工单
3. 点击“修改审核语句”

**Comment by BugsGuru** [comment]
1. 跟前端沟通下来是因为：`/v1/tasks/audits/{task_id}/ [get]`这个接口没有返回 sql_source，前端会根据这个值来处理用什么方式修改 sql
2. 后查看`/v1/tasks/audits/{task_id}/ [get]` 接口代码没有问题，是tasks表未存sql_source，导致该接口未返回sql_source
3. 后定位到创建工单点击审核时，会调用`/v1/task_groups/audit [post]`接口，该接口进行tasks表记录的更新，这部分代码存在问题
4. 但主分支问题代码已被修复：https://github.com/actiontech/sqle-ee/blame/03049844e2fe8797be4c0764cd36e8f0291dbf0a/sqle/api/controller/v1/task.go#L1039
5. 在3.2408.0-pre1版本验证该问题已被修复

**Comment by hasa1K** [comment]
## 版本
sqle-main-ee: 3352722b0f9dbbe242a50632d4a234a80c2b7fd0
## 测试
修改驳回之后的工单
![image](https://github.com/user-attachments/assets/8e5c8767-d515-4e94-a669-77c09dd6b365)
![image](https://github.com/user-attachments/assets/b1a01d98-a6ee-49b9-92e0-2afa3324dff5)
![image](https://github.com/user-attachments/assets/7ac787b0-6f08-4e50-9381-2d3ed47a948c)
