### ISSUE TITLE
快捷切换项目时，项目概览数据不变更

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/sqle#2522]
## 版本信息（Version）
UI: main d11b4e17
DMS: main-ee ae7bae69c7
SQLE: main-ee d9b21b4118

## 问题描述（Describe）
停留在项目概览页面，此时切换项目，项目概览页面的数据不会基于项目做变更，需要点击项目内其他页面，然后再点击项目概览，数据才会变更

default项目
![image](https://github.com/user-attachments/assets/3971f3d0-9b0b-41e7-9762-e580002e7ea3)
切换为test项目
![image](https://github.com/user-attachments/assets/263261af-b9b1-47ef-a671-a8409622119a)
实际test项目数据
![image](https://github.com/user-attachments/assets/11611259-efe9-4c87-bdca-600c9f0cc978)

**Comment by hasa1K** [comment]
## 版本
dms-ui-ee:64dd6152bc1130af44c2c49207fc651de9a8dc2a
## 测试
default项目概览页面
![image](https://github.com/user-attachments/assets/d6903254-1fd7-46da-9d6e-76d32e734226)
切换至test1之后，项目概览页面发生改变
![image](https://github.com/user-attachments/assets/b3296f70-b589-4f50-8a3d-0109d06935d7)
