### ISSUE TITLE
智能扫描重构遗留问题处理

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2523]
原始issue：https://github.com/actiontech/sqle-ee/issues/1576
## 需求描述（Describe）
- [x] 扫描任务跑增量同步时，获取到不需要同步的任务问题修复
- [x] mysql慢日志采集时，start_time字段未保存问题修复
- [x] mysql慢日志新增“启动任务时拉取慢日志时间范围”参数
- [x] 智能扫描自定义参数间的联动
- [x] TBase数据源扫描任务概览新增连接信息字段 @taolx0 
- [x] 扫描任务详情表格数据加载异常 @LZS911 
- [x] 智能扫描配置以及概览表格操作列按钮前端权限控制 @LZS911 
- [x] 创建智能扫描任务时数据源获取需要根据权限进行筛选 @LZS911

**Comment by taolx0** [comment]
# TBase数据源扫描任务概览新增连接信息字段

## 方案

## 影响面

- 需要使用最新版scanner

**Comment by LordofAvernus** [comment]
## 智能扫描报告中LastCollectTime字段与同步任务更新冲突问题
- AuditPlanV2表是否仅作为配置表，如果仅作为配置表存在，LastCollectTime属性与表定义存在冲突
- 当AuditPlanV2作为扫描任务记录，那么默认update_time字段值的变更，不应该被识别为任务做变更。应该由其他标准来确认配置变更（才能做出任务更新/删除动作）

![img_v3_02di_b7dd19cf-eaa5-43ef-9693-2b4d406280cg](https://github.com/user-attachments/assets/4606314e-762a-46a4-86a3-32c3ec2cca0a)

**Comment by iwanghc** [comment]
现象：创建oracle扫描任务时获取不到TOP SQL任务类型
oracle扫描任务获取的instance type错误

**Comment by iwanghc** [comment]
## 新增优化点：

- 增加一个手动触发审核的按钮
智能扫描详情，需要有个“立即审核”按钮。覆盖当前审核结果
- 智能扫描的详情页面需要增加sql分析
扫描详情中SQL分析按钮，希望放在右侧抽屉中

**Comment by iwanghc** [comment]
## 智能扫描动态参数联动问题方案
### 背景：
慢日志类型参数“采集周期”、“启动任务时拉取慢日志时间范围”仅对 mysql.slow_log 表有效，所以需要在当采集来源选择slow.log文件采集时隐藏这两个输入框。
### 方案一：
后端修改GetAuditPlanMetas接口层的ParamsRes参数结构，调整ParamsRes为父子结构，或ParamsRes新增字段关联需要联动的key与value
优点：返回的结构清晰
缺点：前后端都需要调整，且不易做成通用，成本较高
影响面：如果仅对mysql慢日志参数特殊处理的话不影响其他扫描任务类型。
### 方案二：
前端对mysql慢日志的参数做特殊处理
优点：成本小，后端不需要调整
缺点：处理后续新增的扫描任务类型或以后其他需要联动的参数
影响面：不影响其他
![image](https://github.com/user-attachments/assets/92c4ee68-ab67-4bec-9a33-bc6d255d2be3)

**Comment by iwanghc** [comment]
### 扫描任务操作按钮根据权限显示和隐藏
1、创建编辑页面，可选数据源根据权限显隐【前端】
2、页面增删改和立即审核按钮根据权限显隐【前端】
3、实例扫描任务接口返回instance id，支持前端获取权限【后端】

**Comment by LZS911** [comment]
## 扫描任务详情表格数据加载异常

例：
![image](https://github.com/user-attachments/assets/ca457726-bc67-4fd5-825f-4fce48e02966)
此时为初次通过SQL优先级筛选，数据正常。

清楚筛选后再次筛选，表格数据出现异常
![image](https://github.com/user-attachments/assets/3eb12850-09a0-406f-9080-73bdc46952c0)
可以明显发现表格数量多于接口返回的数据。

**Comment by iwanghc** [comment]
关联Comment：https://github.com/actiontech/sqle/issues/2523#issuecomment-2295848522
实例扫描任务列表instance_id出现精度丢失
解决：返回转成string返给前端

**Comment by iwanghc** [comment]
关联遗留问题：https://github.com/actiontech/sqle/issues/2572

**Comment by hasa1K** [comment]
## 

## 测试
 mysql慢日志采集时，start_time字段未保存问题修复
![image](https://github.com/user-attachments/assets/80a7d46e-8033-47c6-bf78-0e0ab77861e4)
start_time字段有值，符合预期
扫描任务没有增量同步
![image](https://github.com/user-attachments/assets/f80b3db1-767a-4e4f-bd5a-86e20965388e)

 扫描任务跑增量同步时，获取到不需要同步的任务问题修复
停用慢日志扫描任务
![image](https://github.com/user-attachments/assets/25379249-0844-4d02-bbb0-d30366b2fed1)

数据库中新增慢日志
![image](https://github.com/user-attachments/assets/3b98751a-1afd-4444-80da-73ca7ed89ba4)

sql_manage_records表没有新增慢日志
![image](https://github.com/user-attachments/assets/3dc4beef-2589-441f-8e63-66a4af4c97d4)
