### ISSUE TITLE
推送报告

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2527]
## 需求描述（Describe）
- SQL管控整理出已知的问题SQL后，仅提供页面的统计展示对于用户不够友好。期望能将问题SQL通过现有的一些推送渠道发送到指定用户的应用上
- 推送报告在工单流程已经默认应用，只是该推送配置不可见。当前实现功能会同时提供工单流的推送配置更新和展示

## 实现方案
1. 增加推送报告配置
    不同来源的报告（工单/SQL管控） 推送给用户（权限控制/指定用户）
2. 新增页面展示推送报告配置
3. 支持更新推送报告

### SQL管控报告推送任务点

- [x] 高优先级接口参数/字段定义
- 项目新增 数据新增 handle / 项目移除数据清理 handle
- 定时任务运行 = 采集时间变更
- 智能扫描SQL高优先级展示

**Comment by LordofAvernus** [comment]
# 新增优先级字段
## 当智能扫描/SQL管控维护的SQL，新增优先级字段，优先级高的SQL会统一推送给配置用户

## 变更点
sql管控记录表新增优先级字段，支持该字段在列表接口筛选和展示

**Comment by hasa1K** [comment]
## 版本
sqle-ee:55917e1f1c5485f612f189dca241885e6e599846
## 测试
配置推送规则
![image](https://github.com/user-attachments/assets/ccb82a00-e598-4a5d-8539-d052a7340641)
有高优先级sql
![image](https://github.com/user-attachments/assets/c1799b7c-e6e8-4584-838a-e83fafcb8a1a)
飞书可以接收到信息
![image](https://github.com/user-attachments/assets/e7522247-62ab-49b7-bec0-b3ac7881a948)
