### ISSUE TITLE
智能扫描导出文件用WPS查看异常换行优化

### ISSUE THREAD

**Issue by BugsGuru** [actiontech/sqle#2530]
## 描述（Describe）
智能扫描详情导出SQL的csv文件，使用WPS查看时异常换行。

## 截图或日志（Log）
![img_v3_02dc_bc5cb120-52f0-4375-b3e7-cb8600e6813g](https://github.com/user-attachments/assets/7ddf53bc-45a7-4ba0-b1e4-df3516aff4aa)

## 原因分析
Excel类工具单元格字符数存在上限（32767），达到这个上限就会导致换行。原始sql列内容会超过该限制。

## 优化方案
当字符数达到上限时，对列内容字符进行截取，并在末尾追加` ...`标志。

#### 受影响的模块或功能

智能扫描详情sql导出

**Comment by hasa1K** [comment]
## 版本
sqle main-ee:3a655e65087af35075c0fffcb3863cb0da645aee

## 测试
准备手动修改数据库中的值，将sql_text字段存储的值长度超过32767
![image](https://github.com/user-attachments/assets/33d158e9-9af7-473e-b95f-9f26311ed0b2)

wps打开后，超过32767的部分用三个点替代了
![image](https://github.com/user-attachments/assets/b3448a03-5ca1-4132-9d93-26f5268a3ff2)
