### ISSUE TITLE
智能扫描配置高优先级SQL

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2539]
## 需求描述（Describe）
入口
智能扫描配置页面

权限
拥有该类型智能扫描创建/编辑权限

需求细节
在智能扫描相关字段下，新增一个开关“标记高优先级SQL”

说明：开启后，符合高优先级标准的SQL将被标记，并推送至指定成员

默认状态为关闭
开启后，需要配置问题标准，参考如下
 

基于不同扫描类型，展示的问题标准
`
库表结构：
审核等级 > warning
慢SQL：执行时间超过？秒的SQL
慢查时间（秒） > 4
审核等级 > warning
TOPSQL
选择的阈值(单位) > ？
会话SQL
会话时间 > warning
JAVA应用程序中的SQL
审核等级 > warning
`

 

保存后，采集到的SQL中，如果符合问题标准，SQL将识别为高优先级的SQL
同时会根据推送配置推送给指定的用户
 

## 实现方案
- 扫描任务原始配置根据不同的类型新增默认筛选条件
- 获取扫描任务Meta接口返回对应的筛选条件
- 新增/创建扫描任务新增筛选条件参数
-

**Comment by LordofAvernus** [comment]
## 智能扫描SQL详情页面 支持高优先级SQL展示和筛选

**Comment by hasa1K** [comment]
## 版本
sqle-ee:785fbb3ad5781a9c2a004131aef5994a2aef2f2e

## 测试
库表元数据开启高优先级sql
![image](https://github.com/user-attachments/assets/a5801ff2-6845-4d87-8b99-48354eb8325e)
标记为高优先级sql
![image](https://github.com/user-attachments/assets/cc9761df-d79a-43a7-8ea5-aa1f3666d0b8)
飞书可以收到信息
![image](https://github.com/user-attachments/assets/a04fdb37-d796-4dd3-8af8-1a37f78e23de)
