### ISSUE TITLE
【智能扫描】sql立即审核和sql分析功能

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2544]
## 需求描述（Describe）
- 增加一个手动触发审核的按钮
- 智能扫描的详情页面需要增加sql分析

## 实现方案
智能扫描详情，需要有个“立即审核”按钮。覆盖当前审核结果
扫描详情中SQL分析按钮，希望放在右侧抽屉中
#### 受影响的模块或功能
无

#### 外部引用的潜在问题或风险
无

#### 版本兼容性
兼容

#### 测试建议
无

**Comment by hasa1K** [comment]
## 测试
前端有立即审核按钮
![image](https://github.com/user-attachments/assets/a5e27546-ad84-4512-b7bb-9ad603f7bd9f)
点击后，审核内容多出一条
![image](https://github.com/user-attachments/assets/30cb4c73-aee6-4fbc-b701-f9a8dabed4ca)

sql分析功能
![image](https://github.com/user-attachments/assets/5b1cdb9c-1c54-4b90-8ccf-c9aaf7f2b78c)
分析结果
![image](https://github.com/user-attachments/assets/121b3429-f854-4e96-ac36-0620e89de1e0)
![image](https://github.com/user-attachments/assets/3ea42091-fd8e-416a-ac8b-0f31367508ce)
