### ISSUE TITLE
智能扫描SQL详情页面 支持高优先级SQL展示和筛选

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2550]
## 需求
智能扫描支持高优先级SQL配置，目前只有库表元数据和MySQL慢日志支持了SQL详情页面. 其他任务类型没有定制的高优先级参数。暂时将触发规则级别作为通用的配置。同时智能扫描SQL页面使用通用筛选参数和展示（规则/sql/优先级）

## 实现效果

-  任务SQL页面都支持高优先级参数的展示和筛选
-  任务SQL页面新增通用的sql/rule的筛选条件
![image](https://github.com/user-attachments/assets/b84974a0-e556-42be-a8c9-e2ed9ba35f8d)

-  任务增加默认的高优先级配置（audit_level)

![image](https://github.com/user-attachments/assets/e898d756-c847-45f5-9463-b0ef601e67b0)

_Originally posted by @LordofAvernus in https://github.com/actiontech/sqle/issues/2539#issuecomment-2298025206_

**Comment by hasa1K** [comment]
## 版本 
sqle main-ee: 3a655e65087af35075c0fffcb3863cb0da645aee
## 测试
开启`标记高优先级sql`
![image](https://github.com/user-attachments/assets/cf8f26bb-95af-4413-96a9-a856d8bb717f)
sql被标记
![image](https://github.com/user-attachments/assets/6b357ab6-80be-4398-b3ef-4fc35bc00cf5)
可以进行筛选
![image](https://github.com/user-attachments/assets/80567305-f033-4091-8d71-5ba1bc7170a7)
