### ISSUE TITLE
前端界面优化

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2558]
## 问题描述（Describe）
1. 页面标题统一
![img_v3_02e0_f09fee28-40a1-4e03-b4b7-44497a9e2cag](https://github.com/user-attachments/assets/a1bdd6c1-527b-4e59-87c9-e008da8184ff)
2. 创建扫描任务时，支持手动筛选数据源
![image](https://github.com/user-attachments/assets/130fca2c-679c-4de0-9744-cc9707844098)

**Comment by hasa1K** [comment]
## 版本
dms-ui-ee:79a479a48cac13c02cf9ab599f75f1f454c72f2d

## 测试
标题得到统一
![image](https://github.com/user-attachments/assets/ddf9a812-de3d-4ce5-acd9-d0ac40002fa4)
