### ISSUE TITLE
快捷审核sql同步到sql管控

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2561]
## 需求描述（Describe）
快捷审核中打标签的sql同步到sql管控中

## 实现方案
1、快捷审核打标签的sql同步至sql管控中。
2、调整sql管控model，预期希望管控的表不需要关联来源表。
3、修改智能扫描model中的sql语句，补充sql_manage_records与sql_audit_plans_v2的关联关系（类型与来源）
4、调整来源为智能扫描任务的sql_manage_records表source_id为instance_audit_plan_id（跳转概览界面需要instance_audit_plan_id）
#### 受影响的模块或功能

sql管控
智能扫描
快捷审核
#### 外部引用的潜在问题或风险

无
#### 版本兼容性

不兼容
1、sql_manage_records表source_id字段类型由bigint调整为string。
2、sql_manage_records表source_id来源为智能扫描的改为实例任务id，且对应的sql_id也要同步更新。
#### 测试建议

1、验证快捷审核打标签与标签删除，以及多条审核相同指纹在sql管控的合并
2、合并的sql跳转快捷审核，列表形式展示
3、sql管控跳转智能扫描

**Comment by iwanghc** [comment]
## 升级方案：
1、更新sql_manage_records表source_id字段类型由bigint调整为string。

2、更新sql_manage_records表source_id的值为instance_audit_plan_id（条件为source <> 'sql_audit_record'）

3、因为source_id变了， 所以要更新sql_manage_records表的sql_id（条件为source <> 'sql_audit_record'）

**Comment by hasa1K** [comment]
## 版本

## 测试
快捷审核sql语句，并打上标签
![image](https://github.com/user-attachments/assets/4eebd6da-f29e-4394-8408-98b270c41008)
同步成功
![image](https://github.com/user-attachments/assets/4c8b7d4d-a2b9-424e-868f-625c1667e156)
快捷审核sql文件，并打上标签
![image](https://github.com/user-attachments/assets/73f06e9f-df6f-4098-8929-8e2127433dab)
![image](https://github.com/user-attachments/assets/b852d1ca-7a7b-4359-95db-27b9b216b1f8)
sql管控同步成功
![image](https://github.com/user-attachments/assets/d015caa9-491d-4234-b8fa-5f621a87f356)
