### ISSUE TITLE
关闭工单按钮添加二次确认

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2581]
## 版本信息（Version）
UI: main 02f867e7
## 问题描述（Describe）
关闭工单没有做二次确认，用户误触后，工单目前不支持开启，影响比较大。建议先对关闭工单按钮做二次确认
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/9ff13f75-b81d-41cb-917f-e4743fa195df)

## 如何复现（To Reproduce）
创建工单后进入工单详情页面

## 解决方案
关闭工单时添加二次确认提醒。

**Comment by Gygkimo95** [comment]
点击关闭工单按钮，出现二次确认弹窗，符合预期
![image](https://github.com/user-attachments/assets/d1f69efc-567a-4c06-bd24-fd3664f714f9)

可优化点：是否可以在提示文字中完整表述关闭工单的影响？
如：工单关闭后将无法再对工单执行任何操作，是否确认关闭当前工单？
