### ISSUE TITLE
Scannerd：社区版代码包含企业版Scannerd扫描任务的问题

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2585]
## 版本信息（Version）
latest-ce
## 问题描述（Describe）
1. 目前已知tidb扫描任务是企业版，但在社区版的meta中，需要将其移动到企业版代码
2. 需要再看看其他的scannerd是否有相同问题

sqle/server/auditplan/meta.go
``` golang
	TypeTiDBAuditLog          = scannerCmd.TypeTiDBAuditLog
......
	{
		Type:          TypeTiDBAuditLog,
		Desc:          "TiDB审计日志",
		TaskHandlerFn: NewTiDBAuditLogTaskV2Fn(),
	},
```
## 变更影响面

社区版不再支持TIDB审计日志功能

**Comment by taolx0** [comment]
![tidb1](https://github.com/user-attachments/assets/d46596c2-2295-45f5-b060-95226fc4bf51)
![tidb2](https://github.com/user-attachments/assets/b1130a9e-906f-4c36-ae68-866a4bf088de)
