### ISSUE TITLE
智能扫描审核结果描述丢失

### ISSUE THREAD

**Issue by BugsGuru** [actiontech/sqle#2596]
## 版本信息（Version）
sqle 76ba04301923d3195bfa9b7298c69e9ae1e51c7d

## 问题描述（Describe）
开启智能扫描后，扫描结果中审核结果描述为空。

## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/1cf00038-cd9d-415a-9f04-1e4d6793b5db)

sql管控中审核结果描述可以正常显示
![image](https://github.com/user-attachments/assets/619d0df9-5db3-468e-a1d0-3cd63b362e70)

## 如何复现（To Reproduce）
开启扫描任务，在SQL管控配置里概览页查看扫描到的sql审核结果。

## 问题原因
这里的审核结果，接口是直接返回的数据库审核结果字段的json格式内容。国际化后该json结构变更，描述字段弃用未同步。
![image](https://github.com/user-attachments/assets/e46c0d14-cf51-4f74-b517-a4bc2e6ae445)

## 解决方案
从国际化的描述中获取对应语言的描述，响应给前端

**Comment by Gygkimo95** [comment]
可以正常查看审核结果，符合预期
![image](https://github.com/user-attachments/assets/0d930e64-86c1-4ca1-9367-e455c6e1fd92)
