### ISSUE TITLE
工单提交，若需审批成员过多时会报错数据超长

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2601]
## 版本信息（Version）
SQLE：main 141b8a1a944216a14f78036c322c93ba5d7abdb4
DMS：main 20d313b918e8d7b0f844352da3b4ef0d146119ff
UI：main 33925954
## 问题描述（Describe）
审批流程模版，匹配拥有数据源审核权限的，若在成员权限中配置超过20人会提示报错（execution_assignees字段长度为255）
## 截图或日志（Log）
![img_v3_02el_6c7938a9-b75c-40ac-a23d-8982bb99128g](https://github.com/user-attachments/assets/142e1922-5fb4-46e8-9fcc-b9158c5bc917)
![image](https://github.com/user-attachments/assets/919797f2-d434-45b7-b618-8d3791f4fdfe)
![image](https://github.com/user-attachments/assets/81961caa-59dc-419a-bc04-cc28f174db45)

修复时注意影响工单列表显示
![image](https://github.com/user-attachments/assets/f129f000-75ba-497b-b4b0-e5abd59c4360)

## 如何复现（To Reproduce）
1、用户中心添加用户20个
2、在成员与权限中，创建成员组，把这20个用户添加到组内，并且给SQLE管理员和数据源权限
3、sql工单中创建工单时选择第2步中的数据源，点击提交，页面提示报错

## 解决方案

增大工单审批人的数量,升级后,最大能支持100人

## 升级方案

增加以下4张表分配人员的长度
```sql
ALTER TABLE sqle.workflow_instance_records MODIFY COLUMN execution_assignees varchar(2000);

ALTER TABLE sqle.sql_manage_record_processes MODIFY COLUMN assignees varchar(2000);

ALTER TABLE sqle.sql_manages MODIFY COLUMN assignees varchar(2000);

ALTER TABLE sqle.workflow_steps MODIFY COLUMN assignees varchar(2000);
```

**Comment by taolx0** [comment]
![num1](https://github.com/user-attachments/assets/b7061e3e-4f55-4727-a6df-dd5eb2f76f88)
![num2](https://github.com/user-attachments/assets/b6ddee60-b15f-41be-999e-8e8bcb6b500a)
