### ISSUE TITLE
FingerPrint算法数组越界导致Panic

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2603]
## 版本信息（Version）
sqle@latest
## 问题描述（Describe）
使用特定SQL生成指纹时，由于生成的指纹长度大于原有SQL，FingerPrint算法访问的数组越界，产生panic
类似问题：https://github.com/percona/go-mysql/pull/30

## 临时修复方案
1. 在每次访问数组前（10处）判断数组是否越界，若越界，返回原始SQL，并且在外侧打印日志
![img_v3_02el_58d1472e-f982-4d87-b0ff-29e99e13c2dg](https://github.com/user-attachments/assets/e20e0d7c-214c-4d2b-8913-2f96560ca01d)
![img_v3_02el_09136c0b-a0b9-41c7-929d-bb84725b1b4g](https://github.com/user-attachments/assets/1f9b28f1-c7f3-412b-97dc-85e44eb3a2c9)

## 如何复现（To Reproduce）
``` golang
func TestName(t *testing.T) {
	fp := query.Fingerprint(`insert into tb values(1)`)
	fmt.Println("11", fp)
}
// 这条SQL虽然是错误的，但也可以触发panic ：SELECT*FROM (SELECT * FROM tb values(1));
``` 

## 问题原因
github.com/percona/go-mysql/query的指纹生成函数缺陷

## 解决方案
使用github.com/actiontech/sqle/sqle/driver/mysql/util中的指纹函数替换

**Comment by taolx0** [comment]
纯后台修改,通过代码验证
![image](https://github.com/user-attachments/assets/1dbe27af-c15c-4902-bbb9-1fe71dd46ba1)

**Comment by BugsGuru** [comment]
修复后生成的指纹会有些区别
eg:
- 指纹关键字是大写字符
- 指纹中表名、字段名带反引号

### 影响面
1. sqle/pkg/driver/impl.go 中 DriverImpl.Parse 方法中
这里业务没有直接使用，插件中也会自己实现Parse方法，暂无影响
2. sqle/cmd/scannerd/scanners/tidb_audit_log/audit_log_ee.go
这里会导致使用scanner上报相同sql的指纹不一致，导致智能扫描中统计数据无法与旧记录一起计算

**Comment by ColdWaterLW** [comment]
## 3.2404.1 临时处理的原因：
1. 3.2407.0开始，智能扫描已经重构，且不再使用query.Fingerprint(sql)这个函数，不会再有panic问题
2. 本次处理在小版本3.2404.1发布，如果使用和3.2407.0之后相同的修复方案，旧的指纹和新的指纹会有不一样。对于旧数据的影响面很大，升级成本较高
