### ISSUE TITLE
新增平台管理平台统计权限

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2619]
# 描述

新增平台管理和平台统计权限

平台管理权限可以操作平台的所有资源,相比admin用户,存在以下限制:

1. 平台管理权限必须由admin创建
2. 平台管理权限互相之间不能修改权限,admin可以修改平台权限

平台统计权限可以查看平台的所有资源,但是不能对资源进行修改

需求背景:

1. 新增的用户需要查看所有项目,假设客户有200多个项目,需要一个个项目添加权限,工作量大
2. 提供可以创建与Admin权限相同的管理用户功能

# 实现方案

- [x] 新增平台管理权限
- [x] 新增平台统计权限

注意点:

- [x] 平台管理权限必须由admin创建
- [x] 所有账号不得修改admin账号
- [x] 平台管理权限互相之间不能修改权限,admin可以修改平台权限
- [x] UI页面的权限控制(接口GET /v1/dms/users/{user_uid})

**Comment by iwanghc** [comment]
UI: main 7f74b66a
DMS: main ab1340f2e9e519e57707e382f7b0de6707bca93f
SQLE: main 0987689a83b64bb0ab82e5fe69c058f948ed7106

用户中心可查看到全局浏览和全局管理的权限
![image](https://github.com/user-attachments/assets/7a5a7bbb-c0ad-4167-8135-57feced045c4)
使用admin账户对用户u赋予全局浏览和t、a赋予全局管理的权限
![image](https://github.com/user-attachments/assets/b905e1ab-f466-4c08-aecf-87f24f3cab03)
### 登录全局管理权限的t账户
拥有全局管理权限的用户直间不能相互修改权限，符合预期
（非admin账户单向操作，只能给一个用户赋全局管理而不能取消，需考虑合理性）
![image](https://github.com/user-attachments/assets/89311e2f-24d9-47b7-bd2d-35705bf5bfa4)
t用户可以创建和管理项目
![image](https://github.com/user-attachments/assets/ee467d28-95e8-4749-8fa4-2181d73f0464)
t用户拥有所有数据源权限
![image](https://github.com/user-attachments/assets/a2a88cda-51ab-4646-bb5f-9c0cac5ba5b3)
t用户可以管理所有项目下的数据源
![image](https://github.com/user-attachments/assets/aee9c22a-edff-4aa6-8f41-1c5dafd77ba4)

### 登录全局浏览权限的u账户
u账户可以浏览所有项目，但不能操作，符合预期
![image](https://github.com/user-attachments/assets/615c50f4-b1e1-44b8-979a-9e362f240f38)
u账户可以浏览所有工单，但无权操作，符合预期
![image](https://github.com/user-attachments/assets/64464647-bd99-43a1-8f82-5c4cbcbb8067)
点击关闭工单，提示错误，预期不显示
![image](https://github.com/user-attachments/assets/722cdc0d-7ef6-46bc-be69-3b03bb48ce62)

验证点：
admin赋权
全局管理用户间赋权约束
全局管理权限的用户可操作性
全局浏览权限的用户可浏览内容

**Comment by taolx0** [comment]
# 现象

拥有全局管理权限的用户可以将普通用户更新为全局管理用户

# 修复

拥有全局管理权限的用户不能将普通用户更新为全局管理用户

# PR链接

https://github.com/actiontech/dms/pull/315
