### ISSUE TITLE
自定义扫描任务TOKEN没有展示到页面

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2646]
## 版本信息（Version）
3.2408.0
## 问题描述（Describe）
智能扫描06版本升级后，页面只能看到启动scanner的命令，无法直接获取到token。自定义扫描任务需要使用方自行对接，所以页面/接口均没有返回对应的TOKEN，导致执行上传SQL时无法通过校验
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/29177fd6-40c2-4e90-b3eb-02d141f3a86d)

## 如何复现（To Reproduce）
1. 创建自定义扫描任务
2. 手动调用接口（ /:project_name/audit_plans/:audit_plan_id/sqls/upload）上传SQL

## 问题原因
自定义扫描任务没有返回token
## 解决方案
- 页面/接口提供token返回值
`--host=<IP> --port=<port> --project=default --audit_plan_id=3  --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcG4iOiJjNGNhNDIzOGEwYjkyMzgyMGRjYzUwOWE2Zjc1ODQ5YiIsImV4cCI6MTc1NzQxNDczMSwiaXNzIjoiYWN0aW9udGVjaCBkbXMiLCJ1aWQiOiI3MDAyMDAifQ.S0hqwpdBCBHbXgeb1o3sTKmQdxoCeNs1k5hqiNSrOIQ
`
临时解决方案：
   从数据库中instance_audit_plans表中查询到token字段
## 变更影响面

- SQL管控配置-详情
#### 受影响的模块或功能

- SQL管控配置

**Comment by littleniannian** [comment]
@LordofAvernus 
- 智能扫描06版本升级后，页面只能看到启动scanner的命令，无法直接获取到token 这个描述在页面的哪里？
- 截图中的`go run upload_sql`是个什么功能？
- 期望在哪个页面/接口返回token?

**Comment by taolx0** [comment]
--host=127.0.0.1 --port=10000 --project=700300 --audit_plan_id=3 --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcG4iOiJjODFlNzI4ZDlkNGMyZjYzNmYwNjdmODljYzE0ODYyYyIsImV4cCI6MTc2MjMyNDQzMSwiaXNzIjoiYWN0aW9udGVjaCBkbXMiLCJ1aWQiOiI3MDAyMDAifQ.kmikb_GfEo2rcO7wexpdsYsZJIyC4-OnytZDPM8wfMo

![cus1](https://github.com/user-attachments/assets/3b5785e9-5bda-4f7a-9412-e7345a59b503)
