### ISSUE TITLE
删除用户后,项目概览页面报错

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2658]
## 版本信息（Version）

3.2410

## 问题描述（Describe）

创建某一个用户user1,使用user1用户登陆sqle,user1用户创建SQL工单,当工单状态是被驳回状态或上线失败状态时,删除user1用户,查看项目概览页面,页面报错

## 截图或日志（Log）

![image](https://github.com/user-attachments/assets/b51d2fdb-009a-438f-b50b-a91958f91967)

## 如何复现（To Reproduce）

1. 创建用户user1
2. 使用user1用户登陆sqle
3. user1用户创建SQL工单
4. 驳回该工单
5. 删除用户user1
6. 打开项目概览页面报错

## 问题原因

用户user1被删除后,项目概览工单风险接口获取工单创建用户失败

## 解决方案
当用户被删除后，应该参照SQL工单中的用户名返回`username[x]`.
## 变更影响面

- 项目概览
#### 受影响的模块或功能

- 项目概览

**Comment by littleniannian** [comment]
自测通过截图
![image](https://github.com/user-attachments/assets/a91d4707-7c09-4e0f-a4bd-eb20473f8a44)
