### ISSUE TITLE
前端语言偏好默认值设置以及页面样式调整

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2660]
## 需求描述（Describe）
1. 当用户未设置用户的语言偏好时，前端默认读取浏览器的语言偏好，而不是默认中文
2. SQL管控 - 变更状态、变更优先级弹窗中对齐选项
![image](https://github.com/user-attachments/assets/eb29d12e-7c12-481c-8721-fb40532605d1)
![image](https://github.com/user-attachments/assets/3685899b-728c-4285-a703-b9d325fa5f1a)

**Comment by LZS911** [comment]
语言偏好默认值前置issue：https://github.com/actiontech/sqle/issues/2626

**Comment by winfredLIN** [comment]
## 测试版本
7f74b66ae5d4a0d602b072988834ca0a358c5ec7

**Comment by Gygkimo95** [comment]
按钮已对齐，符合预期
![image](https://github.com/user-attachments/assets/37314238-341c-470e-88e9-132e012ec20c)
![image](https://github.com/user-attachments/assets/be04dacb-8e6f-402f-bdaf-b77e11a7244d)
