### ISSUE TITLE
停用过期工单自动删除job

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2667]
## 需求变更至：
https://github.com/actiontech/sqle/issues/2667#issuecomment-2413166180

### ~~需求描述（Describe）~~
背景：sqle现在会对过期工单做硬删除，过期时间在系统配置里，默认30天。 使用了一段时间发现工单数量比预期的少，实际是因为过期被删除了
1. 在全局设置中，用户可以自主设置，清除已完成的工单的时间（包含默认值30天）。
2. 但该设置并没有相应引导机制，对于用户来说可能并不知道有这个功能。
3. 这会导致一个问题，在用户不知情的情况下，有一些已完成的工单被删除了，无法追溯。
4. 删除工单可能导致其他与工单联动的系统的数据在SQLE侧没有对应工单，导致联动失败，需要考虑这一点
![image](https://github.com/user-attachments/assets/23966992-e18b-4a0f-be37-a2de7a3ea410)

需要优化这个机制：
~~1.是否可以增加存档机制，将被清除的工单记录保存下来，以供恢复和追溯~~
2. 是否在用户没有主动设置该功能的时候，不自动清除工单，避免用户产生疑惑，以及对用户数据造成影响。
3. 是否可以在清除的时候增加清除动作的记录，~~例如在审计中或日志里体现。~~ 记录在日志文件中。

**在以上背景基础上，将目前所有全局配置都新增一个控制开关**

## ~~实现方案~~
- 定期清理工单：单位小时，默认关闭，开启给默认值8760小时。
- 定期清理操作记录：单位小时，默认关闭，开启给默认值2160小时。
- 定期清理CB工作台操作审计：单位小时，默认关闭，开启给默认值720小时。
- URL地址前缀：默认开启。

开发方案：
1、全局配置表新增字段is_enable，标识全局配置的启用和关闭
2、修改查询和更新全局配置改接口，补充is_enable字段
3、在CleanJob中，清理过期工单和清理过期操作日志的判断is_enable
4、在dms的定时清理过期cb审计记录中判断is_enable（ee功能）

**Comment by iwanghc** [comment]
经重新讨论决定：
调整方案，不再对全局配置进行优化，进行如下修改
1、取消工单过期时间，不再自动销毁工单（目前没有使用场景）
2、CB工作台操作过期时间默认值放大2160h（3个月）

**Comment by taolx0** [comment]
1. 移除取消工单过期时间
2. CB工作台操作过期时间默认值放大2160h（3个月）
![image](https://github.com/user-attachments/assets/36554849-9386-432e-89ca-7563664abc56)

**Comment by taolx0** [comment]
--host=127.0.0.1 --port=10000 --project=700300 --audit_plan_id=3 --token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcG4iOiJjODFlNzI4ZDlkNGMyZjYzNmYwNjdmODljYzE0ODYyYyIsImV4cCI6MTc2MjMyNDQzMSwiaXNzIjoiYWN0aW9udGVjaCBkbXMiLCJ1aWQiOiI3MDAyMDAifQ.kmikb_GfEo2rcO7wexpdsYsZJIyC4-OnytZDPM8wfMo

![cus1](https://github.com/user-attachments/assets/3b5785e9-5bda-4f7a-9412-e7345a59b503)

**Comment by iwanghc** [comment]
3.2404版本同步修复
