### ISSUE TITLE
全局待关注清单：基于角色的展示跨项目的全局的待关注的清单

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2675]
# 需求描述
本次需求背景是为多项目管理环境下的操作人员提供一个全局Dashboard，以便他们能够集中查看和管理跨多个项目的待处理任务和工单。这个Dashboard旨在提高工作效率，确保任务的及时跟进和处理。

# 页面细节
1. 功能入口在SQLE左侧菜单栏左上角的按钮
![image](https://github.com/user-attachments/assets/2d888a77-d565-488d-a775-0731344194cc)
2. 页面顶部有顶部筛选项，根据筛选项可对页面中的列表数据进行筛选，支持根据单个项目、单个数据源和单个项目优先级进行筛选
![image](https://github.com/user-attachments/assets/6f183857-5546-47d3-b59d-5d87041481c5)
3. 全局待关注清单，基于角色权限，区分不同用户视角，展示不同用户所需关注的清单。对于Admin（最高权限管理者）、具有全局管理权限和具有全局查看权限的用户，将会展示所有的待关注的信息。对于多项目管理者（1个以上的项目管理员权限），将会展示该用户所管理的所有项目的待关注信息。对于任务处理人，将会展示该用户所受理的工单和SQL。
4. 待解决工单页，该页面显示了使用者需要解决的工单
![image](https://github.com/user-attachments/assets/15f74bf5-0616-4f52-a161-9de851885f4f)
5. 待解决的SQL页，该页面显示了使用者需要关注的SQL，该功能是企业版，与SQL管控产生联动
![image](https://github.com/user-attachments/assets/7756c072-7d0f-4a1e-8ff2-07e0183cc565)
6. 发起的工单页，该页面显示了使用者发起的工单
![image](https://github.com/user-attachments/assets/8c4ff9ad-bf28-4345-abed-280884d3c052)

# 接口变更
1. 创建项目、更新项目和获取项目这三个接口，增加了项目优先级的可配置项，用于标记项目的重要程度
https://github.com/actiontech/dms/pull/310
https://github.com/actiontech/dms/pull/311
2. 新增全局SQL管控列表接口，用于显示待解决的SQL页
https://github.com/actiontech/sqle-ee/pull/1904

**Comment by winfredLIN** [comment]
# 项目增加优先级
## 创建项目
![image](https://github.com/user-attachments/assets/23655657-82a5-467b-b2b0-fe6f16bc769a)
![image](https://github.com/user-attachments/assets/63ca7a26-4045-4d1c-ae16-fbd01b822d7c)
![image](https://github.com/user-attachments/assets/5330fc1c-a8c7-4cc3-bc3e-bb4f3a04c373)
![image](https://github.com/user-attachments/assets/37376ae1-f7f6-4f4c-88a6-05e63ee80c96)

**Comment by winfredLIN** [comment]
## 目的
由于全局工单列表接口需要获取工单对应的项目优先级以及数据源信息。需要查询多个数据源和项目信息，因此需要增加批量查询的接口
## dms 批量筛选项目
![image](https://github.com/user-attachments/assets/82773dff-fc24-437a-bde4-b0798ffb5b49)
## dms 批量筛选数据源
![image](https://github.com/user-attachments/assets/b03637fb-6ee0-4ad8-acb3-7caa51a01e30)

**Comment by winfredLIN** [comment]
## 问题记录

1. func problemDescriptions(info string) []string函数，处理来自不同的扫描任务中高优先级的数据不一定都能满足，因此需要根据每一个扫描任务，确认描述信息的展示。展示的内容是该SQL成为高优先级SQL的原因。即哪些观测量触发了高优先级的规则

**Comment by winfredLIN** [comment]
## 当用户作为项目管理员的时候，也要显示他在其他项目中作为项目成员被分配的待处理的SQL
![image](https://github.com/user-attachments/assets/3ebd3a73-a233-4c7e-bff1-2234d93882c0)
![image](https://github.com/user-attachments/assets/456862d0-ef80-44ba-9b57-8d709786c94d)

**Comment by taolx0** [comment]
管理员用户能查看全局
![glo3](https://github.com/user-attachments/assets/3a3102cc-f330-4c66-9291-f78c841b5e16)
全局管理用户能查看全局工单
![glo1](https://github.com/user-attachments/assets/bb814b43-a2e4-460a-a156-7f3839db5c7f)
全局浏览用户能查看全局工单
![glo2](https://github.com/user-attachments/assets/725adf4b-9718-4520-a213-c539dcf2b6c6)
