### ISSUE TITLE
The task counter will not be cleared

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#268]
## 问题描述
#114 发现一个延申问题, 审核计划删掉再重新创建一个同名计划后, 审核执行时的任务报告ID(audit_plan_report_id)不会清零,而是从之前的那个审核计划的最后一个报告ID继续往下计数

## 修复方式
1. 前端将会隐藏报告ID, 改为展示报告通过率, 报告分数, 报告等级和审核时间, 审核结果以图标形式展示
2. 后端在 /v1/audit_plans/{audit_plan_name}/reports [get] 和  /v1/audit_plans/{audit_plan_name}/trigger [post] 中增加对应返回值

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/429

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证通过
验证步骤：
1.创建一个慢日志类型的审核任务
2.触发自动审核，然后查看审核记录
目前不会出现报告id，只会显示报告通过率, 报告分数, 报告等级和审核时间

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/54339501/160990532-5ed73911-dc38-40bf-ac27-2fcd36ba88b1.png">
