### ISSUE TITLE
使用脚本执行插件配置，脚本在最后应该restart服务

### ISSUE THREAD

**Issue by littleniannian** [actiontech/sqle#2682]
## 需求描述（Describe）
使用脚本执行插件配置，脚本在最后应该restart服务。
![image](https://github.com/user-attachments/assets/45aaaba8-25b0-4572-bc8e-77857026fcb6)
目前在执行`init_config.sh`后，会执行init脚本， 这里应该执行restart 重启dms,sqle。

## 实现方案
- 在`functions.sh`中增加`restart_sqle`方法
- `restart_sqle`方法的具体实现是先执行`stop_sqle.sh`, 后执行`init_start.sh`
#### 受影响的模块或功能

- 通过脚本配置数据库审核插件
#### 外部引用的潜在问题或风险

- 无
#### 版本兼容性

- 无
#### 测试建议

- 通过`init_config.sh`配置插件能否在SQLE不同的状态下进行正确的重启方式。
- 停止-启动SQLE
- 运行-关闭后启动SQLE

**Comment by taolx0** [comment]
重启SQLE
![image](https://github.com/user-attachments/assets/999895b8-848f-467f-bae1-54ddc789e3e0)
直接启动SQLE
![image](https://github.com/user-attachments/assets/faa44b4f-3b4d-45b2-80cb-7a0d423346b2)
![image](https://github.com/user-attachments/assets/269f2347-4224-4e66-9bda-fcd61d09c6e8)
