### ISSUE TITLE
规则分类展示为空

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2684]
## 版本信息（Version）
3.2409.0
## 问题描述（Describe）
当数据库插件没有的规则没有分类时，页面会有一个多余的分类框，值显示为0
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/cd080e8e-415f-4704-8f6e-1d49662b389c)

## 如何复现（To Reproduce）
使用规则分类都为空数据库插件，启动后在页面效果可见

## 问题原因
插件迭代后，移除了当前的规则分类。导致前端展示异常

**Comment by taolx0** [comment]
![image](https://github.com/user-attachments/assets/2662f69d-07c0-49bd-b931-60deadbed5e5)
