### ISSUE TITLE
docker-compose部署cloudbeaver

### ISSUE THREAD

**Issue by BugsGuru** [actiontech/sqle#2686]
## 需求描述（Describe）
在原有docker-compose部署sqle的基础上，增加cloudbeaver的部署

## 实现方案
1. 在镜像启动脚本start.sh中添加通过环境变量修改配置文件cb连接信息
2. docker-compose.yml中添加cloudbeaver服务，镜像使用：actiontech/cloudbeaver:latest

**Comment by taolx0** [comment]
![image](https://github.com/user-attachments/assets/81387ae7-6e9a-4705-883e-c27904ab82f4)
![image](https://github.com/user-attachments/assets/2df3acab-3ed2-4bd5-92ea-ccecf262387d)
