### ISSUE TITLE
全局待关注清单：增加红点和待办数量数据统计

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2701]
https://github.com/actiontech/sqle/issues/2675
## 需求描述（Describe）
1. 为了便于用户判断是否有待关注事项，以及待关注事项的数量，计划在全局待关注清单入口增加红点提示，在待关注清单中的三个tab页的tab处增加数量信息的显示。
![image](https://github.com/user-attachments/assets/30263baa-f7a4-4221-9069-2d5c34b642a3)

## 实现方案

1. 增加全局待关注清单，工单统计数量接口，社区版
2. 增加全局待关注清单，SQL管控统计数量接口，企业版
3. 增加系统模块红点接口，社区版

### 统计数量接口

- 新增统计全局待处理清单页面的统计数字接口的实现
- 统一管理全局待处理清单的权限处理
- 统一管理了全局待处理清单中，工单和SQL管控过滤逻辑
- 根据之前的修改建议，进行了一些其他优化

**Comment by winfredLIN** [comment]
## 测试
### 待处理工单，均符合预期
1. 待处理工单，不筛选工单
![image](https://github.com/user-attachments/assets/14c85b80-8187-404b-bc19-4effaccd387c)
2. 待处理工单，根据项目筛选
![image](https://github.com/user-attachments/assets/7c52f3cb-e529-41ef-bceb-f74561675206)
3. 待处理工单，根据优先级筛选
![image](https://github.com/user-attachments/assets/c98d6e1d-1309-4087-b3e1-1299108893a2)
4. 待处理工单，根据数据源筛选
![image](https://github.com/user-attachments/assets/9a1a09d7-e086-4f39-9049-706978b3f48d)
### 他人发起的工单 均符合预期
1. 不筛选
![image](https://github.com/user-attachments/assets/620d3e76-cef3-456c-a3d8-bd3e3f786395)
2. 根据项目筛选
![image](https://github.com/user-attachments/assets/c7f086dc-1532-4e6f-ac2a-be30e23db744)
3. 根据优先级筛选
![image](https://github.com/user-attachments/assets/e75b13ef-1b39-4eb0-bbba-61912adb10e3)
4. 根据数据与源筛选
![image](https://github.com/user-attachments/assets/1381f7aa-e87d-4188-9552-4b3d5f41c56e)
### 待处理SQL 
1. 不筛选
![image](https://github.com/user-attachments/assets/9860c13a-0ada-4e45-ae7a-77658d5b27cd)
2. 根据项目筛选
![image](https://github.com/user-attachments/assets/01fd7f75-23d2-4fb0-91ea-d774c97103d7)
![image](https://github.com/user-attachments/assets/e3031bed-a270-44f5-bb3b-2f0fa6e630f2)
3. 根据数据源筛选
![image](https://github.com/user-attachments/assets/61139969-1c97-4a05-9ca8-7efecfd33eac)
![image](https://github.com/user-attachments/assets/18b3d5a4-d361-417d-b28d-6bfb42358f2c)
4. 根据项目优先级筛选
![image](https://github.com/user-attachments/assets/d5f91f9b-d3bf-4785-807f-510252b60931)
![image](https://github.com/user-attachments/assets/63da4f8b-97f6-44b9-a844-9d1ef363a87a)

**Comment by winfredLIN** [comment]
## 测试
测试下面两个接口数量返回值是否准确
增加全局待关注清单，工单统计数量接口，社区版
增加全局待关注清单，SQL管控统计数量接口，企业版
### 待关注的SQL工单 符合预期
![image](https://github.com/user-attachments/assets/c8c750e1-ad6d-4c08-8ef8-49feccb26870)
![image](https://github.com/user-attachments/assets/da4394b1-16e5-42cd-baea-69a18d6fb489)

### 待关注的SQL管控SQL 符合预期
![image](https://github.com/user-attachments/assets/c8306c27-5d33-4bdd-8677-8967d1bd99bf)
![image](https://github.com/user-attachments/assets/834e7347-9773-4f8a-922a-c791d4f8f415)

## 待关注的发起的工单 符合预期
![image](https://github.com/user-attachments/assets/14d9cb75-101f-4f12-8f98-e6487afbdc24)
![image](https://github.com/user-attachments/assets/aadc41da-86b8-4494-8fe8-d2bbe6676f2f)

**Comment by winfredLIN** [comment]
## 系统红点提示
测试方式，使用对应有红点和没有红点的账户的dms-token调用红点接口
1. 有红点
![image](https://github.com/user-attachments/assets/0fe9d59e-cbb4-4d41-8d6e-f9b51b83b3e8)
![image](https://github.com/user-attachments/assets/dfd27fbb-0997-4816-add5-70dbb5be524f)
2. 没红点
![image](https://github.com/user-attachments/assets/2a7027e1-46b3-4f8a-99de-aeb69b953e0f)
![image](https://github.com/user-attachments/assets/4f1dadd4-0bad-4b1a-bc25-c2242198aa8d)
![image](https://github.com/user-attachments/assets/f6f3c0e1-ed6c-4127-857d-a802631d6959)
![image](https://github.com/user-attachments/assets/dfede33a-ae46-4411-bc05-b432ae3522d5)

**Comment by winfredLIN** [comment]
## 待解决SQL高优先级原因
在待解决SQL的说明列，根据SQL触发高优先级的规则，说明触发的原因，显示在说明列上
![image](https://github.com/user-attachments/assets/46509741-772e-4010-84a7-63badc11682b)

**Comment by taolx0** [comment]
![3gou](https://github.com/user-attachments/assets/837a9bec-f179-4390-9cb9-d17e588fe44e)
![6gou](https://github.com/user-attachments/assets/e3ddd1c6-f079-450c-a19a-dfbc3867af21)
![7g](https://github.com/user-attachments/assets/7bdcd59c-f903-4526-bcd9-e7c24889a162)
