### ISSUE TITLE
开启慢日志的审核任务在sqle界面上删除之后，对应的scanner程序出现panic信息

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#273]
**SQLe Version**
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 658ec45d5a

**To Reproduce**
1.创建一个慢日志功能的审核任务，启动对应的scanner程序
2.在对应的mysql数据源上，造出来一些慢语句
3.在sqle对应的审核任务中查看到对应的慢语句之后，删除该审核任务
4.对应的scanner运行结束，且出现panic信息 

panic: runtime error: slice bounds out of range [:18446744073709551615] with length 0

goroutine 51 [running]:
github.com/percona/pmm-agent/agents/mysql/slowlog/parser.(*SlowLogParser).Run(0xc00060e000)
	/universe/vendor/github.com/percona/pmm-agent/agents/mysql/slowlog/parser/parser.go:151 +0x507
created by github.com/actiontech/sqle/sqle/cmd/scannerd/scanners/slowquery.(*SlowQuery).Run
	/universe/sqle/cmd/scannerd/scanners/slowquery/slowquery_ee.go:51 +0x28

**Comment by sjjian** [comment]
MySQL版本多少 @Marcus9530

**Comment by Marcus9530** [comment]
mysql版本：5.7.25 @sjjian

**Comment by HuangWeiCen** [comment]
**解决过程**
1. panic信息中的18446744073709551615是uint64的最大值, 所以猜测应该是SlowLogParser.Run()对一个长度为零的数组进行了[:len-1]的取值
2. 查看SlowLogParser.Run()代码, 发现确实存在这个操作 
![image](https://user-images.githubusercontent.com/37464327/155054906-7fae9ab1-0b0a-4b85-8989-d88d0431bac7.png)

**解决方案**
将ContinuousFileReader修改为可以自定义是否跳过空行, 并在初始化ContinuousFileReader对象时设置为跳过, 上图中的p.r.NextLine()将不会再取出空行, 从而使得line[0:lineLen-1]不会再出现 0-1 的情况

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 1651c64
Server Version: main-ee 8066a53e88

验证步骤：
Steps to reproduce the behavior:
1.创建一个慢日志功能的审核任务，启动对应的scanner程序
2.在对应的mysql数据源上，造出来一些慢语句
3.在sqle对应的审核任务中查看到对应的慢语句之后，删除该审核任务
4.对应的scanner正常结束运行，且没有出现panic信息

![image](https://user-images.githubusercontent.com/54339501/155477416-9c6735fd-684a-4bfc-bc67-c7b0a06ddb4a.png)
![image](https://user-images.githubusercontent.com/54339501/155477437-9834408f-ae0d-48ce-baf4-cd9748392eec.png)
![image](https://user-images.githubusercontent.com/54339501/155477462-5f7001ee-91d8-4a15-978b-1be8a752dbf5.png)
![image](https://user-images.githubusercontent.com/54339501/155477537-2ed0217a-7537-496b-9b9f-e7936b633c59.png)
