### ISSUE TITLE
项目概览下工单潜在风险样式异常

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2735]
## 版本信息（Version）
UI: main-ee 1c76a0ed6
## 问题描述（Describe）

项目概览页面下 「工单潜在风险」样式异常，具体见截图

## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/c7189fd7-cfe3-4591-a7aa-18fc12381621)

![image](https://github.com/user-attachments/assets/7e87250d-c5e6-4aeb-b453-dfeadf594d73)

**Comment by taolx0** [comment]
表格高度不高于容器高度,显示正常
![image](https://github.com/user-attachments/assets/9a1f089f-9b12-41dd-9cc9-b7565c62ba80)
