### ISSUE TITLE
快捷审核支持切换审核规则模版

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#2742]
## 背景

目前快捷审核不支持切换审核规则模版,快捷审核模块初衷是为了支持更快捷的审核SQL,快捷审核相比SQL工单审核少了审批的步骤,但是目前不支持切换审核规则模版,不符合用户的需求,需要支持切换审核规则模版

## 需求描述（Describe）

快捷审核支持切换审核规则模版

## 实现方案

- [x] 创建快捷审核接口请求增加规则模版名参数
- [x]  获取全局规则模版接口返回新增IsDefaultRuleTemplate字段,用来确认规则模版是否是默认规则模版
- [x] Task 表新增 ruleTemplateID 字段,为了关联 Task 和对应的规则模版模块,用户指定的规则模版优先级最高,数据源绑定的规则模版优先级低于用户指定的规则模版,假设用户未指定规则模版且数据源为空,使用数据源类型的默认模版
- [x] 快捷审核离线审核支持切换审核规则模版
- [x] 快捷审核在线审核支持切换审核规则模版

## 升级方案

执行SQL

**Comment by iwanghc** [comment]
Version
UI : main cbe8a0b1
DMS : main  1feab39c44f89c2713794f3e86d801734b7fdb93
SQLE : main cb0747e42aa603378565fbf96d3c2dad8ef51f12
### 离线审核
可以选择切换模板
![image](https://github.com/user-attachments/assets/136148d4-c8ed-408b-b378-36657ab10a6a)
审核结果可以正确对应所选模板
![image](https://github.com/user-attachments/assets/6fc43134-9897-4155-9ef8-77deb7792873)
![image](https://github.com/user-attachments/assets/f7656e06-a162-4ab4-b5f4-d5fa6c2b75e1)
### 在线审核
前端暂未实现

**Comment by asiroliu** [comment]
# 验证
## version：
UI: release-3.2411.x-ee 545342c09
DMS: release-3.2411.x-ee 64c6740598
PROVISION: release-3.2411.x bac22c41eb
SQLE: release-3.2411.x-ee 99d113f088
## 步骤：
1. 离线审核
可以选择切换模板
![image](https://github.com/user-attachments/assets/b98ab36e-435f-4d10-a755-1eda074eb43e)
2. 审核结果可以正确对应所选模板
![image](https://github.com/user-attachments/assets/4c7ff070-a22b-4cc5-8680-896ad9fbd164)
![image](https://github.com/user-attachments/assets/85a9b9d1-01c0-47e4-a98a-fee11ddb2bf8)
