### ISSUE TITLE
删除智能扫描任务导致panic

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2761]
## 版本信息（Version）
3.2409.0

问题版本：
1. 07版本进行扫描任务重构，可能会出现删除任务后sql_manage_queues还会继续尝试同步为管控sql，同步过程中由于任务已经被删除，代码查询出来会触发空指针错误
2. 08版本调整了队列表与扫描任务的关联关系，关联sql_manage_quesus表使用的关联字段错误，导致删除失败

根本原因就是队列表里还有或者继续插入已删除的任务采集到的数据导致的
## 问题描述（Describe）
删除智能扫描任务时，sql_manage_queues数据没有同步删除，导致遗留了脏数据

## 截图或日志（Log）
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x987584]

goroutine 113 [running]:
github.com/actiontech/sqle/sqle/dms.GetAuditPlansWithInstanceV2({0x40005308e8?, 0x10?}, {0x40010c8d50?, 0x4000142280?}, 0x1?)
        /universe/sqle/dms/instance.go:474 +0x34
github.com/actiontech/sqle/sqle/server/auditplan.auditSQLs({0x4000538f40, 0x6, 0x8})
        /universe/sqle/server/auditplan/task_v2.go:116 +0x74
github.com/actiontech/sqle/sqle/server/auditplan.(*TDSQLMonitorDBSlowLogTencentTaskV2).Audit(0x0?, {0x4000538f40?, 0x40010c8d50?, 0x400d7ec100?})
        /universe/sqle/server/auditplan/task_type_td_mysql_monitor_db_slowlog_ee.go.go:352 +0x2c
github.com/actiontech/sqle/sqle/server/auditplan.BatchAuditSQLs({0x401390d000, 0x980, 0x4003ff40c0?}, 0x1)
        /universe/sqle/server/auditplan/job_task_handler.go:129 +0x390
github.com/actiontech/sqle/sqle/server/auditplan.(*AuditPlanHandlerJob).HandlerSQL(0x4000d50960?, 0x4000dd39e0?)
        /universe/sqle/server/auditplan/job_task_handler.go:65 +0x3fc
github.com/actiontech/sqle/sqle/server.(*BaseJob).Start.func1()
        /universe/sqle/server/manager.go:148 +0xec
created by github.com/actiontech/sqle/sqle/server.(*BaseJob).Start
        /universe/sqle/server/manager.go:136 +0x60
register to dms failed :failed to register dms proxy target: failed to register dms proxy target http://127.0.0.1:10000/v1/dms/proxys: query data error: Post "http://127.0.0.1:10000/v1/dms/proxys": dial tcp 127.0.0.1:10000: connect: connection refused
Received SIGUSR1, dumping pprof data to files...
CPU profile written to cpu_20241106_084148.pprof
Memory profile written to mem_20241106_084148.pprof
Goroutine profile written to goroutine_20241106_084148.pprof
```
## 如何复现（To Reproduce）
1. 创建智能扫描任务，等到sql_manage_queues表中有数据后
2. 删除智能扫描任务
4. 等待触发

删除扫描任务时，如果该任务正在执行，可能会导致panic(数据继续采集到队列表中，继续执行后续操作可能找不到任务导致panic)

## 问题原因
- 智能扫描任务删除时候，需要同步删除对应的sql_manage_queues数据和管控记录
- 当执行下列两个删除方法时，关联sql_manage_quesus表使用的关联字段错误，导致删除失败
- 后续sql_manage_queues还会继续尝试同步为管控sql，同步过程中由于任务已经被删除，代码查询出来会触发空指针错误

soure_id无法匹配到audit_planv2的id，对应的是instance_audit_plans的id
![image](https://github.com/user-attachments/assets/c42cdc0b-411a-4351-843e-4c072edb3495)

![image](https://github.com/user-attachments/assets/c8085bb4-36aa-495c-8f13-4fd018892fc1)

## 解决方案
修复获取扫描任务时错误判空返回nil，导致空指针问题
 队列sql出栈执行审核时，若扫描任务被删除，则同步删除已保存的管控sql。
#### 受影响的模块或功能

无
#### 外部引用的潜在问题或风险

无
#### 版本兼容性

无
#### 测试建议

当队列表中有数据时删除扫描任务进行验证

**Comment by BugsGuru** [comment]
### 复现
![image](https://github.com/user-attachments/assets/5fdab8ef-0e60-4970-901a-05c5622850d2)

**Comment by BugsGuru** [comment]
### 修复验证
验证版本：sqle 98e3ffb6d5faf04c5b14db63edcc484de8b5a71c

场景一：采集sql前删除扫描任务
1. 开启扫描任务后即将第一次采集：
![image](https://github.com/user-attachments/assets/87e6ea55-9a2f-4679-aee0-23af0eaa0b86)
2. 在sleep的10s内删除该扫描任务
3. 采集完成后，审核时扫描任务不存在走到DeleteSQLManageRecordBySourceId：
![image](https://github.com/user-attachments/assets/bfb99647-652d-48ad-86ed-0874e1f6bd38)
4. 程序正常没有panic

场景二：采集后审核前删除扫描任务
1. 开启扫描任务后即将第一次审核：
![image](https://github.com/user-attachments/assets/7f7186ea-dd7d-4316-9ab5-f87b671986a9)
2. 在sleep的10s内删除该扫描任务
3. 审核时扫描任务不存在走到DeleteSQLManageRecordBySourceId：
![image](https://github.com/user-attachments/assets/7ee9df2f-352d-467a-b8c6-e81ccedc8ffe)
4. 程序正常没有panic
