### ISSUE TITLE
删除并重建的扫描任务采集到的sql数为0

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2764]
## 版本信息（Version）
sqle: main d4ec1e4b946c3bc83ca019a24c6f6e4d7488bfe8
## 问题描述（Describe）
在同一个实例扫描任务下，创建扫描任务执行采集获取到数据后，删除并重建该扫描任务，新建的扫描任务采集到的sql数为0
## 截图或日志（Log）
库表扫描任务采集到的数据：
![image](https://github.com/user-attachments/assets/2aea4f25-039b-4381-b02b-75b206993c81)
删除该任务
![image](https://github.com/user-attachments/assets/1656a7ee-8b24-4d38-86f2-e382bf0dfd77)
重建该任务：
![image](https://github.com/user-attachments/assets/e5bf182a-0de2-4dee-9ad0-4acb980f0842)
等待一段时间后，依旧显示采集sql数未0
![image](https://github.com/user-attachments/assets/7eb3e738-c86b-419c-bf2f-cd09bca131fe)
![image](https://github.com/user-attachments/assets/695f1ae3-ce84-4a9f-8e7d-be84eb0dffa7)
但是队列表中数据，说明数据能采集到，是在save sql管控时出现了问题
![image](https://github.com/user-attachments/assets/37133d60-d187-42ba-b183-4b48f4996cc7)

## 如何复现（To Reproduce）
创建库表扫描任务 -> 等采集完成并在sql管控中展示 -> 删除该扫描任务 -> 再次在该实例扫描任务下创建库表扫描任务 -> 采集sql数为0

## 问题原因
当在同一个实例扫描任务下删除并重新创建了同一类型的扫描任务，它采集sql生成的sql id可能会与被删除的任务sql id一致
因为source id是实例任务id，不能保证新的扫描任务生成sql id时具有唯一性
所以当其他扫描任务采集的sql与被删除的sql管控记录sql id一致时，需要插入一条新的sql管控记录，而不是去update被软删除的记录

## 解决方案
生成sql id时，新增扫描任务id（audit plan id）作为参数，并去掉实例任务id（source id ）参数，保证每一个扫描任务生成的sql id都是独立且唯一的。
#### 受影响的模块或功能

无
#### 外部引用的潜在问题或风险

无
#### 版本兼容性

不兼容
历史扫描任务生成的sql id与加入audit plan id后新生成的sql id无法进行匹配
升级后导致同一任务下的相同sql都无法进行合并

#### 测试建议

无

**Comment by iwanghc** [comment]
## 升级方案
根据新的参数生成sql id覆盖原本的sql id（管控表与队列表都需要更新）

**Comment by BugsGuru** [comment]
### 复现
第一次采集成功
![de1a05fa-c1cb-42c1-89e8-b9381ec3a9aa](https://github.com/user-attachments/assets/647fa34e-fcb8-4d33-97ac-8d3dac8f9abe)
扫描任务重建后采集时间更新但未采集到数据
![image](https://github.com/user-attachments/assets/a3ad1326-f0d2-4e6a-a0c2-d52995b2b699)

**Comment by BugsGuru** [comment]
### 修复后验证重建后采集有数据
第一次采集：
![20241205-160725](https://github.com/user-attachments/assets/561ba36b-c28b-4664-a41f-357925ab4064)
删除重建：
![20241205-160744](https://github.com/user-attachments/assets/ee2c1205-3019-4948-8fa4-35bdfbe93d31)
重建后采集到数据：
![2b6b218e-df8b-4aa5-8208-cc10e8281c9b](https://github.com/user-attachments/assets/cfcb5d67-229b-4437-998e-18e9d5efb07b)

**Comment by asiroliu** [comment]
# 验证
## version：
UI: release-3.2411.x-ee 545342c09
DMS: release-3.2411.x-ee 64c6740598
PROVISION: release-3.2411.x bac22c41eb
SQLE: release-3.2411.x-ee 99d113f088
## 步骤：
1. 第一次采集：
![image](https://github.com/user-attachments/assets/4df74fde-b364-4ee2-963d-c9751899e6e6)
2. 删除重建：
![image](https://github.com/user-attachments/assets/cdaac3f9-5146-476a-a30a-e083d9ed0b55)
3. 重建后采集到数据：
![image](https://github.com/user-attachments/assets/1be10671-8c3c-4d33-aaeb-dd135b6f0cb2)
