### ISSUE TITLE
智能扫描oracle top sql指标总执行时间为0

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2774]
## 版本信息（Version）
SQLE main 5868e4c6bad23a2be4cd08e7aa2f0878501e133b
## 问题描述（Describe）
oracle top sql采集的指标总执行时间为0，但是在oracle数据源上通过采集的sql语句查询结总执行时间是有值的

首次采集上来在数据库中总执行时间、物理读次数、逻辑读次数都是有值的，但是在页面上总执行时间为0，物理读次数、逻辑读次数显示正常。
第二次采集以后，数据库中总执行时间、物理读次数、逻辑读次数指标值都变为0。
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/2bd26600-7cc6-4534-b584-11da462305e6)
![image](https://github.com/user-attachments/assets/2e1e2cf7-aecc-486e-9a32-a44a9d4e0882)
## 如何复现（To Reproduce）
创建orcale top sql扫描任务->等待采集topsql->查看结果->通过采集sql到oracle库中查询->对比结果

查询SQL：
```
SELECT * FROM (
		SELECT
			sql_fulltext,
			executions,
			elapsed_time,
			user_io_wait_time,
			cpu_time,
 			disk_reads,
			buffer_gets
		FROM
			V$SQLAREA
		WHERE
			EXECUTIONS > 0
			ORDER BY executions DESC
	) WHERE rownum <= 20;
```

## 问题原因
采集后在做Metric类型转换时，没有将相应的类型做对应，导致在通过Metric的key和类型获取value时，获取不到相应的值
总执行时间Metric的类型定义为Int
### 问题点一：接口获取到总执行时间为0的原因
![image](https://github.com/user-attachments/assets/f2d29bb6-df06-4408-afb3-2ea4d2d98116)
而在getSQLData中使用了getFloat
![image](https://github.com/user-attachments/assets/68184542-66d9-4175-9df7-6f5f7e2da1cd)
### 问题点二：扫描任务第二次执行后，总执行时间、物理读次数、逻辑读次数变为0的原因 
创建任务首次采集到的数据是正常的
![image](https://github.com/user-attachments/assets/abf96505-89cd-44c6-ba57-3454c05cf9d0)
但是当再次采集后，Metric三个指标都变为了0
![image](https://github.com/user-attachments/assets/3baa89e9-17d0-437a-9912-8b7b60283e10)
原因在于第二次采集后要对采集上来的sql做一次聚合
![image](https://github.com/user-attachments/assets/2b522128-56f7-4f95-8960-285136f24b3c)
这里 Info.Get(MetricNameXXX).Float()获取到对应的Float的值但实际上总执行时间、物理读次数、逻辑读次数都是Int，导致都变为了0
![image](https://github.com/user-attachments/assets/d7112f46-ca7d-4c90-ab8e-915e870c9258)
![image](https://github.com/user-attachments/assets/6bc59437-0292-4bcf-b59f-8ebd24ff9f7b)

## 解决方案
扫描任务采集sql以及合并sql时，使用定义Metric类型来获取与存储指标信息。
#### 受影响的模块或功能

无
#### 外部引用的潜在问题或风险
无

#### 版本兼容性
兼容

#### 测试建议
无

**Comment by BugsGuru** [comment]
![image](https://github.com/user-attachments/assets/21d3fe6f-ddc0-4d4a-babf-d0668248064b)
