### ISSUE TITLE
规则列表滚动分页无效

### ISSUE THREAD

**Issue by zzyangh** [actiontech/sqle#2777]
## 版本信息（Version）
release-3.2410.x
## 问题描述（Describe）
查看规则、审核规则模板、规则管理中的规则列表滚动分页失效，只能展示一页内容，滚动无法查看更多内容
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/4352e6ac-dd7a-4735-bc7b-702c7d2dffe0)

## 问题原因
前端版本编译代码问题，元素高度未成功设置

**Comment by BugsGuru** [comment]
可以显示完规则：
![image](https://github.com/user-attachments/assets/2325d3cf-a94f-4400-89ad-895108689730)

![image](https://github.com/user-attachments/assets/1b794f94-aebd-43f6-b3f4-19cce8b2dd28)
