### ISSUE TITLE
扫描任务导致慢SQL堆积

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2790]
## 版本信息（Version）
SQLE: main cb0747e42aa603378565fbf96d3c2dad8ef51f12
## 问题描述（Describe）
扫描任务启用后mysql processlist中发现出现了线程堆积，并发连接大量`select count(1)`的sql，并且出现mysql cpu使用率过高问题。
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/990c2d19-9d23-4c06-9267-46572000af5d)
![image](https://github.com/user-attachments/assets/c43e930c-ab05-4f87-b6f1-36ce19226691)

## 如何复现（To Reproduce）
1. 在某个表写入大量数据（5000万以上记录数的表比较容易复现）
2. 在该数据源的审核模板上开启“查询数据量超过阈值，筛选条件必须带上主键或者索引”和规则“UPDATE/DELETE操作影响行数不建议超过阈值”规则
3. 创建processlist扫描任务，，设置采集周期为1秒
4. 在快捷审核中审核select * from xxx触发以上规则（为了让`select count(1) `sql语句出现在processlist中）
5. 查看processlist是不是出现了线程堆积和mysql server cpu使用情况

## 问题原因
**扫描任务并发审核时下发的慢sql堆积导致CPU负载过高**
某些审核规则会下发`select count(1)`sql语句，当该语句统计的表记录数过多时，会导致sql执行变慢，而processlist或慢日志扫描任务会采集到这些慢sql，扫描任务的审核是多线程执行的，当采集到`select count(1)`时，又触发了下发该语句的规则，周而复始，造成连接到数据库的线程堆积，引起cpu高负载。
## 解决方案
问题的根本原因在于并发审核，解决思路有两种，一种改为单线程审核，另一种是审核时过滤数据。
### 方案一：
在AggregateSQL时过滤掉管控表中已经审核过的sql
优点：减小了审核的压力
缺点：审核结果无法自动更新，只能通过页面上一键审核按钮更新审核结果
### 方案二：
将审核sql这个动作改为单线程
![image](https://github.com/user-attachments/assets/0317bb72-2fd5-4612-8407-8e77cffffdf9)
优点：成本小
缺点：采集数据量较大审核较慢时，会按一批一批显示在页面上(每次1000条)，体验不好。
### 方案三：
创建全局map，记录审核中的sql，在审核完后从map中delete，并在审核时过滤已经触发审核但没审核完的sql 。
优点：影响面小，并且保证了采集数据的完整
缺点：使扫描任务审核逻辑变得复杂

### 最终方案：
~~方案三，新增一个map存放审核中的sql，没有数据库操作不会加重扫描任务审核负担，且实现相对较容易，仅需要注意保证map的线程安全。~~
单独启用一个job用来聚合queue更新record表，改为从record中读取数据进行单线程审核。
1. 在sql_manage_record_processes表中新增最后审核时间字段
2. 新增一个更新record表的job，从队列表中取数据聚合后更新到record表，并把审核结果置空，界面显示审核中。
4. 在审核job中，从record表更新时间 > 最后审核时间+?min(刚审完几分钟的就不审了) 或 最后审核时间为空的数据取出来进行审核，并将审核改为单线程，审核时不同实例多线程执行。
5. 来源是快捷审核的数据也要同步更新或插入审核时间字段

#### 受影响的模块或功能

扫描任务采集sql处理的聚合保存模块、审核模块
#### 外部引用的潜在问题或风险

无
#### 版本兼容性

sql_manage_record_processes表新增了last_audit_time字段，记录最后的审核时间，需要根据存量管控数据的updated_time更新last_audit_time。
#### 测试建议

参考**问题原因**和**如何复现**部分测试，注意服务器cpu使用率

**Comment by iwanghc** [comment]
### **问题修复自测：**
准备一张大表
![image](https://github.com/user-attachments/assets/80adb6f5-9649-4597-b7c0-35f47845164e)
开启下发慢sql的规则（此处是计算影响行数）
![image](https://github.com/user-attachments/assets/347c7f87-e99b-405a-8ecd-dd035a638c38)
在同一数据源上开启四个processlist，采集周期为1秒的扫描任务
![image](https://github.com/user-attachments/assets/a0fdb98e-ae0a-4922-873f-37b3753a2354)
审核一条sql，触发规则，下发慢sql
![image](https://github.com/user-attachments/assets/0bfae6be-749e-475f-b5e5-24958e7257bd)
经过一段时间采集后，processlist没有慢sql堆积现象
![image](https://github.com/user-attachments/assets/313cc01b-b1b2-40c2-b757-be3d0c9600f7)
cpu使用率也没有明显升高
![image](https://github.com/user-attachments/assets/22c11130-fc82-4989-8d61-2f34a7049553)

**Comment by iwanghc** [comment]
## 升级方案
假设sqle服务的数据库名称为sqle
添加last_audit_time字段记录最后审核时间：
```ALTER TABLE sqle.sql_manage_record_processes ADD last_audit_time datetime(3) NULL;```
更新last_audit_time字段值为sql_manage_records的最后更新时间：
```UPDATE sqle.sql_manage_record_processes AS p
JOIN sqle.sql_manage_records AS r
ON p.sql_manage_record_id = r.id
SET p.last_audit_time = r.updated_at;
```

**Comment by asiroliu** [comment]
# 复现
## version:
UI: release-3.2411.x-ee 545342c09
DMS: release-3.2411.x-ee 64c6740598
PROVISION: release-3.2411.x bac22c41eb
SQLE: release-3.2411.x-ee 99d113f088
## 步骤：
1. 数据准备
```bash
sysbench /usr/share/sysbench/oltp_common.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=test --mysql-password=test --mysql-db=test --create_secondary=off --table-size=50000000 --tables=1 prepare
```
<img width="421" alt="image" src="https://github.com/user-attachments/assets/2cf4b74b-8d27-4a65-8a92-b72432f67d7a" />

2. 创建审核模板“查询数据量超过阈值，筛选条件必须带上主键或者索引“ 和 ”UPDATE/DELETE操作影响行数不建议超过阈值“
![image](https://github.com/user-attachments/assets/f298e86e-e0b3-4ebc-b021-e9f28d634ecc)
3. 添加智能扫描 - processlist 列表
![image](https://github.com/user-attachments/assets/dc6e951e-ea57-4d9a-95fc-3bfa27782bb4)
4. 创建工单执行”SELECT * FROM sbtest1;“
![image](https://github.com/user-attachments/assets/6b84f637-52b2-476f-831e-eb99791bb19f)
5. MySQL cpu使用率升高
<img width="867" alt="image" src="https://github.com/user-attachments/assets/cf156042-c65e-4364-99e3-ca835fe60443" />
6. 查看processlist
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/61712ed8-1575-4787-8fc1-1787efc45b38" />

**Comment by asiroliu** [comment]
# 验证
## version：
UI: main-ee a6a191365
DMS: main-ee da86843bad
PROVISION: main 8ce5196b73
SQLE: main-ee 9279ed8785
## 步骤：
1. 数据准备
```bash
sysbench /usr/share/sysbench/oltp_common.lua --mysql-host=127.0.0.1 --mysql-port=3306 --mysql-user=test --mysql-password=test --mysql-db=test --create_secondary=off --table-size=50000000 --tables=1 prepare
```
![image](https://github.com/user-attachments/assets/c324590d-f6f9-470d-b072-8b9c3d4fae80)
2. 创建审核模板“查询数据量超过阈值，筛选条件必须带上主键或者索引“ 和 ”UPDATE/DELETE操作影响行数不建议超过阈值“
![image](https://github.com/user-attachments/assets/4b408652-50f6-4d42-8353-496e03815c44)
3. 添加智能扫描 - processlist 列表
![image](https://github.com/user-attachments/assets/dc6e951e-ea57-4d9a-95fc-3bfa27782bb4)
4. 创建工单执行”SELECT * FROM sbtest1;“
![image](https://github.com/user-attachments/assets/6b84f637-52b2-476f-831e-eb99791bb19f)
5. MySQL cpu使用率升为明显高
<img width="853" alt="image" src="https://github.com/user-attachments/assets/955f36e9-7e30-45ce-b665-dc97d182bdef" />
6. 查看processlist只有少量 `SELECT COUNT(1) FROM sbtest1`
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/aed955fe-1ba3-49b0-9f82-0442121291f5" />
