### ISSUE TITLE
规则：使用联合索引时,必须使用联合索引的首字段。误触发

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#2794]
## 版本信息（Version）
sqle 3.2410
## 问题描述（Describe）

SQL中的条件查询引用的列，引用了多列，其中有一列不是复合索引中的首列会触发该规则

## 如何复现（To Reproduce）
``` sql
CREATE TABLE `case_records` (
  `RECORD_ID` bigint NOT NULL,
  `PROJECT_ID` bigint NOT NULL,
  `STATUS` int DEFAULT NULL,
  `MODULE_ID` bigint DEFAULT NULL,
  `CREATION_TIME` datetime DEFAULT NULL,
  `CREATOR_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`RECORD_ID`, `PROJECT_ID`) USING BTREE,
  KEY `idx_case_records_01` (`STATUS`, `PROJECT_ID`),
  KEY `idx_case_records_02` (`STATUS`, `PROJECT_ID`, `MODULE_ID`),
  KEY `idx_case_records_03` (`CREATION_TIME`, `CREATOR_ID`, `PROJECT_ID`)
);
``` 
```sql
SELECT COUNT(1)
FROM case_records
WHERE status = 0
  AND project_id IN (10, 20);
```

## 问题原因
代码逻辑错误
## 解决方案
- [x] 当数据表定义中存在多个联合索引时，若查询条件能够匹配任意一个联合索引的最左前缀，则视为通过规则审核。
- [x] 若查询条件中的字段能够命中数据表上任一联合索引的最左前缀，则满足规则要求。
- [x] 若查询条件中涉及的字段未包含在任何联合索引中，则不触发该规则。

**Comment by LordofAvernus** [comment]
**版本信息**
UI: 3.2412.0-pre3-ee 48d43c188
DMS: 3.2412.0-pre3-ee 8f3da7c462
PROVISION: 3.2412.0-pre3 73bfb7fdd8
SQLE: 3.2412.0-pre3-ee 2871f7a7d7

**验证**
![20241231175321_rec_](https://github.com/user-attachments/assets/d9cfb799-00f4-411f-90b8-dd828620ff98)
