### ISSUE TITLE
扫描任务详情页面报错

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2814]
## 版本信息（Version）
SQLE： 3.2411
## 问题描述（Describe）
扫描任务执行后，点击进入详情页面出现报错，并且页面数据为空
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/3cb8ad92-7b01-4ce7-a874-274db401e904)
## 如何复现（To Reproduce）
创建扫描任务，等待采集，当数据库sql_audit_records表中出现采集的数据并且审核接口为空时（这里可以适当增加审核轮询的时长），刷新扫描任务详情页面，出现报错。

## 问题原因
扫描任务查询sql当审核结果为空时代表审核中，将being_audit以string的形式赋值给audit_result，AuditResult字段在接收时Scan方法Unmarshal失败导致错误
![img_v3_02he_8fb17a6e-34f7-4802-88aa-17a47763a38g](https://github.com/user-attachments/assets/fe96b6c5-9523-41c5-930d-c33f492c600e)
![img_v3_02he_e6f1e6f2-4a63-4b5e-9d67-64634f90fdcg](https://github.com/user-attachments/assets/326410e6-5078-4389-ba58-b7d8e07d5abb)

## 解决方案
新增审核中状态标识扫描任务采集待审核的sql，不再复用audit_results字段
#### 受影响的模块或功能

扫描任务sql详情查询列表
#### 外部引用的潜在问题或风险

无
#### 版本兼容性

无
#### 测试建议

采集后还未审核的sql才会处于审核中状态，建议使用触发下发慢sql的规则进行复现，可参考issue 2790，或者采集大批量数据也可复现，审核的job每次轮询取1000条进行审核。

**Comment by LordofAvernus** [comment]
**版本信息**
UI: 3.2412.0-pre3-ee 48d43c188
DMS: 3.2412.0-pre3-ee 8f3da7c462
PROVISION: 3.2412.0-pre3 73bfb7fdd8
SQLE: 3.2412.0-pre3-ee 2871f7a7d7

**验证**

![20241231181623_rec_](https://github.com/user-attachments/assets/d1872880-4238-4c56-a324-162e700303ba)
