### ISSUE TITLE
在开启索引优化建议的情况下，审核多表 join 的SQL时失败，程序 panic.

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#283]
**SQLe Version**
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x f7a9950c12

**Describe the bug**
在开启索引优化建议的情况下，审核多表 join 的SQL时失败，程序 panic.
```bash
panic: interface conversion: ast.ResultSetNode is *ast.Join, not *ast.TableSource

goroutine 2587 [running]:
github.com/actiontech/sqle/sqle/driver/mysql.(*Inspect).Audit(0xc000650c00, 0x1323f30, 0xc0000c2080, 0xc001cc4000, 0x110, 0xc000a5a090, 0x1, 0x1)
        /universe/sqle/driver/mysql/mysql.go:303 +0x1059
github.com/actiontech/sqle/sqle/server.(*action).audit(0xc0001b4c80, 0x0, 0x0)
        /universe/sqle/server/sqled.go:275 +0x8df
github.com/actiontech/sqle/sqle/server.(*Sqled).do(0xc0001cc720, 0xc0001b4c80, 0x442636, 0x1211130)
        /universe/sqle/server/sqled.go:150 +0x225
github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop.func1(0xc0001cc720, 0xc0001b4c80)
        /universe/sqle/server/sqled.go:138 +0x39
created by github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop
        /universe/sqle/server/sqled.go:137 +0x52
```
**To Reproduce**
1. 配置审核规则，开启审核规则“索引创建建议”
2. 对指定开启了索引创建建议的数据库进行SQL审核
3. 页面录入SQL
```sql
select * from t1
INNER JOIN t2 on t1.id = t2.id
INNER JOIN t3 on t1.id = t3.id
```
4. 页面提示未知错误，查看程序日志发现如描述中的堆栈信息

**Expected behavior**
1. 程序不会panic
2. 能正确给出审核建议

**Comment by drivebyer** [comment]
dup with #226

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2201.x 0ad3134
Server Version: release-1.2201.x-ee 658ec45d5a
复现步骤：
1.配置审核规则，开启审核规则“索引创建建议”
2.对指定开启了索引创建建议的数据库进行SQL审核
3.页面录入SQL
select * from t1
INNER JOIN t2 on t1.id = t2.id
INNER JOIN t3 on t1.id = t3.id
4.点击审核，出现未知错误
![image](https://user-images.githubusercontent.com/54339501/155476206-d30329d4-9e9a-4b59-a7db-136eb72c52d7.png)

![image](https://user-images.githubusercontent.com/54339501/155476161-048f4aaa-2158-41d7-8372-7bc7b1ed1fd5.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 1651c64
Server Version: main-ee 8066a53e88
验证步骤：
1.配置审核规则，开启审核规则“索引创建建议”
2.对指定开启了索引创建建议的数据库进行SQL审核
3.页面录入SQL
select * from t1
INNER JOIN t2 on t1.id = t2.id
INNER JOIN t3 on t1.id = t3.id
4.点击审核，正常对sql语句进行审核，并没有出现未知错误

![image](https://user-images.githubusercontent.com/54339501/155476424-ea15c5ef-4aa3-41e1-b910-736533581372.png)


![image](https://user-images.githubusercontent.com/54339501/155476360-4d70d1c5-d456-4880-be8e-571136dbf339.png)
