### ISSUE TITLE
扫描任务空指针panic

### ISSUE THREAD

**Issue by iwanghc** [actiontech/sqle#2830]
## 版本信息（Version）
SQLE: main f0bcb90e712cbdb6e16f122c1ebd623e90f9a905
## 问题描述（Describe）
扫描任务执行时，删除插件后出现空指针panic，程序退出
存在一种场景，当执行扫描任务采集到的sql插入队列表后，sqle程序停止，禁用该任务的插件，重启后扫描任务会继续从队列表里pull数据，此时该sql的审核会报错，因为插件已不存在，该场景会导致程序出现painc
## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/af8f0802-abbd-45a7-a0c1-1de2d8c01e63)
## 如何复现（To Reproduce）
启用oracle top sql采集任务，当队列表sql_manage_queues中存在数据时，停止sqle程序，将oracle插件禁用，启动sqle，出现panic
![image](https://github.com/user-attachments/assets/036f605d-742c-47ab-b01e-44a985f9e43b)

## 问题原因
审核时插件报错不存在，预期应该是将采集到的原始sql插入或更新到管控
![image](https://github.com/user-attachments/assets/3bc47ef9-8de8-44cb-bcd6-a94e46332ff8)
但是通过审核返回的resp未空
![image](https://github.com/user-attachments/assets/41469f11-9e46-48be-aafb-c94f089bb6c8)
## 解决方案
当审核的返回的resp为nil时，直接取sqls作为原始sql插入管控

**Comment by LordofAvernus** [comment]
**版本信息**
UI: 3.2412.0-pre3-ee 48d43c188
DMS: 3.2412.0-pre3-ee 8f3da7c462
PROVISION: 3.2412.0-pre3 73bfb7fdd8
SQLE: 3.2412.0-pre3-ee 2871f7a7d7

**验证**
![20250102110306_rec_](https://github.com/user-attachments/assets/833faca7-2750-45c4-bca8-add645b604d7)
