### ISSUE TITLE
前端错别字修复

### ISSUE THREAD

**Issue by LZS911** [actiontech/sqle#2838]
## 版本信息（Version）
UI: main-ee 31054760d

## 问题描述（Describe）
需要统一将 「模版」 改为 「模板」，详情见截图

## 截图或日志（Log）
![image](https://github.com/user-attachments/assets/6befa105-2794-46e0-a28a-5f9c26b67c6c)

**Comment by LordofAvernus** [comment]
验证版本：
UI: 3.2412.0-pre3-ee 48d43c188
DMS: 3.2412.0-pre3-ee 8f3da7c462
SQLE: 3.2412.0-pre3-ee 2871f7a7d7

![image](https://github.com/user-attachments/assets/7605b70a-19e3-4fb8-aac3-af55a18be8cf)
