### ISSUE TITLE
fail to parser MyBatis XML, "where" in condition will be repeated

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#302]
**SQLe Version**
sqle main

**Describe the bug**
针对mybatix的xml的静态扫描，针对如下格式的扫描结果，会存在解析失败的问题，XML如下：
```xml
<select id="selectUserByState" resultType="com.bz.model.entity.User">
    SELECT * FROM user    
<choose>
      <when test="state == 1">
        where name = #{name1}
      </when>
      <otherwise>
        where name = #{name2}
      </otherwise>
    </choose>
  </select>
```
解析的内容：
```sql
    SELECT * FROM user    

        where name = ?
      
        where name = ?
```
该SQL语句存在两个where关键字，并非一个正常的SQL语句

**To Reproduce**
1. 创建一个XML文件，内容如描述
2. 创建工单，选择审核SQL语句上传方式选择“上传Mybatis的XML文件”，并上传该文件
3. 点击审核
4. 审核的内容提示“语法错误或者解析器不支持”
![image](https://user-images.githubusercontent.com/18008452/153836464-9e84d2f1-8bf5-4c7f-bdbd-b161c73a66eb.png)

**Expected behavior**
能出现正常SQL语句

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x-ee 0dcf3a29e5
复现步骤：
1.创建一个XML文件，内容如描述
2.创建工单，选择审核SQL语句上传方式选择“上传Mybatis的XML文件”，并上传该文件
3.点击审核，出现审核的内容提示“语法错误或者解析器不支持”
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/54339501/170465445-87cf8620-e868-4255-aaa3-93d535c5e3c0.png">

**Comment by Marcus9530** [comment]
UI Version: main 2ddcae6
Server Version: main-ee 1420a4532a

验证通过
验证步骤：
1.创建一个XML文件，内容如描述
2.创建工单，选择审核SQL语句上传方式选择“上传Mybatis的XML文件”，并上传该文件
3.点击审核，可以正常进行审核
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/54339501/170465675-2e2c711c-46c8-4541-b2d6-6d7fe587fd42.png">
