### ISSUE TITLE
创建一个用户组，然后绑定了用户，但是在用户管理界面上该用户显示没有绑定的用户组

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#318]
**SQLe Version**
UI Version: main b385ae9
Server Version: main-ee 30e301d448

**To Reproduce**
1.创建一个用户test
![image](https://user-images.githubusercontent.com/54339501/155084689-f0ac15e9-eefe-4178-870f-3c46e907bd85.png)
2.然后创建一个用户组aa，并且创建的时候绑定这个test用户
![image](https://user-images.githubusercontent.com/54339501/155084740-c6779128-7c3d-41d9-9fa6-42f7fa17967b.png)
3.查看用户管理test用户，然后发现test用户信息上没有用户组aa
![image](https://user-images.githubusercontent.com/54339501/155084819-87b6efef-032a-42bd-8620-865e79681f90.png)
期望是用户管理也会随之进行绑定用户组

**Comment by jessun** [comment]
Fixed by PR #315

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 1651c64
Server Version: main-ee 8066a53e88
验证步骤：
1.创建一个用户组，然后绑定几个用户
2.然后在用户管理界面上，可以看到绑定的用户也同时显示了用户组信息

![image](https://user-images.githubusercontent.com/54339501/155470424-1e5d500b-f5f4-40de-855c-a67b957fe6e9.png)
![image](https://user-images.githubusercontent.com/54339501/155470439-57a5cdcf-0e1e-428d-a9c8-a2f3cd776a0e.png)
![image](https://user-images.githubusercontent.com/54339501/155470488-3e6d834c-790d-4d4e-860d-53af168dbd2c.png)
