### ISSUE TITLE
Optimize the setting of data sources

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#329]
# 背景
## 问题描述
SQLE中可以通过自定义审核插件的方式兼容各种类型的数据库, 但各种类型的数据库连接时需要的信息有所差异, SQLE的数据源添加接口目前无法全部获取到
## 实际案例
DB2连接时需要知道数据库名, 否则无法连接, 但SQLE的对应接口和界面无法在添加数据源时指定DatabaseName
## 附图
![image](https://user-images.githubusercontent.com/37464327/155272218-f9299a49-c6a0-4c78-8084-37085668de48.png)

# 解决方案
## 方案简述
通过插件主动提供所需连接参数的方式告知SQLE接口需要接收哪些参数
### API调整
1. 新增 /v1/instance_additional_metas [get]
2. /v1/instances [post] 和 /v1/instances/{instance_name}/ [patch] 增加dynamic_params参数用于存放动态参数

### 接口定义
1. 新增一个结构体Param用于存放参数和参数注释
```
  
type Param struct {
	Name        string
	Description string
	Type        string
	Value       string
	IsRequired    bool
}


```
3. 新增一个接口ParamGetterDialector, 新接口继承老的接口Dialector的部分方法以减少代码修改量
```
type ParamGetterDialector interface {
	// 旧接口保留函数
	ShowDatabaseSQL() string

	// 旧接口保留函数
	String() string

	// SQLE界面展示时会根据这个列表的参数顺序展示
	GetParam() []Param

	// SQLE会将从GetParam()处获取到参数列表填充好后和driver.DSN一起传递给插件用于生成DSN
	ParamDialect(dsn *driver.DSN, customParam map[string]interface{}) (string, string)
}
```
#### SQLE插件加载
1. SQLE 会先尝试通过新的接口定义加载插件, 加载失败再按照老版接口定义加载插件
2. 如果SQLE以老版的方式加载的插件会通过一个包装器将老接口的实现包装成新接口的实现
#### SQLE 插件使用
1. SQLE将只会使用新版的插件定义进行业务相关的操作
2. SQLE会先执行新插件的GetParam()获取自定义参数的项, 然后生成填充好值的Map, 再调用ParamDialect()获取DSN用于连接数据库
#### 数据源存储
1. 数据源存储时会新增一列custom_param, 用于存放json格式的自定义参数
#### 数据源使用
1. 从数据库中查询出数据源的信息, 再通过新接口的GetParam()获取自定义参数, 根据自定义参数列表生成对应的Map, 期间如果发现存在没有值的必填项则抛出错误提示用户更新数据源信息
#### 新增数据源
1. 前端请求需要用户填写的项, SQLE调用插件的GetParam()获取自定义参数, 按顺序填充到一个数组类型的参数中, 返回给前端
2. 前端按照数组顺序进行自定义参数的展示, 并根据其中是否必填的项进行必填校验和提示
4. 前端将用户填写好的请求发送给SQLE, 其中插件自定义参数将会放在一个数组类型的参数中, 以[{key:"key", value:"value"}]的方式传给SQLE
5. SQLE进行必填校验和存储

## 影响面
1. 插件的加载和使用(SQLE获取DSN和查询数据库列表)
2. 存储(表结构调整)和使用数据源信息的位置
3. 数据源设置相关接口和UI界面 

## 方案制定考虑的点
1. 旧版接口不可以废弃, 插件需要向后兼容
2. 在真正使用插件的地方需要保持统一, 及尽量不要一版接口一套实现, 而应该只是用一个一个最全的接口, 其他接口通过包装的方式转换成最全的接口
3. 部分参考了创建审核任务的动态参数实现方式

**Comment by Marcus9530** [comment]
UI Version: main bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
验证通过
当选择db2数据库类型的时候，界面出现数据库名字段
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/54339501/161217711-7d23978a-9c7d-48ef-8e94-71e43b83a6cb.png">
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/54339501/161217769-e3f8ba5d-e0f8-44cd-a1f9-4d03fd8d5212.png">
