### ISSUE TITLE
空的SQL工单创建成功，应该限制创建

### ISSUE THREAD

**Issue by zhouzhilu9** [actiontech/sqle#331]
**SQLe Version**
UI Version: main a194f39
Server Version: main-ee 32b5d8def7

To Reproduce
1，点击创建工单，sql语句不填写，点击“审核”
![image](https://user-images.githubusercontent.com/99949903/155299455-d3f2c34a-8446-4f6d-bd5f-3d4a8b6fa428.png)
2，点击“创建工单”
![image](https://user-images.githubusercontent.com/99949903/155299534-101aa01f-15ea-47dc-ac3d-be0d06764293.png)
3，创建成功
![image](https://user-images.githubusercontent.com/99949903/155300119-a28a5ba6-e620-41d7-8d11-9fa656a2e3cf.png)

**Comment by sjjian** [comment]
建议：空的SQL无法审核，前端控制下无法提交审核。后端做下检验。

**Comment by sjjian** [comment]
## 方案
1. 前端： 审核结果返回的条目数是0 的时候 不能创建工单或者更新工单
2. 后端：后端再创建和更新工单的时候判断task的内容，如果里面的SQL条目为0则无法创建更新工单

**Comment by HuangWeiCen** [comment]
# 修复方案

## 前后端
当审核结果sql条目数为0时前后端均禁止创建工单和更新工单

## 影响功能
1. 创建工单
2. 工单驳回后的修改工单

**Comment by zhouzhilu9** [comment]
验证版本：
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证步骤：
1，进入【工单列表】，点击创建工单
2，sql语句不填写，点击"审核”
3，点击“创建工单”，提示不能对空的sql语句创建工单

![Uploading 1648704753(1).jpg…]()
