### ISSUE TITLE
创建的审核任务抓去oracle的topsql，点击审核失败

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#346]
**SQLe Version**
UI Version: main 1651c64
Server Version: main-ee 8066a53e88

**To Reproduce**
1.创建oracle数据源
2.创建审核任务，然后添加抓起topsql类型的任务
3.等抓取到sql语句之后，点击审核，审核失败如图所示
![5W0xHjOEet](https://user-images.githubusercontent.com/54339501/155481263-9581fe64-6a8e-4060-9561-c812b1f567de.png)

**Comment by drivebyer** [comment]
审核插件在执行 Parse 时，将 BEGIN END 切分成了两个字符串导致报错。

**Comment by Marcus9530** [comment]
验证版本：

UI Version: main 1651c64
Server Version: main-ee 08784304bf
验证步骤：
1.添加一个oracle数据源
2.然后创建审核任务且类型为topsql抓取，指定该数据源
3.创建审核任务成功后，然后点击审核，审核成功

![image](https://user-images.githubusercontent.com/54339501/155660115-25bf81c7-267e-4756-ab45-efd0c4b8485a.png)
