### ISSUE TITLE
Add test for email configration

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#353]
## 背景
配置完邮箱后无法确认到底配置的到底正确还是不正确，可能需要实际业务验证邮箱的正确性，体验不好
## 需求
给邮箱配置添加一个快速验证的测试按钮

**Comment by HuangWeiCen** [comment]
# 修复方案

## 前端
前端需要在邮箱配置处添加一个测试按钮, 添加方式参考微信配置

## 后端
后端新增邮箱测试接口, 接收一个邮箱地址, 向传入邮箱发送一封测试邮件, 邮件内容同微信测试消息
