### ISSUE TITLE
SQL Server默认规则模板点击不了下一步

### ISSUE THREAD

**Issue by xiaohuazi123** [actiontech/sqle#361]
SQLe Version
UI Version: main a194f39
Server Version: main 828c6979d0

To Reproduce
1.模板管理-》审核规则模板-》default_SQL Server默认规则模板
2.点【下一步】
3.出现【只能包含字母、数字、中划线和下划线】的报错

![QQ截图20220302162136](https://user-images.githubusercontent.com/45115671/156323185-b94792bd-f81f-41cb-8b08-665dfcaed2e0.jpg)

**Comment by sjjian** [comment]
类似问题： https://github.com/actiontech/sqle/issues/187

**Comment by Marcus9530** [comment]
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x-ee cfc826b110
复现成功
复现步骤：
1.sqle目录下添加sql server审核插件
2.查看审核模版，点击sql server审核模版，点击下一步，无法点击
![Uploading image.png…]()

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/161221824-137f4ca9-1626-4a0c-8091-7410362a4650.png)

**Comment by Marcus9530** [comment]
UI Version: main bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
验证通过
验证步骤

1.sqle目录下添加sql server审核插件
2.查看审核模版，点击sql server审核模版，点击下一步，可以看到审核规则信息
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/54339501/161222083-ec5a66db-baed-47a8-b0d5-5691bca54223.png">
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/54339501/161222099-0a83d77a-9384-4b2a-b933-e6ffd0fceeb3.png">
