### ISSUE TITLE
把一个用户添加到用户组总是失败

### ISSUE THREAD

**Issue by xiaohuazi123** [actiontech/sqle#362]
**SQLe Version**
UI Version: main a194f39
Server Version: main 828c6979d0

**Describe the bug**
把一个用户添加到用户组总是失败

**To Reproduce**
1. 编辑用户
![QQ截图20220302165126](https://user-images.githubusercontent.com/45115671/156327988-a6827f63-61b8-4c4b-b287-12f14f67ff8f.jpg)

2. 加入到某个用户组

![QQ截图20220302165135](https://user-images.githubusercontent.com/45115671/156328001-a2d2c5c0-798d-423a-99d6-f39c18f707d1.jpg)

3. 提交
4. 没有加入成功
![QQ截图20220302165143](https://user-images.githubusercontent.com/45115671/156328034-9ce7373a-c683-499b-a87c-aa4fe627b470.jpg)

**每次都能复现**

**Comment by jessun** [comment]
你好！
此问题同 https://github.com/actiontech/sqle/issues/327，
已在 https://github.com/actiontech/sqle/pull/330 中修复，
可更新项目后再次进行尝试。
