### ISSUE TITLE
配置使用 gh-ost 时 sqle 报错，Data too long for column 'exec_result'

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#363]
**SQLe Version**
sqle main

**Describe the bug**
![7JG{CR}Z@V2}ZA~VYM94_YG](https://user-images.githubusercontent.com/18008452/156350638-5924c3b7-0590-4260-9d95-d9b14c049015.jpg)

**To Reproduce**

** Suggestion **
建议将exec_result 字段加长，调整为text

**Comment by HuangWeiCen** [comment]
修复完毕

**Comment by Marcus9530** [comment]
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x-ee cfc826b110
复现步骤：
1.创建一个binlog rows 模式的数据库，并录入数据源;
2.开启规则gh-ost，可以将表空间大小调小，1MB;
3.在数据库上创建一个库db1,和表t1
create database db1;
create table db1.t1 (id int key, name varchar(255));
4.批量插入数据，可以使用存储过程
delimiter //
create procedure batchInsert()
begin
    declare num int; 
    set num=1;
    while num<=100000 do
        insert into db1.t1(`id`,`name`) values(num, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
        set num=num+1;
    end while;
end
// 
delimiter ;

call batchInsert;
5.对该库进行上线操作，提交审核并上线SQL
alter table t1 add column c2 varchar(255) not null default "1"
6.上线报错

<img width="929" alt="image" src="https://user-images.githubusercontent.com/54339501/161241368-1be3f295-941d-41d3-91ec-1f2aab8cd486.png">

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/54339501/161241341-dd9770c0-b953-4a62-8731-588bac0e4d01.png">

<img width="969" alt="image" src="https://user-images.githubusercontent.com/54339501/161241340-c797aca0-11df-45b5-af8a-db1ccd6ea5da.png">

**Comment by Marcus9530** [comment]
UI Version: main bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
验证通过
验证步骤
1.搭建修复后的版本sqle平台
2.添加复现环境所使用的数据源
3.开启规则gh-ost，可以将表空间大小调小，1MB;
4.对该库进行上线操作，提交审核并上线SQL
alter table t1 add column c2 varchar(255) not null default "1"
5.上线失败但是符合预期，错误信息是由gh-ost发出的，sqle本身并没有发出报错信息
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/54339501/161242698-c4936d30-3037-4395-817a-40e2fd5a9b05.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/54339501/161242746-5987a13d-fc6d-4bbb-a45c-0a331ee514ca.png">
