### ISSUE TITLE
修改完审核任务后退到编辑页面“审核任务类型“与实际不一致

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#366]
**SQLe Version**
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x 4eb97fa471

**Describe the bug**
修改完审核任务后退到编辑页面“审核任务类型“与实际不一致
![image](https://user-images.githubusercontent.com/18008452/156521421-7e98d01f-1fd8-40c9-a3d8-b030c4bc5ae8.png)

**To Reproduce**
1. 编辑任意一个审核任务
![image](https://user-images.githubusercontent.com/18008452/156522014-f87d12a7-c0b2-4845-b0cb-6b9789fbead9.png)
2. 点击提交后，弹窗页面点返回
![image](https://user-images.githubusercontent.com/18008452/156522138-802ab909-18bc-497d-9519-00803142e886.png)
3. 返回后页面对应的“审核任务类型”变成“请选择”
![image](https://user-images.githubusercontent.com/18008452/156522368-9020fed1-e960-4ff8-a25a-151b2ec5e019.png)
4. 再次编辑会无法提交，提示如描述中的错误

**Expected behavior**
期望显示为更新后正确的内容

**Comment by zhouzhilu9** [comment]
验证版本：
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证方式：
1，进入【审核任务列表】，点击”创建审核任务“
2，审核任务类型选择:自定义，点击”提交“
3，创建成功后，点击弹框的”关闭“
4，进入刚创建的任务审核列表，审核任务类型为：自定义
