### ISSUE TITLE
审核界面的回滚语句存在一定歧义，让用户误以为可以回滚

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#367]
**Describe**
审核界面的回滚语句存在一定歧义，让用户误以为可以回滚。

**Suggestion**
希望可以通过类似修改描述来避免歧义。建议将“回滚语句“ 改成 “回滚语句（仅提示，不支持执行回滚）”
![image](https://user-images.githubusercontent.com/18008452/159196656-f98a6d14-1b55-484b-89a2-de9bf05ba642.png)

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证通过
目前文案已经做了相应的变更
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/54339501/161204644-73e8e234-3b87-4795-8211-23a6c91a5743.png">
