### ISSUE TITLE
Oracle 审核任务 TopSQL 展示数据优化

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#375]
**Describe**
1. 将所有时间单位换算为秒，目前是（纳秒）, 数字太大可读性差
2. 将“CPU时间“的描述改成“CPU消耗时间”
3. Top SQL 未按照配置的维度进行排序，例如选择 cpu_time后未按从大到小排序

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证通过
验证步骤：
添加一个oracle数据源，然后创建一个topsql的审核任务类型，等待抓取sql语句，进行查看sql，目前已经是CPU消耗时间且单位都已经是秒，并且按照CPU消耗时间进行排序

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/54339501/161203714-2dfb1da0-a7e4-4388-8480-5b84ab50708a.png">
