### ISSUE TITLE
审核结果建议按等级排序展示

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#379]
**Describe**
目前审核结果集合是随机排序的，不是按等级顺序展示
![image](https://user-images.githubusercontent.com/18008452/157391384-e022b05a-3b95-409d-870a-97199465621d.png)

**Suggestion**
建议按照等级排序，将审核等级高的排在前面

**Comment by HuangWeiCen** [comment]
## 修复方案
通过在添加审核结果的时候排一遍序, 保证审核结果始终是有序的(从高到低)
#### 每次添加都排序的原因
1. 排序不适合放到Message()中,因为这会导致Message的行为不符合语义(偷偷改变内部排序), 放到Add中没问题, 添加时直接插入到对应位置很正常
2. 不直接插入而是每次都排序的原因: 因为审核结果数量很少, 排序很快, 但手动插入代码较为复杂, 所以为了增加代码可读性, 适当的牺牲点性能

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199

验证通过
验证步骤：
目前在对工单内的sql进行审核的时候，对应的审核提示按照级别开始进行排序了

<img width="1802" alt="image" src="https://user-images.githubusercontent.com/54339501/161201660-258c2d81-a987-4afe-bf45-a7dd391c5fe9.png">
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/54339501/161202157-19be7c73-7548-44c1-b710-b033717e29b0.png">
