### ISSUE TITLE
It is necessary to pass a special level for all

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#382]
# 问题描述
平台目前无法根据错误等级判断审核结果到底是全部通过还是触发了normal等级的规则， 因为这两者的等级都是normal， 需要加以区分

# 解决方案
1. 新增一个等级Null表示没有触发任何规则， 此等级对使用平台者无感知
2. Normal等级由以前表示最高触发了Normal等级 改为  触发了规则且触发规则最高等级为normal

## 影响接口
/v1/tasks/audits [post]
/v1/tasks/audits/{task_id}/ [get]
/v1/audit_plans/{audit_plan_name}/trigger [post]
/v1/audit_plans/{audit_plan_name}/reports [get]

### 影响内容
明确 audit_level的含义， 表示最高错误等级， 当没有触发任何规则时没有错误等级， 此时这个字段为空值

## 影响流程
历史记录中可能会有错误的等级记录, 比如以前没触发任何规则记录的等级是normal, 现在normal已经不表示没触发任何规则了

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证通过
验证步骤
创建一个审核任务，然后抓取到的sql使其不会出发任何的审核提示，然后查看审核记录，该记录并不会normal级别，而是通过的标志✅

<img width="696" alt="image" src="https://user-images.githubusercontent.com/54339501/161206658-7f11fefa-a207-44eb-b4a1-104c9a23ad4e.png">

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/54339501/161206733-7f26c575-4fe8-46f1-8792-b72fa3941e6d.png">
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/54339501/161206773-c0dc5154-f2c0-4473-a74a-e2236628a863.png">
