### ISSUE TITLE
MySQL给字段指定非预期的字符集无法触发规则 “必须使用指定数据库字符集“

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#389]
**SQLe Version**
sqle main

**Describe the bug**
MySQL给字段指定非预期的字符集无法触发规则 “必须使用指定数据库字符集“
```sql
create table t1 (
    id varchar(255) character set utf8
) 
```

**To Reproduce**
略

**Expected behavior**
1. MySQL字符集可以通过数据库，表，字段级别配置，需要保证能验证到字段级别
2. 创建修改字段都需要验证

**Comment by Marcus9530** [comment]
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x-ee cfc826b110
复现成功
复现步骤：
开启必须使用指定数据库字符集审核规则，使用以下sql进行审核，并未触发相关审核提示
create table t1 (
    id varchar(255) character set utf8
) 

<img width="1706" alt="image" src="https://user-images.githubusercontent.com/54339501/161202841-bac2905c-7957-4dd6-a74f-075baaee3b8f.png">
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/54339501/161202852-c90ab70e-e91f-4cb8-8a35-0b1f4ece59af.png">

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199
验证通过
验证步骤
开启必须使用指定数据库字符集审核规则，使用以下sql进行审核，触发相关审核提示必须使用utf8mb4数据库字符集

create table t1 (
id varchar(255) character set utf8
)

<img width="1619" alt="image" src="https://user-images.githubusercontent.com/54339501/161203360-f133a32f-36df-485e-b322-9b6204b6404d.png">

<img width="1871" alt="image" src="https://user-images.githubusercontent.com/54339501/161203091-0fe2ad62-212f-4e58-86c5-e1ab4e338dac.png">
