### ISSUE TITLE
开源版本放出审批流程配置页面并提示是企业版功能

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#406]
**Describe**
有很多社区的同学咨询为啥找不到审批流程的配置页面，需要反复提醒这是企业版功能。

**Suggestion**
在开源版本中，将审批流程的配置的页面放出，并且在页面展示“审批流程配置是企业版功能”

**Comment by zhouzhilu9** [comment]
验证版本：
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x 2ed712ad91
验证方式：
进入【流程管理】，出现提示”
审批流程管理为企业版功能，该功能可以为您提供：为不同的数据源绑定不同的审批流程，为审批流程新增审核步骤，为审核步骤指定审核人等等一系列功能。如果您要想使用这些功能，您可以按照以下链接中的商业支持里的联系方式进行咨询。
https://actiontech.github.io/sqle-docs-cn/
https://www.actionsky.com/“
