### ISSUE TITLE
邮件配置新增可以开启或者关闭的按钮

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#407]
**Describe**
邮件的配置目前只能修改而无法删除，配置完了之后无法关闭邮件推送。目前如果不想推送则只能把邮件配置改成错的。

**Suggestion**
新增一个配置项来控制是否推送邮件。后端需要考虑老版本兼容。

**Comment by HuangWeiCen** [comment]
# 修复方案

## 前后端
新增一个字段用于记录是否禁用邮件

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee aaa0497deb

验证通过
1.当开启了邮件推送时，创建工单审批人或执行人都会收到对应的邮件提示
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/54339501/161012887-c73cbfbd-ffd3-4c23-8730-063c2811c1f1.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/54339501/161013082-f8514c3d-084c-4ad4-9e96-a33a893f9b60.png">
2.当关闭邮件推送时，在创建工单审批人或执行人都收不到邮件提示
