### ISSUE TITLE
审核任务进行Mybatis扫描时报错：Error 1062: Duplicate entry

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#410]
**SQLe Version**
sqle main

**Describe the bug**
审核任务进行Mybatis扫描时报错：Error 1062: Duplicate entry。
![6N0AQ0ZIVT8(}OOQUUX PPV](https://user-images.githubusercontent.com/18008452/159258207-7b435939-6ecb-4019-badd-ff5192bb602e.jpg)

```bash
time="2022-03-21T19:37:02+08:00" level=info msg="log/universe/sqle/model/audit_plan.go:87Error 1062: Duplicate entry '1-SELECT `tid`,`id`,`name`,`url`,`code`,`serialindex`,`parent_id' for key 'uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint'" type=sql
```
测试文件XML：
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.chinaums.devops.db.dao.SysOrganizeMapper">
    <sql id="length_than_255">
        t.column00,
        t.column01,
        t.column02,
        t.column03,
        t.column04,
        t.column05,
        t.column06,
        t.column07,
        t.column08,
        t.column09,
        t.column10,
        t.column11,
        t.column12,
        t.column13,
        t.column14,
        t.column15,
        t.column16,
        t.column17,
        t.column18,
        t.column19,
        t.column20,
        t.column21,
        t.column22,
        t.column23,
        t.column24
  </sql>
    <select id="sql1">
        select
        <include refid="length_than_255"/>
        from t1 as t
    </select>
    <select id="sql2">
        select
        <include refid="length_than_255"/>
        from t2 as t
    </select>
</mapper>
```

**Comment by sjjian** [comment]
## 原因
后端存储SQL指纹时，使用的联合索引 UNIQUE KEY `uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint` (`audit_plan_id`,`fingerprint`(255))， 这种前缀索引导致字符超过255时可能会重复

**Comment by sjjian** [comment]
## 方案
使用sql指纹（sql fingerprint）的md5值作为联合唯一索引的字段

**Comment by sjjian** [comment]
### 升级方案
该issue内修改了表字段，导致程序无法自动进行表升级，需要手工该表，如果升级的话
```sql
alter table audit_plan_sqls_v2 add column fingerprint_md5 varchar(255) not null;
update audit_plan_sqls_v2 set fingerprint_md5=MD5(fingerprint);
alter table audit_plan_sqls_v2 add unique key uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint_md5(audit_plan_id, fingerprint_md5);
alter table audit_plan_sqls_v2 drop index uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint;
```

**Comment by Marcus9530** [comment]
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x-ee cfc826b110
复现成功
复现步骤：
1.使用示例xml文件添加到gitlab上面，然后配置jenkins和sqle的审核任务
2.触发jenkins进行编译，然后失败，查看输出台信息出现error:Error 1062: Duplicate entry '1-SELECT `t`.`column00`,`t`.`column01`,`t`.`column02`,`t`.`colum' for key 'uniq_audit_plan_sqls_v2_audit_plan_id_fingerprint'

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/54339501/161226592-ec79a378-fe39-4643-85f7-7381f2ca05b2.png">

**Comment by Marcus9530** [comment]
UI Version: main bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
验证通过
验证步骤
1.使用示例xml文件添加到gitlab上面，然后配置jenkins和sqle的审核任务
2.触发jenkins进行编译，然后失败，查看输出台信息并没有出现error:Error 1062: Duplicate entry 
<img width="1603" alt="image" src="https://user-images.githubusercontent.com/54339501/161227452-ebcac1b4-38b2-4dc8-9cf8-b18ea50411dc.png">
