### ISSUE TITLE
MySQL审核开启索引优化建议时执行特定语句报错

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#416]
**SQLe Version**
sqle main

**Describe the bug**
MySQL审核开启索引优化时执行特定语句报错，例如：
```sql
select * from t1 as t where id = 1;
```
当表结构为：
```sql
 CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `ci` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
报错信息：
```bash
optimize sql: optimize single table t: table t1 not found when check index
```
截图：
![image](https://user-images.githubusercontent.com/18008452/159837455-d278eb09-c122-4ea1-b305-06c9708ef1ff.png)

## 需求
1. 解决上述问题，该类型语句不报错
2. 索引优化的报错不再引起接口报错，而是在日志打印错误信息。影响是可能无法按预期输出索引优化建议

**Comment by HuangWeiCen** [comment]
## 问题分析
报错是因为 缓存sql中涉及到的表时 将表的别名进行缓存, 但校验表是否存在时 使用表的真名进行查询, 从而导致找不到这个表的缓存信息,进而报错

## 影响面
单表查询的索引优化受到影响, 多表查询没有影响

## 修复方式
1. 经确认, 调用相关逻辑时, 使用的表名均为表的真名, 遂将缓存表名的地方改为保存表的真名, 校验表是否存在时可以找到对应信息, 误报即可消失
2. 索引优化的报错信息改为向sqled.log输出一条error等级的日志, 关键词 'optimize sqle failed'

**Comment by Marcus9530** [comment]
UI Version: release-1.2202.x 1651c64
Server Version: release-1.2202.x-ee cfc826b110
复现成功
复现步骤：
1.创建表
 CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `ci` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
2.开启索引优化建议
3.创建工单进行审核

select * from t1 as t where id = 1;


<img width="1313" alt="image" src="https://user-images.githubusercontent.com/54339501/161216795-0b8cd993-4969-4579-9295-931ab3c9964e.png">

**Comment by Marcus9530** [comment]
UI Version: main bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
验证通过
验证步骤：
1.创建表
CREATE TABLE t1 (
id int(11) DEFAULT NULL,
ci varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
2.开启索引优化建议
3.创建工单进行审核，并没有出现错误提示

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/54339501/161217228-03fbf9ca-5637-42d6-bce7-d5572e7c2928.png">
