### ISSUE TITLE
过长的待审核sql将导致sqle无法存储

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#425]
## 问题现象
使用者审核了一条长度达到92万字节的sql, 然后sqle报了下图的错误
![image](https://user-images.githubusercontent.com/37464327/160803231-f8f9523a-cd5e-43dd-abd2-fab0f8aad420.png)

## 问题原因
sqle的 execute_sql_detail 表中的content字段用于存储审核的sql文本, 这个字段是text类型的,最大长度65535, 无法存储这么长的数据

## 手动绕过方案
1. 登入SQLE存储元数据的数据库
2. 执行 alter table sqle.execute_sql_detail change content content mediumtext COLLATE utf8mb4_unicode_ci;

## 修复方案
将BaseSQL{} 的content 字段对应的字段类型改为longtext

### 方案理由
sqle不知道用户会审核怎么样的sql, 如果下回用户要审核一条超过mediumtext 类型的sql, 可能导致再次出现这个问题, 所以一步到位直接设置最长的字段

## 影响面
1. 新部署的sqle  execute_sql_detail表和rollback_sql_detail表的content字段都会改为longtext类型
2. **旧的sqle升级到新sqle需要手动修改表字段**, 修改方式:
              1. 登入SQLE存储元数据的数据库
              2. 执行如下两条SQL
              `alter table sqle.execute_sql_detail change content content longtext COLLATE utf8mb4_unicode_ci;`
              `alter table sqle.rollback_sql_detail change content content longtext COLLATE utf8mb4_unicode_ci;`

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现成功
复现步骤：
1.创建工单
2.上传一条长度达到92万字节的sql文本点击审核，出现报错信息
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/54339501/165878362-41110c25-1dae-44b5-a7d5-f1fd65fdfdc7.png">

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x-ee 0dcf3a29e5
验证成功
验证步骤：
1.创建工单
2.上传一条长度达到92万字节的sql文本点击审核，没有出现报错信息且正常的进行审核
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/54339501/165878624-00fc7718-3640-41d2-8866-160be68f135d.png">
