### ISSUE TITLE
审核任务中审核记录里面没有隐藏id

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#429]
**SQLe Version**
UI Version: release-1.2203.x 198e94d
Server Version: release-1.2203.x-ee 1bf0a18199

**To Reproduce**
1.创建一个审核任务，然后触发审核
2.查看审核记录

原始需求中https://github.com/actiontech/sqle/issues/268说明前端会把审核记录id给隐藏，实际只隐藏了审核任务里面的，但是没有每条审核记录中id

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/54339501/160989951-43fe5926-1a3e-49fe-b8ec-5cfd9a63337d.png">
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/54339501/160990167-ed002a5b-fea3-4f68-9318-4cf67bee05ad.png">

**Comment by HuangWeiCen** [comment]
### 后端调整结果
1. 废弃 /v2/audit_plans/{audit_plan_name}/report/{audit_plan_report_id}/ [get] 因为这个接口定义不合理
2. 新增 /v2/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls [get] , 用于替代(1) 中废弃的接口, 入参出参和(1)保持一致
3. 新增 /v1/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/ [get] , 用于提供参考方案中前端需要的信息

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x f55e40b
Server Version: release-1.2204.x-ee 108c4c0322
验证通过
验证步骤：
1.创建一个审核任务，然后触发审核
2.查看审核记录，并没有出现生成的id
<img width="1703" alt="image" src="https://user-images.githubusercontent.com/54339501/165695656-c8d8aa8c-65ca-4734-b3bb-8881d9cffbe9.png">
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/54339501/165695698-8c6fdf15-b8c3-4fa0-8918-845f8d5bde2f.png">
