### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by goer3** [actiontech/sqle#43]
1. 登录页优化建议：
![image](https://user-images.githubusercontent.com/32036696/138630753-6ee910be-f71b-4169-b164-99932605a4da.png)
说明：登录页效果有点 low，感觉配不上内部的功能组件，建议整的大气点，可以参考现在的 Jumpserver 那样，不用吝啬广告，把你们的名字搞上去。

2. 工单名称不支持中文：
![image](https://user-images.githubusercontent.com/32036696/138630951-83f023b3-ddad-4b9f-982e-daf72b799548.png)
说明：没有明白这个需求，工单名称不是为了更好的描述该工单的用途吗？为啥不能使用中文，而且就算不使用中文，为啥不允许空格呢？全英文通过各种符号连接单词感觉更奇怪。

3. sql 框建议加入 sql 美化功能，便与更好的查看。

**Comment by sjjian** [comment]
建议1 已优化：https://github.com/actiontech/sqle/issues/606

**Comment by sjjian** [comment]
建议2：https://github.com/actiontech/sqle/issues/698
