### ISSUE TITLE
支持AD/LDAP部门人员信息同步

### ISSUE THREAD

**Issue by samgang** [actiontech/sqle#44]
支持AD/LDAP部门人员信息同步

**Comment by sjjian** [comment]
### 需求
1. 【前端/后端】全局配置支持配置 ldap
2. 【前端】登录页面支持选择使用ldap登录或者普通登录
3. 【后端】ldap用户初次登录创建同名SQLE用户并使用当前ldap密码作为SQLE内的用户密码。
4. 【后端】ldap用户可以使用（ldap登录或者普通登录）

**Comment by HuangWeiCen** [comment]
**### 需求调整**
1. [前端/后端] 全局配置支持配置 ldap；
2. [后端] 登录逻辑: 用户登陆时先校验此用户的用户来源, 如果来源是ldap或此用户不存在, 且ldap配置被打开则进入ldap登录流程;
3. [后端] ldap用户初次登录创建同名SQLE用户并使用当前ldap密码作为SQLE内的用户密码，同步ldap内的用户邮箱作为SQLE内用户的邮箱；
4. [后端] ldap用户不允许修改密码(SQLE中存的ldap用户密码无意义也不会被使用);
5. [后端] 存储用户来源，是来自ldap还是sqle平台创建.

**Comment by sjjian** [comment]
> ### **需求调整**
> 1. [前端/后端] 全局配置支持配置 ldap；
> 2. [后端] 登录逻辑: 用户登陆时先校验此用户的用户来源, 如果来源是ldap或此用户不存在, 且ldap配置被打开则进入ldap登录流程;
> 3. [后端] ldap用户初次登录创建同名SQLE用户，同步ldap内的用户邮箱作为SQLE内用户的邮箱；
> 4. [后端] ldap用户不允许修改密码(SQLE中存的ldap用户密码无意义也不会被使用);
> 5. [后端] 存储用户来源，是来自ldap还是sqle平台创建.

我没问题

**Comment by HuangWeiCen** [comment]
ldap 配置修改和获取接口的接口定义在https://github.com/actiontech/sqle/pull/64 中被提交
新增接口如下, 详细接口信息见接口文档
1.   /v1/configurations/ldap [patch]
2.  /v1/configurations/ldap [get]

**Comment by sjjian** [comment]
@HuangWeiCen, 需要补充LDAP每个配置项在页面对应的中文描述

**Comment by sjjian** [comment]
请前端支持下LDAP配置，在系统配置页面。建议采用sqle-ui release-1.2111.x 分支

**Comment by HuangWeiCen** [comment]
### **ldap配置项对应界面中文描述＆释义**
enable_ldap : 启用ldap验证  , 作用: 开启/关闭ldap验证功能
ldap_connect_dn: ldap连接用户DN, 作用: 通过此用户登录ldap查询login界面登录用户的信息
ldap_connect_pwd: ldap连接用户密码, 作用: ldap_connect_dn对应的密码
ldap_search_base_dn: 根域地址, 作用: 查询时会以此目录作为根目录进行查询
ldap_server_host: ldap服务器地址, 作用: ldap服务器地址
ldap_server_port: ldap服务器端口号, 作用: ldap服务器端口号
ldap_user_email_rdn_key: 用户邮箱在ldap中对应的属性名
ldap_user_name_rdn_key: 用户名在ldap中对应的属性名

**Comment by sjjian** [comment]
## 需求整理：
[前端/后端] 全局配置支持配置 ldap；
[后端] 登录逻辑: 用户登陆时先校验此用户的用户来源, 如果来源是ldap或此用户不存在, 且ldap配置被打开则进入ldap登录流程;
[后端] ldap用户初次登录创建同名SQLE用户，同步ldap内的用户邮箱作为SQLE内用户的邮箱；
[后端] ldap用户仅通过ldap登录，密码通过sqle平台修改无效(SQLE中存的ldap用户密码无意义也不会被使用);
[后端] 存储用户来源，是来自ldap还是sqle平台创建.
