### ISSUE TITLE
Mybatis Scanner support skip invalid query in XML

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#442]
## 需求
sqle scanner 添加命令行参数跳过Mybatis 扫描时无法解析的SQL。原因是Mybatis 解析可能存在解析不支持的SQL，添加参数可以让用户选择是否跳过，这样可以保证流程能走通，并且能做到尽量审核最多的SQL

**Comment by HuangWeiCen** [comment]
## 开发方案
提供 '--skip-unqualified-sql' (或 -S) 命令, 此参数为bool类型, 带有此参数时会跳过错误的sql

## 实际效果演示
### 测试用mybatis文件内容
```
<mapper namespace="Test">
        <sql id="someinclude">
        *
        </sql>
    <select id="testBind">
        <bind name="likeName" value="'%' + name + '%'"/>
        SELECT
        name,
        category,
        price
        FROM
        fruits
        WHERE
        name like #{likeName}
    </select>
        <select id="select" resultType="map">
                select
                <include refid="someinclude2" />
                from t
        </select>
</mapper>
```
### 不指定此参数的效果
![image](https://user-images.githubusercontent.com/37464327/162377572-0d144bef-00dc-475a-a4d3-337b891278a4.png)
可以看出因为有错误的sql, 导致无法审核, 抛出错误 'sql someinclude2 is not exist'

### 指定此参数后
![image](https://user-images.githubusercontent.com/37464327/162377765-9ea7658e-0f11-4a85-895b-5a6426813a4c.png)
可以看出可以正常审核了,错误的sql被忽略
