### ISSUE TITLE
MySQL给字段指定非预期的字符集排序规则匹配规则 “建议使用规定的数据库排序规则“

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#443]
**SQLe Version**
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x 2ed712ad91

**Describe the bug**
MySQL给字段指定非预期的字符集排序规则匹配规则 “建议使用规定的数据库排序规则“，例如审核SQL：
```sql
alter table users modify column id varchar(255) character set utf8mb4 collate utf8mb4_bin default 1 comment "111"
```

**To Reproduce**
1. 启用数据源对应的规则模板内规则“建议使用规定的数据库排序规则“，并设置数据库排序规则: utf8mb4_bin
2. 提前在数据源内创建数据和表
```sql
create database db1;
create table t1 (id int);
```
3. 对该数据源进行工单审核，提交审核语句
```sql
alter table users modify column id varchar(255) character set utf8mb4 collate utf8mb4_bin default 1 comment "111"
```
4. 审核提示“建议使用规定的数据库排序规则为utf8mb4_bin”

**Expected behavior**
期望不提示“建议使用规定的数据库排序规则为utf8mb4_bin”，因为该DDL该表的字段字符集排序指定的就是“utf8mb4_bin”

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现成功
复现步骤：
1.启用数据源对应的规则模板内规则“建议使用规定的数据库排序规则“，并设置数据库排序规则: utf8mb4_bin
2.提前在数据源内创建数据和表
create database db1;
create table db1.t1 (id int);
3.对该数据源进行工单审核，提交审核语句
alter table users modify column id varchar(255) character set utf8mb4 collate utf8mb4_bin default 1 comment "111"
4.审核提示“建议使用规定的数据库排序规则为utf8mb4_bin”

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/54339501/165876008-879cbb2a-e687-4483-8916-fda482514b4e.png">

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x-ee 0dcf3a29e5
验证成功
验证步骤：
1.启用数据源对应的规则模板内规则“建议使用规定的数据库排序规则“，并设置数据库排序规则: utf8mb4_bin
2.提前在数据源内创建数据和表
create database db1;
create table db1.t1 (id int);
3.对该数据源进行工单审核，提交审核语句
alter table users modify column id varchar(255) character set utf8mb4 collate utf8mb4_bin default 1 comment "111"
4.审核提示中没有出现“建议使用规定的数据库排序规则为utf8mb4_bin”
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/54339501/165877457-af716aff-249b-4988-bea3-e44d5b311466.png">
