### ISSUE TITLE
API服务里，工单执行完成后，可以提供一个回调地址去通知调用API的服务【企业版】

### ISSUE THREAD

**Issue by bxhbpdxhzGithub** [actiontech/sqle#450]
API服务里，工单执行完成后，可以提供一个回调地址去通知调用API的服务。
已有的工单系统，以API的方式接入后，工单执行完成了，要自己定时去查询结果，能不能在执行完成后，回调一个接口之类的，及时通知一下

**Comment by sjjian** [comment]
我们后续可以规划下

**Comment by ColdWaterLW** [comment]
# 需求细节
## 入口
平台管理员账号登录， 进入系统设置-消息推送，选择webhook配置

## 需求概要
1. 用户点击“修改”，进行webhook配置
- 选择是否开启webhook通知，启用此项后Webhook推送才会生效, 启停Webhook推送不会影响其他推送方式, 启用后如果工单状态发生变化，会向用户配置的 API 发送 POST 请求告知用户工单状态
- 默认不开启，选择开启，用户需填写以下内容，并点击提交
  - webhook url：**必填**，用于工单消息推送的 API 地址
  - 最大重试次数：默认3次，取值范围0-5。如果发送失败，请求重试的最大次数； 
  - 重试间隔：默认1秒，取值范围1-5。请求重试的发送间隔；
  - App ID：默认为 sqle。用于标识推送方，过滤非法请求
  - App Secret：默认为空。用于标识推送方，过滤非法请求

注：
- 会触发通知的事件有创建工单、审核工单、上线工单
- 开启该服务时，需要校验必填项，关闭服务时无需校验任何参数。

2. 用户点击“测试”，如配置正确，能在api服务端收到正确的api调用信息
测试的文字模板：```"This is a SQLE test notification\nIf you receive this message, it only means that the message can be pushed"```

## 原型
**入口**
![image](https://github.com/actiontech/sqle/assets/36940986/ec4bc7c9-bd3d-4c6c-b963-29ededce610b)

**配置页面**
![image](https://github.com/actiontech/sqle/assets/36940986/8e791bbd-48e0-4d6d-bd39-186e9f2aae9d)

**开启配置后页面**
![image](https://github.com/actiontech/sqle/assets/36940986/5a72c9b2-2d4a-48b4-b1eb-33d5ee348bc2)

**SQLE 对用户指定的 URL 发送 POST 请求 Body 示例：**
```json
{   
    "project_name": "default", // 工单对应的 project  
    "workflow_id": "1654042589025800192", // 工单的 workflow_id 
    "workflow_subject ": "工单名称", //id对应的名称
    "workflow_status": "finished" // 工单状态，可能的取值有 "wait_for_audit"（待审核）, "wait_for_execution"（待上线）, "canceled"(已关闭), "rejected"(已驳回), "executing"(正在上线), "exec_failed"(上线失败), "finished"（上线成功） 
    "timestamp": "2023-05-04T17:12:59+08:00" // 发送请求的时间戳
}
```

**Comment by jessun** [comment]
## 新增功能

- 用户可以更新或查看当前的工单 webhook 配置；
- 用户可以通过【测试】按钮对该 webhook 发送测试请求；
- 在配置完成 webhook API 后，同其他工单通知方式相似：在工单处理中，向指定的 URL 发送 Post 请求。

sqle POST 请求的主要格式如下
```bash
POST / HTTP/1.1
Host: 192.168.21.34:8000
Accept-Encoding: gzip
Authorization: Bearer test123
Content-Length: 239
User-Agent: Go-http-client/1.1

{"event":"workflow","action":"create","timestamp":"2023-05-18T15:45:25+08:00","payload":{"workflow":{"project_name":"test_project","workflow_id":"1658637666259832832","workflow_subject":"test_workflow","workflow_status":"wait_for_audit"}}}
```
其中
- "event" 恒为 "workflow"（目前 sqle 只支持工单通知）；
- "action" 可能的取值有 ["create", "approve", "reject", "exec_success", "exec_failed"]。分别对应「工单创建」、「审核通过」、「审核驳回」、「上线成功」、「上线失败」；
- "timestamp" 表示请求发出的时间，RFC3339 格式；
- "payload" 表示该请求的主要业务内容，目前仅支持工单；
- "workflow" 表示该工单的当前信息，与 sqle 后端数据库中记录保持一致；

此外
- 用户配置的 token 会被放置在请求 Header 中的 Authorization 字段。参考规范：https://datatracker.ietf.org/doc/html/rfc6750。
- 接收请求的服务端在收到请求后，需要返回 200 响应。否则 sqle 会打印返回 body 中的文本信息。
- 在发送测试请求时，请确保接收请求的服务端运行正常。否则可能出现如下问题
```json
{
    "code": 0,
    "message": "ok",
    "data": {
        "send_error_message": "Post \"http://192.168.21.34:8000\": dial tcp 192.168.21.34:8000: connect: connection refused"
    }
}
```
