### ISSUE TITLE
规则 "建议选择可选性超过阈值字段作为索引" 给出的建议不准确

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#465]
## 复现方式
在【平台管理】-【数据源】页面配置数据源。在数据库实例上创建数据库和表 ,建库建表语句如下：
create database db1;
use db1;
create table if not exists t1(id bigint unsigned, c1 varchar(10) default 'a', c2 int default null, c3 varchar(10) default 'a') engine innodb charset utf8mb4;
insert into t1(c1,c2,c3) value('test1',1,'test1');
insert into t1(c1,c2,c3) value('test2',2,'test2');
insert into t1(c1,c2,c3) value('test3',3,'test3');
insert into t1(c1,c2,c3) value('test4',1,'test4');
insert into t1(c1,c2,c3) value('test5',2,'test5');
insert into t1(c1,c2,c3) value('test6',3,'test6');
insert into t1(c1,c2,c3) value('test7',1,'test7');
insert into t1(c1,c2,c3) value('test8',2,'test1');
insert into t1(c1,c2,c3) value('test9',3,'test1');
insert into t1(c1,c2,c3) value('test10','1','test1');
2.进入【平台管理】-【模板管理】界面，点击规则详情,启用规则：建议选择可选性超过阈值字段作为索引
3.进入【工单】-【工单列表】界面，进行SQL工单申请，工单SQL为：
alter table t1 add primary key (c1);
4. 观察结果, 发现这条sql触发此项, 但该列的值唯一，不同列值的占比>阈值要求
![image](https://user-images.githubusercontent.com/37464327/164431454-8b6d61e8-4801-4917-bece-d63c16ef2ef6.png)

## 问题原因
在比较可选性和阈值时 比较方式是判断两个值的字符串谁大, 但这种判断方式实际上是比较两个字符在字典上谁更靠前, 这种比较方式实际上没有意义, 比如 "70" > "100.000"

## 修复方式
将字符串先转换为float64, 再进行数字比较

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现成功
复现步骤：
1.在【平台管理】-【数据源】页面配置数据源。在数据库实例上创建数据库和表 ,建库建表语句如下：
create database db1;
use db1;
create table if not exists t1(id bigint unsigned, c1 varchar(10) default 'a', c2 int default null, c3 varchar(10) default 'a') engine innodb charset utf8mb4;
insert into t1(c1,c2,c3) value('test1',1,'test1');
insert into t1(c1,c2,c3) value('test2',2,'test2');
insert into t1(c1,c2,c3) value('test3',3,'test3');
insert into t1(c1,c2,c3) value('test4',1,'test4');
insert into t1(c1,c2,c3) value('test5',2,'test5');
insert into t1(c1,c2,c3) value('test6',3,'test6');
insert into t1(c1,c2,c3) value('test7',1,'test7');
insert into t1(c1,c2,c3) value('test8',2,'test1');
insert into t1(c1,c2,c3) value('test9',3,'test1');
insert into t1(c1,c2,c3) value('test10','1','test1');
2.进入【平台管理】-【模板管理】界面，点击规则详情,启用规则：建议选择可选性超过阈值字段作为索引
3.进入【工单】-【工单列表】界面，进行SQL工单申请，工单SQL为：
alter table t1 add primary key (c1);
4. 观察结果, 发现这条sql触发此项, 但该列的值唯一，不同列值的占比>阈值要求

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/54339501/165691699-1c6f2336-c064-4410-8223-b04aece3cc0d.png">

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现成功
复现步骤：
1.在【平台管理】-【数据源】页面配置数据源。在数据库实例上创建数据库和表 ,建库建表语句如下：
create database db1;
use db1;
create table if not exists t1(id bigint unsigned, c1 varchar(10) default 'a', c2 int default null, c3 varchar(10) default 'a') engine innodb charset utf8mb4;
insert into t1(c1,c2,c3) value('test1',1,'test1');
insert into t1(c1,c2,c3) value('test2',2,'test2');
insert into t1(c1,c2,c3) value('test3',3,'test3');
insert into t1(c1,c2,c3) value('test4',1,'test4');
insert into t1(c1,c2,c3) value('test5',2,'test5');
insert into t1(c1,c2,c3) value('test6',3,'test6');
insert into t1(c1,c2,c3) value('test7',1,'test7');
insert into t1(c1,c2,c3) value('test8',2,'test1');
insert into t1(c1,c2,c3) value('test9',3,'test1');
insert into t1(c1,c2,c3) value('test10','1','test1');
2.进入【平台管理】-【模板管理】界面，点击规则详情,启用规则：建议选择可选性超过阈值字段作为索引
3.进入【工单】-【工单列表】界面，进行SQL工单申请，工单SQL为：
alter table t1 add primary key (c1);
4. 观察结果, 发现这条sql触发此项, 但该列的值唯一，不同列值的占比>阈值要求

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/54339501/165691699-1c6f2336-c064-4410-8223-b04aece3cc0d.png">

**Comment by Marcus9530** [comment]
![Uploading image.png…]()

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x f55e40b
Server Version: release-1.2204.x-ee 108c4c0322

验证成功
验证步骤：
1.在【平台管理】-【数据源】页面配置数据源。在数据库实例上创建数据库和表 ,建库建表语句如下：
create database db1;
use db1;
create table if not exists t1(id bigint unsigned, c1 varchar(10) default 'a', c2 int default null, c3 varchar(10) default 'a') engine innodb charset utf8mb4;
insert into t1(c1,c2,c3) value('test1',1,'test1');
insert into t1(c1,c2,c3) value('test2',2,'test2');
insert into t1(c1,c2,c3) value('test3',3,'test3');
insert into t1(c1,c2,c3) value('test4',1,'test4');
insert into t1(c1,c2,c3) value('test5',2,'test5');
insert into t1(c1,c2,c3) value('test6',3,'test6');
insert into t1(c1,c2,c3) value('test7',1,'test7');
insert into t1(c1,c2,c3) value('test8',2,'test1');
insert into t1(c1,c2,c3) value('test9',3,'test1');
insert into t1(c1,c2,c3) value('test10','1','test1');
2.进入【平台管理】-【模板管理】界面，点击规则详情,启用规则：建议选择可选性超过阈值字段作为索引
3.进入【工单】-【工单列表】界面，进行SQL工单申请，工单SQL为：
alter table t1 add primary key (c1);
4. 观察结果, 发现这条sql没有触发 不同列值的占比>阈值要求审核提示


<img width="1640" alt="image" src="https://user-images.githubusercontent.com/54339501/165695095-31fbb9a9-159e-4caf-9eea-880b93406fd4.png">
