### ISSUE TITLE
Some audit rules have specific audit requirements

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#466]
# 问题描述
部分审核规则有特定的使用场景, 如 <使用explain加强预检查能力> 规则就不应该用于审核mybatis的sql, mybatis中sql的占位符会被预检查规则误判为错误sql
但现在审核规则是跟数据源绑定的, 无法根据实际场景忽略对应的规则
# 方案
1. 数据源多模板模式，对于不同的场景应用不同的规则模板

**Comment by sjjian** [comment]
使用该方案实现：https://github.com/actiontech/sqle/issues/755
