### ISSUE TITLE
The audit rule template cannot be displayed normally when too many datasources in template

### ISSUE THREAD

**Issue by Rain-1214** [actiontech/sqle#469]
![origin_img_v2_7dc3d7df-daa1-4466-9e8d-42abdf66e37g](https://user-images.githubusercontent.com/23204067/164636654-5d455729-2823-4244-b58e-30ba6db4ef2f.jpg)

**Comment by Rain-1214** [comment]
fixed by https://github.com/actiontech/sqle-ui/pull/62

**Comment by Marcus9530** [comment]
复现版本
SQLE
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现步骤：
1.添加十几个数据源到sqle，且数据源名字起的长一点
2.然后使用默认审核模版绑定所有的数据源
3.出现数据源名字超出界面情况
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/54339501/165687539-836b8cc4-4fa2-4fdd-a3e0-f67e48b80dec.png">

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x f55e40b
Server Version: release-1.2204.x-ee 108c4c0322
验证通过
验证步骤：
1.添加十几个数据源到sqle，且数据源名字起的长一点
2.然后使用默认审核模版绑定所有的数据源
3.没有出现数据源名字超出界面的情况

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/54339501/165688432-2692f905-f08e-454f-8bf3-d3f39e0a75bc.png">
