### ISSUE TITLE
optimize cron input. current cron input was too complex.

### ISSUE THREAD

**Issue by Rain-1214** [actiontech/sqle#471]
current:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/23204067/164966773-8df51564-6e2e-4d3f-806d-4f0ce513191d.png">
expect:
1、split simple and manual input mode.
2、only support select every day and every week in simple mode.
3、only support input cron expression by user in manual mode.

**Comment by Marcus9530** [comment]
复现版本
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x-ee 0dcf3a29e5

复现步骤：
创建审核任务，可以看到审核任务周期表达式比较复杂
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54339501/168708451-e3d95f05-983b-4243-b319-bc59b558c3e0.png">

**Comment by Marcus9530** [comment]
UI Version: main 5bfc004
Server Version: main-ee 9ce7104ca3
验证通过
验证步骤：
1.创建一个审核任务，当前选择框已经简化
2.选择一个特定时间点击保存，到点之后进行查看确实进行自动审核，后续没有自动审核
3.选择多个时间点点击保存，到点之后进行查看多个时间点都开始自动审核了

<img width="701" alt="image" src="https://user-images.githubusercontent.com/54339501/170605916-37545674-f3c0-412b-b414-eb8710914bce.png">
<img width="693" alt="image" src="https://user-images.githubusercontent.com/54339501/170606311-ca0d7bb7-8e8d-4ad6-b8bb-00d747ee9c3b.png">
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/54339501/170606312-7856c50d-d880-4322-a5a7-3fa7e4f75613.png">
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/54339501/170607702-103d690f-b906-4719-b5dc-abad9d92dda9.png">
