### ISSUE TITLE
社区版MySQL语法解析失败则审批流程无法正常进行

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#474]
**SQLe Version**
actiontech/sqle-ce:1.2204.0-pre3

**Describe the bug**
当存在语法错误或者无法解析的SQL时提示error级别的错误，导致流程工单无法提交。
![image](https://user-images.githubusercontent.com/18008452/165069455-a96a9d05-351e-445c-b821-990ec51ea0fd.png)
语句可以是其他任何SQL，本次的测试SQL是
```sql
CREATE TABLE `tb01` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增 ID',
  `NAME` varchar(20) NOT NULL DEFAULT '' COMMENT '名字',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='测试表'
```
**Expected behavior**
能提交工单

**Suggestion**
建议将该审核内容调整为“warn”级别。提示信息一并优化为“语法错误或者解析器不支持，请人工确认SQL正确性”

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x 5248287a20
复现步骤：
1.创建一个工单
2.输入一个语法错误的sql语句，然后点击审核
3.提示语法错误或者解析器不支持且级别为error
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/54339501/167248908-fd07da13-6573-4983-8b4c-007d88b8e942.png">

**Comment by Marcus9530** [comment]
UI Version: main 2ddcae6
Server Version: main-ee 1420a4532a
验证通过
验证步骤：
1.创建一个工单
2.输入一个语法错误的sql语句，然后点击审核
3.提示语法错误或者解析器不支持，请人工确认SQL正确性

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/54339501/170458921-cf51c856-0539-4051-8cd8-29160ff4a8b9.png">
