### ISSUE TITLE
期望是修改审核任务的订阅审核失败通知的功能给到操作反馈提示

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#482]
UI Version: release-1.2204.x f55e40b
Server Version: release-1.2204.x-ee 108c4c0322

**Suggestion**
1.创建一个审核任务
2.修改订阅审核失败通知，修改具体信息点击提交
<img width="878" alt="image" src="https://user-images.githubusercontent.com/54339501/165449429-5da4d21d-0cf6-48c3-9d6d-6c4bba24fc8c.png">
3.提交之后窗口变小消失，没有给到操作反馈提示，不知道是否修改成功，需要再次点击查看一下
期望前端给到操作提示让用户感知到修改这个动作是否成功

**Comment by Rain-1214** [comment]
fixed by https://github.com/actiontech/sqle-ui/pull/69

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x-ee 0dcf3a29e5
验证通过
验证步骤：
1.创建一个审核任务
2.修改订阅通知点击提交成功之后，显示订阅成功的提示
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/54339501/165877987-6cc2640c-9c19-41e7-be1e-1da07585f536.png">
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/54339501/165877998-6bd1e59c-041f-4887-8c95-7a9b2786f479.png">
