### ISSUE TITLE
编码格式设置为utf8mb3会导致无法解析sql

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#488]
# 问题描述
1. 执行下方建表语句会报出无法解析的错误
```
CREATE TABLE `tb01` (
  `ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增 ID',
  `NAME` varchar(20) NOT NULL DEFAULT '' COMMENT '名字',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='测试表'
```
2. 如果表是utf8mb3编码, 改表语句将无法正常工作
![H{JUR8P_)QS8KCHDAOLE@ZG](https://user-images.githubusercontent.com/37464327/165874971-96fba395-7011-4a9b-a363-17d77ff28149.png)

**Comment by HuangWeiCen** [comment]
# 修复方案

## 问题分析

1. 通过debug可以发现当sql中指定字符集为utf8mb3时会出现无法解析sql的情况, 字符集为utf8mb4或者uft8无此情况
![utf8mb3](https://user-images.githubusercontent.com/37464327/167058393-5df6ba6d-1333-4667-abe1-bd16e717eb1e.png)
![utf8mb4](https://user-images.githubusercontent.com/37464327/167058478-88efc21c-c48d-47ac-bb3f-b038a98f04a3.png)
![utf8](https://user-images.githubusercontent.com/37464327/167058544-02ef67a0-3370-4d3e-8226-ec117418ee98.png)

2. 通过查看tidb/parser源码可知parser不支持utf8mb3
![image](https://user-images.githubusercontent.com/37464327/167058705-8664b825-b0db-4838-9d23-463598787907.png)
![image](https://user-images.githubusercontent.com/37464327/167059378-340930b1-f937-4dd0-b0bc-1fd9e4282dbb.png)


3. 通过查看tidb相关issue, 发现这个问题并没有被修复, 通过issue时间判断这个问题应该是放弃修复或者被遗忘了(截至此方案已经过去半年了)
https://github.com/pingcap/tidb/pull/28824

## 修复方式
1. fork一个tidb仓库, 手动将uft8mb3字符集补充到tidb中,以保证parser不会因为识别不了这些字符集导致解析sql失败
2. 只保证parser不会因为无法识别字符集而解析失败, 其他与字符集相关的功能(如果有)不做补充

**Comment by HuangWeiCen** [comment]
## 修复方案
将所有解析器抛出的错误记录到审核结果中, 而非弹窗报错

### 修复方式
增加一个新的错误类型 ParserError{} , 将所有解析器的错误包装为此错误, 然后在调用处判断错误类型, 如果为此错误则记录到审核结果中, 如果不是则保持原流程

### 影响功能
![image](https://user-images.githubusercontent.com/37464327/167072649-e513bf78-e59f-492a-81a4-1519a0e6e2ce.png)

### 影响原因
上述功能均涉及使用GetCreateTableStmt()方法, 此方法内部的解析sql失败会抛出此错误

**Comment by HuangWeiCen** [comment]
## PR 相关代码改动说明
1. ParseSql() 改动错误类型无影响, 因为此函数内部的p.PerfectParse() 错误总是为空, 改动仅为了和ParseOneSql()错误类型保持一致, 即解析器抛出的错误统一
2. 更新无效检查的错误信息, 防止被误认为是预检查的错误
3. 统一在无效检查时记录解析器错误, 其他位置(回滚, 检查项, 索引优化等) 此错误将不再抛出, 在无效检查时记录是因为此处第一个执行, 其他功能均在无效检查之后

**Comment by HuangWeiCen** [comment]
因为影响面太大, 暂时停止处理, 研究一下有没有更好的方案, 当前改动放在issue_488分支中, 相关链接: https://github.com/actiontech/sqle/tree/issue_488

**Comment by ColdWaterLW** [comment]
参考 #1630 提到的方案

**Comment by quexiuping** [comment]
验证版本：
UI Version: main 0d3caf7
Server Version: main-ee 32288994f7
验证结果：
![image](https://github.com/actiontech/sqle/assets/44565577/cb146a87-f023-4717-8194-19b0442604c6)
