### ISSUE TITLE
期望在工单列表界面增加sql语句的执行状态

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#49]
sqle-main_b6d4d6579df07d51145097eaf867
**Describe**
每次对一个工单审核通过上线之后都无法在工单列表中看到对应的sql语句执行是否成功，都要点击工单查看具体的sql执行情况
![image](https://user-images.githubusercontent.com/54339501/138838373-a5cd582c-655c-49ca-8d28-fbfc344d6e6f.png)

**Suggestion**
希望在工单列表中可以增加一个sql执行情况的字段，例如sql执行率。如果是一个sql语句执行完成对应的是100%，如果是0%就代表执行失败，再进入到工单内查看具体报错信息。如果是3个sql语句执行通过2个，只有一个sql执行失败，按百分比进行计算，展示执行率33.3%。

**Why**
对工单上线之后可以快速获悉sql执行情况

**Comment by sjjian** [comment]
## 方案
### 增加工单状态
页面展示工单状态包含一下几个状态值
* 处理中，
* 已驳回，
* 已关闭，
* 定时上线，
* 正在上线，
* 上线成功，
* 上线失败。
### 去掉 sql 审核状态
主要是去掉工单列表页面 sql 审核状态的筛选条件
### 工单状态流转图
![image](https://user-images.githubusercontent.com/18008452/145942014-35fcfde8-45e3-4fff-be3e-fc0981fd6315.png)
