### ISSUE TITLE
表名为关键字时审核任务无法正常展示且日志有报错

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#499]
**SQLe Version**
sqle main

**Describe the bug**
创建审核任务时，如果表名中存在以关键字（比如group）明明的表，审核任务可以正常创建，页面可以正常打开，但是SQL语句池是空的，查看日志时发现是SQL执行异常.
```bash
time="2022-05-05T10:24:52+08:00" level=error msg="query sql failed; host: 10.0.11.123, port: 3306, user: root, query: show create table group, error: Error 1064::You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group' at line 1\n" name=meta_iastdb thread_id=J90 type=audit_plan
```

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by Marcus9530** [comment]
UI Version: release-1.2204.x c04917c
Server Version: release-1.2204.x 5248287a20
复现成功：
复现步骤：
1.创建一个关键字为表名的sql表
2.然后创建审核任务，类型选择为库表元数据
3.审核任务创建成功之后，查看sql池为空，然后mysql本神，确实存在sql表
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/54339501/167236321-ae111d96-3090-484a-8d25-9bc57d7214e3.png">
<img width="311" alt="image" src="https://user-images.githubusercontent.com/54339501/167236341-eeb66ee0-92ed-4847-886b-1069fb84b246.png">

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/54339501/167236306-752db03a-4a26-4795-9bcf-0a52588e9e52.png">

**Comment by sjjian** [comment]
https://github.com/actiontech/sqle/issues/502

**Comment by Marcus9530** [comment]
验证通过
验证步骤：
1.创建一个关键字为表名的sql表
2.然后创建审核任务，类型选择为库表元数据
3.审核任务创建成功之后，可以看到所有的表结构，其实关键字开头的表也可以看到
<img width="567" alt="image" src="https://user-images.githubusercontent.com/54339501/170605776-d6455cb8-7ffa-465b-af08-45f2e26d6acc.png">
