### ISSUE TITLE
db2的plugin使用时，排错日志需要优化 

### ISSUE THREAD

**Issue by simplelogic666** [actiontech/sqle#500]
**Describe**

按照文档增加了db2 plugin
https://actiontech.github.io/sqle-docs-cn/3.modules/3.7_auditplugin/auditplugin_management.html

服务被systemd不断守护
![middle_img_v2_5201faf3-7833-4b07-8432-35a5e5a691ag](https://user-images.githubusercontent.com/46476574/167236859-6065371d-974e-44d2-84b4-e511707fb81e.jpg)

查看日志没有启动明显报错
![middle_img_v2_a6bfd172-b5ac-49fa-8743-e3866b42586g](https://user-images.githubusercontent.com/46476574/167236885-62f1b4e4-a0b9-4260-a54b-4b34201622f5.jpg)

通过手工重启获取到了报错信息是缺少依赖
![middle_img_v2_23a013ba-ea6b-49cf-8150-d40b642739bg](https://user-images.githubusercontent.com/46476574/167236902-902527fe-9cf5-4d8f-9365-10d85c50e06f.jpg)

**Suggestion**

建议对启动报错做排错改善，能在日志中获取到报错信息

**Why**
Why it can solve your problem.

**Comment by sjjian** [comment]
建议在系统层面将std和err日志通过管道符输出到指定文件。

**Comment by taolx0** [comment]
### 修复方案
将标准输出重定向至 std.log，错误输出重定向至 err.log

**Comment by Marcus9530** [comment]
UI Version: main 614a04c
Server Version: main-ee ca1d8e4a3a
验证步骤：
1.下载db2审核插件
2.然后赋予权限之后重启sqle
3.查看sqle目录下面没有生成pid文件，然后查看std日志，发现是有相关错误信息输出

![image](https://user-images.githubusercontent.com/54339501/176841659-e3916f1a-368d-415d-882f-5655f2f1b1fe.png)
