### ISSUE TITLE
alter table 审核错误

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#502]
**SQLe Version**

ee6ffe959ec7e5be1c8d76f69784889f62c36d04

**Describe the bug**

alter table 审核错误

**To Reproduce**

1 创建工单，要审核的sql为"ALTER TABLE tb1 add COLUMN d int;"（确定是个正确的sql）
2 审核报错，错误内容见图的右边
![20220509-154351](https://user-images.githubusercontent.com/36940986/167363590-1435c3b9-c43f-4c71-b723-4b258d07cf99.png)

**Expected behavior**

**Suggestion**

原因是func (c *Executor) ShowCreateTable这个函数的第一行在执行sql查询时给tableName加上了一对引号``，但是传进来的tableName已经带了``，所以导致sql的语法错误

**Comment by HuangWeiCen** [comment]
## 修复方案
这是由于工单审核时补过引号了, 此时在获取建表语句时再次补充引号导致的

修复了在表名有引号时再次添加引号的问题
修复了视图名为关键词时SQL会因为没加引号执行失败的问题

**Comment by Marcus9530** [comment]
该issue修复需求时出现的问题，无法复现直接验证

**Comment by Marcus9530** [comment]
UI Version: main 2ddcae6
Server Version: main-ee 1420a4532a
验证通过
验证步骤：
1.创建工单，要审核的sql为"ALTER TABLE tb1 add COLUMN d int;"
2.并无报错提示，直接进行审核
<img width="1604" alt="Snipaste_2022-05-26_17-26-54" src="https://user-images.githubusercontent.com/54339501/170459972-38d934b4-9373-4590-9a9e-e12cbaab7a47.png">
