### ISSUE TITLE
gh-ost dry run 失败的提示不明显，建议审核级别使用error

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#504]
**Describe**

开启gh-ost规则，默认的审核level是normal

![screenshot-20220509-173823](https://user-images.githubusercontent.com/36940986/167384987-12fa89b1-b7bc-45e8-b231-bc04429b9291.png)

创建工单，当审核满足条件并触发gh-ost规则检查时，dry-run gh-ost发生错误，但审核结果里显示的信息等级为normal（和规则等级一样），错误容易被忽略
![screenshot-20220509-174636](https://user-images.githubusercontent.com/36940986/167385467-643b0bc8-ad44-4b4c-8468-ba545b550a5c.png)

**Suggestion**

不管规则等级是什么，dry run gh-ost发生错误时，审核结果都显示为error level

**Why**

**Comment by Marcus9530** [comment]
UI Version: main 5bfc004
Server Version: main-ee 9ce7104ca3
验证通过
验证步骤：
1.添加数据源，然后开启审核规则模版，开启改表时超过空间之后使用gh-ost上线
2.创建工单，然后给表新增一个字段，点击审核，触发审核提示，该级别目前为错误级别
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/54339501/170616897-e6f546ea-78a4-4254-8da4-7b2f22244b2e.png">
