### ISSUE TITLE
添加数据源的时候，数据库的ip输入非数字时应当给予明显提示

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#51]
**SQLe Version**
sqle-main_3c242384eea4bbf4381ef3f0c893b21512126967

**Describe the bug**
添加数据源的时候，数据库的ip输入非数字时应当给予提示
**To Reproduce**
1.数据源管理界面，点击添加数据源
2.然后在数据库的ip地址输入框内，输入非数字的参数，然后前端未给到明显提示
![image](https://user-images.githubusercontent.com/54339501/139211964-a4d85381-25d1-44ac-9a11-550d1b54fc09.png)
![image](https://user-images.githubusercontent.com/54339501/139212012-8f3dc4e7-87ba-4661-8bd0-a6f28e601b99.png)

**Expected behavior**
应该给予前端提示例如爆红提示+提示信息只能允许输入数字之类的，另外应当限制输入非数字的参数

**Comment by sjjian** [comment]
### 方案：
该字段改为支持ip和域名
