### ISSUE TITLE
工单描述过长导致表格超出屏幕显示

### ISSUE THREAD

**Issue by liuruibin** [actiontech/sqle#516]
**Describe**

工单列表页-描述列过长，导致其他列被挤出屏幕
![image](https://user-images.githubusercontent.com/18008452/168009685-fc7c08d6-7d34-4d9a-bc5e-23cda9d82c64.png)
**Suggestion**

希望描述列宽可以自适应，超出长度可以换行或显示tooltip鼠标hover可以展示完整描述
**Why**

**Comment by Marcus9530** [comment]
UI Version: main 5bfc004
Server Version: main-ee 9ce7104ca3
验证步骤：
1.创建一个工单输入50个字符
2.然后在工单列表可以看到描述已经过长隐藏显示，点击描述会出现所有内容显示

<img width="1901" alt="image" src="https://user-images.githubusercontent.com/54339501/170608631-cb2dbc34-c418-457b-813d-115ba8ec2169.png">
