### ISSUE TITLE
工单进度支持显示数据源

### ISSUE THREAD

**Issue by liuruibin** [actiontech/sqle#517]
**Describe**

点击工单后进入详情页，这里没有展示数据源。
**Suggestion**

工单进度增加数据源展示，便于管理员操作
**Why**

**Comment by sjjian** [comment]
![image](https://user-images.githubusercontent.com/18008452/168525196-042e266d-a3de-45bc-b5f7-946b02a667be.png)
建议在工单详情页面新增：
1. 数据源信息
2. 数据库信息

以上信息在现有访问的接口内已有

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main efc0379
Server Version: main-ee 55b437567e
验证步骤：
1.创建一个工单
2.点击查看该工单，可以看到工单内新增数据源和数据库信息
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/54339501/169942260-91588aa2-eb8e-4f76-860b-e0825715b644.png">
