### ISSUE TITLE
审核任务 Oracle Top SQL 指定数据库后获取失败，且有明显报错日志

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#524]
**SQLe Version**
sqle v1.2204.0
**Describe the bug**
审核任务 Oracle Top SQL 指定数据库后获取失败，打开审核任务详情，页面为空，且有明显报错日志。
![image](https://user-images.githubusercontent.com/18008452/168199791-3a71d13a-cbac-4c06-8e6c-6147ae1dccbe.png)

![origin_img_v2_5618f7c0-a0a7-40cc-bf38-0015aa5a74bg](https://user-images.githubusercontent.com/18008452/168199721-82b9b6d3-f56f-41d5-b6b2-14321bdb5fe9.png)

**To Reproduce**
1. 在 SQLE 添加Oracle 数据库审核插件；
2. 录入某个Oracle数据源；
3. 对该数据源添加一个TopSQL的审核任务，并指定数据库
4. 打开审核任务详情无内容，且SQLE日志有明显连接Oracle的报错

**Expected behavior**
正常展示Top SQL

**Suggestion**

**Comment by sjjian** [comment]
## 原因
SQLE连接Oracle时将指定的数据库（instance database）当做了service name。

**Comment by Marcus9530** [comment]
UI Version: main 5bfc004
Server Version: main-ee 9ce7104ca3
复现步骤：
1.添加一个oracle数据源
2.然后创建topsql审核任务
3.审核任务页面空白，然后查看日志发现有连接失败的信息
<img width="1861" alt="image" src="https://user-images.githubusercontent.com/54339501/170621552-cc815868-959b-42a1-b51c-7711af3338c1.png">
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/54339501/170621577-3e196fb3-222a-481d-9c7f-103df136e5da.png">

**Comment by Marcus9530** [comment]
UI Version: main 5bfc004
Server Version: main-ee 9ce7104ca3
验证通过
验证步骤：
1.添加一个oracle数据源
2.然后创建topsql审核任务
3.审核任务页面正常抓取sql语句,日志无连接失败报错信息
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/54339501/170622002-cf2030bd-62d7-4be1-ad1c-fb739a4fc630.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/54339501/170622108-6b828638-7a56-4e99-aab1-f73ab090549b.png">
