### ISSUE TITLE
SQL查询增加审核校验机制，通过审核的才能执行查询

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#541]
## 需求
1. SQL查询增加审核校验机制，通过审核的才能执行查询；
2. 审核不通过的请求暂时通过页面报错；
3. 通过数据源配置项配置SQL查询是否进行审核，参数包括：“SQL查询是否需要审核”，“运行查询的最高审核等级”

**Comment by ColdWaterLW** [comment]
### 更新接口
| URI | 接口名 | 请求方式 | 更新简述 |
| --- | --- | --- | --- |
| /v1/instances | 获取实例信息列表 | get | 新增两个返回值：sql查询前是否审核，sql查询最高审核等级 |
| /v1/instances | 添加实例 | post | 增加两个请求参数：sql查询前是否审核，sql查询最高审核等级 |
| /v1/instances/{instance_name}/ | 获取实例信息 | get | 新增两个返回值：sql查询前是否审核，sql查询最高审核等级 |
| /v1/instances/{instance_name}/ | 更新实例 | patch | 增加两个请求参数：sql查询前是否审核，sql查询最高审核等级 |
