### ISSUE TITLE
当工单描述内容很多的时候，创建工单失败

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#545]
**SQLe Version**
UI Version: main efc0379
Server Version: main-ee 55b437567e

1.创建一个工单
2.然后工单描述内容输入超过200个字符
3.输入审核sql语句，点击审核
4.审核之后，点击创建工单，创建失败提示1046
![origin_img_v2_496e14fe-5297-40cd-a4d2-72beeccbf83g](https://user-images.githubusercontent.com/54339501/169943340-d27455a2-16bb-46cc-aed1-1c9eda2db518.jpg)

**Comment by sjjian** [comment]
建议前端加个限制，不允许提交太长的描述，
![image](https://user-images.githubusercontent.com/18008452/169943804-ba4ed41f-7642-4a35-a4de-2b33a6078b84.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 42d4595
Server Version: main-ee 20b4eab6c8
验证步骤
创建一个工单，现在工单描述已经限制在50个字符之内，无法超出
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/54339501/170193729-eee39a5d-e1df-4912-87eb-0a4a85d28aa3.png">
