### ISSUE TITLE
数据源页面删除数据源后建议自动刷新页面

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#548]
**Describe**

现状：删除完看到删除数据源还在，需要手动刷新才消失
**Suggestion**

点完删除后自动刷新一下页面
**Why**

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 303d979
Server Version: main-ee 4dc49cb04e
验证步骤：
1.在数据源界面选择一个数据源，点击删除
2.删除成功之后，界面自动刷新，删除的数据源已经不再展示


<img width="1720" alt="image" src="https://user-images.githubusercontent.com/54339501/220574496-bc87956e-d361-45d3-a094-2fa9c8117997.png">
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/54339501/220574636-80763d76-7d6b-4e32-9af9-2f76aac75803.png">
