### ISSUE TITLE
support MySQL index optimize

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#55]
sub-task tracking:
- [x] #118 
- [x] #124 
- [x] #142

**Comment by sjjian** [comment]
需要考虑ce/ee功能区分

**Comment by drivebyer** [comment]
### 功能
#### 交互
索引建议集成到审核结果里，当用户输入 select 语句时，给出索引建议（alter table add index...）。
#### ce/ee 功能区分
1. ce 只支持 BTree 索引建议
2. ee 支持 Hash、FullText、Spactial 索引建议

### 实现
索引建议整个流程有两个输入：
1. 存在于 select、group by、order by、join 条件中的各个列
2. 这些列在数据源中的可选择性

有了这两个输入，再依据[Relational Database Index Design and the Optimizers](https://book.douban.com/subject/2410000//)中「THREE-STAR INDEX—THE IDEAL INDEX FOR A SELECT」一节，尽量给到三星索引建议。例如，对于查询语句`select c1, c2 from t1 where c1 = 1 and c2 = 1 order by c1`(假设可选择性 c2 > c1)。这时，三星索引应该是 `create index idx_t1_c2_c1 on t1(c2, c1)`。

**Comment by drivebyer** [comment]
### 审核规则支持配置多参数
#### 背景
当前审核规则只支持配置一个参数，当遇到复杂规则时，用户的可配置性较低。
#### 目标
1. 一个规则支持多项配置
2. 单个配置类型多样化，可以在页面上友好的展示配置值的类型

**Comment by drivebyer** [comment]
sub-task tracking:
- [ ] #118

**Comment by drivebyer** [comment]
方案：
1. 等值查询时：使用 three-star index 算法（参考《Relational database index design and the optimizers》第四章）作为多数据库类型的索引建议通用方案（three-star index 算法只对单表查询给出索引建议）
2. 多表关联查询时：结合 explain 找到被驱动表，对被驱动表使用 three-star index 算法
3.
