### ISSUE TITLE
tips接口在提供sql查询可用实例时可能会提供无法执行查询的实例

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#555]
当用户拥有某一类型的实例SQL查询权限, 但该实例类型的插件未实现SQL查询功能时, tips接口依然会将此实例提供给用户, 但此实例是无法正常工作的

**Comment by Marcus9530** [comment]
UI Version: main efc0379
Server Version: main-ee 1ef9184a6f
复现步骤：
1.添加一个oracle数据源
2.然后查看sql查询界面，发现数据源下可以看到oracle

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/54339501/170456713-74b9c48f-9971-4d9f-a84f-f182bfc55f5f.png">
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/54339501/170456866-099a044e-99fc-473f-a8b6-7e10c8011910.png">

**Comment by Marcus9530** [comment]
UI Version: main 2ddcae6
Server Version: main-ee 1420a4532a
验证步骤：
1.添加一个oracle数据源
2.然后查看sql查询界面，发现数据源下已经看不到oracle


<img width="1102" alt="image" src="https://user-images.githubusercontent.com/54339501/170456942-a5c3638d-55ac-4587-a59e-56998f2e822c.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/54339501/170457042-3b6c7d45-854b-4c08-a0d4-364cd8737c47.png">
