### ISSUE TITLE
Support DB Plugin

### ISSUE THREAD

**Issue by re-f** [actiontech/sqle#56]
# 功能描述
不同的数据库的SQL 审核流程是相同的，但是规则上会有不一样，因此对于不同的数据库支持可通过 Plugin 的形式实现，以实现以下目标
- 不同的数据库规则相关的功能单独维护
- DB 种类增删能通过非编译时集成

**Comment by sjjian** [comment]
support PG: https://github.com/actiontech/sqle-pg-plugin， docs: https://actiontech.github.io/sqle-docs-cn/3.modules/3.7_auditplugin/overview.html

**Comment by sjjian** [comment]
TODO：数据库插件提供方便接入的三方库 @sjjian

**Comment by re-f** [comment]
当前Plugin方案问题：
1. 从业务角度来说，rule和[ rule 的实现]是1 对 1或者1对多，但是插件中的实现没有此对应关系
2. 命名带有歧义，目前插件需要自定义的部分包括2个部分 【rule的描述/页面展示】和【rule的实现】但是，【rule的描述/页面展示】命名为了model.Rule，而【rule的实现】则隐藏在Audit中
3.  从实现上来说，不够便利和直观。理想情况下，自定义规则需要做的事应该是在同一处书写【rule的描述】+【rule的实现】，而目前添加一条规则需要
       1.  在register中填写【rule的描述】
       2. 在Audit中增加判断条件，在遇到这条规则的处理方式
       3. 在某个地方，完成【rule的实现】

**Comment by drivebyer** [comment]
## 优化方案
### 概述
提供 Driver 层的封装库 adaptor。封装库提供默认 Parser 与默认 DB 操作。在一些关键步骤上，支持用户使用自定义配置覆盖默认配置。例如：
1. 连接数据库的 dsn 配置
2. Driver.Schemas 中对外展示的数据库列表

### 使用步骤
1. import ("adaptor"; _ "database driver")
2. 插件定义规则
3. 启动插件 `func Serve(l hclog.Logger, name string, rules []*Rule, opts ...Option)`

使用优化后的方案，插件实现者仅需提供插件名与规则列表即可完成一个默认插件的全部开发。

**Comment by drivebyer** [comment]
### Driver 层移除 model 层依赖
原因是，Driver 层现在主要依赖了 model.Rule，mode.Instance。这两个结构体中很多字段是 Driver 层不需要的。

### 方案
现有的 Rule 结构体定义：
```
type Rule struct {
	Name      string `json:"name" gorm:"primary_key; not null"`
	DBType    string `json:"db_type" gorm:"primary_key; not null; default:\"mysql\""`
	Desc      string `json:"desc"`
	Value     string `json:"value"`
	Level     string `json:"level" example:"error"` // notice, warn, error
	Typ       string `json:"type" gorm:"column:type; not null"`
	IsDefault bool   `json:"is_default" gorm:"default:false; not null"`
}
```
1. DBType 字段仅在 SQLE 的视角与 Name 做数据库联合主键，对于插件来说属于冗余字段，不应该暴露给插件开发者
2. Typ 字段其实是规则的分类，更名为 Category 较好
3. IsDefault 字段主要用来创建默认规则模板。准备将该字段移除，默认一个插件下注册的所有规则创建一个默认规则模板。

综上，在 Driver 层新增结构体：
```
type Rule struct {
	Name string
	Desc string
	Category string
	Level RuleLevel
	Value string
}
```

model.Instance 则用下面的结构体替代：
```
type DSN struct {
	Host     string
	Port     string
	User     string
	Password string

	DatabaseName string
}
```
该结构体只定义了一些连接数据库时必要的字段。

**Comment by sjjian** [comment]
需求：
1. 使用新的优化方案提供 Oracle 实现
2. 更新开发文档
