### ISSUE TITLE
企业qa版本使用license功能点击收集，报错信息需要优化

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#560]
**SQLe Version**
UI Version: main 2ddcae6
Server Version: main-ee 1420a4532a

使用企业版本的qa时，如果想使用license，点击收集信息会提示sqle-qa no license required，建议对报错信息优化，否则让人迷惑
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/54339501/170472928-b2cb6a02-fa97-4f3f-9a82-d9daf8aee637.png">

**Comment by sjjian** [comment]
## 建议：
1. 后端：对于企业版 qa版本，接口不再报错，返回固定内容；
2. 前端：许可证的配置信息移动到**平台管理**->**许可证** 页面，该项配置仅企业版展示，包括内容和左边菜单。

**Comment by Marcus9530** [comment]
UI Version: main c981fec
Server Version: main-ee 8d0d16eb08
验证通过
验证步骤：
1.使用qa版本进入到系统设置中没有明显报错信息，并且license限制显示无限制
![image](https://user-images.githubusercontent.com/54339501/180907728-5caeeeb8-3f25-4f9a-81bd-1928797471cb.png)
