### ISSUE TITLE
查询历史记录没有过滤数据源

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#561]
**SQLe Version**

sqle-ee 9ce7104ca334e588baf18e560085ea2bf43f3d7e
**Describe the bug**

查看sql查询的历史记录时，是从所有历史记录中查找，没有根据数据源过滤

原始需求： #509

**Comment by Marcus9530** [comment]
UI Version: main efc0379
Server Version: main-ee 1ef9184a6f
复现步骤：
1.选择一个数据源进行sql查询
2.选择另一个数据源进行sql查询
3.点击历史记录可以看到所有sql查询语句

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/54339501/170673935-c7985b37-bf84-44c4-8c68-a6e35af53e8e.png">
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/54339501/170673992-0a015188-9e9e-411d-b900-2268e1dc2117.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/54339501/170674012-a1e2c457-e3fe-498e-8e23-edf0bfb27912.png">

**Comment by Marcus9530** [comment]
UI Version: main b4c6fc1
Server Version: main-ee ac7e75f6df
验证通过
验证步骤：

1.选择一个数据源进行sql查询
2.选择另一个数据源进行sql查询
3.点击历史记录可以筛选数据源看到该数据源上进行过的sql查询语句
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/54339501/170674434-a7be06e1-ff1e-4018-94d8-8542189f0168.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/54339501/170674466-067b6040-2826-47c4-bd50-4603c176e6c3.png">
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/54339501/170674489-17b67e47-7007-48b7-b3f0-1f172c1e26c5.png">
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/54339501/170674530-25803317-4f0c-450e-be41-7448ca8a3b0f.png">
