### ISSUE TITLE
SQLE scanner 解析带有空otherwise标签的 mybatis XML时异常崩溃

### ISSUE THREAD

**Issue by staysun** [actiontech/sqle#563]
**SQLe Version**
1.2203

**Describe the bug**

**To Reproduce**

**Suggestion**

![D01C17CF4C27D07ED93EB58B1B49EC23](https://user-images.githubusercontent.com/17513989/171075729-4bba70b8-2d98-440a-a9be-5c23ab8cab86.jpg)
![FF2CF1093495E2223E411AB446477FFA](https://user-images.githubusercontent.com/17513989/171075742-6c10441b-ef5d-470c-a120-8bc038fbc955.jpg)

**Comment by sjjian** [comment]
## 原因
mybatis 解析库空指针报错了，在解析<otherwise>标签时未处理空标签的情况

**Comment by Marcus9530** [comment]
UI Version: release-1.2203.x bfd9fc0
Server Version: release-1.2203.x-ee aaa0497deb
复现步骤：
1.使用上述内容创建mybatis文件
2.创建审核任务
3.配置jenkins然后触发打包编译
4.查看控制台输出信息，发现出现panic信息


![image](https://user-images.githubusercontent.com/54339501/176846976-4d7fa7a4-f38b-4809-b0d8-1f63318e6c91.png)

**Comment by Marcus9530** [comment]
UI Version: main 614a04c
Server Version: main-ee ca1d8e4a3a
验证步骤
1.使用上述内容创建mybatis文件
2.创建审核任务
3.配置jenkins然后触发打包编译
4.查看控制台输出信息，没有出现panic信息

![image](https://user-images.githubusercontent.com/54339501/176847439-e1d1bf01-4b86-4f07-ab98-2e1745aa6481.png)
