### ISSUE TITLE
通过open api往审核任务中添加sql时，部分数据报错

### ISSUE THREAD

**Issue by icemanX987** [actiontech/sqle#597]
**SQLe Version**
UI Version: release-1.2205.x b4c6fc1
Server Version: release-1.2205.x 4438927c79

**Describe the bug**
调用/v1/audit_plans/{audit_plan_name}/sqls/partial，往审计任务中添加数据时，audit_plan_sqls_v2 表的info字段存储的json时，部分数据的counter字段存储不正确。如下图
![image](https://user-images.githubusercontent.com/106566863/173557353-ea9a4ba0-60bd-4585-beff-1e2b37cb9642.png)
导致前端解析时报错
![image](https://user-images.githubusercontent.com/106566863/173557458-87999fd2-0985-4b9a-a504-287c0ebbd843.png)

发送的数据如下
![image](https://user-images.githubusercontent.com/106566863/173557627-faf2f6f0-5b6b-4e23-aaf1-7e2f9813f1d6.png)

**To Reproduce**

**Suggestion**

**Comment by taolx0** [comment]
基于你的发送数据，我尝试复现这个错误，发现不能复现。所以，你能提供更多的复现信息吗？

**Comment by taolx0** [comment]
你的数据库版本是 mysql8.0 吗？

**Comment by icemanX987** [comment]
docker 跑的环境，mysql:8.0.28

**Comment by taolx0** [comment]
这个 issue 是 mysql 版本差异导致的，mysql8.0 累加时会引发这个问题，使用 mysql5.7 不会出现这个问题。

这段代码在 mysql8.0 上执行会出现小数点的问题：https://github.com/actiontech/sqle/blob/513b5d6fce8636ba36e3eb9ed6e4c197740fee1c/sqle/model/audit_plan.go#L129

建议参照文档部署。文档链接：https://actiontech.github.io/sqle-docs-cn/2.deploy/2.1_source_deploy.html

**Comment by sjjian** [comment]
@taolx0 看看有啥办法从产品的角度避免吗

**Comment by taolx0** [comment]
> @taolx0 看看有啥办法从产品的角度避免吗

ok

**Comment by taolx0** [comment]
### 背景
这段代码```JSON_EXTRACT(values(info), '$.counter'), 0)+COALESCE(JSON_EXTRACT(info, '$.counter')```会计算counter字段的累加值，mysql8.0将累加值转换为json时会出现小数点，而 mysql5.7 不会出现小数点的情况。https://github.com/actiontech/sqle/blob/513b5d6fce8636ba36e3eb9ed6e4c197740fee1c/sqle/model/audit_plan.go#L129

### 修复方案
主动将累加值先转换为整型，避免格式转换的小数点问题。

**Comment by Marcus9530** [comment]
UI Version: release-1.2205.x b4c6fc1
Server Version: release-1.2205.x-ee ac7e75f6df
复现步骤：
1.创建自定义审核任务
2.swagger页面调用接口请求两次
3.回到界面查看，出现报错信息
![image](https://user-images.githubusercontent.com/54339501/176864745-88a2762c-d729-481d-b7c3-b5c154fe280a.png)

**Comment by Marcus9530** [comment]
UI Version: main 614a04c
Server Version: main-ee c1a9993765
验证步骤：
1.创建自定义审核任务
2.swagger页面调用接口请求两次
3.回到界面查看，可以正常查看审核任务内sql
![image](https://user-images.githubusercontent.com/54339501/176865388-5f758d0a-76dd-4ad4-82b6-fadcd916b9ba.png)
![image](https://user-images.githubusercontent.com/54339501/176865426-ed7ece58-a654-473f-8c6d-5b0068cc2fdd.png)
