### ISSUE TITLE
使用 Mybatis Scanner 扫描的 xml 为空文件时，Scanner panic

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#61]
**SQLe Version**
v1.2110.0.pre1

**Describe the bug**
使用 Mybatis Scanner 扫描的 xml 为空文件时，Scanner panic：
![image](https://user-images.githubusercontent.com/18008452/140270443-0a60d298-5f46-4c7a-89d7-afdba6d7d4f5.png)

**To Reproduce**
1. 创建一个空的xml文件，例如：sql.xml，内不含任何内容，放入某个文件夹下；
2. 创建审核计划，并通过scanner 指定该文件夹上传；
3. 执行报错

**Expected behavior**
期望为空时不上传

**Comment by sjjian** [comment]
## 原因：
Mybatis XML解析库未处理匹配不到Mybatis 内容的情况，未对解析的内容判空处理导致后续引用空指针

**Comment by Marcus9530** [comment]
"release-1.2111.x 5d24144eb56b6202d030ac935897053b793f1a23"
验证通过
验证步骤：
1.gitlab上创建一个空文件
![image](https://user-images.githubusercontent.com/54339501/143530368-2a9daa58-913a-4d45-933a-8bdac11590f5.png)
2.sqle上创建审核计划然后，配置jenkins和gitlab，触发gitlab变更，然后查看jenkins输出
![image](https://user-images.githubusercontent.com/54339501/143530442-1a43928e-b9e2-4700-b7eb-8b698b179c76.png)
3.jeknins输出台信息没有出现panic信息，查看sqled日志也没有panic信息
![image](https://user-images.githubusercontent.com/54339501/143530517-5e50c62e-ce97-46b0-a4eb-965cb23ca4b8.png)
![image](https://user-images.githubusercontent.com/54339501/143530545-83ee2845-d077-4c6e-9e04-f7da1728c10a.png)

**Comment by Marcus9530** [comment]
复现版本：
sqle-1.2109.0_6a6de329f50bba5d61a880e1
复现步骤；
1.gitlab上创建一个空文件
2.sqle上创建审核计划然后，配置jenkins和gitlab，触发gitlab变更，然后查看jenkins输出，看到启动scanner失败且出现panic信息

![image](https://user-images.githubusercontent.com/54339501/143537723-33559b9a-6edd-472c-95e3-65e1bb160997.png)

![image](https://user-images.githubusercontent.com/54339501/143537700-dea335db-5291-491a-961f-ff6a20a9cf78.png)
