### ISSUE TITLE
建议数据源界面增加数据库类型字段以及筛选条件方便进行分类查看

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#625]
**Suggestion**
建议数据源界面增加数据库类型字段以及筛选条件方便进行分类查看

**Why**
在添加数据源的时候有数据库类型进行选择
![image](https://user-images.githubusercontent.com/54339501/176131660-5fe7b595-6469-461f-aa14-997c060c169b.png)
但是在数据源界面的时候发现没有数据库类型字段，想要判断数据源是哪种类型需要点进去查看详情之后才可以知道
![image](https://user-images.githubusercontent.com/54339501/176131928-cce240e5-6d3b-475d-ba1d-6c7a5d7c11d4.png)
![image](https://user-images.githubusercontent.com/54339501/176131977-09bd6a77-ed49-4977-acaf-187839ade7f1.png)
建议把数据库类型放到数据源界面展示字段进行展示，以及新增筛选条件以便用户可以快速查看

**Comment by sjjian** [comment]
### 建议
数据库类型为后续版本迭代中加入的功能，需要确认是否还有其他列表需要补充该字段

**Comment by ColdWaterLW** [comment]
**方案**

1. 数据源页面新增数据库类型展示。相关接口：/v1/instances [get]
    返回字段原本已经有了db_type，只是把值填充上去
2. 工单详情页面新增数据库类型展示。相关接口：/v1/tasks/audits/{task_id}/ [get]
    新增返回字段instance_db_type
3. 角色管理页面新增数据库类型展示。相关接口：/v3/roles [get]
    在v2的基础上修改返回字段instance_name_list为instance_list，结构体中包含name和db_type

**Comment by Marcus9530** [comment]
UI Version: main b19d80a
验证步骤；
1.添加不同类型的数据源
2.在数据源管理界面可以看到每个数据源的类型
![image](https://user-images.githubusercontent.com/54339501/181704572-50c005a1-b3a6-4c1b-a747-a8249a734f54.png)
