### ISSUE TITLE
建议菜单栏中的”模板管理“名称改为“规则管理”

### ISSUE THREAD

**Issue by zhouzhilu9** [actiontech/sqle#627]
**Suggestion**
建议将菜单栏中的“模板管理”改名为“规则管理”

**Why**
当前名称为“模板管理”，不太明确菜单内是哪些模板的管理，流程管理中也会有“审批流程模板”，容易产生混淆的概念，建议改为“规则管理”可以明确菜单的含义
![image](https://user-images.githubusercontent.com/99949903/176143248-9eebb9ca-698e-408f-8189-ed6129e9dcda.png)
![image](https://user-images.githubusercontent.com/99949903/176143358-961992c8-facf-457c-8f02-aa1c9e70331f.png)

**Comment by Sharkzeng** [comment]
支持
