### ISSUE TITLE
新增审核规则模版或者是克隆审核规则模版都很耗时

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#628]
**SQLe Version**
UI Version: main f26ec78
Server Version: main-ee eb709a2935

1.新建一个mysql（tidb）审核规则模版，开启所有的审核规则
2.等待创建成功，查看接口调用发现总时长为27s
3.然后去克隆tidb审核规则模版，等待克隆成功发现时长为25s
![origin_img_v2_df33b229-9a95-42b8-a5d2-aff4252cc36g](https://user-images.githubusercontent.com/54339501/176143688-1cb32921-a460-41ee-94bb-445142f720fb.jpg)
mysql慢日志信息
![origin_img_v2_fb95d4b7-1e4a-493c-9dc1-9fc674546ffg](https://user-images.githubusercontent.com/54339501/176144402-e8a0dac6-1068-4ff0-b9ca-4b9f3c64ef07.jpg)

**Comment by HuangWeiCen** [comment]
## 问题原因

### 慢日志
1. 慢日志目前没发现什么问题, 实际执行时间为4s确实有点长, 但SQL和对应表设计均未发现有什么不合理的地方, 使用的字段也均是索引
2. 后续无法再次复现, 当时出问题的环境查询时间也降下来了, 所以暂时没法确认这条SQL是否是因为机器原因导致执行慢

### 工单本身
1. 耗时过长是因为更新规则模板和规则的对应关系时使用了gorm的实体关联模式, 这个模式会自动更新关联表, 且数据是一条一条更新的, 这导致规则模板每条规则都会产生8条SQL(类似下图), 以前只有三十多条规则看不出速度慢, 现在规则增加到一百多条后如果克隆/创建一个启用所有规则的模板, 会下发八百多条SQL, 虽然每条速度都很快, 但总量太大导致实际时间很长
![image](https://user-images.githubusercontent.com/37464327/176412535-892388a2-3791-4f8c-8405-fdb4e646a708.png)

2. 为什么之前没发现: 因为原来sqle只有三十多条规则, 现在扩充到一百多条, 这导致下发的sql从原来的两百多条变成了八百多条, 可能以前需要等两秒, 感觉不明显, 现在要等8秒, 才发现这个问题

## 修复方案

### 慢日志
慢日志暂时未找到原因, 也无法复现, 经确认SQL语句没什么问题, 所以暂时不处理

### 新增/克隆模板很慢

#### 方案解释
因为在更新 "模板和规则关系表" 之前会先删掉此表中所有此模板的记录, 且更新关系的时候无需更新规则和模板的信息
所以将原来通过gorm更新关系表改为手动向关系表中插入, 此方式可以减少更新关联表的操作

#### 细节说明
因为sqle目前使用的是gorm版本不支持批量插入, 不支持预编译, 也没找到如何关掉关联模式的自动更新关联表, 遂使用事务的方式, 在一个事务中一条一条更新

#### 效率提升估算
原来一个规则执行8条SQL, 现在只执行一条, 执行时间经简单测试确实大幅提升

**Comment by Marcus9530** [comment]
UI Version: main 614a04c
Server Version: main-ee-csdc 26c6848faa
验证步骤：
1.新建一个审核规则模版，查看接口时间几十毫秒结束
2.克隆一个审核规则模版，查看接口时间也是几十毫秒结束



<img width="1494" alt="image" src="https://user-images.githubusercontent.com/54339501/176813172-0c3eea0c-9e8e-4eb8-b618-54dd00e7a181.png">
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/54339501/176813209-eabdf25f-ffa5-43ec-b89b-0e3b9046c6c6.png">

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/573
