### ISSUE TITLE
tidb审核规则group by中需要包含非聚合列审核提示信息展示不全

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#629]
**SQLe Version**
UI Version: main f26ec78
Server Version: main-ee eb709a2935

1.开启tidb所有审核规则
2.使用以下sql进行审核
`SELECT student_class,AVG(student_age) AS 平均年龄 FROM t_student GROUP BY (student_class) HAVING AVG(student_age)>20;`
3.可以看到前段展示信息不完整

![image](https://user-images.githubusercontent.com/54339501/176376585-b30cf5d7-12ff-4d66-8df7-8171bfa79f79.png)
![image](https://user-images.githubusercontent.com/54339501/176376684-aa72c0e2-fd4d-4720-8f91-613bcff01962.png)

**Comment by taolx0** [comment]
问题已在插件端修复

**Comment by Marcus9530** [comment]
UI Version: main 614a04c
Server Version: main-ee-csdc 26c6848faa
验证通过
验证步骤：
1.添加一个tidb数据源，开启对应的审核规则
2.使用上述sql进行审核
3.可以看到该审核规则已经正常展示了


<img width="1445" alt="image" src="https://user-images.githubusercontent.com/54339501/176813491-b11353c9-438f-4379-ad02-80d70bc77b07.png">

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/573
