### ISSUE TITLE
sql查询页面执行计划tab的关闭问题

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#634]
输入两个一样的sql，点执行计划
然后关掉“执行计划2“
![20220630-112149](https://user-images.githubusercontent.com/36940986/176586508-b2be3b61-426c-44eb-b40e-9a0adca7c41b.png)

结果是“执行计划1”关掉了，且剩下的这个“执行计划2”关不掉
![20220630-112202](https://user-images.githubusercontent.com/36940986/176586494-84811088-2c37-47eb-bd49-a305c6f29d51.png)

**期望：**“执行计划2”tab可以正常关闭

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/568
