### ISSUE TITLE
期望sql查询界面给到一个快速清空表结构按钮

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#637]
**Suggestion**
复现步骤：
1.选中sqle自带的数据源，然后查看sqle库下的表结构信息
2.然后清空选中的数据源，可以看到数据库表也随之清空，但是下面的表结构信息依旧存在
3.切换到其他的数据库下，点击表信息，之前sqle库下的表结构依旧存在，不太容易找到最新的表结构信息
![image](https://user-images.githubusercontent.com/54339501/176615667-ff84d6b9-791f-4b7c-9fac-2d71b24e5525.png)
![image](https://user-images.githubusercontent.com/54339501/176615726-8fb5e0f5-7c16-41c0-98ba-0e742fa40fd3.png)
![image](https://user-images.githubusercontent.com/54339501/176615773-3a9de606-2491-459c-bff3-302140207130.png)

**Why**
前段交互使用不太友好

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/568

**Comment by sjjian** [comment]
该优化涉及的功能已经使用 https://github.com/actiontech/sqle/issues/891 代替
