### ISSUE TITLE
使用慢日志功能的scanner之后，报错:Error 1406: Data too long for column 'sql_content'

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#646]
**SQLe Version**
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x-ee c1a9993765

1.创建慢日志功能的审核任务
2.开启数据源的慢日志功能，然后等待慢日志写入sql语句
3.开启scanner的慢日志功能，然后启动报错
![image](https://user-images.githubusercontent.com/54339501/177072191-a2ea8353-74e9-4642-b657-f5b6e47eb73c.png)
期望对此进行排查
以下是出现该问题时所使用的慢日志
[mysql-for-sqle-slow.log](https://github.com/actiontech/sqle/files/9036090/mysql-for-sqle-slow.log)

**Comment by taolx0** [comment]
###  为什么会出现 sql_content 太长的报错？
我注意到 [mysql-for-sqle-slow.log](https://github.com/actiontech/sqle/files/9036090/mysql-for-sqle-slow.log) 日志文件里，存在3～4处超长的insert语句，插入语句的 sql_content 字段值太长导致的。

**Comment by taolx0** [comment]
### 老版本升级

新部署的sqle audit_plan_sqls_v2表的sql_content字段都会改为mediumtext类型，旧的sqle升级到新sqle需要手动修改表字段。
修改方式:
1. 登入SQLE存储元数据的数据库
2. 执行如下两条SQL，以下SQL假设SQLE业务库为`sqle`
```sql
alter table sqle.audit_plan_sqls_v2
    change sql_content sql_content mediumtext not null COLLATE utf8mb4_unicode_ci;
```

**Comment by Marcus9530** [comment]
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
1.对应的数据源开启慢日志功能
2.然后在服务器启动scanner，当前并没有保错，且sqle平台收集到慢sql

![image](https://user-images.githubusercontent.com/54339501/181701667-8e3f372b-f47d-4db1-9984-116529d31b73.png)
![image](https://user-images.githubusercontent.com/54339501/181701731-c7c2dd84-799f-48cd-8de4-df9cb07004d6.png)
