### ISSUE TITLE
建议新增系统设置中license使用数量和剩余数量

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#647]
**Suggestion**
建议新增系统设置中license使用数量和剩余数量，以便用户可以直观的看到目前使用的资源情况
![image](https://user-images.githubusercontent.com/54339501/177087624-deeb49b6-5210-4582-95ea-3b962b628479.png)

**Comment by Marcus9530** [comment]
https://github.com/actiontech/sqle/issues/589

**Comment by sjjian** [comment]
已在统计报表页面展示
