### ISSUE TITLE
使用命令行参数启动sqle时会爆出空指针

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#65]
**SQLe Version**
main e1fafc0281d3f376c51ea793e40016ec83d5b97b

**Describe the bug**
在sqle启动时如果通过命令行参数启动且有些参数没填会爆出空指针异常
![image](https://user-images.githubusercontent.com/37464327/140887145-d73f6142-b15d-4445-bf94-94089b690bd3.png)
![image](https://user-images.githubusercontent.com/37464327/140887274-0a8c6cdb-abbe-4c23-ad72-804a85f7842a.png)

**To Reproduce**
在启动时不指定任何参数即可触发, 只指定mysql相关参数也可以触发

**Expected behavior**
1. 对于必填的参数期望能在没填的时候给个提示而非运行中抛出空指针
2. 对于参数的类型期望给到提示, 如mysql密码字段的默认值并非加密的, 但这个字段要求填一个加密后的字段

**Comment by drivebyer** [comment]
### 问题 1

#### 缺陷原因：
启动 SQLE 不指定 plugin-path 时，会使用默认值 ./plugins。在初始化插件时，传入 `InitPlugins` 的插件目录 ./plugins 不存在，`filepath.Walk` 时未先处理 err，而是直接使用了一个 nil 的文件句柄，从而导致 panic。

#### 修复方案：
1. `filepath.Walk` 时有 err 直接返回
2. 默认用户不使用插件，将参数 plugin-path 的默认值设置为空，与配置文件保持一致（配置文件中默认没有此参数）。

**Comment by Marcus9530** [comment]
"release-1.2111.x 3d69edc91e634ae9d93f1a0ff2301016f2ea4249
验证通过
在sqle的安装目录下，执行./bin/sqled启动sqled，然后并没有出现panic信息，然后kill进程之后再次执行命令 也每次出现panic信息

![image](https://user-images.githubusercontent.com/54339501/143389964-5f5c8f1b-20c3-4104-9fe3-ea56c52938ee.png)
![image](https://user-images.githubusercontent.com/54339501/143390143-31b70791-efa6-4315-a1c5-f3db75ca8d8c.png)
