### ISSUE TITLE
MySQL的lower_case_table_names配置为2时，部分审核进行库表检查不符合预期的问题

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#666]
# 问题说明
### 问题版本
之前的所有版本

### 问题简述
当mysql的lower_case_table_names设置为2时, 部分库表表将会找不到,但实际上库表是存在的

### 背景知识
lower_case_table_names的作用:
- 如果设置为 0，表名将按指定方式存储，并且在对比表名时区分大小写。
- 如果设置为 1，表名将以小写形式存储在磁盘上，在对比表名时不区分大小写。
- 如果设置为 2，则表名按给定格式存储，但以小写形式进行比较。

## 问题分析
ps: 请无视问题说明里的换行, 换行仅仅为了将一段话拆开,不是分成1234条

### 问题一
**场景**
lower_case_table_names=2, 存在大写schema 'A', 'A'中存在表 't' , 用户下发SQL为: 'select * from a.T;'

**代码关键词**
func (c *Executor) ShowSchemaTables(schema string) ([]string, error)

**问题说明**
SQLE在获取schema包含表的时候会下发一条SQL
select TABLE_NAME from information_schema.tables where table_schema="%s" and TABLE_TYPE="BASE TABLE"
这条SQL中的%s和用户下发SQL中的schema大小写保持一致
因为lower_case_table_names=2
所以information_schema.tables 中记录的table_schema为'A'
又因为用户SQL里的schema为'a', 这就导致SQLE下发sql时查询条件实际是 'where table_schema="a"' 
从而导致查不出这个库的表信息

### 问题二
**场景**
lower_case_table_names=2, 存在大写schema 'A', 'A'中存在表 't' , 用户下发SQL为: 'select * from a.T;'

**代码关键词**
func (c *Context) IsSchemaExist(schemaName string) (bool, error)
func (c *Context) getSchema(schemaName string) (*SchemaInfo, bool)

**问题说明**
IsSchemaExist()在检测到没有生成schema缓存的时候会下发一条SQL获取所有database信息("show databases")
因为lower_case_table_names=2, 所以"show databases"命令返回的schema名称都是区分大小写的
loadSchemas()在缓存大小写时会保持查寻结果的大小写不变, 即 "show databases" 查出的结果为 'A', 缓存的schema也叫 'A'
getSchema()在查找缓存前会先根据lower_case_table_names的值处理一下传入的schemaName, 具体表现为此值大于零就会将schemaName转换成全小写
因为生成缓存时存入的是大写, 查询时却用小写查的, 所以将会查不出来任何结果,进而导致调用getSchema()的函数都认为这个schema不存在

**其他**
目前暂未发现表名有相同问题, 表名缓存时已经做了统一小写的处理

## 问题影响
MySQL: MySQL在Windows或MacOS上部署时如果将lower_case_table_names设置为2将会出现此问题,Linux上的MySQL因为不支持lower_case_table_names=2, 所以暂时没有影响 [参考文档](https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html)
TiDB: TiDB永远会受到影响, 因为TiDB仅支持lower_case_table_names=2, 即使将这个值设置为别的TiDB依然会按照此值等于2的状态工作 [参考文档](https://docs.pingcap.com/zh/tidb/v5.3/mysql-compatibility)

# 解决方案
1. 当lower_case_table_names=2时, 统一将缓存中的所有schema全部换成小写, 查询时也全部换成小写(session.Context)
2. func (c *Executor) ShowSchemaTables(schema string) ([]string, error)改为func (c *Executor) ShowSchemaTables(schema string, ignoreSchemaCase bool) ([]string, error), 当ignoreSchemaCase =true时 ,函数将schemaName转换为小写,  并将table_schema转换为小写
         - 原函数签名: func (c *Executor) ShowSchemaTables(schema string) ([]string, error)
         - 新函数签名: func (c *Executor) ShowSchemaTables(schema string, ignoreSchemaCase bool) ([]string, error)
         - 原下发SQL: select TABLE_NAME from information_schema.tables where table_schema="%s" and TABLE_TYPE="BASE TABLE"
         - 新下发SQL: select TABLE_NAME from information_schema.tables where lower(table_schema) = "%s" and TABLE_TYPE="BASE TABLE"(仅当ignoreSchemaCase =true时调整SQL)
3. 代码可靠性由单测保证

## 备注
解决方案第二条不用like匹配是因为like在TiDB上不会忽略大小写, 加上这个SQL返回的条目数不会太多, 遂使用lower统一成小写再比较

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x-ee c1a9993765
复现步骤：
1.在mac安装一个mysql
2.然后创建数据库名为“TEST_DB”
3.然后在该库下面创建表名为“test_table”
4.创建工单，界面上选中数据库为“TEST_DB”，然后进行查询
`SELECT * from test_table;`

5.提示预检查失败
![image](https://user-images.githubusercontent.com/54339501/181457357-45399755-5635-4976-83c9-12ffb4164eae.png)
![image](https://user-images.githubusercontent.com/54339501/181463483-7816c071-ed6c-43cb-a428-d447ecd43d05.png)
![image](https://user-images.githubusercontent.com/54339501/181463542-b7a7a8d3-ffa2-4019-a099-3bb8efb1cf76.png)

**Comment by Marcus9530** [comment]
验证版本“
UI Version: main 3a38fd3
Server Version: main-ee 3ba4f96787
验证步骤：
1.在mac安装一个mysql
2.然后创建数据库名为“TEST_DB”
3.然后在该库下面创建表名为“test_table”
4.创建工单，界面上选中数据库为“TEST_DB”，然后进行查询
`SELECT * from test_table;`
`SELECT * from test_db.TEST_TABLE;`
5.直接进行审核成功，没有提示预检查失败
![image](https://user-images.githubusercontent.com/54339501/181467437-3f99616b-0af5-40cc-99e9-136047f09d20.png)

![image](https://user-images.githubusercontent.com/54339501/181467356-4360ef9d-25be-4c44-ad15-2fda3d39722c.png)
![image](https://user-images.githubusercontent.com/54339501/181467383-bea681c0-61f7-403a-8447-cdd5685bc19e.png)
