### ISSUE TITLE
SQLE查询不到系统库里的表信息

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#667]
# 问题描述

## 影响版本
之前所有版本

### 代码关键词
func (c *Executor) ShowSchemaTables(schema string) ([]string, error)

### 问题描述
这个方法会下发一条SQL: select TABLE_NAME from information_schema.tables where table_schema="%s" and TABLE_TYPE="BASE TABLE"
这条SQL会过滤掉所有TABLE_TYPE不等于"BASE TABLE" 的表, 包括系统表(系统表是SYSTEM VIEW)(查看系统表建表语句可知系统表是临时表,不是视图)
当希望查询系统库的信息时, 这条SQL将不会返回任何数据, 导致SQLE拿不到系统库里的表列表

### 修复方案
SQL调整为select TABLE_NAME from information_schema.tables where table_schema="%s" and TABLE_TYPE in ("BASE TABLE", "SYSTEM VIEW")

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x-ee c1a9993765
复现步骤：
使用系统库下面的表进行查询，然后点击审核提示不存在
`select * from information_schema.USER_PRIVILEGES;`
![image](https://user-images.githubusercontent.com/54339501/181448414-997dedca-95ea-451e-be02-ffbc899ac93e.png)
![image](https://user-images.githubusercontent.com/54339501/181448732-d588856f-13f6-4594-a658-2b4bab43923b.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main c981fec
Server Version: main-ee 3ba4f96787
验证步骤：
使用系统库下面的表进行查询，然后点击审核，目前没有提示不存在的报错
select * from information_schema.USER_PRIVILEGES;
![image](https://user-images.githubusercontent.com/54339501/181448842-c1e3d900-797a-4a25-bf00-7707383d542a.png)
