### ISSUE TITLE
SQLE 增加静态审核接口

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#674]
# 需求描述
增加一个静态审核接口, 该接口直接传入要审核的SQL, 返回审核结果, 调用此接口审核不会保留审核记录, 此接口使用默认审核模板中启用的静态审核规则进行审核

# 开发方案

## 接口定义
1. 新增 'audit' Tag, 用于标记直接审核类接口
2. 新增 /v1/audit/static_audit [post] 接口用于审核
3. 新增接口需要登录后才能使用
4. 新增审核接口支持批量审核, 用户只要传入一段SQL文本, 接口实现将自行解析成单独的SQL, 然后逐条审核
5. 入参 ↓↓↓
```
type StaticAuditReqV1 struct {
	// 实例类型可以是包括"/"在内的任何字符串, 不适合放到URI里面
	InstanceType string
	// 调用方不应该关心SQL是否被完美的拆分成独立的条目, 拆分SQL由SQLE实现
	SQLs string
}
```
6. 返回值 ↓↓↓
```

type AuditResDataV1 struct {
	InstanceType   string          `json:"instance_type"`
	AuditLevel     string          `json:"audit_level" enums:"normal,notice,warn,error,"`
	Score          int32           `json:"score"`
	PassRate       float64         `json:"pass_rate"`
	SQLResults     []AuditSQLResV1 `json:"sql_results"`
	ResultTotalNum int             `json:"result_total_num"`
}

type AuditSQLResV1 struct {
	Number      uint   `json:"number"`
	ExecSQL     string `json:"exec_sql"`
	AuditResult string `json:"audit_result"`
	AuditLevel  string `json:"audit_level"`
	RollbackSQL string `json:"rollback_sql,omitempty"`
}

```

## 内部实现
1. 当前SQLE 大部分driver的DSN为空时会启用静态审核, 遂在审核时传入一个空的DSN, 以实现静态审核
2. 将server.audit()暴露出去, 因为此函数允许使用传入的driver进行审核, 而静态审核需要手动传入空的DSN
3. 传入的SQL会在初步解析成单条SQL后包装成Task, 然后调用暴露出去的 server.audit()进行审核, server.audit()内部实现不会保存审核结果
4. 审核出现报错将会记录到日志中, 界面上只会显示 "审核失败, 请确认该类型的审核插件是否支持静态审核, 详情请查看日志"

**Comment by Marcus9530** [comment]
UI Version: main 92b44b8
Server Version: main-ee dcb6203c09
验证步骤：
1.在swagger界面调用接口，然后输入审核sql点击请求
2.查看返回结果，触发了相关审核提示

![image](https://user-images.githubusercontent.com/54339501/181726366-2b95c52b-6a04-4679-84f5-a420e5464096.png)
![image](https://user-images.githubusercontent.com/54339501/181726413-f48c2adf-af87-4f99-a554-50c64378b4dc.png)
