### ISSUE TITLE
SQLe的审核任务，老以为是工单的审核工作流，建议换个名字

### ISSUE THREAD

**Issue by maxbelial** [actiontech/sqle#682]
**需求**

1、使用SQLE过程中，发现审核任务是用于 自动扫描指定数据源上执行的SQL。容易跟工单本身的审批工作流混淆了。
2、审核任务，从界面上看不出 可以查看详情；希望能让用户一眼就能知道是可以打开查看详情。
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/20533617/179704962-75fb8705-d852-4c0b-8dca-36a785a17c13.png">

**建议**

1、审核任务 改成 智能扫描？
2、审核任务名称允许可以点击的样式；光标移到审核任务上 鼠标样式变为 点击样式。

**Comment by sjjian** [comment]
![image](https://user-images.githubusercontent.com/18008452/179720525-22491973-e50a-4823-a878-0689ade2fabf.png)
![image](https://user-images.githubusercontent.com/18008452/179728167-33a07ed5-29e8-4342-80c7-5f15afb71e5d.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
进入到智能扫描界面。当前名字和文案已做变更
![image](https://user-images.githubusercontent.com/54339501/181670035-695fbd4e-d164-404d-81fb-ada6add543f3.png)
![image](https://user-images.githubusercontent.com/54339501/181670060-4da0a13d-15a6-4cb7-96f3-b8a32b194caf.png)
![image](https://user-images.githubusercontent.com/54339501/181670110-a804f645-f5a2-4dbd-93ab-cd08b73185ae.png)
