### ISSUE TITLE
对于增量场景的智能扫描（原：审核任务）应该提供可增量审核的方式

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#687]
## 背景
对于慢日志，tidb 审计日志扫描类的审核，由于scanner使用的是增量扫描日志文件来实时提交sql到sqle，那么存在一个问题，即当某个存在问题的sql被修复后sqle内依然会对该sql进行审核，且目前无法避免掉。
## 方案
提供一个智能扫描任务的特有参数令sqle可以仅审核最近某段时间内的sql，并输出审核报告。
## 不足
当前的sql统计信息（sql语句池）内依然会存在该sql，后续可能通过其他方式处理。可能是页面提供手动关闭并说明原因。

**Comment by ColdWaterLW** [comment]
![image](https://user-images.githubusercontent.com/36940986/180734627-dd5974d5-f6a2-487b-b1ba-ac29e0115ec9.png)
![image](https://user-images.githubusercontent.com/36940986/180734706-acb8c4ce-28d5-45fb-a977-ca49df740f7c.png)
