### ISSUE TITLE
dashboard 工单概览的相关内容试用反馈

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#693]
**Describe**

### 列表的列宽处理优化
1、列表的列宽按照百分比固定。列表的【创建时间】和【工单状态】的列宽，按照内容计算出来并满足最大值的宽度即可。
2、列的内容展示更多文字内容，不要剩余很大空间，见场景四。
3、当页面小的一定程度，列表内容不需要换行，可以新增横向滚动条，让用户看到全部数据。

场景一：列表有数据或者没有数据时，列宽相同。
场景二：内容值不一样时，列宽不同。
场景三：创建时间和工单状态的列宽按照内容计算出来满足最大值即可。
场景四：列的内容期望展示更多内容，目前列表还剩余很大空间。
场景五：列表宽度小到一定程度时，没有横向混动条，导致看不到数据。

### 列表样式优化
期望列表能有完整的列表框，目前tab下方的列表内容看起来完整性不强。

#### 1、第一个列表新增标题：待处理的工单
tab修改为：需审核；需上线。
#### 2、第二个列表新增标题：我的工单情况
tab修改为：待审核；待上线；被驳回。
 注意：
列表标题与后面的每个状态在同一行上，可参考Jira的发版报告列表（样式设计上不需要表现出多种颜色）
举例：【待处理的工单】是父类，【需审核，需上线】是其子类。

### 按钮优化
1、创建工单按钮期望位于页面右上，右下角不好操作。（注意不要覆盖到页面文字内容。）
期望加号可以直接支持点击，不需要再点击【创建工单】。
2、【查看所有】按钮期望优化为【更多】。
3、列表中不同tab之前的切换，需要页面体现切换效果，目前页面完全静止，看不出来切换效果。

**Comment by sjjian** [comment]
ref：https://github.com/actiontech/sqle/issues/680

**Comment by Marcus9530** [comment]
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
目前前端界面效果已修改为优化后的效果
![image](https://user-images.githubusercontent.com/54339501/181712570-a30e5db5-7500-430a-a89e-883cbbadcccf.png)
![image](https://user-images.githubusercontent.com/54339501/181712621-5b7b7bfd-7fba-4f28-a79f-e7b0c35c7aa1.png)
![image](https://user-images.githubusercontent.com/54339501/181712735-82eb1e5a-ae67-4f05-9f75-678f68a86d90.png)
![image](https://user-images.githubusercontent.com/54339501/181712852-8049097f-0e8e-473b-8f41-9ac2aa27af3b.png)
![image](https://user-images.githubusercontent.com/54339501/181712872-55be0999-77ad-426c-95f9-f9ee918ef900.png)
![image](https://user-images.githubusercontent.com/54339501/181712979-ab3eaa5f-e753-4583-bf55-e0d54b261627.png)
切换效果
![image](https://user-images.githubusercontent.com/54339501/181713273-08e484af-fa9a-4385-808e-05c1da7180bc.png)

![image](https://user-images.githubusercontent.com/54339501/181713310-b8055c1c-9a55-4317-81ea-07ef14d0103f.png)
