### ISSUE TITLE
MySQL插件在界面上的展示由"mysql"调整为"MySQL"

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#694]
**Describe**
目前界面上MySQL插件的展示名为mysql，拼写与现有插件风格不符。改为”MySQL”，需要考虑面影响，和升级方案

**Comment by ColdWaterLW** [comment]
**影响面**
1. 审核规则相关的MySQL类型名称
2. 智能扫描相关的MySQL类型名称
3. 审核规则模板相关的MySQL类型名称
4. 工单相关的MySQL类型名称

**升级方案**
在sqled元数据所在的mysql实例执行如下语句，假设sqled使用的数据名为sqle
* 升级rules表
    * 执行语句:UPDATE sqle.rules SET db_type='MySQL' WHERE BINARY db_type='mysql';
* 升级audit_plans表
    * 执行语句:UPDATE sqle.audit_plans SET db_type='MySQL' WHERE BINARY db_type='mysql';
* 升级instances表
    * 执行语句:UPDATE sqle.instances SET db_type='MySQL' WHERE BINARY db_type='mysql';
* 升级rule_templates表
    * 执行语句:UPDATE sqle.rule_templates SET db_type='MySQL' WHERE BINARY db_type='mysql';
* 升级tasks表
    * 执行语句:UPDATE sqle.tasks SET db_type='MySQL' WHERE BINARY db_type='mysql';

**Comment by sjjian** [comment]
看起来还有个默认规则模版名称

**Comment by Marcus9530** [comment]
UI Version: main 92b44b8
Server Version: main-ee dcb6203c09


智能扫描相关的MySQL类型名称：
![image](https://user-images.githubusercontent.com/54339501/181713809-fd7fc24d-185b-4f32-8713-4c6291a452bd.png)
![image](https://user-images.githubusercontent.com/54339501/181713821-3d3089fe-1019-40eb-acf1-2e5a025c288a.png)
![image](https://user-images.githubusercontent.com/54339501/181713864-bb4a8163-3484-42ed-bd1e-ab31fa4c770a.png)
审核规则相关的MySQL类型名称：
![image](https://user-images.githubusercontent.com/54339501/181713995-8a9d2b23-408b-494a-a7cc-ecfd4482a362.png)
![image](https://user-images.githubusercontent.com/54339501/181714006-f8642640-052c-4bca-baae-fe27ada176a2.png)
![image](https://user-images.githubusercontent.com/54339501/181714048-c0cfbb1a-43d0-465a-bd0b-fd3e1ae3c8b2.png)

工单相关的MySQL类型名称

![image](https://user-images.githubusercontent.com/54339501/181714260-edb67c6a-ae0d-4d4e-87c0-d01529b4cdf9.png)
![image](https://user-images.githubusercontent.com/54339501/181714470-bdb3071e-67a0-475c-a86d-5247150924ea.png)

审核规则相关的MySQL类型名称
![image](https://user-images.githubusercontent.com/54339501/181716244-d050c3dc-a094-46aa-8982-dc9e8c578147.png)
![image](https://user-images.githubusercontent.com/54339501/181716263-73704af5-dbf6-4096-bb6b-1b51889a0fe1.png)
