### ISSUE TITLE
mysql的规则模板里数据库类型错误

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#695]
**复现步骤**

1 在规则模板里编辑mysql模板
![image](https://user-images.githubusercontent.com/36940986/180953308-f47dd6f5-228e-4996-9dfc-d0e5f314bdd8.png)

2 来到规则页面，点击编辑规则
![image](https://user-images.githubusercontent.com/36940986/180953494-466829c0-520b-48cc-be67-9a271ed1db4c.png)

3 数据库类型显示为“TiDB”
![image](https://user-images.githubusercontent.com/36940986/180953623-0d4a1f1b-429a-4f9a-bb59-b1e9b73360b5.png)

**原因**
查询结果出错，可能和表定义有关
![20220726-165231](https://user-images.githubusercontent.com/36940986/180965938-2d7fd88d-2466-40e5-b6e3-6f6a15428099.png)
![20220726-165239](https://user-images.githubusercontent.com/36940986/180965998-91c72463-887f-4298-9347-c75a04bc302e.png)

**影响面**
目前使用到这个函数的地方有：
1. 克隆规则模板，接口/v1/rule_templates/{rule_template_name}/clone [post]
2. 上文提到的编辑审核规则
3. 获取实例应用的规则列表，接口/v1/instances/{instance_name}/rules [get]
4. SQL审核（newDriverManagerWithAudit()用到了）

**Comment by Marcus9530** [comment]
复现版本：
UI Version: main c981fec
Server Version: main-ee 3ba4f96787
复现步骤；
1.找到mysql的审核规则模版
2.选择禁止使用没有where条件的sql语句或者使用where 1=1等变相没有条件的sql规则，然后点击编辑
3.发现该规则类型为tidb，实际应该为mysql
![image](https://user-images.githubusercontent.com/54339501/181153684-dae4a5c4-fde5-4469-9ae5-aa55a293a0c6.png)

![image](https://user-images.githubusercontent.com/54339501/181153656-b32941be-4d04-4f22-aa61-eaf4e1a4e974.png)

**Comment by HuangWeiCen** [comment]
# 问题原因
在之前的一次重构中(commit=d5f8a83f), RuleTemplateRule表的RuleDBType字段被当作无用字段删掉了(在当时看来确实没用), 从而导致RuleTemplateRule.Rule设置的外键"DBType"失效, 见下图
![image](https://user-images.githubusercontent.com/37464327/181445873-b7c02268-89a4-433a-99f2-99ac34331cc5.png)
原来应该下发的SQL
```
SELECT * FROM `rules`  WHERE (`name` IN ('ddl_check_column_without_comment','ddl_check_decimal_type_column') AND `db_type` IN ('Default_MySQL')) ORDER BY `rules`.`name` ASC;
```
变成了
```
SELECT * FROM `rules`  WHERE (`name` IN ('ddl_check_column_without_comment','ddl_check_decimal_type_column')) ORDER BY `rules`.`name` ASC;
```
因为db_type的限制没了, 从而导致查询出来的规则没有经过实例类型的过滤, 从而导致当规则名重复时查出哪个实例类型的规则不确定

## 问题影响面
rule_template_rule表只记录了规则名, 规则模板id, 规则等级和规则自定义参数, 没有记录规则对应实例类型, 所以元数据依然是正确的, 修复SQLE的查询语句即可

# 修复方案

## 选择的方案
经过查看代码, 可以发现所有获取规则模板详情的地方最终都会汇集到
```
func (s *Storage) GetRuleTemplateDetailByName(name string) (*RuleTemplate, bool, error) {
```
中, 所以直接调整此处代码, 拼入一个查询条件
```
`rules`.`db_type` IN (select `db_type` from `rule_templates` where `name` = '" + name + "')"
```
其中name变量是此方法接收的规则模板名, 拼入此条件后的新SQL将会变成
```
SELECT * FROM `rules`  WHERE (rules.db_type IN (select db_type from rule_templates where name = 'default_MySQL')) AND (`name` IN ('ddl_check_column_without_comment','ddl_check_decimal_type_column')) ORDER BY `rules`.`name` ASC  
```
可以看到, 新的SQL限制了db_type, 从而实现查询规则模板里的规则详情时不会误查到其他类型的同名规则上

## 舍弃的方案
还原之前的设计, 在rule_template_rule表中增加一列db_type, 用于记录规则的数据库类型

### 舍弃原因
rule_template_rule表当前存在的四个字段都是无法通过其他方式获取到的, 但db_type可以通过rule_template_id 获取到, 再存一份有些多余

**Comment by HuangWeiCen** [comment]
# 升级方案

在新版SQLE部署完成并启动后, 在SQLE元数据所在数据库中执行
```
update `sqle`.`rule_template_rule` set `db_type` = (select `db_type` from `sqle`.`rule_templates` where `rule_templates`.`id` = `rule_template_id`);
```

**Comment by HuangWeiCen** [comment]
测试注意事项:
1. 多尝试几个实例类型的规则模板
2. 需要进入数据库, 查看rule_template_rule这张表的db_type一列是否展示正常, db_type应该展示什么可以通过这一行的 rule_template_id 在rule_templates表里查到
3. 升级方案需要测试
4. 克隆规则模板, 新增规则模板, 修改已有规则模板需要测试
5. 需要关注一下/v1/instances/{instance_name}/rules 这个接口返回的规则数据库类型是否正常(不晓得这个接口前端在哪用的, 可以从swagger里测)

**Comment by Marcus9530** [comment]
UI Version: main 92b44b8
Server Version: main-ee 018349a02a
验证步骤：

1.查看不同类型的审核规则模版
mysql模版审核规则
![image](https://user-images.githubusercontent.com/54339501/181728822-e2c3cbf6-d954-4150-8c94-4830bdcba140.png)
![image](https://user-images.githubusercontent.com/54339501/181728896-c90da7fb-bac2-4ef5-86b5-0ec167d124eb.png)
tidb模版审核规则
![image](https://user-images.githubusercontent.com/54339501/181728987-d933511d-eef6-45f0-a77f-aeda91f8cd40.png)
![image](https://user-images.githubusercontent.com/54339501/181729018-da66ea81-c623-438a-aea2-21da67589cc4.png)
ob审核规则
![image](https://user-images.githubusercontent.com/54339501/181729071-c38618d3-bf80-4344-a91b-9b3e3bb11f7d.png)
2.登陆sqle自身使用的mysql，然后下发升级测试修改的sql语句
![image](https://user-images.githubusercontent.com/54339501/181729276-5f187b8a-351f-4fd9-bee5-f8f78938e49f.png)
3.查看rule_template_rule表中列展示
![image](https://user-images.githubusercontent.com/54339501/181729474-f0c1e227-e959-4614-92ea-b0002b202d60.png)
4.克隆mysql审核规则模版
![image](https://user-images.githubusercontent.com/54339501/181729579-d9ed90ad-7008-4875-826b-55d6c80a9ba1.png)
![image](https://user-images.githubusercontent.com/54339501/181729616-268420fe-3fbe-4cec-9531-4f84a495aff6.png)
![image](https://user-images.githubusercontent.com/54339501/181729638-9c50a332-34b2-4d29-b7d7-40908a8218dc.png)
新增审核规则模版
![image](https://user-images.githubusercontent.com/54339501/181729810-91b6973b-0158-4a8a-aabe-6f2eb01d2ae6.png)
![image](https://user-images.githubusercontent.com/54339501/181729839-05c0ae68-1d87-45e3-9fc4-6462e191560e.png)
![image](https://user-images.githubusercontent.com/54339501/181729884-5f83c591-5d5a-4117-8219-153c9ba285e8.png)
修改已有审核规则模版
![image](https://user-images.githubusercontent.com/54339501/181729931-d125038b-37df-481c-9184-e8959d175291.png)
![image](https://user-images.githubusercontent.com/54339501/181729969-605ec34a-75fd-448e-9837-ea2160593778.png)
5.调用接口查看数据源返回信息，类型也是mysql
![image](https://user-images.githubusercontent.com/54339501/181730450-44b7bb84-587d-4cd7-ae00-c885d42e8de9.png)
![image](https://user-images.githubusercontent.com/54339501/181730505-20abca6b-9117-4166-bfc2-7eda6811655a.png)

6.创建工单点击审核可以成功审核
![image](https://user-images.githubusercontent.com/54339501/181730612-2d2f879c-cb88-4a86-8389-1e883e282329.png)
