### ISSUE TITLE
审核任务库表审核带“-”的数据库时，后端报错，库表审核任务内无数据

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#696]
**SQLe Version**
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x 73518af8a0

time="2022-07-26T16:08:12+07:00" level=error msg="query sql failed; host: 192.168.0.227, port: 3306, user: root, query: show create table acquire-test.`agent`, error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-test.`agent`' at line 1\n" name=AESYGO_TEST_DB_AUDIT_META thread_id=UR6 type=audit_plan
![A3F45DC8E9A2134D7426542D7B97C6DB](https://user-images.githubusercontent.com/18008452/180974585-70a6ee73-6605-4256-b54e-45ff01a18bb9.jpg)

**Comment by sjjian** [comment]
@ColdWaterLW 该case需要加自动化测试，缺陷已经反复出现两次了

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x-ee c1a9993765
复现步骤：
1.在mysql上创建一个带-的数据库，然后在该库下创建表
`create database `sqle-test``
`CREATE TABLE `sqle-test` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Name` varchar(32) NOT NULL DEFAULT '',
  `AppId` varchar(32) NOT NULL DEFAULT '',
  `Format` varchar(32) NOT NULL DEFAULT 'properties',
  `IsPublic` bit(1) NOT NULL DEFAULT b'0',
  `Comment` varchar(64) NOT NULL DEFAULT '',
  `IsDeleted` bit(1) NOT NULL DEFAULT b'0',
  `DataChange_CreatedBy` varchar(32) NOT NULL DEFAULT '',
  `DataChange_CreatedTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DataChange_LastModifiedBy` varchar(32) DEFAULT '',
  `DataChange_LastTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `IX_AppId` (`AppId`),
  KEY `Name_AppId` (`Name`,`AppId`),
  KEY `DataChange_LastTime` (`DataChange_LastTime`)
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb4`
2.sqle审核任务中创建一个任务，选中该数据库
3.然后创建成功之后查看该任务，发现sql池并无任何表结构信息
4.查看sqle日志，发现日志中已经报错
![image](https://user-images.githubusercontent.com/54339501/181153091-7bc1e0dd-177b-4fc2-86bd-a2649ef675ba.png)
![image](https://user-images.githubusercontent.com/54339501/181153104-88910aa7-6a7d-4911-9975-c053b02da05e.png)
![image](https://user-images.githubusercontent.com/54339501/181153125-2cf44090-e61f-4a92-87c1-78f347dc6e98.png)

**Comment by ColdWaterLW** [comment]
**解决方案**
执行SQL时给schema加上引号

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
1.在mysql上创建一个带-的数据库，然后在该库下创建表
2.sqle审核任务中创建一个任务，选中该数据库
3.然后创建成功之后查看该任务，发现sql池出现刚刚创建表结构sql语句
![image](https://user-images.githubusercontent.com/54339501/181669732-da6fe9be-a4b8-4364-b312-757fdcd23898.png)
![image](https://user-images.githubusercontent.com/54339501/181669801-c2fe188e-370e-4f90-8576-810f625a4d3f.png)
![image](https://user-images.githubusercontent.com/54339501/181669835-7e549f24-87f7-4ad8-a298-0468432478ac.png)
