### ISSUE TITLE
同一个审核规则触发之后显示两次审核提示

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#699]
**SQLe Version**
UI Version: main c981fec
Server Version: main-ee 3ba4f96787

1.开启精确浮点数建议使用DECIMAL审核规则
2.创建工单进行审核
`CREATE TABLE test(f FLOAT(5,2) DEFAULT NULL,d DOUBLE(5,2) DEFAULT NULL,de DECIMAL(5,2) DEFAULT NULL);`
3.查看审核结果，出现两次相同的审核提示
![image](https://user-images.githubusercontent.com/54339501/181173325-2745309e-b95b-4ff2-8cfb-263911008d3a.png)

已确认mysql，tidb，ob都有该问题，期望对此进行修复

**Comment by HuangWeiCen** [comment]
## 问题原因
此规则在被触发后没有退出匹配, 所以第二次匹配到就又触发了一次, 从而出现两个审核结果

## 修复方案
"精确浮点数建议使用DECIMAL" 审核规则触发一次后退出匹配此规则

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
1.开启精确浮点数建议使用DECIMAL审核规则
2.创建工单进行审核分别在tidb、ob、mysql上进行审核
`CREATE TABLE test(f FLOAT(5,2) DEFAULT NULL,d DOUBLE(5,2) DEFAULT NULL,de DECIMAL(5,2) DEFAULT NULL);`
3.查看审核结果，只出现了一次审核提示


![image](https://user-images.githubusercontent.com/54339501/181699743-fe8b7dff-41f0-4f1e-82c2-76964c896410.png)
![image](https://user-images.githubusercontent.com/54339501/181699774-d676cc2e-0147-4f31-8aac-05e148e1f12e.png)
![image](https://user-images.githubusercontent.com/54339501/181699814-2b39282f-27cf-4c55-8822-3a598e9a4e36.png)
