### ISSUE TITLE
SQLED日志清空后无法继续写日志

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#700]
当SQLED 日志变很大的时候 大约4到达 700MB  人工ECHO "" > SQLED  后再执行其它操作并不会继续产生新的日志; 需要重启SQLED服务才行; 可否在不重启的情况下继续生成新日志呢?

**Comment by sjjian** [comment]
你指的执行是执行下面的明明对吧
```bash
echo "" > sqled.log
```

**Comment by Sharkzeng** [comment]
> 

是的

**Comment by sjjian** [comment]
我测试没有问题
