### ISSUE TITLE
SQLE scanner 较高概率出现扫描上传SQL超时

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#701]
请问下 哪里设置超时秒数呢? SCANNER 
INFO[0000] scanner started...                           
failed to upload sql: Post "http://192.168.0.221:10000/v1/audit_plans/PAYLABS_TEST_DB_AUDIT_MYBAITS/trigger": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by Marcus9530** [comment]
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
同样碰到上述报错

![origin_img_v2_98cfe09f-6612-480b-85d1-8388066b4e5g](https://user-images.githubusercontent.com/54339501/181710275-335d812e-be67-43be-bae4-6866df402cee.jpg)

**Comment by sjjian** [comment]
## 原因
scanner 进行http请求时默认超时设置为了1s，暂时设置为60s吧

**Comment by Marcus9530** [comment]
UI Version: main 92b44b8
Server Version: main-ee 018349a02a
验证步骤：
当前scanner运行成功，并没有出现超时报错
![image](https://user-images.githubusercontent.com/54339501/181734036-1e1c5cc5-4ee6-44ca-bc1e-d90b87bd5289.png)
![image](https://user-images.githubusercontent.com/54339501/181734066-15c3e78d-563e-468f-8cea-e9ae37cd4750.png)
