### ISSUE TITLE
SCANNERD 扫描先别立刻审核

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#702]
觉得SCANNERD 工具 工作太多了, 一般是扫描大量的XML文件,然后上传到服务端的对应任务SQL池中. 然后由定时任务进行审核;
实际上 SCANNERD  分析,上传,审核一条龙干完. 可遇到审核不过的SQL 就退出了工作,接下来的XML 就不继续了.

INFO[0000] scanner started...                           
failed to upload sql: Post "http://192.168.0.221:10000/v1/audit_plans/PAYLABS_TEST_DB_AUDIT_MYBAITS/trigger": EOF

**Comment by taolx0** [comment]
### 自测
![image](https://user-images.githubusercontent.com/63177450/200723874-bce4ce29-a506-4580-b6f2-a87125c0dfd8.png)
跳过审核
![image](https://user-images.githubusercontent.com/63177450/200724102-665e09e3-6c2d-46f9-a3c0-d1bd739cc287.png)
不跳过审核
![image](https://user-images.githubusercontent.com/63177450/200724506-f20410ea-8b2e-410f-844d-f0a11c360676.png)

**Comment by Marcus9530** [comment]
验证版本
UI Version: main ff420bf
Server Version: main-ee 0b72a93f63
验证步骤
1.使用scanner的mybatis功能，然后使用跳过参数-k的时候，scannerd直接审核
2.然后重新下发命令，增加-k=true参数，此时scanner只扫描不审核

![image](https://user-images.githubusercontent.com/54339501/205235128-2988e15f-e5f4-4829-b6f1-b602bab683ae.png)
![image](https://user-images.githubusercontent.com/54339501/205235221-0562dec8-fce9-42e6-9e38-80ab2559c207.png)
