### ISSUE TITLE
解析MyBatis的trim 语法时，suffix 属性未生效

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#704]
## 版本
1.2206版本

## 描述
解析MyBatis的trim 语法时，suffix 属性未生效，测试xml如下：
```XML
<mapper namespace="Test">
	<insert id="insertSelective" parameterType="com.paylabs.merchant.pojo.Agent">
		<selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
			SELECT LAST_INSERT_ID()
		</selectKey>
		insert into agent
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<if test="agentNo != null">
				agent_no,
			</if>
			<if test="agentName != null">
				agent_name,
			</if>
		</trim>

		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<if test="agentNo != null">
				#{agentNo,jdbcType=VARCHAR},
			</if>
			<if test="agentName != null">
				#{agentName,jdbcType=VARCHAR},
			</if>
		</trim>
	</insert>
</mapper>
```
解析出 INSERT 语句如下:
```SQL
insert into agent
        		( agent_no,
        			
        				agent_namevalues ( ?,
        			
        				?;
```

**Comment by sjjian** [comment]
## 原因
目前的 mybatis 解析器未处理trim的 suffix 属性

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2206.x 614a04c
Server Version: release-1.2206.x-ee c1a9993765
复现步骤：
1.使用上述xml内容创建mybatis文件
2.使用jenkins跟gitlab对接，然后触发编译
3.查看jenkins控制台输出和sqle审核任务内sql池输出信息，提示该sql无法解析

![image](https://user-images.githubusercontent.com/54339501/181668139-2f959ff0-8dc2-48ba-b55b-0c7f1494b22f.png)
![image](https://user-images.githubusercontent.com/54339501/181668146-4786b214-21fd-44cd-a38d-9c1b3a5fe9aa.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b19d80a
Server Version: main-ee 251e1b0963
验证步骤：
1.使用上述xml内容创建mybatis文件
2.使用jenkins跟gitlab对接，然后触发编译
3.查看sqle审核任务内sql池输出信息当前可以正常解析该sql
![image](https://user-images.githubusercontent.com/54339501/181668661-5074ab0b-45c9-4354-9db3-035a4045c849.png)
