### ISSUE TITLE
SQL审核判定字段不存在

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#708]
1.2206

UPDATE report_info m,
(
		SELECT m.merchant_no,m.pay_day,s.effective_time,
		DATEDIFF(m.pay_day,s.effective_time) AS days 
		FROM report_info m 
		LEFT JOIN merchant_info s ON m.merchant_no=s.merchant_no
) b
 SET profit_type='00' 
 WHERE m.merchant_no=b.merchant_no 

**error
字段 b.merchant_no 不存在**
warn
delete/update 语句必须有limit条件
notice
暂不支持回滚多表的 DML 语句

**Comment by sjjian** [comment]
建议这种子查询的忽略检查

**Comment by taolx0** [comment]
你能提供```merchant_info```，```report_info```这两张表的DDL信息吗？

**Comment by taolx0** [comment]
### 修改后的效果
![image](https://user-images.githubusercontent.com/63177450/183568423-533f89c9-bffa-4368-b0b1-1f6675e55dac.png)

**Comment by taolx0** [comment]
### 发现 delete 语句也存在类似的问题
![image](https://user-images.githubusercontent.com/63177450/183590468-418d6420-82a2-4674-be26-cac1c9ecf7e0.png)

**Comment by taolx0** [comment]
### 修改后的效果
![image](https://user-images.githubusercontent.com/63177450/184587204-ea7245f9-aad1-44bf-b46d-0fc469198932.png)

**Comment by taolx0** [comment]
> 你能提供`merchant_info`，`report_info`这两张表的DDL信息吗？

根据sql反推的建表DDL信息
```
create table t1
(
    id int primary key not null
);

create table t2
(
    id int primary key not null
);

create table report_info
(
    merchant_no int primary key not null,
    profit_type varchar(20)     not null,
    pay_day     datetime        not null

);

create table merchant_info
(
    merchant_no    int primary key not null,
    effective_time datetime        not null
);
```

**Comment by Marcus9530** [comment]
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：
1.根据上述表结构创建好mysql表
2.然后根据上述的UPDATE语句去审核，然后出校zi duan字段不存在的报错


![image](https://user-images.githubusercontent.com/54339501/187147127-39334f9e-984a-49b4-a57a-ee1c9c1aefad.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b4bfb8d
Server Version: main-ee 3c255f3b01
验证步骤：
1.根据上述表结构创建好mysql表
2.然后根据上述的UPDATE何delete语句去审核，未出现字段不存在的报错

![image](https://user-images.githubusercontent.com/54339501/187822961-ff128fc1-fb0f-4def-9566-e9d8356f64ab.png)
![image](https://user-images.githubusercontent.com/54339501/187822988-bc22c4c5-8083-401a-b0f7-b6521b25473b.png)
