### ISSUE TITLE
创建的扫描任务的审核周期建议默认设置久一点，防止未设置的情况下每秒都审核

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#712]
**Describe**

目前的默认审核周期是* * * * *， 代表审核周期为每秒钟审核，从目前的用户反馈来看，他们一般不怎么修改这个值（在试用时），会导致试用的环境放置几天后生成海量的审核报告，给用户造成一定的困惑，因此创建的扫描任务的审核周期建议默认设置久一点，防止未设置的情况下每秒都审核
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/18008452/181674153-1b787be0-5742-4eb2-83e1-25963a5d3d6e.png">

**Suggestion**

默认值建议设置为小时：0，分钟：0，预览：0 0 * * *

**Why**

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee d1e0ce3019
验证步骤；
当前创建扫描任务的时候，审核周期已默认修改为0 0 * * *

![image](https://user-images.githubusercontent.com/54339501/188083693-008781ff-8e90-47af-9784-25cf0529f9c1.png)
