### ISSUE TITLE
审核规则界面接口返回有延迟

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#715]
**SQLe Version**
UI Version: main 92b44b8
Server Version: main-ee 018349a02
MySQL: 5.7.36

1.下载不同类型的审核插件到sqle内
2.然后重启sqle
3.在审核规则界面刷新之后，接口返回需要2s多时间
![origin_img_v2_d5577597-97e9-4fd3-a357-682c5fcefaeg](https://user-images.githubusercontent.com/54339501/182058299-67afe0fa-c9d5-499a-adb5-f14ae9aac954.jpg)

期望对此进行一下排查，理论上应该很快就返回

**Comment by sjjian** [comment]
ref: https://github.com/actiontech/sqle/issues/826

**Comment by Marcus9530** [comment]
已经在https://github.com/actiontech/sqle/issues/826验证
