### ISSUE TITLE
绑定了流程模板的用户无法被删除

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#717]
## 问题复现步骤
1. 创建用户
2. 创建流程模板, 流程模板里某个步骤执行人指定刚创建的用户
3. 删除刚创建的流程模板
4. 删除刚创建的用户, 发现删除失败, 提示用户绑定了流程模板, 无法删除

## 问题原因
删除流程模板时只删掉了流程模板, 没有删掉步骤模板,  删除用户时检查的是绑定用户的步骤模板是否都被删除了, 所以绑了流程模板的用户将会永远无法删除

## 修复方案
改为判断用户是否绑定了未删除的流程模板

## 影响功能
删除用户

## 任务拆分

- [x] 修改代码
- [ ] 补充自动化测试

**Comment by Marcus9530** [comment]
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：
1.创建test用户
2.创建审批流程，然后第一步审核人指定test用户
3.删除审批流程
4.删除test用户，提示报错

![image](https://user-images.githubusercontent.com/54339501/187114953-c6532f0b-d590-4829-aa74-a6cd1371b2d7.png)
![image](https://user-images.githubusercontent.com/54339501/187114976-aa2a0bed-8320-4554-afa1-83c2b618c1dc.png)
![image](https://user-images.githubusercontent.com/54339501/187115007-0c14cdc1-cc95-4eea-a02d-25191cec1e3f.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b4bfb8d
Server Version: main-ee 3c255f3b01
验证步骤：
1.创建test用户
2.创建审批流程，然后第一步审核人指定test用户
3.删除审批流程
4.删除test用户成功

![image](https://user-images.githubusercontent.com/54339501/187820377-e57b5b9c-268a-4dc3-a22a-dcd888db65f2.png)
![image](https://user-images.githubusercontent.com/54339501/187820400-197a8988-12a7-467e-b9ee-435a04435f55.png)
![image](https://user-images.githubusercontent.com/54339501/187820409-6c9917ae-be85-4700-b919-1b571f15cf53.png)
