### ISSUE TITLE
SQLE后端库不应该记录邮箱配置的明文密码

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#722]
**SQLe Version**
SQLE后端库不应该记录邮箱配置的明文密码
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by Marcus9530** [comment]
复现版本
UI Version: main 2a0b15e
Server Version: main-ee 06950e07b6
复现步骤：
1.系统设置，添加一个邮箱和密码
2.查看mysql里面的表，发现密码被明文记录
![image](https://user-images.githubusercontent.com/54339501/183351702-bbe0d938-5a72-4389-b2e8-bdc6b8b92492.png)

**Comment by taolx0** [comment]
### 自测
无明文密码
![image](https://user-images.githubusercontent.com/63177450/187363233-f6a14015-6ac0-48c2-b4a4-5d31ed26426d.png)
接收到邮件
![image](https://user-images.githubusercontent.com/63177450/187363503-6fdf6fc9-cc97-45eb-8fd2-606c64cf9502.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3

验证步骤：
1.系统设置，添加一个邮箱和密码
2.查看mysql里面的表，目前邮箱密码被加密记录

![image](https://user-images.githubusercontent.com/54339501/187845518-2ab68763-42d4-41f5-bcd4-d71df3b1d522.png)
