### ISSUE TITLE
将SQLE所有用双引号包裹字符串的地方改为单引号

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#731]
# 背景
SQL语句中需要包裹字符串时请务必使用单引号而非双引号, 因为MySQL的 sql_mode中有一项 'ANSI_QUOTES', 开启后双引号包裹的内容会被当作标识符而非字符串, 从而导致本来正确的sql执行不了

# 官方文档
[MySQL :: MySQL 5.7 Reference Manual :: 5.1.10 Server SQL Modes](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes)

# 测试过程

开启此项后执行SQL的结果如图
![origin_img_v2_d8c27657-d64d-40ed-a086-7f3e3c5a844g](https://user-images.githubusercontent.com/37464327/183623836-2f494d33-6f10-4499-aaa2-4f1ab86040da.jpg)

关闭此项后执行SQL的结果如图
![origin_img_v2_950cd405-0db7-49b7-aeda-a60cc9eeca0g](https://user-images.githubusercontent.com/37464327/183623918-493bc5fd-e108-4af1-bd7b-575c46341ef5.jpg)

**Comment by Marcus9530** [comment]
复现版本：
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：
1.开启该项
`SET GLOBAL sql_mode = 'ANSI_QUOTES';`
2.使用以下sql语句进行审核，出现错误提示
`select TABLE_NAME from information_schema.tables where table_schema="dcisdb02" and TABLE_TYPE in ("BASE TABLE","SYSTEM VIEW");`
![image](https://user-images.githubusercontent.com/54339501/188102763-f5c49be0-558f-43b3-88bb-d025535d05c9.png)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee c233f3efea
验证步骤：
1.开启该项
`SET GLOBAL sql_mode = 'ANSI_QUOTES';`
2.使用以下sql语句进行审核，正常审核
`select TABLE_NAME from information_schema.tables where table_schema="dcisdb02" and TABLE_TYPE in ("BASE TABLE","SYSTEM VIEW");`

![image](https://user-images.githubusercontent.com/54339501/188103349-04af7d3c-55bb-47d7-8c32-a2aac24a9dd8.png)
