### ISSUE TITLE
/v1/instance_tips [get] 指定实例类型时会报错

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#736]
# 问题现象
/v1/instance_tips 接口调用者不是admin, 且functional_module为create_audit_plan, filter_db_type不为空时会出现这个情况
![image](https://user-images.githubusercontent.com/37464327/183854701-d6b8995a-d86f-4267-bec2-6f2f559bb258.png)
![image](https://user-images.githubusercontent.com/37464327/183854768-0660f238-fcfe-4ce3-8247-0b113d4029cb.png)

# 影响功能
非admin用户修改审核任务
![image](https://user-images.githubusercontent.com/37464327/183861076-0726137b-9983-4ac3-af6e-c98ad85cf405.png)

# 问题说明
在满足问题现象说的情况时, 获取实例列表的sql在实例类型的SQL需要六个参数, 少传了两个

# 修复方案
补上那两个参数

**Comment by Marcus9530** [comment]
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：
1.admin用户创建一个审核任务
2.然后创建test用户并赋予所有权限
3.切换到test用户，然后对admin用户创建的审核任务进行修改，出现报错

![image](https://user-images.githubusercontent.com/54339501/187114446-69f707c0-e597-43cd-86d0-d1c9676f473a.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3
验证步骤：
1.admin用户创建一个扫描任务
2.然后创建test用户并赋予所有权限
3.切换到test用户，然后对admin用户创建的审核任务进行修改，无其他报错信息，可正常修改
![image](https://user-images.githubusercontent.com/54339501/187842383-a34d22bc-ed1a-41dc-9389-7f5b862da9de.png)

![image](https://user-images.githubusercontent.com/54339501/187842332-fdddc5a8-292c-4471-ad4c-74fcd035b7a5.png)
![image](https://user-images.githubusercontent.com/54339501/187842481-dfd93bfb-26f1-45a8-97ec-1f6ae0a8f598.png)
