### ISSUE TITLE
审核规则“必须使用指定数据库字符集”导致panic

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#758]
复现步骤：
1. 启用审核规则“必须使用指定数据库字符集”
2. 创建工单，填入修改字段默认值的SQL语句，如：alter table tb1 alter column a set default 0;
3. 点击“审核”
4. sqled发生panic，panic信息如下：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf3965d]

goroutine 121 [running]:
github.com/pingcap/parser/types.(*FieldType).EvalType(0x0)
	/usr/local/src/sqle-ee/vendor/github.com/pingcap/parser/types/field_type.go:82 +0x1d
github.com/actiontech/sqle/sqle/driver/mysql/rule.getColumnCSFromColumnsDef({0xc001253440, 0x1, 0x1})
	/usr/local/src/sqle-ee/sqle/driver/mysql/rule/rule.go:1465 +0xf6
github.com/actiontech/sqle/sqle/driver/mysql/rule.checkCharacterSet(0xc0012e9bc0, {{0xc00070bae0, 0x1d}, {0xc0009656b0, 0x24}, {0xc00092f710, 0x9}, {0xc00135c390, 0x6}, {0xc0012fcc60, ...}}, ...)
	/usr/local/src/sqle-ee/sqle/driver/mysql/rule/rule.go:1512 +0x9db
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).Audit(0xc001296a20, {0x1b46cb0, 0xc0000440f0}, {0xc00054f8f0, 0x2d})
	/usr/local/src/sqle-ee/sqle/driver/mysql/mysql.go:307 +0x8f9
github.com/actiontech/sqle/sqle/server.hookAudit(0xc0005c2310, 0xc001306400, {0x1b5c3c0, 0xc001296a20}, {0x1b357e8, 0x34f0b98})
	/usr/local/src/sqle-ee/sqle/server/audit.go:133 +0x4a5
github.com/actiontech/sqle/sqle/server.audit(0xc0005c2310, 0xc001306400, {0x1b5c3c0, 0xc001296a20})
	/usr/local/src/sqle-ee/sqle/server/audit.go:77 +0x6f
github.com/actiontech/sqle/sqle/server.(*action).audit(0xc0012efbc0)
	/usr/local/src/sqle-ee/sqle/server/sqled.go:240 +0xaa
github.com/actiontech/sqle/sqle/server.(*Sqled).do(0xc00011a640, 0xc0012efbc0)
	/usr/local/src/sqle-ee/sqle/server/sqled.go:154 +0x71
github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop.func1()
	/usr/local/src/sqle-ee/sqle/server/sqled.go:142 +0x45
created by github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop
	/usr/local/src/sqle-ee/sqle/server/sqled.go:141 +0x16b
```

**Comment by re-f** [comment]
需要在所有规则校验的地方加上 panic recover

**Comment by taolx0** [comment]
### 自测
审核sql```alter table tb1 alter column a set default 0;```，程序正常运行。
![image](https://user-images.githubusercontent.com/63177450/187393445-07e4ff11-d3d8-4b85-b865-e7d1379c8e78.png)

**Comment by taolx0** [comment]
> 需要在所有规则校验的地方加上 panic recover
### 准备
直接通过sqle二进制可执行文件启动
### 自测
1. 在审核规则```必须使用指定数据库字符集```里加入panic
![image](https://user-images.githubusercontent.com/63177450/187394683-1fbffd6f-34b1-4c14-a90f-8a0c8130b236.png)
2. 审核sql
3. 程序未崩溃，日志成功打印panic信息
![image](https://user-images.githubusercontent.com/63177450/187395289-e2c902e3-eccb-4436-b877-66c17df71e0c.png)

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：

1. 启用审核规则“必须使用指定数据库字符集”
2. 创建工单，填入修改字段默认值的SQL语句，如：alter table tb1 alter column a set default 0;
3. 点击“审核”
4. sqled发生panic，panic信息如图所示：

![image](https://user-images.githubusercontent.com/54339501/187844548-8da203ba-467f-40be-a791-9c6861f9ffe6.png)
![image](https://user-images.githubusercontent.com/54339501/187844572-e8e84423-77d6-47d0-9280-fd2d689c0712.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3
验证步骤：

1. 启用审核规则“必须使用指定数据库字符集”
2. 创建工单，填入修改字段默认值的SQL语句，如：alter table tb1 alter column a set default 0;
3. 点击“审核”，目前可以正常审核，没有出现未知错误
![image](https://user-images.githubusercontent.com/54339501/187844940-e63b1026-41b3-40bb-9563-bb8c09339953.png)

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/187845044-57fd3348-8637-4723-bd90-5f2883884b55.png)
