### ISSUE TITLE
角色删除后，该角色绑定的用户还能访问绑定的数据源

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#77]
**SQLe Version**
main

**Describe the bug**
角色删除后，该角色绑定的用户还能访问绑定的数据源

**To Reproduce**
1. 创建用户1；
2. 创建数据源1；
2. 创建角色绑定用户1，数据源1；
3. 用户1可以对数据源1创建工单；
4. 删除角色1
5. 用户1依然能对数据源1创建工单

**Expected behavior**
用户1无法访问数据源1

**Comment by sjjian** [comment]
TODO: 修复后，启用该bug对应的自动化测试

**Comment by Marcus9530** [comment]
验证版本
SQLe Version:"release-1.2111.x 3d69edc91e634ae9d93f1a0ff2301016f2ea4249"
验证步骤：
1.创建数据源test，然后创建角色绑定该数据源，创建test用户绑定角色
2.然后通过test用户创建工单
3.删除绑定数据源的角色test
4.切换到test用户，然后创建工单，已经没有可以选择的数据源了
![image](https://user-images.githubusercontent.com/54339501/143378829-22c32f0f-4ad9-494f-b0d5-c48ab42e379a.png)
![image](https://user-images.githubusercontent.com/54339501/143378895-a0f8a240-9db7-4c40-92b9-855df38ec9fd.png)
![image](https://user-images.githubusercontent.com/54339501/143379188-ed52121d-02c1-46b3-b7bc-368e52daefef.png)
![image](https://user-images.githubusercontent.com/54339501/143379241-181abffb-8179-4ed5-bf2f-c7ce791664cd.png)
