### ISSUE TITLE
开启全局配置中的“在 DML 语句中预计影响行数超过指定值则不回滚”审核SQL导致服务崩溃

### ISSUE THREAD

**Issue by S0uLHun43r** [actiontech/sqle#773]
建表语句如下：
CREATE TABLE `p_process_info` (
  `id` bigint(64) NOT NULL AUTO_INCREMENT,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `delete_time` timestamp NULL DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `structure` json DEFAULT NULL,
  `classify` bigint(64) DEFAULT NULL,
  `tpls` json DEFAULT NULL,
  `task` json DEFAULT NULL,
  `submit_count` bigint(64) DEFAULT '0',
  `creator` bigint(64) DEFAULT NULL,
  `notice` json DEFAULT NULL,
  `icon` varchar(128) DEFAULT NULL,
  `remarks` varchar(1024) DEFAULT NULL,
  `tenant_id` varchar(12) NOT NULL DEFAULT '000000',
  `order_type` int(11) NOT NULL DEFAULT '1',
  `isanalysis` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_p_process_info_delete_time` (`delete_time`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

审核的SQL语句为指纹SQL：
 UPDATE `p_process_info` SET `submit_count` = ?, `update_time` = ?  WHERE (id = ?);

**Comment by taolx0** [comment]
# 为什么程序会panic？
先介绍下sql生成回滚语句的背景，以本次issue为例，sqle会提取```UPDATE p_process_info SET submit_count = ?, update_time = ? WHERE (id = ?);```语句的where部分，通过类似```select * from p_process_info where id = 1```这样的select语句获取生成回滚语句所需的信息。
然而此issue的sql的where部分是指纹类型```WHERE (id = ?);```，所以sqle无法获取回滚sql所需的信息。具体panic原因是，将包含指纹的语法树转为sql字符串时，sql解析器panic。

**Comment by taolx0** [comment]
### 修复效果
```UPDATE p_process_info SET submit_count = ?, update_time = ? WHERE (id = ?);```
![image](https://user-images.githubusercontent.com/63177450/187166504-0b0e1e18-3f4a-4d11-bcb0-571ebca5e9de.png)

```
delete from users where id = ?;
```
![image](https://user-images.githubusercontent.com/63177450/187166799-fe7da831-bd5d-4bf1-8f31-0ecf6e113458.png)

```
insert into rule_template_rule(rule_template_id, rule_name, level, db_type)
values (2, 'test123', 'error', 'mysql');
```
![image](https://user-images.githubusercontent.com/63177450/187166994-287710e1-5f53-4ca5-b06c-c4b76c04faad.png)

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a
复现步骤：
1.创建工单使用表结构进行审核且上线
2.使用修改语句的sql指纹进行审核，出现未知错误
![image](https://user-images.githubusercontent.com/54339501/187843845-8735c32a-c20d-4b28-b5a9-44c914a7de42.png)


![image](https://user-images.githubusercontent.com/54339501/187843712-570c10d2-bd3c-4eaf-935d-ce4d548b3ef1.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3
验证步骤：
1.创建工单使用表结构进行审核且上线
2.使用修改语句的sql指纹进行审核，没有出现报错可以正常审核

![image](https://user-images.githubusercontent.com/54339501/187843991-cba9d450-2fd7-409b-9016-3532f351e025.png)
![image](https://user-images.githubusercontent.com/54339501/187844059-18dea2e8-413d-45b2-8ad6-9d228914191e.png)
