### ISSUE TITLE
智能扫描功能，扫描任务列表的任务名称 提供一个 可打开的标识。

### ISSUE THREAD

**Issue by maxbelial** [actiontech/sqle#778]
**Describe**

现状：
某一个扫描任务是允许点击打开后，查看任务详情，从任务列表里看不出可以操作的地方。
![image](https://user-images.githubusercontent.com/20533617/186062782-27e00630-ab1a-4779-b61f-3cd05039397b.png)

**Suggestion**

期望：任务名称上提供一个标识，可以快速知道点击这里查看任务详情。
案例下图
![image](https://user-images.githubusercontent.com/20533617/186063107-867bb785-71c3-4ab7-af15-58b4d22b5b3e.png)

**Why**

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3


![image](https://user-images.githubusercontent.com/54339501/187842072-8c6c2aaa-a299-486e-95ac-b962fdbdc060.png)
