### ISSUE TITLE
工单列表待操作人之间建议优化为用逗号隔开，目前是连在一起

### ISSUE THREAD

**Issue by yunxixi** [actiontech/sqle#789]
**Describe**

![image](https://user-images.githubusercontent.com/16645348/186622776-53912954-92d4-42eb-af95-66026fd0237d.png)
应该是三个审核人：为admin，tc，test，目前看上去是一人
**Suggestion**

可以和用户列表里”角色“列采用同样的处理方式
**Why**

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main b4bfb8d
Server Version: main-ee 3c255f3b01
验证步骤；
1.创建审批流程，然后指定三个用户为审核用户
2.创建工单并提交
3.工单界面查看工单，目前三个用户已经可以看到明显区分

![image](https://user-images.githubusercontent.com/54339501/187823209-6754a5f2-5032-489a-a660-610b3a3b82e1.png)
![image](https://user-images.githubusercontent.com/54339501/187823261-17266c37-a7fb-4a94-9f85-9ffd9e8c9728.png)
