### ISSUE TITLE
报表统计菜单只对admin展示其它用户应该隐藏掉

### ISSUE THREAD

**Issue by yunxixi** [actiontech/sqle#798]
**SQLe Version**

  "main-ee b083bde1a24e7bccfa82969ae7ce4b4915e717fb"

**Describe the bug**
创建一个用户；
登入用户；
![image](https://user-images.githubusercontent.com/16645348/187129058-37cfe1a5-f550-44bd-b60d-3724aff1dc3a.png)

**To Reproduce**

**Expected behavior**

只有admin用户有统计报表的菜单权限其它都角色用户应该隐藏掉
**Suggestion**

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3

验证步骤：
1.创建一个具有所有权限的用户
2.登陆该用户，目前已经看不到报表统计界面
![image](https://user-images.githubusercontent.com/54339501/187864634-faca638b-bb58-4dd2-a336-512eef196f75.png)
