### ISSUE TITLE
当前审核任务已经改成扫描任务，对应的权限名称也应当随之一样。

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#799]
**SQLe Version**
UI Version: release-1.2207.x 92b44b8
Server Version: release-1.2207.x-ee 018349a02a

当前审核任务已经改成扫描任务，对应的权限名字也应当随之更改，保持一致。
（ps平台内其他有用到的地方都应该都改为扫描任务）

![image](https://user-images.githubusercontent.com/54339501/187130581-ecb59d27-801e-4496-a3c3-85d9a5c19b25.png)

**Comment by taolx0** [comment]
### 测试
名字显示正常
![image](https://user-images.githubusercontent.com/63177450/187840345-e534abd7-514d-4f96-849d-7ca6990b8dc5.png)
