### ISSUE TITLE
MySQL规则建表必须含字段 CREATE_TIME和UPDATE_TIME 建议字段命名可配置

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#800]
**Describe**
每个公司或者项目对该名称的定义都不太一样，可配置的话试用场景更广泛

**Suggestion**

**Why**

**Comment by sjjian** [comment]
ref: https://github.com/actiontech/sqle/issues/734

**Comment by taolx0** [comment]
### 测试
1. 开启规则```建表DDL必须包含创建时间字段且默认值为CURRENT_TIMESTAMP```，设置自定义字段名
![image](https://user-images.githubusercontent.com/63177450/188044504-52cc586d-6990-4dda-ad2a-5bc3d9c5cf92.png)

2. 测试错误sql，触发规则
![image](https://user-images.githubusercontent.com/63177450/188044415-b930fe6a-a139-4d4b-8c57-f71fda60f295.png)

3. 输入正确sql，审核通过
![image](https://user-images.githubusercontent.com/63177450/188044634-7f486668-1210-45f1-90f7-13d9f453c93b.png)

**Comment by Marcus9530** [comment]
验证版本：
Server Version: main-ee a53f860324

验证步骤；
1.修改审核规则规则建表DDL必须包含创建时间字段且，默认值为CURRENT_TIMESTAMP
![image](https://user-images.githubusercontent.com/54339501/188108956-d7337d43-5e7a-4c91-b40d-688148a227a9.png)
匹配字段名
![image](https://user-images.githubusercontent.com/54339501/188108903-3b078ea8-0ec7-4870-9411-6f16ad0c6e18.png)
未匹配字段名
![image](https://user-images.githubusercontent.com/54339501/188109290-c17177d0-8ad1-4e43-8c40-359e318e89c6.png)
2.修改审核规则：建表DDL必须包含更新时间字段且默认值为CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP默认值为TEST_TIME
![image](https://user-images.githubusercontent.com/54339501/188109574-3363150d-f74a-4d98-ac1a-ac271361ed77.png)
匹配字段名
![image](https://user-images.githubusercontent.com/54339501/188109775-6f798e34-542a-4d81-b428-0c9a8582726f.png)

未匹配字段名
![image](https://user-images.githubusercontent.com/54339501/188109728-30caaf38-07a4-46d9-9e7d-94030676acc6.png)
