### ISSUE TITLE
创建扫描任务的时候不指定规则模版，提交报错

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#806]
**SQLe Version**
UI Version: main 3000044
Server Version: main-ee b083bde1a2

1.创建审核规则模版
2.创建扫描任务，然后不选择指定的规则模版
3.点击提交报错
![mHaggRFofq](https://user-images.githubusercontent.com/54339501/187365449-e979e4a7-bb66-4d41-a04c-681d8add2df1.jpg)

**Comment by HuangWeiCen** [comment]
# 问题原因
当扫描任务指定了一个没有绑定审核规则模板的实例但没有指定自定义模板时, 按照原逻辑, 扫描任务将会使用实例绑定的审核模板, 但实例没有审核模板, 就会报出找不到数据的错误

# 修复方式
如果找不到实例绑定的审核模板, 则使用实例类型的默认审核模板

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee acc51031d3
验证步骤；
1.创建审核规则模版
2.创建扫描任务，然后不选择指定的规则模版
3.点击提交成功，可以正常创建扫描任务

![image](https://user-images.githubusercontent.com/54339501/187865045-4790188a-e29a-42f0-a993-8a16e98e83c9.png)
