### ISSUE TITLE
页面显示邮件发送成功，但邮箱未收到

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#807]
**SQLe Version**
main

**Describe the bug**
页面显示邮件发送成功，但邮箱未收到

**To Reproduce**
1. 配置系统设置的SMTP，关闭启用邮件推送
![image](https://user-images.githubusercontent.com/63177450/187367455-242a8430-c98d-4452-947e-7d04c0583eea.png)

2. 点击测试
![image](https://user-images.githubusercontent.com/63177450/187368175-c0f52fe8-c90f-4e9b-b554-dd61378c048e.png)

3. 测试邮箱未收到邮件

**Expected behavior**
邮箱收到邮件

**Suggestion**
测试邮件发送功能是否正常，应该与 是否启用邮件推送 无关

**Comment by olddriver4** [comment]
我有同样的问题，web前端相应error -> dial tcp: i/o timeout

**Comment by olddriver4** [comment]
{"code":0,"message":"ok","data":{"is_smtp_send_normal":false,"send_error_message":"send email to [limeng_bj@meican.com] error: dial tcp: i/o timeout"}}

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2209.x 604e0ac
Server Version: release-1.2209.x-ee 3f8ad37ce4
复现步骤：
1.在系统设置中填写smtp相关参数
2.然后关闭smtp功能
3.然后使用测试功能，往另一个邮箱发送测试邮件
4.实际另一个邮箱没有收到邮件

![image](https://user-images.githubusercontent.com/54339501/197944041-1451568c-68b7-46ef-8ff2-0d801580d2e7.png)
![image](https://user-images.githubusercontent.com/54339501/197944145-9fecee3d-6e38-4fc7-b750-c5afed5a1004.png)
![image](https://user-images.githubusercontent.com/54339501/197944194-a092a63d-1baf-4a7f-9aa3-76abc4f4f94a.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 9ad6f1b
Server Version: main-ee e4e5da233a
验证步骤：
1.在系统设置中填写smtp相关参数
2.然后关闭smtp功能
3.然后使用测试功能，往另一个邮箱发送测试邮件
4.界面提示stmp功能没有开启

![image](https://user-images.githubusercontent.com/54339501/197994886-cc05c46c-52a9-4ba9-9394-51db3efa55b9.png)
![image](https://user-images.githubusercontent.com/54339501/197994934-22ebca8e-263f-4eac-94fd-e4cb7ff5bd73.png)
![image](https://user-images.githubusercontent.com/54339501/197994969-fc3f8755-06a1-47c1-9dbe-da07019f8203.png)
