### ISSUE TITLE
使用select sleep(1)语句进行审核出现请求错误，查看后台信息发现sqle重启

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#809]
**SQLe Version**
UI Version: main b4bfb8d
Server Version: main 7481bdf47d

1.创建工单，然后对以下sql语句进行审核
`select sleep(1)`
2.出现请求错误，查看后台发现sqle重启
![origin_img_v2_29948067-51e4-4bdd-aaa2-d8f4516eb74g](https://user-images.githubusercontent.com/54339501/187580213-5d3b536e-42c2-4902-b644-695680b8ca96.jpg)
![origin_img_v2_3f35e74e-3edb-42bc-8696-697e1ff8d3bg](https://user-images.githubusercontent.com/54339501/187580258-c0163bd2-f21f-48c0-a98b-44cc6897107d.jpg)
![Uploading origin_img_v2_63a66242-de1a-43f4-aedd-3ca2ec05f2ag.jpg…]()

**Comment by taolx0** [comment]
### 为什么页面会出现请求错误提示并且sqle重启？
因为sqle在检测```JOIN字段类型不一致```规则时，程序panic，所以页面会提示未知错误，崩溃的sqle会被systemctl重启。

###

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/187853623-3fe67120-764e-48cc-b9a3-33de2dc73fb9.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main d965f85
Server Version: main-ee d1e0ce3019

验证步骤：
1.创建工单，然后对以下sql语句进行审核
`select sleep(1)`
2.当前可以正常审核

![image](https://user-images.githubusercontent.com/54339501/188064143-3687a3ad-c368-4075-9eac-fec06bd0333a.png)
