### ISSUE TITLE
当sqle出现崩溃重启时，std日志不应该被覆盖

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#810]
**SQLe Version**
UI Version: main b4bfb8d
Server Version: main 7481bdf47d

出现类似于请求错误的现场时，查看std日志发现被覆盖，无法提供有效信息，当时的日志信息理应被保留以供后续排查，建议可以把当时的std日志命令为std_1.log 后续以此类推，重启后的最新的一直为std_0.log
![image](https://user-images.githubusercontent.com/54339501/187580381-8c293989-4ea2-4100-a5dc-c90cb73f5e64.png)

参考如下：
![image](https://user-images.githubusercontent.com/54339501/187580696-544a0ac8-5ef1-4c28-874e-b89da7038115.png)

**Comment by sjjian** [comment]
目前的实现是通过命令行重定向的，因此难以实现std日志轮转。暂时保持增量写入

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 7705820
Server Version: main-ee c64c8ce973
验证步骤：

通过systemctl restart sqled命令重启sqle，然后观测std日志，发现std日志依旧保留之前的日志内容

![image](https://user-images.githubusercontent.com/54339501/193198595-bce64f3e-ee49-4474-a06e-99b096edc771.png)
