### ISSUE TITLE
建议开发自定义规则

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#813]
容许用户自定义规则, 并且使用外部的程序或者脚本去检查SQL文本
SQLE 设置规则名称,检查外部程序名称,路径,
SQLE 传递SQL文本给外部程序
SQLE 回收 检查通过,检查失败,报错信息.

**Comment by sjjian** [comment]
Duplicated by：https://github.com/actiontech/sqle/issues/462
