### ISSUE TITLE
新增MySQL规则 “SELECT 语句必须带LIMIT, 默认1000”

### ISSUE THREAD

**Issue by Sharkzeng** [actiontech/sqle#816]
MYSQL 规则
DML
告警
SELECT 语句 必须带LIMIT  默认1000
主要防止 查询过多行

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 88b6102
Server Version: main-ee c06bde1532

验证步骤：
1.开启改规则
2.输入不带limit语句的进行触发，可以看到审核提示
3.输入限制limit数量之内的进行触发，没有看到审核提示

![image](https://user-images.githubusercontent.com/54339501/197454216-6cb63199-7cb8-433f-8294-7db338a21c30.png)
![image](https://user-images.githubusercontent.com/54339501/197454373-3013af95-46b5-4d20-8868-cede651e27a4.png)
![image](https://user-images.githubusercontent.com/54339501/197454547-20abf762-56e1-485a-ab4e-8970acd4b913.png)
