### ISSUE TITLE
当审批流程某一步骤绑定的用户删除之后，后续工单使用该审批流程会在这一步骤显示正在等待用户进行操作

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#817]
**SQLe Version**
UI Version: main b4bfb8d
Server Version: main-ee 3c255f3b01
复现步骤：
1.创建一个审批流程，然后指定审核为test用户
2.创建工单并提交，可以看到审核步骤中显示下一步用户为test
3.删除test用户，然后在创建工单并提交，但是显示正在等待用户进行操作
![image](https://user-images.githubusercontent.com/54339501/187820898-cdbcf2ff-487a-4179-bbba-0dc8ebbe1f52.png)
未删除test用户：
![image](https://user-images.githubusercontent.com/54339501/187820970-d56d72f4-c578-4696-afea-df3c68fc35fc.png)
删除test用户：
![image](https://user-images.githubusercontent.com/54339501/187821099-eee8be3c-4372-414f-96df-738310e78cbf.png)
![image](https://user-images.githubusercontent.com/54339501/187821170-266f3751-5729-46d9-b9d2-aa4bb2677aa2.png)

当前现状：没有告知哪个用户去操作这一步，可以能会让用户产生疑问，不知道如何处理这个工单，即使使用admin用户也无法进行后续操作
期望：当审批流程中某一个步骤中只指定了一个用户，而该用户被删除之后，审批流程自动移除该步骤，或者是在工单里面审核流程中显示test用户已删除请修改审批流程之类的引导文案

**Comment by Marcus9530** [comment]
临时解决手段：修改审批流程，去除该步骤

**Comment by ColdWaterLW** [comment]
现在删除用户的条件之一是审批流程没有指定该用户，该问题已不存在
