### ISSUE TITLE
为每种智能扫描建立独立的菜单页面

### ISSUE THREAD

**Issue by re-f** [actiontech/sqle#825]
**Describe**

**Suggestion**

![image](https://user-images.githubusercontent.com/8351089/188049138-02eea1d2-a33a-4c89-a042-0723642b4c62.png)
将目前SQLe支持的智能扫描类型，在一级菜单中展示出来

**Why**

智能扫描在SQL审核流程中是重要的模块，需要能让使用者最快知道SQL支持哪些类型扫描，降低SQLe的使用门槛

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 9ad6f1b
Server Version: main-ee e4e5da233a

验证步骤：
1.创建不同类型的智能任务
2.然后在每个类型的智能任务界面进行查看


![image](https://user-images.githubusercontent.com/54339501/198242543-9d9d2454-e1e3-4d22-8440-21bea783df00.png)
![image](https://user-images.githubusercontent.com/54339501/198243389-9ceab1c2-ca9e-4740-9905-c994f28a1947.png)
![image](https://user-images.githubusercontent.com/54339501/198243427-55362307-0202-4180-8752-48672ce5a372.png)
![image](https://user-images.githubusercontent.com/54339501/198243517-fc0983bd-1047-4682-b6cf-799d2c5d7745.png)
![image](https://user-images.githubusercontent.com/54339501/198243537-1942c5bf-ad10-41c8-bc52-8511ba8cd518.png)
![image](https://user-images.githubusercontent.com/54339501/198243562-025dedfc-7693-460c-9295-db14ce704201.png)
![image](https://user-images.githubusercontent.com/54339501/198243593-06a8347c-dcb8-42a4-9dcf-5864382e1d60.png)
![image](https://user-images.githubusercontent.com/54339501/198243623-56faef88-b203-455b-bb9b-5445c3ff778a.png)
![image](https://user-images.githubusercontent.com/54339501/198243650-04686cd8-f914-4dff-a420-bbe26ae02dd1.png)
![image](https://user-images.githubusercontent.com/54339501/198243687-4e4b9609-0b70-4126-ab7c-19a4f1466686.png)
![image](https://user-images.githubusercontent.com/54339501/198243720-4172c7d3-f9eb-474b-ba8a-617082d6b112.png)
![image](https://user-images.githubusercontent.com/54339501/198243747-77effb58-3343-4765-9501-f872dbc76675.png)
![image](https://user-images.githubusercontent.com/54339501/198243773-9943480e-b9ec-4715-8f7d-2027ab0b4f44.png)
