### ISSUE TITLE
建议规则中增加禁止使用rename、change 这种命令，不允许修改列名，表名

### ISSUE THREAD

**Issue by bdper0** [actiontech/sqle#850]
建议规则中增加禁止使用rename、change 这种命令，不允许修改列名，表名

**Comment by bdper0** [comment]
背景: rename/change 表名/列名会对线上业务不停机发布造成影响，如需这种操作应当DBA手工干预

**Comment by HuangWeiCen** [comment]
下列四种SQL会触发此规则:

1. ALTER TABLE exist_tb_1 CHANGE v1 a BIGINT;
2. ALTER TABLE exist_tb_1 RENAME COLUMN v1 TO a
3. RENAME TABLE exist_tb_1 TO test
4. ALTER TABLE exist_tb_1 RENAME TO test

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main a904e6c
Server Version: main-ee c06bde1532

验证步骤：
1.开启该规则，使用CHANGE和RENAME命令对表进行操作，可以看到能够触发相关提示
2.关闭该规则，使用CHANGE和RENAME命令对表进行操作，可以看到没有触发相关提示

开启该规则：
![image](https://user-images.githubusercontent.com/54339501/197955891-bf25f8ae-0cd0-463e-a083-a3e264186f2d.png)
![image](https://user-images.githubusercontent.com/54339501/197956019-e4594d8f-1a3a-436e-ac9c-af8b0091ded3.png)
![image](https://user-images.githubusercontent.com/54339501/197956092-2b968ab4-1e27-4937-b393-2ed758b8e4be.png)
![image](https://user-images.githubusercontent.com/54339501/197956152-8e401489-ce25-46b1-b58a-2e4bab744ffc.png)

关闭规则：
![image](https://user-images.githubusercontent.com/54339501/197956356-47ba86a2-e2fe-4d7e-a6c2-313e316ec224.png)
![image](https://user-images.githubusercontent.com/54339501/197956449-152c1245-e7fb-423d-ae84-db44832a2f76.png)
![image](https://user-images.githubusercontent.com/54339501/197956565-8f9bc746-6f80-4ec7-9817-08fcbd1267b0.png)


![image](https://user-images.githubusercontent.com/54339501/197956471-4c900082-f922-41c6-b469-a601f60b41dc.png)
