### ISSUE TITLE
录入MySQL数据源如果用户存在特殊字符":"时，连接数据库失败

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#859]
**SQLe Version**
main
**Describe the bug**
录入MySQL数据源如果用户存在特殊字符":"时，连接数据库失败，例如用户“test:"
![image](https://user-images.githubusercontent.com/18008452/190547829-a18459f5-fa89-45b8-8284-ab7671db4807.png)

![image](https://user-images.githubusercontent.com/18008452/190547168-da992b96-b628-49d4-834e-163fe05b46b0.png)

**Comment by sjjian** [comment]
## 原因：
当前连接MySQL的驱动采用的DSN串进行拼接用户名密码，不兼容特殊字符，https://github.com/go-sql-driver/mysql/issues/1323

**Comment by sjjian** [comment]
![image](https://user-images.githubusercontent.com/18008452/190549970-a48076cb-7ffb-44dc-8da5-a10f09fc3317.png)

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2208.x d965f85
Server Version: release-1.2208.x-ee a53f860324
复现步骤：
1.给mysql实例创建一个test:test用户
2.在sqle平台上添加这个mysql实例当数据源上
3.点击测试数据库连通性失败
![image](https://user-images.githubusercontent.com/54339501/192959177-4ef6e81e-10bb-4273-be92-0b412da708d6.png)
![image](https://user-images.githubusercontent.com/54339501/192959463-4bee74fd-3d22-4e9f-aac9-cdaa3bc8372a.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main bd11b2c
Server Version: main-ee bd74aa1d8e

验证步骤：
1.给mysql实例创建一个test:test用户
2.在sqle平台上添加这个mysql实例当数据源上
3.点击测试数据库连通性成功

![image](https://user-images.githubusercontent.com/54339501/192959770-46b4b308-341f-4536-8fe2-799a31618443.png)
