### ISSUE TITLE
ldap类型的用户在sqle使用重置密码功能成功，但是没什么实际意义

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#88]
**SQLe Version**
Version:"release-1.2111.x 382da4a190b282d1527c411e1ffa1cb34b6b0af2"

**Describe the bug**
ladp账号登录到sqle平台后，sqle对该类型的用户重置密码功能未作限制，可以重置密码，但是实际上登录sqle还是需要ldap配置的密码

**To Reproduce**
1. ldap配置一个账号
2. sqle全局配置设置ldap各参数配置，并且开启该功能
3. 使用ldap创建的账号进行登录sqle，然后切换admin用户，可以看到ldap账号生成的用户
4. 对ldap的用户进行密码重置，重置密码成功后，使用最新的密码提示ldap的user和密码不一致无法登录。
![image](https://user-images.githubusercontent.com/54339501/142365556-47f0b545-a92d-4aae-bc74-0c4c3cba559c.png)

**Expected behavior**
期望在sqle平台对ldap类型的用户进行重置密码功能使用的限制，不应该让用户在sqle进行密码修改，应该让用户去ldap上去修改密码

**Comment by Marcus9530** [comment]
影响面：
1.当前用户的个人中心的修改密码
![image](https://user-images.githubusercontent.com/54339501/142366374-e0dfebb3-a870-439b-9037-b58f636e14a7.png)
2.admin账号，用户管理界面
![image](https://user-images.githubusercontent.com/54339501/142366448-4db7a674-8a13-47cf-9dda-26e2c9cbe667.png)

**Comment by HuangWeiCen** [comment]
**开发方案**
后端: 
1. 获取用户列表的接口提供一个新的返回值字段,用于标记用户的登陆类型
2. 重置用户的接口判断要重置的用户登陆类型是否为ldap类型,是的不允许重置密码
前端:
1. 根据获取用户列表的接口登陆类型字段进行判断, ldap类型的用户重置密码按钮置灰

**开发成本**
共计: 1人/天

**Comment by Marcus9530** [comment]
sqle版本
release-1.2111.x 3d69edc91e634ae9d93f1a0ff2301016f2ea4249
根据开发修复方案也希望前端进行限制，目前看到的是前端未做限制，后端是做了限制
![image](https://user-images.githubusercontent.com/54339501/143380680-ec3f5e16-4799-4c2e-9477-3d2eb00b01aa.png)
![image](https://user-images.githubusercontent.com/54339501/143380791-aa07a7f0-29f7-43a6-8f90-d9fc5c8eff12.png)
后端限制
![image](https://user-images.githubusercontent.com/54339501/143380884-75bcfbab-6f3d-44ba-a587-773d8d371300.png)

**Comment by Marcus9530** [comment]
更新版本
  "release-1.2111.x 3d69edc91e634ae9d93f1a0ff2301016f2ea4249"

然后ldap创建ztest用户，在sqle登录该用户之后，该用户的 个人中心修改密码已经无法使用，admin账号的用户管理关于ztest用户已经没有修改密码的功能选项
![image](https://user-images.githubusercontent.com/54339501/143386934-3f916509-4298-47f4-9170-70e3268fea13.png)
![image](https://user-images.githubusercontent.com/54339501/143387022-389b5fd8-41e3-4e05-8946-1db859459d73.png)
