### ISSUE TITLE
无法删除用户邮箱

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#880]
填写用户邮箱
![image](https://user-images.githubusercontent.com/36940986/191193841-0588123a-08d2-4785-b7c1-8753a67e291b.png)

编辑用户，把邮箱删除后提交
![image](https://user-images.githubusercontent.com/36940986/191193956-79b14dca-12b2-47d3-b12e-3bc2dc95c0b4.png)

邮箱仍然存在
![image](https://user-images.githubusercontent.com/36940986/191194029-526d496a-d10b-4d04-9bb8-821957ff290c.png)

**Comment by ColdWaterLW** [comment]
需要后端支持
现状：修改email为空后，前端不会回传email字段，所以email没有被修改；但前端回传email字段为空时后端校验不通过
![image](https://user-images.githubusercontent.com/36940986/195031256-9b728a1e-b1cb-4c54-95eb-87cf1daeba21.png)

**Comment by Rain-1214** [comment]
会出现跟上述相同情况的还有在个人中心修改邮箱的时候。
![ry8soPFC3H](https://user-images.githubusercontent.com/23204067/195035478-015feda9-fba0-4c25-a36e-cc41942156af.jpg)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main ea5c57c
Server Version: main-ee c06bde1532

验证步骤：
1.找到一个带邮箱的用户，点击编辑
2.去掉该用户的邮箱，点击提交
3.该用户的邮箱已经去除
4.然后登录一个带有邮箱的用户
5.然后在个人中心，把邮箱给去除，点击提交
6.邮箱已经为空

![image](https://user-images.githubusercontent.com/54339501/197942917-51a37662-2028-4c40-9418-6ce7323bbf18.png)
![image](https://user-images.githubusercontent.com/54339501/197942936-f8c9c4a7-9625-46bd-8eef-f596b183fea9.png)
![image](https://user-images.githubusercontent.com/54339501/197943308-7ea333cf-435a-455a-8668-1d115ec1daa4.png)
个人中心
![image](https://user-images.githubusercontent.com/54339501/197943494-635f97be-d8d4-42c6-a37b-09dcc413e27c.png)
![image](https://user-images.githubusercontent.com/54339501/197943516-1959a162-57c0-409f-acc1-b77af02c9920.png)
![image](https://user-images.githubusercontent.com/54339501/197943540-060d5b90-db22-4693-85d0-336bedd28ecf.png)
