### ISSUE TITLE
SQL分析特定语句时展示的表信息重复

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#883]
**SQLe Version**

**Describe the bug**

执行特定语句时展示的表信息重复，例如：insert into t1 select * from t1
![image](https://user-images.githubusercontent.com/18008452/191226672-088e1106-9078-438b-859a-6302b5f82529.png)

**To Reproduce**

**Expected behavior**

**Suggestion**

**Comment by taolx0** [comment]
### 自测
![image](https://user-images.githubusercontent.com/63177450/194815463-02621812-300a-4726-be3f-37c23b3bebb6.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: release-1.2209.x 604e0ac
Server Version: release-1.2209.x-ee 3f8ad37ce4
1.创建工单
2.使用以下sql进行审核
`insert into t1 select * from t1`
3.点击sql分析，出现重复信息
![image](https://user-images.githubusercontent.com/54339501/197701310-7a07af83-307e-4a8a-8095-01238b004bd5.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main ea5c57c
Server Version: main-ee c06bde1532
验证步骤：
1.创建工单
2.使用以下sql进行审核
`insert into t1 select * from t1`
3.点击sql分析，没有出现重复信息


![image](https://user-images.githubusercontent.com/54339501/197712954-d679651d-af3d-4e7b-9d8a-bd39e0cd188e.png)
