### ISSUE TITLE
当使用不同sql选择不同类型数据源之后，点击相同sql可以正常使用，应该给予限制

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#915]
**SQLe Version**
UI Version: main bd11b2c
Server Version: main-ee bd74aa1d8e

1.创建工单，选择不同sql
2.选择一个ob类型的数据源，2个mysql数据源
3.然后在点击相同sql模式
4.正常输入sql语句进行审核，然后点击创建
 
![5b9e758d-807f-47fd-887e-3127624616ee](https://user-images.githubusercontent.com/54339501/192967827-b287b486-ce71-43fe-a097-4114659e3b2e.jpeg)
![e02707ed-36cb-4102-b349-96d19b10c606](https://user-images.githubusercontent.com/54339501/192967838-421185ee-befb-4ab3-943c-69a720c6f553.jpeg)

**Comment by ColdWaterLW** [comment]
方案：
1. 后端在创建工单时对数据源类型判断限制
2. 在切换相同SQL按钮时，前端把已选的数据源清空

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 604e0ac
Server Version: main-ee c64c8ce973

验证步骤：
1.创建工单，选择不同sql
2.选择一个ob类型的数据源，2个mysql数据源
3.然后在点击相同sql模式，现在无法点击
![image](https://user-images.githubusercontent.com/54339501/193213976-3636e9c3-207a-4982-804f-eaec8eb7af0a.png)
![Uploading image.png…]()
