### ISSUE TITLE
无论是相同sql还是不同sql，当添加好第一个数据源之后，添加第二个数据源展示全量数据源

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#917]
**SQLe Version**
UI Version: main bd11b2c
Server Version: main-ee bd74aa1d8e

1.创建工单，选择不同sql类型
2.然后添加第一个数据源
3.在添加第二个数据源，展示了全量的数据源
第二个数据源应该只展示第一个数据源绑定的审批流程上的数据源，而不是全量数据源

**Comment by ColdWaterLW** [comment]
原因：
刷新页面时后端接口返回的流程模板id是0，导致前端筛选时相应参数传了0
![image](https://user-images.githubusercontent.com/36940986/192974125-6a83048c-dd6f-45fa-8558-0ca52a0ec096.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 7705820
Server Version: main-ee c64c8ce973
验证步骤：
1.创建工单，选择不同sql类型
2.然后添加第一个数据源
3.在添加第二个数据源，只展示了相同类似的数据源


![image](https://user-images.githubusercontent.com/54339501/193196592-2386f453-2900-4b71-bd92-db236b8e70d1.png)
![image](https://user-images.githubusercontent.com/54339501/193196607-1744c492-838f-4c9b-8526-5ff3deadb745.png)
![image](https://user-images.githubusercontent.com/54339501/193196637-1be74428-eea8-4db2-90ff-651beb9de0c7.png)
