### ISSUE TITLE
SQL工作台跳转流程优化

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#925]
**Suggestion**

在配置了SQL工作台的情况下，点击“SQL工作台”后，不再直接跳转Cloudbeaver 地址，而是在SQLE展示如下图的页面，通过页面内的地址跳转CloudBeaver 窗口
![image](https://user-images.githubusercontent.com/18008452/194803030-6bef55a0-349b-494e-ad52-e8d5c7dc2fe4.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main ea5c57c
Server Version: main-ee c06bde1532
验证步骤：
1.进入到sql查询功能界面，该节目提示打开sql工作台
2.点击打开sql工作台，进入到cloud界面

![image](https://user-images.githubusercontent.com/54339501/197735524-f5343918-bd26-4cc7-9ee6-1ffe524f062e.png)
![image](https://user-images.githubusercontent.com/54339501/197735785-411969ba-186f-45e9-8f9a-8df13cedb2e2.png)
