### ISSUE TITLE
社区版pg插件往不存在的表插入数据导致程序panic

### ISSUE THREAD

**Issue by taolx0** [actiontech/sqle#928]
**SQLe Version**
main

**Describe the bug**
1. 使用社区版pg插件
2. 执行sql上线操作，往不存在的表插入一条数据
3. 程序崩溃（如果有守护进程会被自动拉起），sql状态一直是```doing```

**Comment by taolx0** [comment]
### 为什么程序会panic？
pg插件调用sqle版本过低，未实现 Registerer 接口新增 AdditionalParams()方法。results, txErr := a.driver.Tx(context.TODO(), qs...)调用返回值 results, txErr 都为nil，引发sqle panic。
https://github.com/actiontech/sqle/blob/8281aa5b51637ece4feaa78613b6e541b57a9a5d/sqle/server/sqled.go#L400

**Comment by Marcus9530** [comment]
验证版本：
root@ubuntu:~# ./sqle-pg-plugin -version
"main 4b748c2ff9e46673fe03e01808e49c93e282a18b"
UI Version: main a904e6c
Server Version: main-ee e4e5da233a
验证步骤：
1.添加一个pg数据源
2.创建工单，往pg数据源插入一条不存在的表数据sql语句
3.创建成功之后审核并执行上线，可以正常进行审核
4.使其工单进行上线，可以看到上线执行结果

![image](https://user-images.githubusercontent.com/54339501/197989878-cc5abb2d-11de-4746-af7f-56476d9b507a.png)
![image](https://user-images.githubusercontent.com/54339501/197989982-7aad10db-780e-4a7e-9033-77b8f4064900.png)
