### ISSUE TITLE
期望提供一个数据源去除功能按钮

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#942]
背景：
1.在创建工单的时候可以看到有很多个数据源
2.如果想使用多数据源进行对同一个sql进行审核的时候，第一个数据源选择错了，则后面选择都是第一个数据源
3.如果想要在进行修改数据源的话，目前是只能刷新页面，或者重新打开一个创建工单的界面，这样操作不太方便
期望是在数据源框里提供一个删除按钮，可以删除掉当前选择错误的数据源，重新在进行选择
![image](https://user-images.githubusercontent.com/54339501/195519229-3ea173a3-8ce1-45d5-ad7c-8887ad7830ba.png)
![image](https://user-images.githubusercontent.com/54339501/195519256-4ecc2a46-b6e2-4d0f-a100-cfb203685da7.png)
![image](https://user-images.githubusercontent.com/54339501/195519274-dd9ebed7-1ff2-4837-984d-aa979664ee94.png)

**Comment by ColdWaterLW** [comment]
问题已经被修复
