### ISSUE TITLE
当SQLE用户为LDAP用户时, 同步到CloudBeaver的用户无法登录

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#957]
## 问题描述
SQLE会自动同步用户信息到CloudBeaver, 当SQLE用户的登陆方式为LDAP登陆时, 
因为SQLE不会记录LDAP用户的密码, 所有LDAP用户的密码都是固定的默认密码, 
所以导致SQLE同步到CloudBeaver的LDAP用户密码都是固定的默认密码

## 期望
使用SQLE用户登录CloudBeaver时, 使用SQLE自身的登录校验逻辑代替CloudBeaver的登录校验逻辑

## 方案

当前无法实现期望内容, 因为SQLE并不知道LDAP用户的密码是多少, 也无法查询(LDAP记录的密码可能是加密的); 且SQLE也无法知道CloudBeaver直接登录时使用的密码是多少(加密过的), 所以SQLE既无法在本地做密码比对, 也无法将用户传递的密码拿到LDAP中验证

当前临时处理方案: 放弃处理用户使用LDAP用户直接从CloudBeaver上登陆的场景处理, 并提供密码错误时的绕过方案

#### 方案说明
暂时不按照期望的逻辑改为SQLE校验, 替换校验方式放到后续SQLE接管CloudBeaver登录的时候处理, 当前处理方式为在SQLE将最近一次LDAP用户登录时的密码同步到CloudBeaver, 校验依然由CloudBeaver进行

#### 调整LDAP用户密码逻辑

原来: SQLE不会记录LDAP用户密码

现在: 每次LDAP用户登录SQLE, SQLE都会将当前密码进行更新

说明: SQLE登录时会在登录校验完成后同步此用户到CloudBeaver, 所以如果LDAP登录成功, 此时SQLE中记录的LDAP用户密码是最新的, 同步到CloudBeaver的用户密码也是最新的

##### 场景描述
1. 用户修改LDAP密码
2. 用户使用新的LDAP密码直接从CloudBeaver登录

##### 无法处理的原因
CloudBeaver前端像后端传递的密码是加密的, SQLE无法得到用户在前端填写的密码, 如果LDAP用户在最近一次登录SQLE后修改了此密码, SQLE和CloudBeaver将无法感知到此次密码修改

##### 绕过方式
1. 退出CloudBeaver
2. 使用LDAP用户登录SQLE
3. 重新登录CloudBeaver

**Comment by HuangWeiCen** [comment]
## 验证流程

### 1. 连接LDAP环境
![image](https://user-images.githubusercontent.com/37464327/196908176-791040bf-c48e-4cb9-a3be-c254e580bf77.png)

### 2. 使用ldap特有用户登录
![image](https://user-images.githubusercontent.com/37464327/196908316-90b28a14-13d5-47d4-a662-9a524c22f749.png)
![image](https://user-images.githubusercontent.com/37464327/196908383-8675639a-c7db-457b-a988-f0a85d6384a6.png)
![image](https://user-images.githubusercontent.com/37464327/196908412-29553c37-dfa3-43c0-a2c5-f315eb22fbd5.png)

### 3. 从数据库中将LDAP验证改为SQLE验证
![image](https://user-images.githubusercontent.com/37464327/196909507-39cbc664-00ea-430d-a9f9-20bbb6f652b6.png)

### 4. 再次使用这个用户登录
![image](https://user-images.githubusercontent.com/37464327/196909655-b8f411f1-afdd-44c2-808d-9ff55dfbe03c.png)
![image](https://user-images.githubusercontent.com/37464327/196909687-0a9a9ada-de6f-4d19-b5b1-a4eaad099036.png)

### 5. 登陆成功, 证明在ldap用户第一次登录SQLE时密码会被SQLE记录

### 6. 从数据库中将验证方式改回ldap验证
![image](https://user-images.githubusercontent.com/37464327/196909930-42b8fd1d-ac26-4681-8dbb-e4b20f4b1bb9.png)

### 7. 修改ldap用户的密码
![image](https://user-images.githubusercontent.com/37464327/196910302-4b14c9d3-2277-4544-8c2f-841599f9a613.png)
![image](https://user-images.githubusercontent.com/37464327/196910366-e4fcd2b2-a0a3-421c-8995-ae47fde87f01.png)
![image](https://user-images.githubusercontent.com/37464327/196910486-0708ba9f-4d2a-4a5a-9d5f-1d5706598e0c.png)

### 8. 使用原密码登录, 发现登录失败, 使用新密码登录, 发现登录成功,  确认ldap密码修改成功
![image](https://user-images.githubusercontent.com/37464327/196911176-c68cace9-4fcb-461c-a655-89d1acb7596f.png)
![image](https://user-images.githubusercontent.com/37464327/196911250-4a7cf37a-a449-455a-96ec-9ec040471bc7.png)
![image](https://user-images.githubusercontent.com/37464327/196911277-8f25e808-c53e-4b07-a39d-2c75ee98564a.png)

### 9. 从数据库中将此用户的验证方式改为SQLE验证
![image](https://user-images.githubusercontent.com/37464327/196911397-1ea293d4-9652-4927-8144-3d9b07f963df.png)


### 10. 重新使用此用户登录
![image](https://user-images.githubusercontent.com/37464327/196911581-680ad4fa-afac-49cf-90c9-197af49dbd0c.png)
![image](https://user-images.githubusercontent.com/37464327/196911612-860285c7-6e78-44e4-9626-331a3e264518.png)

### 11. 登录成功, 证明修改ldap密码后登录SQLE, SQLE也能正常同步最新的密码

### 12. 使用LDAP用户当前密码登录CloudBeaver, 发现登录成功
![image](https://user-images.githubusercontent.com/37464327/196912339-ec41504a-896d-4973-a15d-a75a2f43bb15.png)
![image](https://user-images.githubusercontent.com/37464327/196912191-84b548e2-6539-427b-a8a2-5111bf4712d1.png)

### 13. 将LDAP用户密码改掉
![image](https://user-images.githubusercontent.com/37464327/196912543-1953399d-ec61-4914-af27-e2e781ce2132.png)
![image](https://user-images.githubusercontent.com/37464327/196912603-6957c655-3257-43fb-85c4-764aba8047b1.png)

### 14. 将数据库中LDAP用户的验证方式改回LDAP验证
![image](https://user-images.githubusercontent.com/37464327/196913966-4be573a8-e667-4d67-afb6-30ee831cdd55.png)

### 15. 使用第13步改动之前的密码登录CloudBeaver, 发现登录成功, 这是正常情况, 这个就是放弃的那个场景

### 16. 使用第13步之前的密码登录SQLE, 发现登录失败, 确认LDAP密码修改成功
![image](https://user-images.githubusercontent.com/37464327/196914149-6edaa15c-1ce1-44f4-ab8d-bac91c406011.png)

### 17. CloudBeaver 使用另外一个用户登录(用户不存在自动同步的场景不用验, 没涉及到那块)
![image](https://user-images.githubusercontent.com/37464327/196914509-88259f68-c859-44b5-a833-4f16ab9c8aac.png)

### 18. 使用新的密码登录SQLE, 发现登录成功
![image](https://user-images.githubusercontent.com/37464327/196914630-89235d46-8b74-4ec7-a62a-b0eeb082f5dd.png)
![image](https://user-images.githubusercontent.com/37464327/196914659-b0aa7eb5-b515-4fae-8942-d9a4d954297c.png)

### 19. 使用旧密码登录CloudBeaver, 发现登录失败, 改为用新密码登录
![image](https://user-images.githubusercontent.com/37464327/196914832-dcb9a567-d12f-41c5-80ba-3ba60aeff8b1.png)
![image](https://user-images.githubusercontent.com/37464327/196914939-898fbfcd-0bb8-4984-86af-0cba14512dbc.png)
![image](https://user-images.githubusercontent.com/37464327/196914885-3e3d8a77-7285-4e02-9853-be864f222a17.png)

### 20. 登陆成功, 这说明绕过手段有效, 在SQLE最后一次登录使用的LDAP密码可以在CloudBeaver使用

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-1.2209.x 604e0ac
Server Version: release-1.2209.x-ee 3f8ad37ce4

复现步骤：
1.创建一个ldap类型的用户
2.赋予该用户sql查询的权限
3.登陆该用户，然后点击sql查询，在sql查询界面无法登陆到该用户，手动登陆也失败
![image](https://user-images.githubusercontent.com/54339501/197726408-85060139-6509-42ab-ac2e-8bae285a3db1.png)

![image](https://user-images.githubusercontent.com/54339501/197726163-f8f5a7cc-3aa4-4499-9f10-a032196dd7e9.png)
![image](https://user-images.githubusercontent.com/54339501/197726303-0debfd84-cfaf-4a23-a951-f55fdc7cd8a7.png)
![image](https://user-images.githubusercontent.com/54339501/197727076-7fb4ec7c-479c-4363-a360-dfee5aa9dbd6.png)

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main ea5c57c
Server Version: main-ee c06bde1532
验证步骤：
1.创建一个ldap类型的用户
2.赋予该用户sql查询的权限
3.登陆该用户，然后点击sql查询，手动登录成功



![image](https://user-images.githubusercontent.com/54339501/197733040-7db540b9-55d4-4836-8e1e-498955762612.png)
![image](https://user-images.githubusercontent.com/54339501/197733172-1b79db6e-36d6-4907-b6bf-1030d4f9faee.png)
![image](https://user-images.githubusercontent.com/54339501/197733285-84351609-2e62-4d54-a2c1-ff62dde20e19.png)
