### ISSUE TITLE
上线失败的过期工单没有被回收

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#961]
原因：
之前工单状态上线成功和失败的状态都是finished，后来把上线失败改为exec_failed，但清理过期工单时还是只回收了状态为finished和canceled的工单，导致上线失败的工单不会被回收

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/197713983-e1b80aa0-e8f2-409f-8731-d4618aa078c9.png)
![image](https://user-images.githubusercontent.com/54339501/197714014-94753182-4ffd-4f8e-8e8d-bdf2fd70b676.png)

**Comment by Marcus9530** [comment]
![image](https://user-images.githubusercontent.com/54339501/197714778-f325ad68-3cf7-443b-9126-7f1c737eda48.png)
![image](https://user-images.githubusercontent.com/54339501/197714804-7bfcc227-9077-4b9d-9024-b9a49e42f12a.png)
