### ISSUE TITLE
CloudBeaver改为使用实例绑定的模板中启用的的静态规则审核

### ISSUE THREAD

**Issue by HuangWeiCen** [actiontech/sqle#964]
## 背景
CloudBeaver 当前和 IDEA插件一样使用默认模板中启用的静态规则审核, 现改为使用实例自身绑定的模板中的静态规则审核

**Comment by HuangWeiCen** [comment]
# 改动验证

## 1. 创建两个MySQL审核模板, 一个关闭所有规则, 一个开启所有规则

全关的模板
![image](https://user-images.githubusercontent.com/37464327/196866513-9c7314ef-4581-4e99-8f84-0a0458fa1f7b.png)

全开的模板
![image](https://user-images.githubusercontent.com/37464327/196866451-8be6dba7-8a42-47ee-86db-355b8cd6d29d.png)

## 2. 创建两个MySQL实例, 分别绑定两个模板, 并将是否审核开启, 审核等级设置为normal
![image](https://user-images.githubusercontent.com/37464327/196866728-63c457fd-23b5-4e02-86f2-4b35cf30c804.png)
![image](https://user-images.githubusercontent.com/37464327/196866763-ef0083e9-f625-4d9d-a8f6-56c26c704ae3.png)

## 3. 跳转到CloudBeaver(使用admin跳转)
略

## 4. 分别在两个实例中执行 select * from mysql.user;
![image](https://user-images.githubusercontent.com/37464327/196866924-d0370f26-6892-4868-91d5-7b272183492d.png)
![image](https://user-images.githubusercontent.com/37464327/196866963-96324b4c-6ea2-41e7-a87b-5aada62c11b5.png)
![image](https://user-images.githubusercontent.com/37464327/196866984-b2b6d677-1abd-4a35-b266-57c1b4ff858d.png)

## 5. 观察4的结果, 可以发现, 绑定全开模板的SQL审核没通过, 并按预期抛出错误, 绑定全关模板的SQL审核通过, 可以得出结论, 现在审核时使用的是实例自身绑定的模板

**Comment by Marcus9530** [comment]
验证版本
UI Version: main 9ad6f1b
Server Version: main-ee e4e5da233a

验证步骤
1.添加一个数据源1开启sql查询，并且设置等级
2.添加一个数据源2开启sql查询，并且设置等级
3.添加一个审核规则模版，然后开启所有规则，并添加 数据源1
4.添加一个审核规则模版，然后关闭所有规则，并添加 数据源2
5.在CloudBeaver对数据源1跟数据源2分别下发select * from mysql.user 
6.可以看到数据源2正常返回数据，数据源1出现预期错误


<img width="1190" alt="image" src="https://user-images.githubusercontent.com/54339501/198475439-17607f3d-7d8e-49db-9688-a453643c29ce.png">
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/54339501/198475630-03750e85-89c3-42fd-b998-263bd06acc3f.png">
