### ISSUE TITLE
工单审核结果的筛选条件“审核结果”存在歧义，建议优化描述

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#966]
**Describe**

工单审核结果的筛选条件“审核结果”存在歧义，建议优化描述。当如下图所示的审核结果内的审核建议包含notice级别的内容时，在审核结果内筛选notice筛选不到记录
![image](https://user-images.githubusercontent.com/18008452/196875681-289fbd58-cc88-4cc9-93d9-0ac1bf8969ce.png)
筛选条件改成warn时能筛选结果
![image](https://user-images.githubusercontent.com/18008452/196875300-f091fc0d-c527-4f8b-9606-bef2ff3d4400.png)
实际筛选与正常人的思维不符，存在歧义，为什么我筛选notice，确实有notice的结果，为什么不展示

#### 原因：
但是对于一个SQL来说，提示等级是当前所有审核建议的最大等级，例如，有warn和notice时，审核等级是warn，有error，warn，notice时，审核等级是error。

**Suggestion**

筛选条件可以先改成“最高审核告警等级”，消除歧义

**Comment by Marcus9530** [comment]
验证版本：
UI Version: main 86710b0
Server Version: main-ee d6ade44ccf
验证步骤：
当前创建工单内的文案已经变更，功能正常使用

![image](https://github.com/actiontech/sqle/assets/54339501/c8e35cd9-fb0f-4b4b-ae13-f6e4f3a6344f)
![image](https://github.com/actiontech/sqle/assets/54339501/9781dedc-fa84-44a1-a767-41bd8ec72b23)
