### ISSUE TITLE
容器启动报错， Table 'sqle.global_configuration_oauth2' doesn't exist

### ISSUE THREAD

**Issue by GodzillaHua** [actiontech/sqle#973]
容器： actiontech/sqle-ce:latest

启动报错信息如下：
(/universe/sqle/model/utils.go:141) 
[2022-10-23 13:01:43]  Error 1067: Invalid default value for 'login_tip' 
panic: Error 1146: Table 'sqle.global_configuration_oauth2' doesn't exist

goroutine 1 [running]:
github.com/jinzhu/gorm.mysql.HasIndex(0x1c305a0, 0xc00089bba0, 0x0, 0xc0006c6a80, 0x1b, 0xc000140a20, 0x2a, 0x37bc200)
        /universe/vendor/github.com/jinzhu/gorm/dialect_mysql.go:189 +0x2dc
github.com/jinzhu/gorm.(*Scope).addIndex(0xc00024db80, 0x1853d00, 0xc000140a20, 0x2a, 0xc0007b6f30, 0x1, 0x1)
        /universe/vendor/github.com/jinzhu/gorm/scope.go:1216 +0x8a
github.com/jinzhu/gorm.(*DB).AddIndex(0xc0000f9790, 0xc000140a20, 0x2a, 0xc0007b6f30, 0x1, 0x1, 0x0)
        /universe/vendor/github.com/jinzhu/gorm/main.go:711 +0xaf
github.com/jinzhu/gorm.(*Scope).autoIndex(0xc00024d800, 0xc00024d800)
        /universe/vendor/github.com/jinzhu/gorm/scope.go:1316 +0x9e7
github.com/jinzhu/gorm.(*Scope).createTable(0xc00024d800, 0xc0006c67e0)
        /universe/vendor/github.com/jinzhu/gorm/scope.go:1198 +0x7a5
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc00024d800, 0x1853d40)
        /universe/vendor/github.com/jinzhu/gorm/scope.go:1269 +0x436
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc00089bc70, 0x3742020, 0x20, 0x20, 0xae9fa5)
        /universe/vendor/github.com/jinzhu/gorm/main.go:689 +0x97
github.com/actiontech/sqle/sqle/model.(*Storage).AutoMigrate(0xc000010018, 0x4, 0xc000926474)
        /universe/sqle/model/utils.go:141 +0x6a
github.com/actiontech/sqle/sqle.Run(0xc00055a120, 0x0, 0x0)
        /universe/sqle/sqled.go:65 +0xb1f
main.run(0xc0002a4840, 0xc0000a06e0, 0x0, 0x2, 0x0, 0x0)
        /universe/sqle/cmd/sqled/sqled.go:135 +0x28c
main.main.func1(0xc0002a4840, 0xc0000a06e0, 0x0, 0x2)
        /universe/sqle/cmd/sqled/sqled.go:49 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc0002a4840, 0xc000114160, 0x2, 0x2, 0xc0002a4840, 0xc000114160)
        /universe/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a4840, 0xc000943f50, 0x1, 0x1)
        /universe/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /universe/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /universe/sqle/cmd/sqled/sqled.go:73 +0x788

**Comment by sjjian** [comment]
看提示是因为访问的表不存在。请提供下环境信息，1. docker启动命令，2. docker images 看下sqle的image id，3. 确认下连接的数据库版本和对应数据是否包含这张表 sqle.global_configuration_oauth2。

**Comment by GodzillaHua** [comment]
截图如下，
![image](https://user-images.githubusercontent.com/18274190/197912539-d4ef7a0d-951e-45c7-b09f-e56891486366.png)
![image](https://user-images.githubusercontent.com/18274190/197912796-90206aa4-a330-46bb-a3bd-4ebff4cc254f.png)

**Comment by sjjian** [comment]
把数据库的database `sqle`  删掉，重新创建后再试试启动。使用下面的语句创建database
```sql
CREATE DATABASE IF NOT EXISTS sqle default character set utf8mb4 collate utf8mb4_unicode_ci
```

**Comment by sjjian** [comment]
无后续
