### ISSUE TITLE
智能扫描菜单按数据源类型分类

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#999]
版本：v1.2210.0
现状：当前智能扫描菜单将支持的任务类型全都展示在同一级菜单，没有分类会造成使用困难，需要进入到创建扫描任务页面才知道支持的数据源类型。
![image](https://user-images.githubusercontent.com/36940986/197963097-fbd0833d-7bc1-43fc-b1d2-dc8a104bd53d.png)

建议优化：菜单上的任务类型按数据源类型分类展示

相关issue：#825

**Comment by Marcus9530** [comment]
UI Version: main 4842afb
Server Version: main-ee 17dd4ca441
验证步骤
当前智能扫描任务已经按照不同数据库类型进行了分类

<img width="238" alt="image" src="https://user-images.githubusercontent.com/54339501/210040859-2167a0b9-0b71-40f7-94f3-1ce0f0d11dd7.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/54339501/210040872-3ed4c4fd-3851-4c59-b621-2c8c908067f8.png">
